### ISSUE TITLE
Pristine-1.5 compilation failed at librina phase in debian jessie.

### ISSUE THREAD

**Issue by selvakumar8292** [IRATI/stack#1014]
../librina/src/security-manager.cc: In member function 'void rina::AuthSSH2PolicySet::edh_init_params()':
../librina/src/security-manager.cc:770:15: error: invalid use of incomplete type 'DH {aka struct dh_st}'
  dh_parameters->p = BN_bin2bn(dh2048_p,sizeof(dh2048_p),NULL);
               ^
compilation terminated due to -Wfatal-errors.
Makefile:1247: recipe for target 'librina_la-security-manager.lo' failed
make[3]: **\* [librina_la-security-manager.lo] Error 1

Please help me to solve this issue

**Comment by edugrasa** [comment]
I guess you could work around this issue?
