### ISSUE TITLE
Pristine-1.5 compilation failed at librina phase in ubuntu 12.04

### ISSUE THREAD

**Issue by arjungeth** [IRATI/stack#1015]
make  install-am
make[3]: Entering directory `/home/abc/stack/build/librina/src'
make[3]: *** No rule to make target`/home/xyz/stack/librina/src/jsoncpp/json_reader.cpp', needed by `jsoncpp/librinajsoncpp_la-json_reader.lo'.  Stop.
make[3]: Leaving directory`/home/abc/stack/build/librina/src'
make[2]: **\* [install] Error 2
make[2]: Leaving directory `/home/abc/stack/build/librina/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory`/home/abc/stack/build/librina'

Please someone find me a solution..

**Comment by edugrasa** [comment]
Maybe OS version is too old? We usually use Debian 7 as the target OS, we've tested with more recent versions of Ubuntu without problems..
