### ISSUE TITLE
kernel: page fault in shim-tcp-udp

### ISSUE THREAD

**Issue by jmuchemb** [IRATI/stack#1022]
I only have photos. The machine is quite busy (currently, load average: 5.03, 4.51, 5.38) but it has very little RINA activity (for the moment, 1 enrollment, no app).

For [crash 1](https://cloud.githubusercontent.com/assets/11165223/19117170/6089be12-8b18-11e6-8e8a-e97f41e1844c.jpg) and [crash 3](https://cloud.githubusercontent.com/assets/11165223/19117171/6090498a-8b18-11e6-89eb-594446c83ffa.jpg), I got "Watchdog detected hard LOCKUP on cpu 6". Maybe it's the same thing for [crash 2](https://cloud.githubusercontent.com/assets/11165223/19117169/60885464-8b18-11e6-8dcb-be3f668d45b7.jpg).

In all 3 cases:
- it happened in less than 1 day
- there are also tracebacks of page faults in `tcp_udp_write_worker` (more exactly, 0x20e maps to the `send_msg` call of `tcp_sdu_write`)

For the moment, the machine runs without IPCM, but still with the same kernel.

**Comment by jmuchemb** [comment]
I think I got the same issue in a VM. [oops1-tcp_udp_write_worker.gz](https://github.com/IRATI/stack/files/515853/oops1-tcp_udp_write_worker.gz) is the full console output.
The kernel code is that of jmuchemb/irati-stack@47e2b6a5f32d1090ec75206ccdb797b78a1a3330.

**Comment by edugrasa** [comment]
Seems to be resolved after a number of bug fixes in the shim.
