### ISSUE TITLE
pristine-1.5: rina-tools cdapc build fails

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#1033]
@mcrotty Could you please take a look at this?

using install-user-from-scratch fails in rina-tools/src/cadapc because the resulting binary unittests does not have the --version argument. 

Since it seems that the check code that looks for this argument is autogenerated by autotools, the only way I could solve it is by modifying catch.h to add this argument (currently just redirecting to the usage function). This change is here: 

https://github.com/lbergesio/stack/commit/8934390170d7d92abdbe702fd6ce745a6317a357

Nevertheless, since catch.h seems to be a compendium of different header files from Catch and Clara I am not sure this is the proper solution. Could you please check it? If it is ok as I did it I will generate the corresponding pull request.

**Comment by mcrotty** [comment]
FYI: The proper (ie. documented) way to do this is to define your own main, and then call to catch to process its arguments, and use whatever to process application specific arguments.

However, in this case we are extending "catch.h" command line arguments, for which there is no documentation on how to do correctly. The API currently returns a const reference, and this is listed on the under development items for catch.h.
  
In the interim, i suggest we merge this result and leave a README.asciidoc in the source folder indicating that this is running a patched version of catch.h, and why we patched it. ie. pointing to this issue.

**Comment by edugrasa** [comment]
Fixed by #1035
