### ISSUE TITLE
Pristine-1.5 shim-tcp enrollment operation fails to create DIF

### ISSUE THREAD

**Issue by selvakumar8292** [IRATI/stack#1060]
I am using 2 different rina systems. one for client and other for server. Testing the shim-tcp-udp program.
I have used the same configuration given by IRATI stack under the tests/conf/ folder. only the ipaddress i changed for both server and client in the shim-tcp-udp config file.
Files used for shim-tcp-udp experiment are
1. ipcmanager.conf-normalovertcpudp1
2. shim-tcp-udp.dif
3. default.dif

configuration starts successfully at both server and client machines. When I tried to enroll the ipcp of client with server, facing the issue in establishing DIF from client to server.

from the client(test2.IRATI) terminal enroll with server(test1.IRATI) ipcp
ipcm>>enroll-to-dif 2 normal.DIF shim.DIF test1.IRATI 1
enrollment failed.

Please somebody help me to solve this problem. Thanks in advance.

Error at client machine during enrollment with server
![direntrynotfound client](https://cloud.githubusercontent.com/assets/5600806/22503917/e77ddadc-e899-11e6-8203-c25ae5787d32.png)

ipcm terminal @client 
![ipcm client](https://cloud.githubusercontent.com/assets/5600806/22503920/e7dc644e-e899-11e6-8753-c91f3f178793.png)

ipcm terminal @server 
![ipcm server](https://cloud.githubusercontent.com/assets/5600806/22503918/e7845b28-e899-11e6-96e0-34d1200d45e2.png)

error at client side 
![log server](https://cloud.githubusercontent.com/assets/5600806/22503919/e786a2ca-e899-11e6-8752-b7455bf59c04.png)

**Comment by edugrasa** [comment]
It looks like the shim TCP UDP configuration file, in particular the directory, is not properly configured. 

The Error logs in both systems point to that:
* Directory Entry not Found for ..
* The application is not expected to register ...

You should check that the names of the IPC Processes in the directory and in the expected registrations sections of the configuration file are consistent with your deployment.

**Comment by selvakumar8292** [comment]
Thanks for your quick reply. I understand the point. But I am using the default configuration provided as follows. I am trying to connect the echo-time server and client applications, using shim-tcp-udp environment to make them run in 2 systems, after the vlan experiment. In the same system it works fine. Please provide the correct working configuration for this scenario. It will be helpful. Again thanks in advance.

**At Server:**
1.   ipcmanager.conf-normalovertcpudp1
{
    "configFileVersion": "1.4.1",
    "localConfiguration": {
        "installationPath": "/usr/local/irati/bin",
        "libraryPath": "/usr/local/irati/lib",
        "logPath": "/usr/local/irati/var/log",
        "consoleSocket": "/usr/local/irati/var/run/ipcm-console.sock",
	"pluginsPaths": [
		"/usr/local/irati/lib/rinad/ipcp",
		"/lib/modules/4.1.33/extra"
	]
    },
    "ipcProcessesToCreate": [
        {
            "apName": "test-eth",
            "apInstance": "1",
            "difName": "shim.DIF"
        },
        {
            "apName": "test1.IRATI",
            "apInstance": "1",
            "difName": "normal.DIF",
            "difsToRegisterAt": [
                "shim.DIF"
            ]
        }
    ],
    "difConfigurations": [
        {
             "name" : "shim.DIF",
             "template" : "shim-tcp-udp.dif"
        },
        {
            "name": "normal.DIF",
            "template": "default.dif"
        }
    ]
}

    shim-tcp-udp.dif
{
    "difType" : "shim-tcp-udp",
     "configParameters" : {
         "hostname" : "84.88.40.131",
         "dirEntry" : "1:25:rina.apps.echotime.server0:12:84.88.40.1314:2426",
         "expReg" : "1:25:rina.apps.echotime.server0:4:2426"
     }
}

**At client:**
1.   ipcmanager.conf-normalovertcpudp2
{
    "configFileVersion": "1.4.1",
    "localConfiguration": {
        "installationPath": "/usr/local/irati/bin",
        "libraryPath": "/usr/local/irati/lib",
        "logPath": "/usr/local/irati/var/log",
        "consoleSocket": "/usr/local/irati/var/run/ipcm-console.sock",
	"pluginsPaths": [
		"/usr/local/irati/lib/rinad/ipcp",
		"/lib/modules/4.1.33/extra"
	]
    },
    "ipcProcessesToCreate": [
        {
            "apName": "test-eth",
            "apInstance": "1",
            "difName": "shim.DIF"
        },
        {
            "apName": "test2.IRATI",
            "apInstance": "1",
            "difName": "normal.DIF",
            "difsToRegisterAt": [
                "shim.DIF"
            ]
        }
    ],
    "difConfigurations": [
        {
             "name" : "shim.DIF",
             "template" : "shim-tcp-udp.dif"
        },
        {
            "name": "normal.DIF",
            "template": "default.dif"
        }
    ]
}

    shim-tcp-udp.dif
{
    "difType" : "shim-tcp-udp",
     "configParameters" : {
         "hostname" : "84.88.40.132",
         "dirEntry" : "1:25:rina.apps.echotime.client0:12:84.88.40.1324:2426",
         "expReg" : "1:25:rina.apps.echotime.client0:4:2426"
     }
}

**Comment by edugrasa** [comment]
Hi,

So you are trying to have an application (rina-echo-time) running over a DIF, and the DIF over TCP using a shim DIF. Therefore, what has to register in the shim TCP/UDP DIF is the IPC process, not the application (rina-echo-time).

The shim DIF configuration files provided are wrong, since they expect the application to run over the shim DIF, not the IPC Processes in the normal DIF. Correct ones should be:

* Server configuration
````
{
"difType" : "shim-tcp-udp",
"configParameters" : {
"hostname" : "84.88.40.131",
"dirEntry" : "1:11:test2.IRATI0:12:84.88.40.1314:2426",
"expReg" : "1:11:test1.IRATI0:4:2426"
}
````

* Client configuration
````
"difType" : "shim-tcp-udp",
"configParameters" : {
"hostname" : "84.88.40.132",
"dirEntry" : "1:11:test1.IRATI0:12:84.88.40.1324:2426",
"expReg" : "1:11:test2.IRATI0:4:2426"
}
````

**Comment by selvakumar8292** [comment]
Hi Eduard Grasa,
Thanks for  your guidance. I applied the configuration as you provided, but it gives me an error as below when i run the config. Please suggest me a solution for this. It will be helpful for us. 

3012(1486448239)#ipcm (DBG): SIGSEGV handler installed successfully
3012(1486448239)#ipcm (DBG): SIGINT handler installed successfully
3012(1486448239)#ipcm (DBG): SIGQUIT handler installed successfully
3012(1486448239)#ipcm (DBG): SIGTERM handler installed successfully
3012(1486448239)#ipcm (DBG): SIGHUP handler installed successfully
3012(1486448239)#ipcm (DBG): SIGPIPE handler installed successfully
3012(1486448239)#ipcm (DBG): SIGCHLD handler installed successfully
3012(1486448239)#ipcm (DBG): Config file is: tests/conf/ipcmanager.conf-normalovertcpudp2
3012(1486448239)#librina.logs (DBG): New log level: INFO
3012(1486448239)#librina.common (WARN): Error setting log file, using stdout only
3012(1486448239)#librina.nl-manager (INFO): Netlink socket connected to local port 1 
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest default.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest sm-passwd.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest sm-auth-psoc.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest sm-cbac.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest rina-default-plugin.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest sm-example.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest fare.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest pff-multipath.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest red-plugin.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest cas-plugin.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest ecn.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest pffb.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest cherish-urgency-plugin.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest pff-lfa.manifest
3012(1486448239)#ipcm-catalog (INFO): Catalog: found manifest cdrr.manifest
3012(1486448239)#ipcm.dif-allocator (INFO): DIF Directory file: tests/conf/da.map
3012(1486448239)#ipcm.dif-template-manager (INFO): Template folder: tests/conf
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: default.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: security2.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-tcp-udp.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-hv2.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: ipcp-cher-urg.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-tcpudp.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-tcp-udp (copy).dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-hv.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: vm-to-vm.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-tcp-udp (another copy).dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-eth-vlan2.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: security-tls.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: vpn2.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: security.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-eth-vlan.dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shim-tcp-udp (3rd copy).dif
3012(1486448239)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: vpn.dif
3012(1486448239)#ipcm (INFO)[create_ipcp]: IPC process test-eth:1:: created [id = 1]

3012(1486448239)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process test-eth:1:: to DIF shim.DIF:::

3012(1486448239)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process test-eth:1:: [success=1]

3012(1486448239)#ipcm (INFO)[create_ipcp]: IPC process test1.IRATI:1:: created and waiting for initialization[id = 2]

3012(1486448239)#ipcm.console (ERR): Error [2] calling bind()
3018(1486448239)#librina.ipc-manager (ERR): Problems loading IPC Process program, finalizing OS Process with error No such file or directory
3018(1486448239)#ipcm (CRIT): Got signal SIGSEGV

**Comment by selvakumar8292** [comment]
Hi Eduard Grasa. Thanks for your help and guidance. We are thankful for your patience and time for adjusting the config files. It works. Thanks again.

**Comment by edugrasa** [comment]
Glad I could help :)

**Comment by azk04** [comment]
Dear @edugrasa,

i am trying to carry out the same test. But i was wondering if you could tell us more about the set of  parameters you have added in "directory entry" and "expected application registration" lines: 
"dirEntry" : "1:11:test1.IRATI0:12:84.88.40.1314:2426",
"expReg" : "1:11:test2.IRATI0:4:2426",

**Comment by avoskanian** [comment]
Hello,

To be more specific with Andy's question above, we are trying to connect 2 VM via RINA over UDP, using the same configuration as presented in this issue.

Here is the list of our IPCPs:

**On the server (93.187.165.96):**
Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | test-eth:1:: | shim-tcp-udp | ASSIGNED TO DIF shim.DIF | test1.IRATI-1-- | -
    2 | test1.IRATI:1:: | normal-ipc | ASSIGNED TO DIF normal.DIF | - | -

**On the client (93.187.165.95):**
Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | test-eth:1:: | shim-tcp-udp | ASSIGNED TO DIF shim.DIF | test2.IRATI-1-- | -
    2 | test2.IRATI:1:: | normal-ipc | ASSIGNED TO DIF normal.DIF | - | -

The enrollment is failing (enroll-to-dif 2 normal.DIF shim.DIF). And we doubt on the configuration of the shim-tcp-udp.dif configuration file:

**On the server (93.187.165.96):**
{
    "difType" : "shim-tcp-udp",
     "configParameters" : {
         "hostname" : "93.187.165.96",
         "dirEntry" : "1:11:test2.IRATI0:12:93.187.165.954:2426",
         "expReg" : "1:11:test1.IRATI0:4:2426"
     }
}


**On the client (93.187.165.95):**
{
    "difType" : "shim-tcp-udp",
     "configParameters" : {
         "hostname" : "93.187.165.95",
         "dirEntry" : "1:11:test1.IRATI0:12:93.187.165.964:2426",
         "expReg" : "1:11:test2.IRATI0:4:2426"
     }
}

If you could tell us what we are doing wrong as well as what is expected in the dirEntry and expReg parameters, that would be a great help.

Thanks,

Annie

**Comment by edugrasa** [comment]
Hi,

Sorry for the complicated syntax in these configuration files. A little explanation of the formats:

* expReg: <number of application registrations>:<number of characters in ap name>:<apname>0:<number of chars in port number>:<port_number>

* dirEntry: <number of dir entries>:<number of chars in app name>:<app name>:0:<number of chars in IP address>:<IP address><number of chars in port number>:<port number>

Your expReg lines looks ok, but there is an error on the dirEntry ones

- Instead of "1:11:test2.IRATI0:12:93.187.165.954:2426" it should be "1:11:test2.IRATI0:**13**:93.187.165.954:2426"

- Instead of "1:11:test1.IRATI0:12:93.187.165.964:2426" it should be "1:11:test1.IRATI0:**13**:93.187.165.964:2426"

**Comment by avoskanian** [comment]
Dear Eduard,

Thank you very much for the answer. The explanation is clear. And it does work now!

Annie

**Comment by avoskanian** [comment]
Dear Eduard,

May I ask you if the shim-tcp-udp works with private IP addresses for the interfaces?
I took my previous config files and put them in 2 other systems and it doesn't work. The only change is the IP addresses (I also changed the _number of chars in IP address_ parameter in the dirEntry).

Thank you in advance,

Annie

**Comment by edugrasa** [comment]
Dear Annie,

It should make no difference. Can you paste your config files? 

Cheers,

Eduard

**Comment by avoskanian** [comment]
Here are the files for 10.10.10.152 :

[shim-tcp-udp.dif.txt](https://github.com/IRATI/stack/files/4076474/shim-tcp-udp.dif.txt)
[ipcm.conf.txt](https://github.com/IRATI/stack/files/4076475/ipcm.conf.txt)
[default.dif.txt](https://github.com/IRATI/stack/files/4076476/default.dif.txt)

**Comment by avoskanian** [comment]
And these are the ones for 10.10.10.104 :
[default.dif.txt](https://github.com/IRATI/stack/files/4076491/default.dif.txt)
[ipcm.conf.txt](https://github.com/IRATI/stack/files/4076492/ipcm.conf.txt)
[shim-tcp-udp.dif.txt](https://github.com/IRATI/stack/files/4076493/shim-tcp-udp.dif.txt)

**Comment by avoskanian** [comment]
The IPCPs, the DIFs are creating. The normal DIF IPCP is registering to the shim.DIF.
The enrollement doesn't work.

However, the enrollement does work when I use a shim-eth.
I also checked the port by sending just a UDP packet from one host to the other. That works.

Thank you for your help!

**Comment by edugrasa** [comment]
can you actually ping 10.10.10.104 from 10.10.10.152 and vice-versa?

**Comment by avoskanian** [comment]
Yes I can :) also checked that!

**Comment by edugrasa** [comment]
Do all IPC Processes have an "ASSIGNED TO DIF <dif_name>" status? Could you check system messages (dmesg) to see if there is any kernel log related to the shim TCP UDP?

**Comment by avoskanian** [comment]
Yes they do have the « ASSIGNED TO DIF <dif_name » status.
I am out of the office now but I will check the system messages on Monday and tell you. 
Thank you very much for your availability!

**Comment by avoskanian** [comment]
Dear Eduard, 
Here are the IPCPs assignments:

**On 10.10.10.152:**

IPCM >>> list-ipcps
Management Agent not started

Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | test-eth:1:: | shim-tcp-udp | ASSIGNED TO DIF shim.DIF | test2.IRATI-1-- | -
    2 | test2.IRATI:1:: | normal-ipc | ASSIGNED TO DIF normal.DIF | - | -

**On 10.10.10.104:**

IPCM >>> list-ipcps
Management Agent not started
Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
1 | test-eth:1:: | shim-tcp-udp | ASSIGNED TO DIF shim.DIF | test1.IRATI-1-- | -
2 | test1.IRATI:1:: | normal-ipc | ASSIGNED TO DIF normal.DIF | - | -

And attached the dmesg. I indeed have an error on 10.10.10.104:
rina-shim-tcp-udp(ERR): Couldn't retrieve hostname

Shall I add something in /etc/hosts? I have added these 2 lines:
10.10.10.152    annie-rina
10.10.10.104    rina1

[dmesg152.txt](https://github.com/IRATI/stack/files/4084991/dmesg152.txt)
[dmesg104.txt](https://github.com/IRATI/stack/files/4084992/dmesg104.txt)

Thanks,

Annie

**Comment by edugrasa** [comment]
Hi Annie,

I've checked the code (we did not write the shim-tcp-udp at i2CAT, so I was not very familiar with it), and I've found that it tries to retrieve the socket address and fails:
https://github.com/IRATI/stack/blob/master/kernel/ipcps/shim-tcp-udp.c#L1700

The getsockname sockets primitive  (https://linux.die.net/man/2/getsockname) is about retrieving addresses, not domain names, hence you don't need to use them at all (so no need to edit /etc/hosts). Hence it may be an issue with the configuration of the IP address vs. the data in the shim-tcp-udp config file? Can you paste here the configuration of the IP interfaces in the 10.10.10.104 machine? Thanks!

**Comment by avoskanian** [comment]
enp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.10.104  netmask 255.255.255.0  broadcast 10.10.10.255
        inet6 fe80::5401:ac04:e4ca:b40b  prefixlen 64  scopeid 0x20<link>
        ether 6c:f0:49:7f:0d:f8  txqueuelen 1000  (Ethernet)
        RX packets 85  bytes 11684 (11.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 73  bytes 7552 (7.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by avoskanian** [comment]
Dear Eduard,

I found another computer to replace the one that showed an error, and now it works with the same configuration.
So we can close the issue, as you said it is not related to the sim-tcp-udp.

Thanks again for your help !

**Comment by edugrasa** [comment]
Excellent, thanks :)
