### ISSUE TITLE
Make IRATI easier to compile and more portable between hardware architectures

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#1087]
1. Eliminate all syscalls, move them to Netlink messages (the only performance-sensitive once were read and write, which already use the standard read and write calls now): 
1.1 ipc_create : 2 Netlink messages IPCM_CREATE_IPCP_REQUEST, IPCM_CREATE_IPCP_RESPONSE
1.2 ipc_destroy: 2 Netlink messages IPCM_DESTROY_IPCP_REQUEST, IPCM_DESTROY_IPCP_RESPONSE
1.3 allocate_port: 2 Netlink messages
1.4 deallocate_port: 2 Netlink messages
1.5 management_sdu_write: 2 Netlink messages
1.6 management_sdu_read: 1 Netlink message (kernel notifies user space)

2. Move definition of RINA Ethertype to a header file inside the net/rina folder (e.g. common.h)

3. Package all the RINA code into kernel modules (so that full kernel does not need to be recompiled when we recompile the RINA code)

**Comment by sandervrijders** [comment]
+1

**Comment by vmaffione** [comment]
Right, this is something that has been pending for some time, and it's doable.

**Comment by edugrasa** [comment]
Fixed by #1089
