### ISSUE TITLE
Compilation problem on arcfire branch

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#1100]
When trying to install the userspace on a Debian 7.7 machine I get the following error:

```
configure.ac:34: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

Autoreconf version is 2.69

**Comment by sandervrijders** [comment]
Aha, it's because I didn't have pkg-config installed. But then it seems that AC_MSG_ERROR is not found, hence the weird message. So probably configure.ac should be updated to define that macro.

**Comment by edugrasa** [comment]
Closing it, since the build will be updated to use cmake and build all user-space at once
