### ISSUE TITLE
Add routing policy to allow static routes and commands to the CLI to add or remove these routes 

### ISSUE THREAD

**Issue by miqueltarzan** [IRATI/stack#1111]
The rationale being that static routes are a very interesting option for some scenarios.

**Comment by edugrasa** [comment]
Very interesting feature, and should not be hard to implement

**Comment by vmaffione** [comment]
Yeah it's just an additional user/ kernel control message

Il 26 lug 2017 6:00 AM, "Eduard Grasa" <notifications@github.com> ha
scritto:

**Comment by edugrasa** [comment]
Even easier, messages to configure the forwarding table are already there ;)
