### ISSUE TITLE
Build fails on Raspberry Pi, missing <asm/config.h>

### ISSUE THREAD

**Issue by TRIA** [IRATI/stack#1115]
./install-from-scratch build of latest version fails compilation on Raspberry Pi:

sudo ./install-from-scratch /usr/local/irati
compile-kernel: Compiling kernel modules
make -C /lib/modules/`uname -r`/build REGRESSION_TESTS=n HAVE_VMPI=n TCP_UDP_BUFFER_SIZE=1500 M=/home/srb/stack/kernel modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.35-v7+'
  CC [M]  /home/srb/stack/kernel/core.o
  CC [M]  /home/srb/stack/kernel/utils.o
  CC [M]  /home/srb/stack/kernel/rds/rstr.o
  CC [M]  /home/srb/stack/kernel/rds/rmem.o
  CC [M]  /home/srb/stack/kernel/rds/rmap.o
  CC [M]  /home/srb/stack/kernel/rds/rwq.o
  CC [M]  /home/srb/stack/kernel/rds/rbmp.o
  CC [M]  /home/srb/stack/kernel/rds/rqueue.o
  CC [M]  /home/srb/stack/kernel/rds/rfifo.o
  CC [M]  /home/srb/stack/kernel/rds/ringq.o
  CC [M]  /home/srb/stack/kernel/rds/rref.o
  CC [M]  /home/srb/stack/kernel/rds/rtimer.o
  CC [M]  /home/srb/stack/kernel/rds/robjects.o
  CC [M]  /home/srb/stack/kernel/rds/rds.o
  CC [M]  /home/srb/stack/kernel/iodev.o
/home/srb/stack/kernel/iodev.c:33:24: fatal error: asm/compat.h: No such file or directory
 #include <asm/compat.h>
                        ^
compilation terminated.
scripts/Makefile.build:293: recipe for target '/home/srb/stack/kernel/iodev.o' failed

--------------
There is no asm/config.h in the normal raspberry pi headers:
# find /usr/src/linux-headers-4.9.24-v7+ -name compat.h -print
/usr/src/linux-headers-4.9.24-v7+/include/net/compat.h
/usr/src/linux-headers-4.9.24-v7+/include/linux/compat.h
/usr/src/linux-headers-4.9.24-v7+/include/config/i2c/compat.h

(Same results for latest headers, /usr/src/linux-headers-4.9.35-v7+)

In addition to stack/kernel/iodev.c, the compile also fails for stack/kernel/ctrldev.c

In both cases, changing the include directive to:
#include <linux/compat.h>
compiles.  (Not yet tested.)

**Comment by edugrasa** [comment]
Fixed by #1119
