### ISSUE TITLE
Closing a flow that has not been written onto does not cause an EOF at the other end.

### ISSUE THREAD

**Issue by TRIA** [IRATI/stack#1133]
When using rinacat to copy a zero-length file, the sending end terminates normally, but at the receiving end of the flow, the select() on reading from the flow does not complete to indicate EOF on the flow.  To repeat:

Source end:   
touch xx;  rinacat -l -A test <xx  

Destination end:  
rinacat -a test >xx-as-received  

The source (listening/source) end terminates normally, the destination end hangs indefinitely.

**Comment by TRIA** [comment]
The debug output of the test above at the source end: 
root@razzycam2:~# rinacat -l -A test <xx  
5033(1506427645)#librina.ctrldev (DBG): Wrote ctrl msg of 57 bytes to cfd 4  
5033(1506427645)#librina.ctrldev (DBG): Trying to read ctrl msg of 49 bytes  
5033(1506427645)#librina.ctrldev (DBG): Read ctrl msg of 49 bytes from cfd 4  
5033(1506427649)#librina.ctrldev (DBG): Trying to read ctrl msg of 119 bytes  
5033(1506427649)#librina.ctrldev (DBG): Read ctrl msg of 119 bytes from cfd 3  
5033(1506427649)#librina.ctrldev (DBG): Wrote ctrl msg of 24 bytes to cfd 3  
5033(1506427649)#librina.ctrldev (DBG): Wrote ctrl msg of 39 bytes to cfd 0  
5033(1506427649)#librina.ctrldev (DBG): Trying to read ctrl msg of 39 bytes  
5033(1506427649)#librina.ctrldev (DBG): Read ctrl msg of 39 bytes from cfd 0  

At the destination end:  
Opened control fd 3  
Running in Client mode, attempting to connect out to apn test  
14864(1506428467)#librina.ctrldev (DBG): Wrote ctrl msg of 109 bytes to cfd 4  
14864(1506428467)#librina.ctrldev (DBG): Trying to read ctrl msg of 57 bytes  
14864(1506428467)#librina.ctrldev (DBG): Read ctrl msg of 57 bytes from cfd 4

**Comment by edugrasa** [comment]
I've tried to recreate this behaviour and have not been able to (rinacat server also closes). I've also tried with the "chat mode" (server has no commands to execute), starting a client and then Ctrl-Cing it without having send any data: the server also stops. 

Client end:
````
root@e2-edu-vm2:/usr/local/irati/bin# ./rinacat -a test
WARNING: Default application name will be used: 'e2-edu-vm2.rinacat'
19355(1507107040)#librina.ctrldev (DBG): Wrote ctrl msg of 110 bytes to cfd 4
19355(1507107040)#librina.ctrldev (DBG): Trying to read ctrl msg of 58 bytes
19355(1507107040)#librina.ctrldev (DBG): Read ctrl msg of 58 bytes from cfd 4
^C
root@e2-edu-vm2:/usr/local/irati/bin# 
````

Server end:
````
root@e2-edu-vm3:/usr/local/irati/bin# ./rinacat -l -A test
11529(1507107036)#librina.ctrldev (DBG): Wrote ctrl msg of 57 bytes to cfd 4
11529(1507107036)#librina.ctrldev (DBG): Trying to read ctrl msg of 49 bytes
11529(1507107036)#librina.ctrldev (DBG): Read ctrl msg of 49 bytes from cfd 4
11529(1507107040)#librina.ctrldev (DBG): Trying to read ctrl msg of 120 bytes
11529(1507107040)#librina.ctrldev (DBG): Read ctrl msg of 120 bytes from cfd 3
11529(1507107040)#librina.ctrldev (DBG): Wrote ctrl msg of 24 bytes to cfd 3
11529(1507107048)#librina.ctrldev (DBG): Wrote ctrl msg of 39 bytes to cfd 0
11529(1507107048)#librina.ctrldev (DBG): Trying to read ctrl msg of 39 bytes
11529(1507107048)#librina.ctrldev (DBG): Read ctrl msg of 39 bytes from cfd 0
root@e2-edu-vm3:/usr/local/irati/bin# 
````

**Comment by edugrasa** [comment]
Closing, latest tests work
