### ISSUE TITLE
shim-eth-vlan: Use 802.1Q VLAN module symbols

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#120]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [salvestrini](https://github.com/salvestrini)**
_Monday Oct 21, 2013 at 10:19 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/117_

----

That would a) clean up the shim-eth-vlan b) auto-load 802.1Q module automatically ...

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Tuesday Oct 29, 2013 at 13:08 GMT_

----

Should automatically close #111

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Wednesday Nov 20, 2013 at 16:04 GMT_

----

Notes on #230 applies here. Watch out!

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Dec 13, 2013 at 12:56 GMT_

----

Why is this needed? It is autoloaded in userspace when you use 'ip link add ... ' to add a vlan. Setting up the VLAN is considered the enrollment phase. Or do you want the shim-eth-vlan to auto-create a new vlan interface?

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Friday Dec 13, 2013 at 13:32 GMT_

----

The latter. shim-eth-vlan to auto-create a new vlan interface would be good

**Comment by sandervrijders** [comment]
This can be closed since we are deprecating the shim-eth-vlan with the new shim-eth-llc #579
