### ISSUE TITLE
./rina-echo-time has some problem

### ISSUE THREAD

**Issue by ye1990** [IRATI/stack#1212]
In the experiment of Tutorial 1(: DIF over a VLAN (point to point DIF) ), Dif enrollment  is succesfully completed, but when i use the command "./rina-echo-time", it  appears two problems:  Failed to register application in DIF, Could not register application to any DIF.  How to solve?

**Comment by edugrasa** [comment]
Hi,

It's a problem of obsolete tutorial files, we'll fix that sorry. To fix your configuration, you can just go to the <IRATI installation path>/etc folder, and edit the "da.map" configuration file. Replace all 'normal.DIF' for 'Normal.DIF', and that should be it.

**Comment by edugrasa** [comment]
You're welcome!

Regarding your question it depends on what you want to do. You can find introductory and more advanced material at http://pouzinsociety.org/ (papers, tutorials, video presentations), at there is also John Day's book "Patters in Network Architecture". 

There are a number of people doing active research and development activities on RINA, you will be able to engage via mailing lists http://pouzinsociety.org/participate. Just tell us what are your interests and we will be able to provide some guidance.
