### ISSUE TITLE
Dynamic DIF Allocator

### ISSUE THREAD

**Issue by kciko** [IRATI/stack#1226]
I tried a simple scenario as Tutorial1 just to see if Dynamic DIF Allocation would work, but I got an error:

_root@ubuntu:~# cat /var/log/ipcm.log
...
21267(1532099681)#ipcm.dif-allocator (ERR): Unrecognized DIF Allocator type: , using default
.._
One short question: Is Dynamic DIF Allocation not implemented yet, or am I missing something?

The scenario works just fine when a manual enrollment to DIF is done.

**Comment by edugrasa** [comment]
Hi,

How did you configure the system to use the Dynamic DIF Allocator? The message says that you did not specify the Dynamic DIF Allocator, hence it uses the default one (which just reads the application to DIF mappings from the _IRATI installation path/etc/da.map_ file. 

I'll add the documentation on how to configure the different DIF Allocators and what they do.

**Comment by edugrasa** [comment]
I've just updated the documentation to include the DIF Allocator implementations and how to configure them: https://github.com/IRATI/stack#3211-dif-allocator

**Comment by kciko** [comment]
It worked, thanks.
