### ISSUE TITLE
RINA implementation between two systems connected by a vlan compatible switch

### ISSUE THREAD

**Issue by samsneelam1981** [IRATI/stack#1282]
Can anybody guide me in this issue. I am trying to connect two PCs over a router, but was unable to know how to configure intermediate router and to create DIFs in the router. Please help me in this issue. 
Thanks

**Comment by edugrasa** [comment]
Could you elaborate a bit? When you mean a router, do you mean a Linux system with the IRATI prototype installed? Or a commercial router that has no RINA software running?

**Comment by samsneelam1981** [comment]
Both systems(PCs) are installed with IRATI Stack. But the router is a commercial one. Both systems with IRATI Stack are connected through the router. In my case router is a commercial router that has no RINA software running on it.

**Comment by edugrasa** [comment]
Then you can't instantiate DIFs on the router, it has no RINA implementation running. If you are trying RINA over Ethernet with VLANs, all you can do is make sure the router is forwarding the packets tagged with the VLAN you have selected between the interfaces that connect to the two PCs. This has nothing to do with RINA, it is just configuring VLANs in the commercial router you are using.

**Comment by samsneelam1981** [comment]
So you mean i should use a router which supports VLAN tagging. In my case I am using a small domestic router DLink DIR-615 model with 4 ports. I searched for VLAN support in its setup, but was unable to find. Is there any proposal from you regarding the routers to be used. Thank you for your guidance so far.

**Comment by edugrasa** [comment]
Yeap, that's it, or use a Linux box with multiple network interfaces, install IRATI there and make it your router. 

If you go for the VLAN-aware router, we have used this one for some experiments in the past, for example: TP-Link 8-port Gigabit Easy Smart Switch (Model: TL-SG108E or similar; needs to be VLAN-capable). It's cheap (around 50 € or even less I think) and easy to configure via a web interface.

**Comment by samsneelam1981** [comment]
Thank you Edward

**Comment by samsneelam1981** [comment]
I have replaced my router with tp-link 8-port Gigabit Easy smart switch, and tried to establish the connection between two rina installed hosts. 
but I am unable to establish communication between two hosts by IRATI
Here with I am attaching the log details in host 1 and Host 2
Host-1: ipcm.log
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest fare.manifest
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest nsm-address-change.manifest
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest default.manifest
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest sm-auth-psoc.manifest
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest sm-example.manifest
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest sm-passwd.manifest
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest rina-default-plugin.manifest
23749(1566985836)#ipcm-catalog (INFO): Catalog: found manifest sm-cbac.manifest
23749(1566985836)#ipcm-catalog (WARN): Failed to open plugins directory: '/lib/modules/4.1.33-irati/extra'
23749(1566985836)#ipcm.dif-allocator (ERR): Unrecognized DIF Allocator type: , using default
23749(1566985836)#ipcm.dif-allocator (INFO): DIF Directory file: ../etc/da.map
23749(1566985836)#rinad.rina-configuration (WARN): Cannot open apps to DIF mappings file
23749(1566985836)#ipcm.dif-template-manager (INFO): Template folder: ../etc
23749(1566985836)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: default.dif
23749(1566985836)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shimeth.system1.100.dif
23749(1566985836)#ipcm (INFO)[create_ipcp]: IPC process eth.1.IPCP:1:: created and waiting for initialization[id = 1]

23749(1566985836)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 1] created

23749(1566985836)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process eth.1.IPCP:1:: to DIF 100:::

23749(1566985836)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process eth.1.IPCP:1:: [success=1]

23749(1566985836)#ipcm (INFO)[create_ipcp]: IPC process Normal.1.IPCP:1:: created and waiting for initialization[id = 2]

23749(1566985836)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 2] created

23749(1566985836)#ipcm.ipcp (INFO)[ipc_process_daemon_initialized_event_handler]: IPC process daemon initialized [id = 2]

23749(1566985836)#ipcm-catalog (INFO): Plugin 'rina-default-plugin' successfully loaded
23749(1566985836)#ipcm (INFO)[plugin_load]: Issued plugin-load to IPC process Normal.1.IPCP:1::

23749(1566985836)#ipcm.policies (INFO)[ipc_process_plugin_load_response_handler]: plugin-load-op [plugin=default, load=1] completed on IPC process Normal.1.IPCP:1:: [success=1]

23749(1566985836)#ipcm-catalog (INFO): Plugin 'default' successfully loaded
23749(1566985836)#ipcm-catalog (WARN): Catalog does not contain a policy-set called default for component errc
23749(1566985836)#ipcm-catalog (WARN): Failed to load policy-set errc/default
23749(1566985836)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process Normal.1.IPCP:1:: to DIF Normal.DIF:::

23749(1566985836)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process Normal.1.IPCP:1:: [success=1]

23749(1566985836)#ipcm (INFO)[register_at_dif]: Requested DIF registration of IPC process Normal.1.IPCP:1:: at DIF 100::: through IPC process eth.1.IPCP:1::

23749(1566985836)#ipcm.ipcp (INFO)[ipcm_register_response_ipcp]: IPC process Normal.1.IPCP:1:: informed about its registration to N-1 DIF 100:::

23749(1566986040)#ipcm (INFO)[enroll_to_dif]: Requested enrollment of IPC process Normal.1.IPCP:1:: to DIF Normal.DIF::: through DIF 100::: and neighbor IPC process :::

23749(1566986040)#ipcm.flow-alloc (INFO)[flow_allocation_requested_local]: IPC process eth.1.IPCP:1:: requested to allocate flow between Normal.1.IPCP:1:: and Normal.DIF:::

23749(1566986050)#ipcm.ipcp (ERR)[enroll_to_dif_response_event_handler]: : Error: Enrollment operation of process Normal.1.IPCP:1:: failed

23749(1566986182)#ipcm (INFO)[enroll_to_dif]: Requested enrollment of IPC process Normal.1.IPCP:1:: to DIF Normal.DIF::: through DIF 100::: and neighbor IPC process :::

23749(1566986182)#ipcm.flow-alloc (INFO)[flow_allocation_requested_local]: IPC process eth.1.IPCP:1:: requested to allocate flow between Normal.1.IPCP:1:: and Normal.DIF:::

23749(1566986192)#ipcm.ipcp (ERR)[enroll_to_dif_response_event_handler]: : Error: Enrollment operation of process Normal.1.IPCP:1:: failed


Host-1: Normal.1.IPCP-1.log

23755(1566985836)#ipcp[2].ipc-process (INFO): Librina initialized
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATION_FAILED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_DECLARED_DEAD
23755(1566985836)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
23755(1566985836)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_ALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_DEALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_ALLOCATION_FAILED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
23755(1566985836)#internal-events (INFO): EventListener subscribed to event CONNECTIVITY_TO_NEIGHBOR_LOST
23755(1566985836)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
23755(1566985836)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
23755(1566985836)#ipcp[2].normal-ipcp (INFO): Initialized IPC Process with name: Normal.1.IPCP, instance 1, id 2 
23755(1566985836)#ipcp[2] (INFO): IPC Process name:     Normal.1.IPCP
23755(1566985836)#ipcp[2] (INFO): IPC Process instance: 1
23755(1566985836)#ipcp[2] (INFO): IPC Process id:       2
23755(1566985836)#ipcp[2] (INFO): IPC Manager port:     1
23755(1566985836)#ipcp[2] (INFO): IPC Process type:     normal-ipc
23755(1566985836)#ipcp[2] (INFO): IPC Process initialized, executing event loop...
23755(1566985836)#librina.application (INFO): Plugin default loaded successfully
23755(1566985836)#librina.application (INFO): Pluggable component 'security-manager/default' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'security-manager/PSOC_authentication-none' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'flow-allocator/default' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'flow-allocator/RoundRobin' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'flow-allocator/qta-ps' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'namespace-manager/default' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'resource-allocator/default' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'enrollment-task/default' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'routing/link-state' [default] published
23755(1566985836)#librina.application (INFO): Pluggable component 'routing/static' [default] published
23755(1566985836)#ipcp (INFO): PDUFT Generator policy-set default added to the resource-allocator
23755(1566985836)#librina.application (INFO): Policy-set link-state selected for component routing
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_ADDED
23755(1566985836)#internal-events (INFO): EventListener subscribed to event CONNECTIVITY_TO_NEIGHBOR_LOST
23755(1566985836)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
23755(1566985836)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_ADDRESS_CHANGE
23755(1566985836)#librina.application (INFO): Policy-set default selected for component namespace-manager
23755(1566985836)#librina.application (INFO): Policy-set default selected for component security-manager
23755(1566985836)#librina.security-manager (INFO): Authentication policy-set PSOC_authentication-none added to the security-manager
23755(1566985836)#librina.application (INFO): Policy-set default selected for component flow-allocator
23755(1566985836)#librina.application (INFO): Policy-set default selected for component enrollment-task
23755(1566985836)#ipcp[2].enrollment-task (INFO): Could not parse use_reliable_n_flow, using default value: 0
23755(1566985836)#ipcp[2].resource-allocator (INFO): IPC Process registered to N-1 DIF 100
23755(1566986040)#librina.irm (INFO): Requested the allocation of N-1 flow to application Normal.DIF- through DIF 100
23755(1566986050)#ipcp[2].enrollment-task (ERR): An error happened during enrollment of remote IPC Process Normal.DIF--- because of N-1 Flow allocation timeout
23755(1566986182)#librina.irm (INFO): Requested the allocation of N-1 flow to application Normal.DIF- through DIF 100
23755(1566986192)#ipcp[2].enrollment-task (ERR): An error happened during enrollment of remote IPC Process Normal.DIF--- because of N-1 Flow allocation timeout

Host-1: Terminal-1
rinauser@rinauser:/usr/local/irati/bin$ sudo socat - UNIX:/usr/local/irati/var/run/ipcm-console.sock
[sudo] password for rinauser: 
IPCM >>> list-ipcps
Management Agent not started

Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | eth.1.IPCP:1:: | shim-eth-vlan | ASSIGNED TO DIF 100 | Normal.1.IPCP-1-- | -
    2 | Normal.1.IPCP:1:: | normal-ipc | ASSIGNED TO DIF Normal.DIF | - | -

IPCM >>> enroll-to-dif 2 Normal.DIF 100
Enrollment operation failed

IPCM >>> enroll-to-dif 2 Normal.DIF 100
Enrollment operation failed

IPCM >>> 

Host-1: Terminal-2
rinauser@rinauser:/usr/local/irati/bin$ ls
backtrace-demangler  ipcp          iporinad   key_managers  mgr-ctl      rina-bug-report  rina-cdap-echo   rina-echo-time  rina-mem-stats  tg-client
ipcm                 ipcp-plugins  irati-ctl  mac2ifname    net_manager  rinacat          rina-echo-async  rina-gw         rinaperf        tg-server
rinauser@rinauser:/usr/local/irati/bin$ sudo ./ipcm -c ../etc/ipcm.conf 
23749(1566985836)#ipcm (DBG): SIGSEGV handler installed successfully
23749(1566985836)#ipcm (DBG): SIGINT handler installed successfully
23749(1566985836)#ipcm (DBG): SIGQUIT handler installed successfully
23749(1566985836)#ipcm (DBG): SIGTERM handler installed successfully
23749(1566985836)#ipcm (DBG): SIGHUP handler installed successfully
23749(1566985836)#ipcm (DBG): SIGPIPE handler installed successfully
23749(1566985836)#ipcm (DBG): SIGCHLD handler installed successfully
23749(1566985836)#ipcm (DBG): Config file is: ../etc/ipcm.conf
23749(1566985836)#librina.timer (DBG): Timer with ID 10899120 started
23749(1566985836)#librina.logs (DBG): New log level: INFO
23755(1566985836)#ipcp[2] (DBG): SIGSEGV handler installed successfully
23755(1566985836)#ipcp[2] (DBG): SIGPIPE handler installed successfully
23755(1566985836)#ipcp[2] (DBG): SIGINT handler installed successfully
23755(1566985836)#librina.logs (DBG): New log level: INFO
  


Host-2: ipcm.log
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest fare.manifest
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest nsm-address-change.manifest
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest default.manifest
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest sm-example.manifest
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest sm-auth-psoc.manifest
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest sm-passwd.manifest
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest sm-cbac.manifest
1063(1566932733)#ipcm-catalog (INFO): Catalog: found manifest rina-default-plugin.manifest
1063(1566932733)#ipcm-catalog (WARN): Failed to open plugins directory: '/lib/modules/4.1.33-irati/extra'
1063(1566932733)#ipcm.dif-allocator (ERR): Unrecognized DIF Allocator type: , using default
1063(1566932733)#ipcm.dif-allocator (INFO): DIF Directory file: ../etc/da.map
1063(1566932733)#rinad.rina-configuration (WARN): Cannot open apps to DIF mappings file
1063(1566932733)#ipcm.dif-template-manager (INFO): Template folder: ../etc
1063(1566932733)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: default.dif
1063(1566932733)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shimeth.system2.100.dif
1063(1566932733)#ipcm (INFO)[create_ipcp]: IPC process eth.1.IPCP:1:: created and waiting for initialization[id = 1]

1063(1566932733)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 1] created

1063(1566932733)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process eth.1.IPCP:1:: [success=1]

1063(1566932733)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process eth.1.IPCP:1:: to DIF 100:::

1063(1566932733)#ipcm (INFO)[create_ipcp]: IPC process Normal.2.IPCP:1:: created and waiting for initialization[id = 2]

1063(1566932733)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 2] created

1063(1566932733)#ipcm.ipcp (INFO)[ipc_process_daemon_initialized_event_handler]: IPC process daemon initialized [id = 2]

1063(1566932733)#ipcm-catalog (INFO): Plugin 'rina-default-plugin' successfully loaded
1063(1566932733)#ipcm (INFO)[plugin_load]: Issued plugin-load to IPC process Normal.2.IPCP:1::

1063(1566932733)#ipcm.policies (INFO)[ipc_process_plugin_load_response_handler]: plugin-load-op [plugin=default, load=1] completed on IPC process Normal.2.IPCP:1:: [success=1]

1063(1566932733)#ipcm-catalog (INFO): Plugin 'default' successfully loaded
1063(1566932733)#ipcm-catalog (WARN): Catalog does not contain a policy-set called default for component errc
1063(1566932733)#ipcm-catalog (WARN): Failed to load policy-set errc/default
1063(1566932733)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process Normal.2.IPCP:1:: to DIF Normal.DIF:::

1063(1566932733)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process Normal.2.IPCP:1:: [success=1]

1063(1566932733)#ipcm (INFO)[register_at_dif]: Requested DIF registration of IPC process Normal.2.IPCP:1:: at DIF 100::: through IPC process eth.1.IPCP:1::

1063(1566932733)#ipcm.ipcp (INFO)[ipcm_register_response_ipcp]: IPC process Normal.2.IPCP:1:: informed about its registration to N-1 DIF 100:::

Host-2: Normal.2.IPCP-1.log
1070(1566932733)#ipcp[2].ipc-process (INFO): Librina initialized
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATION_FAILED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_DECLARED_DEAD
1070(1566932733)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
1070(1566932733)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_ALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_DEALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_ALLOCATION_FAILED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
1070(1566932733)#internal-events (INFO): EventListener subscribed to event CONNECTIVITY_TO_NEIGHBOR_LOST
1070(1566932733)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
1070(1566932733)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
1070(1566932733)#ipcp[2].normal-ipcp (INFO): Initialized IPC Process with name: Normal.2.IPCP, instance 1, id 2 
1070(1566932733)#ipcp[2] (INFO): IPC Process name:     Normal.2.IPCP
1070(1566932733)#ipcp[2] (INFO): IPC Process instance: 1
1070(1566932733)#ipcp[2] (INFO): IPC Process id:       2
1070(1566932733)#ipcp[2] (INFO): IPC Manager port:     1
1070(1566932733)#ipcp[2] (INFO): IPC Process type:     normal-ipc
1070(1566932733)#ipcp[2] (INFO): IPC Process initialized, executing event loop...
1070(1566932733)#librina.application (INFO): Plugin default loaded successfully
1070(1566932733)#librina.application (INFO): Pluggable component 'security-manager/default' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'security-manager/PSOC_authentication-none' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'flow-allocator/default' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'flow-allocator/RoundRobin' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'flow-allocator/qta-ps' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'namespace-manager/default' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'resource-allocator/default' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'enrollment-task/default' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'routing/link-state' [default] published
1070(1566932733)#librina.application (INFO): Pluggable component 'routing/static' [default] published
1070(1566932733)#ipcp (INFO): PDUFT Generator policy-set default added to the resource-allocator
1070(1566932733)#librina.application (INFO): Policy-set link-state selected for component routing
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_ADDED
1070(1566932733)#internal-events (INFO): EventListener subscribed to event CONNECTIVITY_TO_NEIGHBOR_LOST
1070(1566932733)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
1070(1566932733)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_ADDRESS_CHANGE
1070(1566932733)#librina.application (INFO): Policy-set default selected for component namespace-manager
1070(1566932733)#librina.application (INFO): Policy-set default selected for component security-manager
1070(1566932733)#librina.security-manager (INFO): Authentication policy-set PSOC_authentication-none added to the security-manager
1070(1566932733)#librina.application (INFO): Policy-set default selected for component flow-allocator
1070(1566932733)#librina.application (INFO): Policy-set default selected for component enrollment-task
1070(1566932733)#ipcp[2].enrollment-task (INFO): Could not parse use_reliable_n_flow, using default value: 0
1070(1566932733)#ipcp[2].resource-allocator (INFO): IPC Process registered to N-1 DIF 100

Host-2: Terminal-1
pi@raspberrypi:/usr/local/bin $ sudo ./ipcm -c ../etc/ipcm.conf 
1063(1566932733)#ipcm (DBG): SIGSEGV handler installed successfully
1063(1566932733)#ipcm (DBG): SIGINT handler installed successfully
1063(1566932733)#ipcm (DBG): SIGQUIT handler installed successfully
1063(1566932733)#ipcm (DBG): SIGTERM handler installed successfully
1063(1566932733)#ipcm (DBG): SIGHUP handler installed successfully
1063(1566932733)#ipcm (DBG): SIGPIPE handler installed successfully
1063(1566932733)#ipcm (DBG): SIGCHLD handler installed successfully
1063(1566932733)#ipcm (DBG): Config file is: ../etc/ipcm.conf
1063(1566932733)#librina.timer (DBG): Timer with ID 12002080 started
1063(1566932733)#librina.logs (DBG): New log level: INFO
1070(1566932733)#ipcp[2] (DBG): SIGSEGV handler installed successfully
1070(1566932733)#ipcp[2] (DBG): SIGPIPE handler installed successfully
1070(1566932733)#ipcp[2] (DBG): SIGINT handler installed successfully
1070(1566932733)#librina.logs (DBG): New log level: INFO

Host-2: Terminal-2

pi@raspberrypi:/usr/local/bin $ sudo socat - UNIX:/usr/local/var/run/ipcm-console.sock
IPCM >>> list-ipcps
Management Agent not started

Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | eth.1.IPCP:1:: | shim-eth-vlan | ASSIGNED TO DIF 100 | Normal.2.IPCP-1-- | -
    2 | Normal.2.IPCP:1:: | normal-ipc | ASSIGNED TO DIF Normal.DIF | - | -

IPCM >>> 


Can anyone help me in resolving this

Thank you

**Comment by edugrasa** [comment]
It looks like VLAN 100 is not configured on the switch?

You have to add VLAN 100 to the switch ports where you have attached the hosts running IRATI.

**Comment by samsneelam1981** [comment]
![Screenshot from 2019-09-18 11-21-02](https://user-images.githubusercontent.com/48311499/65116495-822a9b00-da06-11e9-8a21-ac6e09a34a8c.png)
![Screenshot from 2019-09-18 11-21-24](https://user-images.githubusercontent.com/48311499/65116536-8a82d600-da06-11e9-9507-3889d3f577ed.png)

This is how I configured the switch. still unable to establish the connection between two hosts.
Can anybody help

**Comment by edugrasa** [comment]
We can try a remote debugging session. If you email me to eduard.grasa@i2cat.net we can arrange a date and a time that suits both.

**Comment by samsneelam1981** [comment]
Thank you

**Comment by samsneelam1981** [comment]
The solution lies in 
1. configuring ethernet switch properly. VLAN configuration shuold have ports tagged to that particular VLAN name which i missed and kept untagged. 
2. Configuration of VLAN interface with an IP relavant to the particular domain range. 

Thanks Eduard for the help.
