### ISSUE TITLE
failed to open config file

### ISSUE THREAD

**Issue by musaddiq13** [IRATI/stack#1283]
hi
i am running ubuntu 16.04 and trying to configure the irati stack but when i reach the Running the IPC Manager Daemon and run the first command it gives me an error of failed to open config file
running the command: ./ipcm -c /home/user/irati/etc/ipcmanager.conf
![image](https://user-images.githubusercontent.com/49472714/55858901-e1e06880-5b81-11e9-8eea-4154c5ac31b4.png)

Please help

**Comment by edugrasa** [comment]
Hi,

You pointed to the wrong config file. The command should have been:

````
sudo ./ipcm -c /home/user/irati/etc/ipcmanager.conf
````

You run:

````
sudo ./ipcm -c home/user/irati/etc/ipcmanager.conf.orig
````
