### ISSUE TITLE
Installation Problem on Raspberry Pi with Raspbian Stretch

### ISSUE THREAD

**Issue by samsneelam1981** [IRATI/stack#1297]
When I am trying to 
"sudo make install" after configuration, I am getting the following results. 
My kit is Raspberry Pi-3 b and the operating system is Raspbian Buster. 

pi@raspberrypi:~/stack $ sudo make install 
make: the '-j' option requires a positive integer argument
cd kernel && make && make install
make[1]: Entering directory '/home/pi/stack/kernel'
make -C /lib/modules/4.19.66-v7+/build CONFIG_RINA_DTCP_RCVR_ACK=y CONFIG_RINA_DTCP_RCVR_ACK_ATIMER=n REGRESSION_TESTS=n HAVE_VMPI=n TCP_UDP_BUFFER_SIZE=1500 M=/home/pi/stack/kernel modules
make[2]: Entering directory '/usr/src/linux-headers-4.19.66-v7+'
  CC [M]  /home/pi/stack/kernel/ipcps/shim-tcp-udp.o
/home/pi/stack/kernel/ipcps/shim-tcp-udp.c: In function ‘tcp_udp_rcv_process_msg’:
/home/pi/stack/kernel/ipcps/shim-tcp-udp.c:1699:13: error: too many arguments to function ‘kernel_getsockname’
         if (kernel_getsockname(sock, &own.sa, &len)) {
             ^~~~~~~~~~~~~~~~~~
In file included from ./include/linux/skbuff.h:29,
                 from ./include/net/net_namespace.h:36,
                 from ./include/linux/inet.h:46,
                 from /home/pi/stack/kernel/ipcps/shim-tcp-udp.c:33:
./include/linux/net.h:299:5: note: declared here
 int kernel_getsockname(struct socket *sock, struct sockaddr *addr);
make[4]: *** [scripts/Makefile.build:310: /home/pi/stack/kernel/ipcps/shim-tcp-udp.o] Error 1
make[3]: *** [scripts/Makefile.build:544: /home/pi/stack/kernel/ipcps] Error 2
make[2]: *** [Makefile:1519: _module_/home/pi/stack/kernel] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.19.66-v7+'
make[1]: *** [Makefile:12: all] Error 2
make[1]: Leaving directory '/home/pi/stack/kernel'
make: *** [Makefile:42: ker_install] Error 2
---

Can you please help me in this regard.

**Comment by samsneelam1981** [comment]
Solved by modifying ‘kernel_getsockname' function in **/home/pi/stack/kernel/ipcps/shim-tcp-udp.c** according to its definition in **./include/linux/net.h**
In /home/pi/stack/kernel/ipcps/shim-tcp-udp.c  - Change 
**if (kernel_getsockname(sock, &own.sa, &len))** ->**if (kernel_getsockname(sock, &own.sa))**

Problem is solved

And the other problem I faced is 
from _**/home/pi/stack/kernel/dtp.c:1565:47: error: Implicit declaration of function 'local_softirq_pending' [-Werror=implicit-function-declaration]
                      LOG_DBG("local_soft_irq_pending:  %d", local_softirq_pending());**_

The Solution for this is 
insert #include <linux/interrupt.h>
 in the definition file for the log messages
 /home/pi/stack/kernel/logs.h 
And add #include <linux/uaccess.h>
in /home/pi/stack/kernel/dtp.c

The problem solved and I installed IRATI on my Raspberry Pi 3B with Raspbian Stretch 

Thank you

**Comment by edugrasa** [comment]
Thanks for posting the fix! I'll reopen the issue to address it in the IRATI source code, adding the fix for the specific kernel version. 

If I'm not wrong, the change to the kernel_getsockname API comes from kernel version 4.17+. Will add this in short.

**Comment by samsneelam1981** [comment]
Yes, Thank you @edugrasa

**Comment by edugrasa** [comment]
Fixed by #1298
