### ISSUE TITLE
DIF over a VLAN - Shim IPCP not assigning to SHIM DIF

### ISSUE THREAD

**Issue by avoskanian** [IRATI/stack#1305]
When I follow tutorial 1 "DIF over a VLAN", I can't manage to have the Shim IPCP assigned to my Shim DIF.

I created my VLAN:
sudo ip link add link ens19 name eth1.101 type vlan id 101
sudo ip link set dev eth1.101 up

Attached are the irati config files:

[default.dif.txt](https://github.com/IRATI/stack/files/3885437/default.dif.txt)
[ipcm.conf.txt](https://github.com/IRATI/stack/files/3885438/ipcm.conf.txt)
[shimeth.dif.txt](https://github.com/IRATI/stack/files/3885439/shimeth.dif.txt)

And when I check the IPCPs here is what I have:

Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | SRER.IPCP:1:: | shim-eth-vlan | INITIALIZED | - | -
    2 | SR.IPCP:1:: | normal-ipc | ASSIGNED TO DIF g.DIF | - | -

Also I work on a VM, and the net card is virtio.

**Comment by edugrasa** [comment]
Hi Annie,

I guess that the interface name is "ens19",  right? Notice that the syntax of the IP link command is

ip link add link **interface_name** name **interface_name.vlan_id** type vlan id **vlan_id**

Hence, it should be 
    
    sudo ip link add link ens19 name ens19.101 type vlan id 101
    sudo ip link set dev ens19.101 up

Cheers

**Comment by avoskanian** [comment]
Oh ok thank you Eduard! Sorry for the stupid mistake :) It works now.
