### ISSUE TITLE
Add support for Linux kernel version 5.x

### ISSUE THREAD

**Issue by RaroHub** [IRATI/stack#1310]
make[2]: Entering directory '/usr/src/linux-headers-5.0.0-37-generic'
  CC [M]  /home/stack/kernel/dtcp.o
/home/stack/kernel/dtcp.c: In function ‘dtcp_rate_exceeded’:
/home/stack/kernel/dtcp.c:1345:8: error: implicit declaration of function ‘timespec_sub’; did you mean ‘timespec64_sub’? [-Werror=implicit-function-declaration]
  sub = timespec_sub(now, last);
        ^~~~~~~~~~~~
        timespec64_sub
/home/stack/kernel/dtcp.c:1345:6: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
  sub = timespec_sub(now, last);
      ^

**Comment by edugrasa** [comment]
I see you are trying to compile with kernel version 5, only 4.x is supported for now. However, I'll try to update the kernel modules to support 5.0 in the next few days.

**Comment by TRIA** [comment]
This particular problem with building the stack on 5.x kernels is fixed, as reported in issue #1326, but there are still functional errors being worked on for 5.x kernels.  So although the stack currently (2020 Sept. 22) builds, you will likely encounter runtime problems and should hold off using the stack on 5.x kernels for now.

**Comment by TRIA** [comment]
As of #1335, we have been compiling and running the stack successfully on 5.2 Linux kernels.  Testing has not been exhaustive, but no new problems have been seen.  This can probably be closed.

**Comment by edugrasa** [comment]
Thnaks @TRIA, let's close it for  now and reopen if we find more bugs!
