### ISSUE TITLE
Ubuntu 18,04 build error in kernel/sdup-crypto-ps-default.c

### ISSUE THREAD

**Issue by TRIA** [IRATI/stack#1331]
In file kernel/sdup-crypto-ps-default.c, there are two instances of:
shash->flags = 0;

The flags field is not present in that data structure in the kernel used in 18.04, so the build fails with syntax errors on those two lines.  It has been confirmed that removing the two lines allows the kernel to build, but it has not been confirmed whether removing them will break earlier kernels.  Therefore, it should be confirmed that the flags field has never been used (or defaults to an acceptable value) so that the lines can be unconditionally removed, or the fix should be made conditional on kernel or crypto library version.

Build error:
  CC [M]  /stack/kernel/sdup-crypto-ps-default.o
/stack/kernel/sdup-crypto-ps-default.c: In function ‘add_hmac’:
/stack/kernel/sdup-crypto-ps-default.c:409:7: error: ‘struct shash_desc’ has no member named ‘flags’
  shash->flags = 0;
       ^~
/stack/kernel/sdup-crypto-ps-default.c: In function ‘check_hmac’:
/stack/kernel/sdup-crypto-ps-default.c:451:7: error: ‘struct shash_desc’ has no member named ‘flags’
  shash->flags = 0;
       ^~
scripts/Makefile.build:288: recipe for target '/stack/kernel/sdup-crypto-ps-default.o' failed
make[3]: *** [/stack/kernel/sdup-crypto-ps-default.o] Error 1
Makefile:1664: recipe for target '_module_/stack/kernel' failed

OS Version:
/stack$ uname -a
Linux silverL1 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by edugrasa** [comment]
@TRIA this issue should have been fixed by PR #1329, could you check if your branch contains this code? (it is already merged onto master) 
Thanks!

**Comment by TRIA** [comment]
Confirming that this is fixed by PR #1329, I was on a stale branch.  Closed.

**Comment by TRIA** [comment]
Yes, that fixes #1331.  I was indeed on a branch that did not have that fix.  Sorry!
I closed #1331 as fixed.

Steve
