### ISSUE TITLE
Executing rina-echo-time causes trouble

### ISSUE THREAD

**Issue by joholly** [IRATI/stack#1339]
Hello,

I installed IRATI on two Ubuntu machines (16.04.07). The kernel version is 4.15.0-117-generic on both machines. 
I tried to go through the first Tutorial "1. DIF-over-a-VLAN-(point-to-point-DIF)".  The configuration of both systems went well.

(Configuration of system 1)
![Configuration System 1](https://user-images.githubusercontent.com/79869667/109546669-cdd1e700-7aca-11eb-92d3-58085930bd54.PNG)
(Configuration of System 2)
![Configuration system 2](https://user-images.githubusercontent.com/79869667/109546673-ce6a7d80-7aca-11eb-9d74-90129b50671c.PNG)

The enrollment of IPC processes in the normal DIF went well, too.  

I started the rina-echo-time server on system 2.
![rina-echo-time -l started](https://user-images.githubusercontent.com/79869667/109547273-78e2a080-7acb-11eb-872a-2b9c17e88b93.PNG)
It was registered to the normal DIF as well.
![rina-echo-time -l registered in DIF](https://user-images.githubusercontent.com/79869667/109547418-a16a9a80-7acb-11eb-8bd4-42f8743912c7.PNG)

When I tried to run the rina-echo-time client, I recieved the following error messages:
![rina-echo-time -c 100 ERROR](https://user-images.githubusercontent.com/79869667/109548207-a4b25600-7acc-11eb-80de-8047c73f06ce.PNG)

The Output of the Server in system 2 was:
![rina-echo-time -l recieved message](https://user-images.githubusercontent.com/79869667/109548519-070b5680-7acd-11eb-8620-e7716b1342c5.PNG)

Can anyone tell me, how to fix this problem?

Thank you

**Comment by edugrasa** [comment]
Hi,

The rina-echo-time application has not been updated for a while, I'd recommend using the rinaperf application instead. To use rinaperf to do the equivalent thing you were trying to achieve with rina-echo-time, please do the following:

- Server side: ./rinaperf -l
- Client side: ./rinaperf -t ping -c 100

You can execute ./rinaperf -h for the full list of options that rinaperf accepts. I hope that helps :)

**Comment by joholly** [comment]
Hi,

rinaperf is working, but there isn't any output on the console, where rinaperf is running on server mode. Is that normal?

console of the client:
![image](https://user-images.githubusercontent.com/79869667/111617569-93af5780-87e3-11eb-9466-2346b169035c.png)

console of the server:
![image](https://user-images.githubusercontent.com/79869667/111617622-a4f86400-87e3-11eb-8e42-85e4c58cd530.png)

**Comment by edugrasa** [comment]
Yes, this is normal. If you want to see more output to the console, you can run the server with the -v flag (rinaperf -l -v).

**Comment by joholly** [comment]
Alright :). Thank you for your help :)
