### ISSUE TITLE
Add smart pointers to avoid problems when SDU's have to be destroyed in read/write operations. Change kfa_sdu_post and shims (at least) accordingly.

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#173]
<a href="https://github.com/miqueltarzan"><img src="https://avatars.githubusercontent.com/u/3428055?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [miqueltarzan](https://github.com/miqueltarzan)**
_Monday Oct 28, 2013 at 18:47 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/170_

----

**Comment by edugrasa** [comment]
Closing, since the whole SDU fast path in the kernel will be updated by #580
