### ISSUE TITLE
kernel: the struct sdu has to be hidden

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#179]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [salvestrini](https://github.com/salvestrini)**
_Wednesday Oct 30, 2013 at 17:44 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/176_

----

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Monday Jun 09, 2014 at 09:49 GMT_

----

Why has this issue been closed? It seems to me it is currently
not-completed (looking at the porting branch)...

**Comment by edugrasa** [comment]
Closing, since the kernel SDU data path will be redesigned by #580
