### ISSUE TITLE
Failure to add name in ARP table

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#242]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Nov 26, 2013 at 13:21 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/239_

----

[  147.558820] rina-rnl: IPC Manager port: 1
[  147.558891] rina-rnl-utils: Result of genlmesg_end: 32
[  147.559087] rina-rnl-utils: Going to send NL unicast message (type = 28, seq-num 0, port = 1)
[  147.559191] rina-rnl-utils: Unicast NL message sent (type = 28, seq-num 0, port = 1)
[  147.559308] rina-rnl: IPC Manager port: 1
[  147.559375] rina-rnl-utils: Result of genlmesg_end: 32
[  147.559443] rina-rnl-utils: Going to send NL unicast message (type = 28, seq-num 0, port = 1)
[  147.559535] rina-rnl-utils: Unicast NL message sent (type = 28, seq-num 0, port = 1)
[  165.690008] rina-rnl: IPC Manager port: 1
[  165.690083] rina-rnl-utils: Result of genlmesg_end: 32
[  165.690151] rina-rnl-utils: Going to send NL unicast message (type = 28, seq-num 0, port = 1)
[  165.690244] rina-rnl-utils: Unicast NL message sent (type = 28, seq-num 0, port = 1)
[  165.691195] rina-rnl: IPC Manager port: 1
[  165.691263] rina-rnl-utils: Result of genlmesg_end: 32
[  165.691331] rina-rnl-utils: Going to send NL unicast message (type = 28, seq-num 0, port = 1)
[  165.691423] rina-rnl-utils: Unicast NL message sent (type = 28, seq-num 0, port = 1)
[  166.406566] rina-rnl: Dispatching message (skb-in=f6e8ee80, info=ee92fcc4)
[  166.406644] rina-rnl: Multiplexing message type 18
[  166.406712] rina-rnl: Fetching handler callback and data
[  166.406782] rina-rnl: Gonna call f84f6426(ee6124c0, f6e8ee80, ee92fcc4)
[  166.406911] rina-rnl-utils: RINA Netlink parser started ...
[  166.406980] rina-rnl-utils: msg at ef32b740 / msg->attrs at f6e357c0
[  166.407049] rina-rnl-utils:   src-ipc-id: 0
[  166.407114] rina-rnl-utils:   dst-ipc-id: 1
[  166.407182] rina-ipcp-utils: Name at f71132c0 finalized successfully
[  166.407253] rina-ipcp-utils: Name at f6c3f320 finalized successfully
[  166.407325] rina-ipcp-utils: Copying name f71132c0 into f724b8c0
[  166.407394] rina-ipcp-utils: Name at f724b8c0 finalized successfully
[  166.407464] rina-ipcp-utils: Name f71132c0 copied successfully into f724b8c0
[  166.407540] rina-arp826-tables: Adding GPA/GHA couple to the 0xd1f0 ptype table
[  166.407626] rina-arp826-tables: Cannot add GPA/GHA couple, there is no table for ptype 0xd1f0
[  166.407714] rina-shim-eth-vlan: Failed to register application in ARP
[  166.407784] rina-ipcp-utils: Name at f724b8c0 finalized successfully
[  166.407853] rina-ipcp-utils: Name at f724b8c0 destroyed successfully
[  166.407923] rina-ipcp-utils: Name at f71132c0 finalized successfully
[  166.407993] rina-ipcp-utils: Name at f71132c0 destroyed successfully
[  166.408062] rina-ipcp-utils: Name at f6c3f320 finalized successfully
[  166.408132] rina-ipcp-utils: Name at f6c3f320 destroyed successfully
[  166.408205] rina-rnl-utils: Result of genlmesg_end: 32
[  166.408273] rina-rnl-utils: Going to send NL unicast message (type = 19, seq-num 1385471981, port = 1)
[  166.408368] rina-rnl-utils: Unicast NL message sent (type = 19, seq-num 1385471981, port = 1)
[  166.408455] rina-rnl: Message 18 handled successfully
[  166.432594] rina-rnl: IPC Manager port: 1
[  166.432666] rina-rnl-utils: Result of genlmesg_end: 32
[  166.432741] rina-rnl-utils: Going to send NL unicast message (type = 28, seq-num 0, port = 1)
[  166.432833] rina-rnl-utils: Unicast NL message sent (type = 28, seq-num 0, port = 1)

**Comment by kewinrausch** [comment]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Wednesday Nov 27, 2013 at 07:52 GMT_

----

This is due to the way ARP-826 works. If you configure the VLAN after loading the ARP-826 modules you'll get this error, since ARP-826 only works with the device drivers presents in the system when the ARP-826 module is loaded. 

To fix this ARP-826 needs to get notifications of when device drivers are added/removed in the system. I think I would close the issue for now?

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Wednesday Nov 27, 2013 at 09:03 GMT_

----

Let's keep it open, to avoid forgetting bits here and there

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Wednesday Nov 27, 2013 at 09:04 GMT_

----

Yes, it's already there as #100. Silly I didn't think of the why behind
the error :)

On 11/27/2013 08:52 AM, Eduard Grasa wrote:
> This is due to the way ARP-826 works. If you configure the VLAN after loading the ARP-826 modules you'll get this error, since ARP-826 only works with the device drivers presents at the system when the ARP-826 module is loaded. 
> 
> To fix this ARP-826 needs to get notifications of when device drivers are added/removed in the system. I think I would close the issue for now?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dana-i2cat/irati/issues/239#issuecomment-29365797
> 

-- 
Sander Vrijders
Department of Information Technology
Internet Based Communication Networks and Services (IBCN)
Ghent University - iMinds
Gaston Crommenlaan 8 (Bus 201), B-9050 Gent, Belgium
T: +32 9 33 14977 ; T Secr: +32 9 33 14900
F: +32 9 33 14899
E: sander.vrijders@intec.UGent.be
W : www.ibcn.intec.UGent.be

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Dec 13, 2013 at 15:10 GMT_

----

Do we need to create a table for every device in the system? Maybe only the ones a shim-eth-vlan is using. That way we can create the tables with a call from the shim-eth-vlan's assign_to_dif operation.

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Tuesday Jun 10, 2014 at 07:48 GMT_

----

This issue is not closed at all, re-opening

**Comment by sandervrijders** [comment]
To be fixed in #579

**Comment by vmaffione** [comment]
@sandervrijders @vmaffione this should be fixed by making assign_to_dif create the ARP table

**Comment by edugrasa** [comment]
Fixed by #891
