### ISSUE TITLE
Make 'connection' struct internal to EFCP 

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#264]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Thursday Jan 16, 2014 at 13:35 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/261_

----

**Comment by sandervrijders** [comment]
@lbergesio Has there been any work done on this?

**Comment by edugrasa** [comment]
Foxed by #671
