### ISSUE TITLE
Sysfs support for monitoring of connections has to be added

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#276]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Wednesday Jan 22, 2014 at 15:56 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/273_

----

**Comment by edugrasa** [comment]
Closing, duplicated
