### ISSUE TITLE
Kernel bangs when running echo-client in a DIF that was not enrolled yet 

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#284]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Feb 04, 2014 at 13:42 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/281_

----

[  675.927191] rina-ipcp-utils: Name at f70196e0 finalized successfully
[  675.927261] rina-ipcp-utils: Name at f70196e0 destroyed successfully
[  675.966022] rina-syscalls: Handling personality hook deallocate_port
[  675.966082] rina-syscalls: Calling personality hook deallocate_port
[  675.966140] rina-personality-default: Calling wrapped function
[  675.966198] rina-kfa: We are destroying a flow
[  675.966253] rina-pidm: Bitmap release completed successfully
[  675.966331] ------------[ cut here ]------------
[  675.966386] kernel BUG at net/rina/kfa.c:327!
[  675.966441] invalid opcode: 0000 [#4] SMP 
[  675.966561] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc coretemp kvm_intel kvm psmouse iTCO_wdt ioatdma gpio_ich iTCO_vendor_support pcspkr serio_raw i2c_i801 microcode lpc_ich i7core_edac edac_core hid_generic usbmouse usbkbd usbhid hid igb i2c_algo_bit dca ptp pps_core
[  675.968249] CPU: 6 PID: 3473 Comm: java Not tainted 3.10.0-test996 #4
[  675.968308] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
[  675.968368] task: f379e600 ti: f376e000 task.ti: f376e000
[  675.968425] EIP: 0060:[<f82e4cdb>] EFLAGS: 00010246 CPU: 6
[  675.968488] EIP is at kfa_flow_destroy.isra.2+0x9b/0xd0 [rina_personality_default]
[  675.968562] EAX: 00000000 EBX: 00000000 ECX: f55d4824 EDX: 00000007
[  675.968620] ESI: f49e51c0 EDI: f70194d8 EBP: f376ff6c ESP: f376ff54
[  675.968678]  DS: 007b ES: 007b FS: 00d8 GS: 00e0 SS: 0068
[  675.968736] CR0: 80050033 CR2: 7b15b130 CR3: 3373b000 CR4: 000007d0
[  675.968794] DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
[  675.968852] DR6: ffff0ff0 DR7: 00000400
[  675.968905] Stack:
[  675.968956]  f82eb4c0 f82ee31c f70194d4 f70194d0 00000001 b77099c0 f376ff84 f82e4e0e
[  675.969292]  00000001 00000000 f82ee31c b678df60 f376ff98 f82e89a0 f82eca1c 00000001
[  675.969629]  00000001 f376ffac c1592b7e c17d41e4 c17ce370 00000001 f376e000 c15b90a1
[  675.969964] Call Trace:
[  675.970022]  [<f82e4e0e>] kfa_flow_deallocate+0x9e/0x100 [rina_personality_default]
[  675.970100]  [<f82e89a0>] default_deallocate_port+0x40/0x60 [rina_personality_default]
[  675.970180]  [<c1592b7e>] SyS_deallocate_port+0x5e/0x90
[  675.970238]  [<c15b90a1>] sysenter_do_call+0x12/0x22
[  675.970294] Code: c9 74 09 8b 55 08 ff d1 85 c0 75 0a 31 c0 83 c4 0c 5b 5e 5f 5d c3 c7 04 24 58 b5 2e f8 e8 07 3e 2c c9 83 c8 ff eb e7 0f 0b 0f 0b <0f> 0b 8b 45 08 c7 04 24 24 b5 2e f8 89 44 24 04 e8 e9 3d 2c c9
[  675.972524] EIP: [<f82e4cdb>] kfa_flow_destroy.isra.2+0x9b/0xd0 [rina_personality_default] SS:ESP 0068:f376ff54
[  675.972684] ---[ end trace f0da646656362de9 ]---
[  675.972959] rina-rnl-utils: Result of genlmesg_end: 32

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Jun 06, 2014 at 08:49 GMT_

----

Fixed by Miquel? But not referenced from commit.

**Comment by vmaffione** [comment]
Not reproducible anymore.
