### ISSUE TITLE
Netlink parse error when using rinaperf over shim eth

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#333]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Thursday Mar 27, 2014 at 15:50 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/330_

----

[ 3783.469659] rina-rnl-utils: Could not format rnl_ipcm_alloc_flow_req_arrived_msg message correctly
[ 3783.469755] rina-shim-eth-vlan: Couldn't tell the KIPCM about the flow
[ 3783.469826] rina-kfa: Instance ef7308a0 SDU-ready FIFO is NULL

**Comment by vmaffione** [comment]
Bug not present anymore.
