### ISSUE TITLE
Destroying flow in KFA doesn't take into account all the cases

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#334]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [edugrasa](https://github.com/edugrasa)**
_Thursday Mar 27, 2014 at 17:14 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/331_

----

Some cases are not handled properly, like when the flow is destroyed but there are SDUs in the KFA flow structure queue. Also, freeing the port-id number and destroying the flow data structures is not an atomic operation, which may bring problems sometimes.

(Suspect that a flow queue may end up being part of another flow, as Sander has experienced while testing with rinaperf.)

**Comment by sandervrijders** [comment]
@miqueltarzan Can you fix this bug?

**Comment by lbergesio** [comment]
This one is very old and outdated, @miqueltarzan please confirm it can be closed

**Comment by miqueltarzan** [comment]
Yes, it's old and fixed.
