### ISSUE TITLE
Calling updatedifconf without an argument on the shim-eth-vlan causes a panic

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#335]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Monday Apr 14, 2014 at 14:22 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/332_

----

[ 1857.697949] PGD 336aa6067 PUD 338736067 PMD 0 
[ 1857.697969] Oops: 0000 [#4] SMP 
[ 1857.697983] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 w83781d hwmon_vid i2c_piix4 nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop iTCO_wdt iTCO_vendor_support coretemp kvm_intel kvm i7core_edac snd_pcm snd_timer snd ioatdma edac_core soundcore lpc_ich acpi_cpufreq ehci_pci crc32c_intel microcode i2c_i801 psmouse serio_raw pcspkr mfd_core processor tpm_tis thermal_sys button tpm joydev evdev ext3 mbcache jbd sg sd_mod crc_t10dif crct10dif_common hid_generic ata_generic usbhid hid ata_piix uhci_hcd libata ehci_hcd scsi_mod usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
[ 1857.698306] CPU: 1 PID: 3696 Comm: java Not tainted 3.14.0-v64 #4
[ 1857.698321] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
[ 1857.698339] task: ffff8801b90e1330 ti: ffff88003723a000 task.ti: ffff88003723a000
[ 1857.698357] RIP: 0010:[<ffffffff8110263b>]  [<ffffffff8110263b>] __cache_free.isra.45+0x25/0x1ae
[ 1857.698381] RSP: 0018:ffff88003723b9a8  EFLAGS: 00010002
[ 1857.698395] RAX: 0000000000000001 RBX: 0000000000000282 RCX: 00000000c0000100
[ 1857.698426] RDX: 0100000000000000 RSI: ffff88003723ba20 RDI: 0000000000000000
[ 1857.698457] RBP: ffff88003723ba20 R08: ffff88003723a000 R09: 0000000000000000
[ 1857.698488] R10: 0000000000000020 R11: 0000000000000004 R12: 0000000000000000
[ 1857.698519] R13: ffff88003723ba20 R14: ffff8801b5c67a80 R15: ffff8801b815a3a0
[ 1857.698550] FS:  00007fc42ac0e700(0000) GS:ffff8801bfc20000(0000) knlGS:0000000000000000
[ 1857.698597] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 1857.698625] CR2: 0000000000000088 CR3: 0000000337609000 CR4: 00000000000007e0
[ 1857.698656] Stack:
[ 1857.698677]  ffff8801b815a660 ffff8801b80e9ac0 ffff8801b815a660 0000000000000282
[ 1857.698732]  ffff88003723ba20 ffffffffa03a219c ffff8801b815a660 ffff8801b5c67a80
[ 1857.698787]  ffff8801b815a3a0 ffffffff81102cc1 ffff8801b5c39480 ffff8801b815a660
[ 1857.698842] Call Trace:
[ 1857.698869]  [<ffffffffa03a219c>] ? eth_vlan_update_dif_config+0xa9/0x1ba [shim_eth_vlan]
[ 1857.698917]  [<ffffffff81102cc1>] ? kfree+0x50/0x67
[ 1857.698947]  [<ffffffffa03a219c>] ? eth_vlan_update_dif_config+0xa9/0x1ba [shim_eth_vlan]
[ 1857.698998]  [<ffffffffa0393c17>] ? notify_ipcp_update_dif_config_request+0xba/0x122 [rina_personality_default]
[ 1857.699052]  [<ffffffffa0393b5d>] ? notify_ipcp_register_app_request+0x120/0x120 [rina_personality_default]
[ 1857.699107]  [<ffffffff81383ff1>] ? dispatcher+0x12b/0x163
[ 1857.699137]  [<ffffffff812f809a>] ? genl_family_rcv_msg+0x235/0x2a2
[ 1857.699170]  [<ffffffff81043555>] ? __mod_timer+0xfa/0x10c
[ 1857.699199]  [<ffffffff812f813f>] ? genl_rcv_msg+0x38/0x5b
[ 1857.699230]  [<ffffffff812c7f0a>] ? __kmalloc_reserve.isra.42+0x2a/0x6d
[ 1857.699261]  [<ffffffff812f8107>] ? genl_family_rcv_msg+0x2a2/0x2a2
[ 1857.699293]  [<ffffffff812f6f99>] ? netlink_rcv_skb+0x36/0x7c
[ 1857.699323]  [<ffffffff812f7166>] ? genl_rcv+0x1f/0x2c
[ 1857.699352]  [<ffffffff812f6a5d>] ? netlink_unicast+0xff/0x17f
[ 1857.699383]  [<ffffffff812f6dc1>] ? netlink_sendmsg+0x2e4/0x312
[ 1857.699414]  [<ffffffff812c1fc6>] ? sock_sendmsg+0x49/0x64
[ 1857.699444]  [<ffffffff812c2966>] ? move_addr_to_kernel+0x2e/0x53
[ 1857.699475]  [<ffffffff812cbd8e>] ? verify_iovec+0x4c/0x9a
[ 1857.699504]  [<ffffffff812c28ae>] ? ___sys_sendmsg+0x1e7/0x271
[ 1857.699536]  [<ffffffff813985c0>] ? __do_page_fault+0x33a/0x3e0
[ 1857.699567]  [<ffffffff812bffa2>] ? sock_do_ioctl+0x1b/0x36
[ 1857.699596]  [<ffffffff812c03b3>] ? sock_ioctl+0x1f9/0x204
[ 1857.699627]  [<ffffffff8111bee0>] ? do_vfs_ioctl+0x3ed/0x436
[ 1857.699657]  [<ffffffff812c2c3a>] ? __sys_sendmsg+0x39/0x57
[ 1857.699687]  [<ffffffff8139a7e2>] ? system_call_fastpath+0x16/0x1b
[ 1857.699716] Code: 5c 41 5d 41 5e c3 41 57 41 56 41 55 49 89 f5 41 54 49 89 fc 55 53 48 83 ec 18 65 8b 04 25 c4 b0 00 00 83 3d df 2f 59 00 01 48 98 <48> 8b 9c c7 80 00 00 00 0f 8e d2 00 00 00 b8 00 00 00 80 48 ba 
[ 1857.699943] RIP  [<ffffffff8110263b>] __cache_free.isra.45+0x25/0x1ae
[ 1857.699977]  RSP <ffff88003723b9a8>
[ 1857.700000] CR2: 0000000000000088
[ 1857.700357] ---[ end trace a12a73a98fb34907 ]---

**Comment by edugrasa** [comment]
Does not happen in pristine-1.4 anymore
