### ISSUE TITLE
Kernel dump related to RINARP

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#357]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Thursday Jul 24, 2014 at 13:07 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/354_

----

Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] INFO: rcu_sched self-detected stall on CPU { 0}  (t=15000 jiffies g=18338 c=18337 q=5139)
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] sending NMI to all CPUs:
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] NMI backtrace for cpu 0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] CPU: 0 PID: 3352 Comm: kworker/u17:2 Not tainted 3.15.0 #504
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] Workqueue: arp826-wq rwq_worker
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] task: ef76c3e0 ti: ee8c6000 task.ti: ee8c6000
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] EIP: 0060:[<c102f24c>] EFLAGS: 00000046 CPU: 0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] EIP is at default_send_IPI_mask_logical+0x8c/0xf0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] EAX: 00000c00 EBX: 03000000 ECX: 00000000 EDX: fffff000
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] ESI: 00000006 EDI: 00000002 EBP: ee8c7c70 ESP: ee8c7c60
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] CR0: 8005003b CR2: 70b8a000 CR3: 2e0a8000 CR4: 000006d0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] Stack:
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  00000800 00002710 c192dba0 f503de40 ee8c7c80 c102f3d8 00002710 c192dba0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  ee8c7c90 c102f512 c182220e c192dba0 ee8c7cd4 c10abca4 c18302b8 00003a98
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  000047a2 000047a1 00001413 00000001 00000082 c192dba0 f503de40 00001413
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] Call Trace:
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c102f3d8>] default_send_IPI_all+0x88/0x90
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c102f512>] arch_trigger_all_cpu_backtrace+0x42/0x70
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c10abca4>] rcu_check_callbacks+0x3a4/0x5a0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c104ea5b>] update_process_times+0x3b/0x70
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c10b78a3>] tick_sched_handle.isra.15+0x33/0x40
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c10b7d50>] tick_sched_timer+0x40/0x70
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c106419c>] __run_hrtimer+0x6c/0x1c0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c10b7d10>] ? tick_sched_do_timer+0x30/0x30
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c1064cff>] hrtimer_interrupt+0xff/0x2b0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c1064d8d>] ? hrtimer_interrupt+0x18d/0x2b0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c102d0bf>] local_apic_timer_interrupt+0x2f/0x60
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c16682a3>] smp_apic_timer_interrupt+0x33/0x50
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c1660432>] apic_timer_interrupt+0x32/0x38
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c131a464>] ? delay_tsc+0x44/0x70

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.640014] CPU: 0 PID: 3352 Comm: kworker/u17:2 Not tainted 3.15.0 #504

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.640014] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.640014] Workqueue: arp826-wq rwq_worker

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.640014] task: ef76c3e0 ti: ee8c6000 task.ti: ee8c6000

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.640014] Stack:

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.640014] Call Trace:
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c131a39e>] __delay+0xe/0x10
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c1094d2e>] do_raw_spin_lock+0x6e/0x150
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c165f1ce>] _raw_spin_lock+0x5e/0x70
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<f80ba45d>] ? rinarp_resolve_handler+0x3d/0x1b0 [shim_eth_vlan]
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<f80ba45d>] rinarp_resolve_handler+0x3d/0x1b0 [shim_eth_vlan]
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<f8d80cfa>] resolver+0x16a/0x260 [arp826]
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c163e11e>] rwq_worker+0x1e/0x50
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c105acdc>] process_one_work+0x19c/0x490
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c105ac67>] ? process_one_work+0x127/0x490
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c105b19e>] ? worker_thread+0x19e/0x320
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c105b0f9>] worker_thread+0xf9/0x320
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c105b000>] ? process_scheduled_works+0x30/0x30
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c106171b>] kthread+0x9b/0xb0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c165fbe7>] ? _raw_spin_unlock_irq+0x27/0x40
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c1060000>] ? posix_timer_event+0x70/0xa0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c1667b41>] ret_from_kernel_thread+0x21/0x30
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014]  [<c1061680>] ? kthread_create_on_node+0x170/0x170
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] Code: 00 d3 ff ff 80 e5 10 75 ee c1 e3 18 89 98 10 d3 ff ff 89 f8 09 d0 80 ce 04 83 ff 02 0f 44 c2 8b 15 0c f1 91 c1 89 82 00 d3 ff ff <f7> c6 00 02 00 00 74 14 e8 27 e2 05 00 56 9d 8b 5d f4 8b 75 f8
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] NMI backtrace for cpu 1
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 3.15.0 #504
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] task: f35b2d40 ti: f35f2000 task.ti: f35f2000
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] EIP: 0060:[<c100959e>] EFLAGS: 00200246 CPU: 1
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] EIP is at default_idle+0x1e/0xc0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] EAX: c100959c EBX: 00000000 ECX: 00000000 EDX: 00000000
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] ESI: 00000000 EDI: 00000001 EBP: f35f3f5c ESP: f35f3f50
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] CR0: 8005003b CR2: 0986f808 CR3: 2e521000 CR4: 000006d0
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] Stack:
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  00000000 00000000 f35f2000 f35f3f64 c1009d2e f35f3f98 c1082be0 f35f3f7c
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  c10b576a 00000001 f35f3fec f35f3f90 c102cf3b f35f3fec f35f3fec 00000001
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  00000000 00000000 f35f3fb4 c102baa9 00000000 00000000 00000000 00000000

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.640014] Code: 00 d3 ff ff 80 e5 10 75 ee c1 e3 18 89 98 10 d3 ff ff 89 f8 09 d0 80 ce 04 83 ff 02 0f 44 c2 8b 15 0c f1 91 c1 89 82 00 d3 ff ff <f7> c6 00 02 00 00 74 14 e8 27 e2 05 00 56 9d 8b 5d f4 8b 75 f8

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.652035] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 3.15.0 #504

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.652035] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.652035] task: f35b2d40 ti: f35f2000 task.ti: f35f2000

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.652035] Stack:
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] Call Trace:
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  [<c1009d2e>] arch_cpu_idle+0xe/0x10
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  [<c1082be0>] cpu_startup_entry+0x1e0/0x370
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  [<c10b576a>] ? clockevents_register_device+0xaa/0x100
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  [<c102cf3b>] ? setup_APIC_timer+0xab/0x130
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035]  [<c102baa9>] start_secondary+0x189/0x210
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.652035] Code: 00 00 00 e9 4a ff ff ff 90 90 90 90 90 55 89 e5 57 56 53 66 66 66 66 90 64 8b 3d 10 10 a6 c1 66 66 66 66 90 e8 e4 3e 08 00 fb f4 <64> 8b 3d 10 10 a6 c1 66 66 66 66 90 5b 5e 5f 5d 66 90 c3 8d b4
Jul 24 16:33:15 irati-vm-leo-1 kernel: [ 5306.640014] INFO: NMI handler (arch_trigger_all_cpu_backtrace_handler) took too long to run: 248.462 msecs

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.652035] Call Trace:

Message from syslogd@irati-vm-leo-1 at Jul 24 16:33:15 ...
 kernel:[ 5306.652035] Code: 00 00 00 e9 4a ff ff ff 90 90 90 90 90 55 89 e5 57 56 53 66 66 66 66 90 64 8b 3d 10 10 a6 c1 66 66 66 66 90 e8 e4 3e 08 00 fb f4 <64> 8b 3d 10 10 a6 c1 66 66 66 66 90 5b 5e 5f 5d 66 90 c3 8d b4

**Comment by sandervrijders** [comment]
Leo, is this reproducible, or should it be closed?
