### ISSUE TITLE
After running 416 tests, server node hangs

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#359]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Thursday Jul 24, 2014 at 18:53 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/356_

----

Had debug logs disabled:

Jul 24 18:28:22 m kernel: [ 7967.607803] rina-kfa: There is no flow bound to port-id 2
Jul 24 18:28:22 m kernel: [ 7967.607823] rina-dtp: Could not post SDU to KFA
Jul 24 18:28:22 m kernel: [ 7967.607842] rina-efcp: DTP cannot receive this PDU
Jul 24 18:28:22 m kernel: [ 7967.607854] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.607954] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.607977] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.607980] rina-kfa: There is no flow bound to port-id 2
Jul 24 18:28:22 m kernel: [ 7967.607982] rina-dtp: Could not post SDU to KFA
Jul 24 18:28:22 m kernel: [ 7967.607996] rina-efcp: DTP cannot receive this PDU
Jul 24 18:28:22 m kernel: [ 7967.607997] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608045] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608075] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608087] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608113] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608116] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608143] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608154] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608185] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608206] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608246] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608248] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608312] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608330] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608340] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608369] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608381] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608428] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608449] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608456] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608464] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608489] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608501] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608553] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608560] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608608] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608626] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608663] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608683] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608724] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608736] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608753] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608764] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608794] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608806] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608832] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608842] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608890] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608902] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608932] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608943] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.608989] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.608997] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609017] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609035] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609070] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609080] rina-rmt: EFCP container problems
...

Jul 24 18:28:22 m kernel: [ 7967.609527] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609534] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609548] kmemleak: Cannot insert 0xffff8801a0a4d800 into the object search tree (overlaps existing)
Jul 24 18:28:22 m kernel: [ 7967.609551] CPU: 0 PID: 5105 Comm: kworker/u52:1 Not tainted 3.15.0-test99991 #5
Jul 24 18:28:22 m kernel: [ 7967.609552] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
Jul 24 18:28:22 m kernel: [ 7967.609557] Workqueue: rmt-ingress-wq-ffff8801 rwq_worker
Jul 24 18:28:22 m kernel: [ 7967.609560]  0000000000000000 ffff8800b23dd890 ffffffff81397ef7 ffff8800a552fd60
Jul 24 18:28:22 m kernel: [ 7967.609562]  ffffffff8110bdf6 ffff8800a5885520 000000100000000f ffff8800a552fde8
Jul 24 18:28:22 m kernel: [ 7967.609563]  ffff880100000000 ffff8801bf800c40 00000000000000d0 00000000000000d0
Jul 24 18:28:22 m kernel: [ 7967.609564] Call Trace:
Jul 24 18:28:22 m kernel: [ 7967.609568]  [<ffffffff81397ef7>] ? dump_stack+0x41/0x51
Jul 24 18:28:22 m kernel: [ 7967.609572]  [<ffffffff8110bdf6>] ? create_object+0x1e8/0x292
Jul 24 18:28:22 m kernel: [ 7967.609575]  [<ffffffff81102e9b>] ? __kmalloc+0xb2/0xfd
Jul 24 18:28:22 m kernel: [ 7967.609577]  [<ffffffff813843bc>] ? rkmalloc+0x22/0x42
Jul 24 18:28:22 m kernel: [ 7967.609578]  [<ffffffff813843bc>] ? rkmalloc+0x22/0x42
Jul 24 18:28:22 m kernel: [ 7967.609580]  [<ffffffff81388cd9>] ? buffer_create_from_gfp+0x55/0x82
Jul 24 18:28:22 m kernel: [ 7967.609584]  [<ffffffff81389dc6>] ? pdu_deserialize+0x31d/0x57b
Jul 24 18:28:22 m kernel: [ 7967.609591]  [<ffffffffa02ec3c8>] ? receive_worker+0xbd/0x448 [rina_personality_default]
Jul 24 18:28:22 m kernel: [ 7967.609593]  [<ffffffff8138491f>] ? rwq_worker+0x1f/0x3a
Jul 24 18:28:22 m kernel: [ 7967.609596]  [<ffffffff8104d5c8>] ? process_one_work+0x191/0x293
Jul 24 18:28:22 m kernel: [ 7967.609597]  [<ffffffff8104d810>] ? worker_thread+0x121/0x1e7
Jul 24 18:28:22 m kernel: [ 7967.609599]  [<ffffffff8104d6ef>] ? process_scheduled_works+0x25/0x25
Jul 24 18:28:22 m kernel: [ 7967.609601]  [<ffffffff810521e6>] ? kthread+0x99/0xa1
Jul 24 18:28:22 m kernel: [ 7967.609603]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
Jul 24 18:28:22 m kernel: [ 7967.609606]  [<ffffffff813a0e3c>] ? ret_from_fork+0x7c/0xb0
Jul 24 18:28:22 m kernel: [ 7967.609608]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
Jul 24 18:28:22 m kernel: [ 7967.609612] kmemleak: Kernel memory leak detector disabled
Jul 24 18:28:22 m kernel: [ 7967.609613] kmemleak: Object 0xffff8801a0a4d800 (size 2048):
Jul 24 18:28:22 m kernel: [ 7967.609614] kmemleak:   comm "kworker/u52:4", pid 3901, jiffies 4296882529
Jul 24 18:28:22 m kernel: [ 7967.609614] kmemleak:   min_count = 1
Jul 24 18:28:22 m kernel: [ 7967.609615] kmemleak:   count = 0
Jul 24 18:28:22 m kernel: [ 7967.609615] kmemleak:   flags = 0x1
Jul 24 18:28:22 m kernel: [ 7967.609616] kmemleak:   checksum = 0
Jul 24 18:28:22 m kernel: [ 7967.609616] kmemleak:   backtrace:
Jul 24 18:28:22 m kernel: [ 7967.609618]      [<ffffffff81102e9b>] __kmalloc+0xb2/0xfd
Jul 24 18:28:22 m kernel: [ 7967.609620]      [<ffffffff813843bc>] rkmalloc+0x22/0x42
Jul 24 18:28:22 m kernel: [ 7967.609622]      [<ffffffff813843bc>] rkmalloc+0x22/0x42
Jul 24 18:28:22 m kernel: [ 7967.609624]      [<ffffffffa035ff3b>] eth_vlan_rcv_worker+0xc1/0x4bf [shim_eth_vlan]
Jul 24 18:28:22 m kernel: [ 7967.609627]      [<ffffffff81059f8a>] finish_task_switch+0x7f/0xbf
Jul 24 18:28:22 m kernel: [ 7967.609628]      [<ffffffff8104d5c8>] process_one_work+0x191/0x293
Jul 24 18:28:22 m kernel: [ 7967.609630]      [<ffffffff8104d810>] worker_thread+0x121/0x1e7
Jul 24 18:28:22 m kernel: [ 7967.609631]      [<ffffffff8104d6ef>] worker_thread+0x0/0x1e7
Jul 24 18:28:22 m kernel: [ 7967.609633]      [<ffffffff810521e6>] kthread+0x99/0xa1
Jul 24 18:28:22 m kernel: [ 7967.609635]      [<ffffffff8105214d>] kthread+0x0/0xa1
Jul 24 18:28:22 m kernel: [ 7967.609638]      [<ffffffff813a0e3c>] ret_from_fork+0x7c/0xb0
Jul 24 18:28:22 m kernel: [ 7967.609639]      [<ffffffff8105214d>] kthread+0x0/0xa1
Jul 24 18:28:22 m kernel: [ 7967.609644]      [<ffffffffffffffff>] 0xffffffffffffffff
Jul 24 18:28:22 m kernel: [ 7967.609647] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609648] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609655] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609656] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609656] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609657] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609661] ------------[ cut here ]------------
Jul 24 18:28:22 m kernel: [ 7967.609662] rina-serdes: Received an unknown version of the EFCP PDU (0)
Jul 24 18:28:22 m kernel: [ 7967.609668] WARNING: CPU: 1 PID: 4584 at mm/slab_common.c:468 kmalloc_slab+0x2e/0x86()
Jul 24 18:28:22 m kernel: [ 7967.609669] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609670] rina-serdes: Could not deser base PCI
Jul 24 18:28:22 m kernel: [ 7967.609672] Modules linked in:
Jul 24 18:28:22 m kernel: [ 7967.609672] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609672] rina-rmt: Failed to deserialize PDU!
Jul 24 18:28:22 m kernel: [ 7967.609675]  normal_ipcp
Jul 24 18:28:22 m kernel: [ 7967.609675] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609676]  shim_eth_vlan
Jul 24 18:28:22 m kernel: [ 7967.609676] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609678]  rinarp
Jul 24 18:28:22 m kernel: [ 7967.609678] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609679]  arp826
Jul 24 18:28:22 m kernel: [ 7967.609679] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609684]  rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 w83781d
Jul 24 18:28:22 m kernel: [ 7967.609684] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609686]  hwmon_vid
Jul 24 18:28:22 m kernel: [ 7967.609686] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609690]  i2c_piix4 nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache
Jul 24 18:28:22 m kernel: [ 7967.609690] rina-serdes: Received an unknown version of the EFCP PDU (0)
Jul 24 18:28:22 m kernel: [ 7967.609691]  sunrpc
Jul 24 18:28:22 m kernel: [ 7967.609691] rina-serdes: Could not deser base PCI
Jul 24 18:28:22 m kernel: [ 7967.609693]  loop
Jul 24 18:28:22 m kernel: [ 7967.609693] rina-rmt: Failed to deserialize PDU!
Jul 24 18:28:22 m kernel: [ 7967.609705]  coretemp kvm_intel snd_pcm snd_timer iTCO_wdt iTCO_vendor_support i7core_edac kvm snd edac_core lpc_ich mfd_core psmouse i2c_i801 microcode soundcore acpi_cpufreq ioatdma ehci_pci tpm_tis serio_raw processor
Jul 24 18:28:22 m kernel: [ 7967.609705] rina-rmt: Failed to deserialize PDU!
Jul 24 18:28:22 m kernel: [ 7967.609708]  button pcspkr joydev evdev
Jul 24 18:28:22 m kernel: [ 7967.609708] rina-rinarp: Cannot find GPA, bad input parameters
Jul 24 18:28:22 m kernel: [ 7967.609710]  thermal_sys
Jul 24 18:28:22 m kernel: [ 7967.609710] rina-efcp: Cannot find the requested instance cep-id: 0
Jul 24 18:28:22 m kernel: [ 7967.609711]  tpm
Jul 24 18:28:22 m kernel: [ 7967.609711] rina-rmt: EFCP container problems
Jul 24 18:28:22 m kernel: [ 7967.609724]  ext3 mbcache jbd sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata uhci_hcd ehci_hcd scsi_mod usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
Jul 24 18:28:22 m kernel: [ 7967.609726] CPU: 1 PID: 4584 Comm: kworker/u52:2 Not tainted 3.15.0-test99991 #5
Jul 24 18:28:22 m kernel: [ 7967.609727] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
Jul 24 18:28:22 m kernel: [ 7967.609730] Workqueue: rmt-ingress-wq-ffff8801 rwq_worker
Jul 24 18:28:22 m kernel: [ 7967.609733]  0000000000000000 0000000000000009 ffffffff81397ef7 0000000000000000
Jul 24 18:28:22 m kernel: [ 7967.609735]  ffffffff810395fb ffff8801b8f53800 ffffffff810df394 0000000000012e80
Jul 24 18:28:22 m kernel: [ 7967.609737]  0000000000000000 ffffffffffffffed 00000000000000d0 00000000000000d0
Jul 24 18:28:22 m kernel: [ 7967.609737] Call Trace:
Jul 24 18:28:22 m kernel: [ 7967.609741]  [<ffffffff81397ef7>] ? dump_stack+0x41/0x51
Jul 24 18:28:22 m kernel: [ 7967.609745]  [<ffffffff810395fb>] ? warn_slowpath_common+0x78/0x90
Jul 24 18:28:22 m kernel: [ 7967.609752]  [<ffffffff810df394>] ? kmalloc_slab+0x2e/0x86
Jul 24 18:28:22 m kernel: [ 7967.609754]  [<ffffffff810df394>] ? kmalloc_slab+0x2e/0x86
Jul 24 18:28:22 m kernel: [ 7967.609757]  [<ffffffff81102e0c>] ? __kmalloc+0x23/0xfd
Jul 24 18:28:22 m kernel: [ 7967.609758] BUG: unable to handle kernel 
Jul 24 18:28:22 m kernel: [ 7967.609761] NULL pointer dereference
Jul 24 18:28:22 m kernel: [ 7967.609761]  [<ffffffff813843bc>] ? rkmalloc+0x22/0x42
Jul 24 18:28:22 m kernel: [ 7967.609762]  at 0000000000000008
Jul 24 18:28:22 m kernel: [ 7967.609765] IP:
Jul 24 18:28:22 m kernel: [ 7967.609765]  [<ffffffff813843bc>] ? rkmalloc+0x22/0x42
Jul 24 18:28:22 m kernel: [ 7967.609768]  [<ffffffff81384b43>] rqueue_head_pop+0x4f/0x73
Jul 24 18:28:22 m kernel: [ 7967.609770]  [<ffffffff81388cd9>] ? buffer_create_from_gfp+0x55/0x82
Jul 24 18:28:22 m kernel: [ 7967.609772] PGD 0 
Jul 24 18:28:22 m kernel: [ 7967.609772] 
Jul 24 18:28:22 m kernel: [ 7967.609774]  [<ffffffff81389dc6>] ? pdu_deserialize+0x31d/0x57b
Jul 24 18:28:22 m kernel: [ 7967.609777] Oops: 0002 [#4] 
Jul 24 18:28:22 m kernel: [ 7967.609783] SMP 
Jul 24 18:28:22 m kernel: [ 7967.609783]  [<ffffffffa02ec3c8>] ? receive_worker+0xbd/0x448 [rina_personality_default]
Jul 24 18:28:22 m kernel: [ 7967.609783] 
Jul 24 18:28:22 m kernel: [ 7967.609786]  [<ffffffff8138491f>] ? rwq_worker+0x1f/0x3a

**Comment by vmaffione** [comment]
Not reproducible anymore
