### ISSUE TITLE
Shim-eth: Sleeping in atomic when creating a flow

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#360]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Friday Jul 25, 2014 at 08:05 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/357_

----

During enrollment, normal over shim-eth

Jul 25 11:18:10 irati-vm-leo-2 kernel: [62490.625046] rina-rnl-utils: Going to send NL unicast message (type = 19, seq-num 1406279892, port = 1)
Jul 25 11:18:10 irati-vm-leo-2 kernel: [62490.625095] rina-rnl-utils: Unicast NL message sent (type = 19, seq-num 1406279892, port = 1)
Jul 25 11:18:10 irati-vm-leo-2 kernel: [62490.625095] rina-rnl: Message 18 handled successfully
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.758064] rina-arp826-rxtx: Processing ARP skb e9c47c80
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761512] rina-arp826-rxtx: Decoded ARP header:
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx:   Hardware type           = 0x0001
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx:   Protocol type           = 0xD1F0
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx:   Hardware address length = 6
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx:   Protocol address length = 15
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx:   Operation               = 0x0001
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx: We can handle this ARP
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx: Fetching addresses
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-rxtx: Shrinking as needed
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-utils: GPA f4615f18 (15): 0x74657374312E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-utils: Looking for filler 0x00 in GPA (length = 15)
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-utils: GPA doesn't need to be shrinked ...
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-utils: GPA f4615170 (15): 0x74657374322E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-utils: Looking for filler 0x00 in GPA (length = 15)
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-utils: GPA doesn't need to be shrinked ...
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-tables: Looking for the following address in table
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-utils: GPA f4615f18 (15): 0x74657374312E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.761904] rina-arp826-tables: Showing addresses in table in the meanwhile
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.852917] rina-arp826-utils: GPA f46150b8 (15): 0x74657374322E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.858660] rina-arp826-utils: GPA efccb7e8 (15): 0x74657374312E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.862639] rina-arp826-tables: That's the address I need
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.865683] rina-arp826-rxtx: Updating old entry e60ffc00 into the table
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.869122] rina-arp826-tables: Looking for the following address in table
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.873073] rina-arp826-utils: GPA f4615170 (15): 0x74657374322E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.877157] rina-arp826-tables: Showing addresses in table in the meanwhile
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.880825] rina-arp826-utils: GPA f46150b8 (15): 0x74657374322E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.884680] rina-arp826-tables: That's the address I need
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.887963] rina-arp826-rxtx: Showing the target ha
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.890403] rina-arp826-utils: GHA efd2b6c0: 95:F0:44:3E:16:00
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.893409] rina-arp826-rxtx: Sending ARP reply
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.895623] rina-arp826-rxtx: Growing addresses to 15
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.898630] rina-arp826-utils: GPA f4615e60 (15): 0x74657374322E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.902682] rina-arp826-utils: No needs to grow the GPA
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.905652] rina-arp826-utils: GPA f4615228 (15): 0x74657374312E49524154492F312F2F
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.909990] rina-arp826-utils: No needs to grow the GPA
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.912992] rina-arp826-rxtx: Creating an ARP packet
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.916000] rina-arp826-rxtx: ARP packet sent successfully
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.925664] rina-arp826-rxtx: Request replied successfully
Jul 25 11:18:23 irati-vm-leo-2 kernel: [62503.933398] rina-arp826-rxtx: Processing completed successfully
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.287335] rina-shim-eth-vlan: Worker waking up
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.291963] rina-shim-eth-vlan: Have to create a new flow
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.295658] BUG: sleeping function called from invalid context at kernel/locking/mutex.c:586
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.305173] in_atomic(): 1, irqs_disabled(): 0, pid: 4243, name: kworker/u17:2
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.312589] INFO: lockdep is turned off.
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.317058] CPU: 0 PID: 4243 Comm: kworker/u17:2 Not tainted 3.15.0 #133
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.327785] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.332527] Workqueue: shim-eth-vlan eth_vlan_rcv_worker [shim_eth_vlan]
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.340929]  00000000 00000000 e5f5dde0 c1653c61 eecd96b0 e5f5de04 c1069ef9 c182e038
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.353425]  00000001 00000000 00001093 eecd9a78 f079fcb0 f079fcb0 e5f5de4c c165d073
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.361219]  c164ad2c 00008020 00000000 e5f5de48 c116668e 00008020 00000000 00000000
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.366816] Call Trace:
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.368276]  [<c1653c61>] dump_stack+0x48/0x60
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.371576]  [<c1069ef9>] __might_sleep+0xe9/0x120
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.374369]  [<c165d073>] mutex_lock_nested+0x23/0x370
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.377583]  [<c164ad2c>] ? kmemleak_alloc+0x2c/0x60
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.380721]  [<c116668e>] ? __kmalloc+0xde/0x1c0
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.384151]  [<c163e92f>] ? rkzalloc+0x1f/0x60
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.387404]  [<f80e9eba>] kfa_port_id_reserve+0x1a/0x80 [rina_personality_default]
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.391983]  [<f80d6a00>] eth_vlan_rcv_worker+0x2a0/0x6a4 [shim_eth_vlan]
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.396335]  [<c105ad9c>] process_one_work+0x19c/0x490
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.399198]  [<c105ad27>] ? process_one_work+0x127/0x490
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.402701]  [<c105b25e>] ? worker_thread+0x19e/0x320
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.405969]  [<c105b1b9>] worker_thread+0xf9/0x320
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.409777]  [<c105b0c0>] ? process_scheduled_works+0x30/0x30
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.415298]  [<c10617db>] kthread+0x9b/0xb0
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.418668]  [<c1060000>] ? SYSC_clock_adjtime+0x60/0xb0
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.421963]  [<c1668ae1>] ret_from_kernel_thread+0x21/0x30
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.425442]  [<c1061740>] ? kthread_create_on_node+0x170/0x170
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.429961] rina-pidm: The pidm bitmap find returned id 0 (bad = -1)
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.434775] rina-pidm: Bitmap allocation completed successfully (id = 0)
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.439597] rina-shim-eth-vlan: Added flow to the list
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.443410] rina-rfifo: FIFO f4615f18 created successfully
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.447098] rina-shim-eth-vlan: Created the queue
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.450279] rina-rqueue: Entry e60ffcc0 tail-pushed into queue e60fff00 (length = 1)
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.455387] rina-ipcp-utils: Name at e60ffe40 finalized successfully
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.459252] rina-shim-eth-vlan: Got the address from ARP
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.463162] rina-rnl-utils: Result of genlmesg_end: 248
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.466618] rina-rnl-utils: Going to send NL unicast message (type = 12, seq-num 3, port = 1)
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.471855] rina-rnl-utils: Unicast NL message sent (type = 12, seq-num 3, port = 1)
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.482869] rina-rnl: Dispatching message (skb-in=ed1b5b00, info=eb2b7b44, attrs=f01311e0)
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.482870] rina-rnl: Multiplexing message type 14
Jul 25 11:18:24 irati-vm-leo-2 kernel: [62504.482871] rina-rnl: Fetching handler callback and data

**Comment by vmaffione** [comment]
Not reproducible anymore
