### ISSUE TITLE
Porting: VLAN not initialized -> seg Fault

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#362]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Tuesday Aug 19, 2014 at 07:51 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/359_

----

If VLAN is not properly initialized the loading of the stack produces a seg fault and console does not charge which means that a reboot is needed

**Comment by sandervrijders** [comment]
Bernat, is this still the case?

**Comment by bernatgaston** [comment]
Yes, it is still open

**Comment by bernatgaston** [comment]
this can be closed
