### ISSUE TITLE
Add CDAP timeout in the configurations

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#372]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Friday Sep 05, 2014 at 07:40 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/369_

----

CDAPSessionManager Timeout must be configured from ipcmanager.conf

**Comment by sandervrijders** [comment]
Was this added?

**Comment by bernatgaston** [comment]
yes it is still open

**Comment by edugrasa** [comment]
@vmaffione @bernatgaston this can be closed
