### ISSUE TITLE
Kernel crash when a connection is destroyed and the RMT ingress rwq_worker still has work to do

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#378]
<a href="https://github.com/miqueltarzan"><img src="https://avatars.githubusercontent.com/u/3428055?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [miqueltarzan](https://github.com/miqueltarzan)**
_Friday Sep 05, 2014 at 10:28 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/375_

----

The problem arises in the following way: The RMT ingress rwq_worker is trying to process a PDU, so it calls the receive_worker, which in turns calls the efcp_container_receive, and this calls dtp_receive. At this point, this process is put to sleep; and the connection that was being used is destroyed, along with the DTP used in the call to dtp_receive. When that process is working again, trying to take one of the DTP spinlocks (the sequencing queue spinlock, probably, thouhg this is not sure) causes the crash.

Excerpt from the log:

[ 2496.071701] rina-normal-ipc: Trying to read mgmt SDU from IPC Process 3
[ 2496.071705] rina-normal-ipc: Mgmt read going to sleep...
[ 2496.312151] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[ 2496.312151] Workqueue: rmt-ingress-wq-ef9820f0 rwq_worker
[ 2496.312151] task: f1bb3900 ti: f2baa000 task.ti: f2baa000
[ 2496.312151] EIP: 0060:[<c15ff78d>] EFLAGS: 00010212 CPU: 1
[ 2496.312151] EIP is at _raw_spin_lock+0xd/0x30
[ 2496.312151] EAX: 6b6b6b73 EBX: ef851960 ECX: 00160001 EDX: 00000100
[ 2496.312151] ESI: f14dea10 EDI: f538b1a0 EBP: f2babe60 ESP: f2babe60
[ 2496.312151]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[ 2496.312151] CR0: 8005003b CR2: 6b6b6b73 CR3: 019e8000 CR4: 000006d0
[ 2496.312151] Stack:
[ 2496.312151]  f2babea4 f8d6b536 f2babe74 c15e69d1 f14deac8 000001f4 00000001 004de2e0
[ 2496.312151]  7fffffff f8d7c014 ef851970 ef851964 f14094e0 f538b270 f14dea10 f1908b40
[ 2496.312151]  00000000 f2babec0 f8d6c588 c15e6118 f14dea10 00000000 ef9820f0 00000001
[ 2496.312151] Call Trace:
[ 2496.312151]  [<f8d6b536>] dtp_receive+0x226/0x5c0 [rina_personality_default]
[ 2496.312151]  [<c15e69d1>] ? pdu_ser_destroy+0x21/0x30
[ 2496.312151]  [<f8d6c588>] efcp_container_receive+0xc8/0x170 [rina_personality_default]
[ 2496.312151]  [<c15e6118>] ? pdu_is_ok+0x28/0x30
[ 2496.312151]  [<f8d6e928>] receive_worker+0x388/0x5d0 [rina_personality_default]
[ 2496.312151]  [<c15e143e>] rwq_worker+0x1e/0x50
[ 2496.312151]  [<c1059354>] process_one_work+0x114/0x370
[ 2496.312151]  [<c106ddf0>] ? default_wake_function+0x10/0x20
[ 2496.312151]  [<c10596d9>] worker_thread+0xf9/0x310
[ 2496.312151]  [<c10595e0>] ? process_scheduled_works+0x30/0x30
[ 2496.312151]  [<c105f1eb>] kthread+0x9b/0xb0
[ 2496.312151]  [<c100a35e>] ? __switch_to_xtra+0x11e/0x130
[ 2496.312151]  [<c16071c1>] ret_from_kernel_thread+0x21/0x30
[ 2496.312151]  [<c105f150>] ? flush_kthread_worker+0x70/0x70
[ 2496.312151] Code: 10 0f b6 ce 38 d1 75 04 5d c3 f3 90 0f b6 10 38 ca 75 f7 5d c3 89 f6 8d bc 27 00 00 00 00 55 89 e5 3e 8d 74 26 00 ba 00 01 00 00 <f0> 66 0f c1 10 0f b6 ce 38 d1 75 04 5d c3 f3 90 0f b6 10 38 ca
[ 2496.312151] EIP: [<c15ff78d>] _raw_spin_lock+0xd/0x30 SS:ESP 0068:f2babe60
[ 2496.312151] CR2: 000000006b6b6b73
[ 2496.312151] ---[ end trace 55141f6e12d56051 ]---
[ 2496.425272] BUG: unable to handle kernel paging request at ffffffec
[ 2496.425283] IP: [<c105f30f>] kthread_data+0xf/0x20
[ 2496.425290] *pde = 019eb067 *pte = 00000000 
[ 2496.425297] Oops: 0000 [#5] SMP 
[ 2496.425311] Modules linked in: normal_ipcp shim_dummy rina_personality_default binfmt_misc nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc 8021q garp stp llc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbhid hid pcnet32 ahci libahci mii e1000
[ 2496.425316] CPU: 1 PID: 4171 Comm: kworker/u5:2 Tainted: G      D       3.15.0 #331
[ 2496.425319] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[ 2496.425327] task: f1bb3900 ti: f2baa000 task.ti: f2baa000
[ 2496.425331] EIP: 0060:[<c105f30f>] EFLAGS: 00010002 CPU: 1
[ 2496.425335] EIP is at kthread_data+0xf/0x20
[ 2496.425339] EAX: 00000000 EBX: 00000001 ECX: 00000002 EDX: 00000001
[ 2496.425342] ESI: f1bb3c7c EDI: f1bb3900 EBP: f2babc34 ESP: f2babc2c
[ 2496.425346]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[ 2496.425349] CR0: 8005003b CR2: 00000014 CR3: 32c02000 CR4: 000006d0
[ 2496.425355] Stack:
[ 2496.425363]  c105a260 00000001 f2babcb4 c15fca6a 00000000 f2babc4c 00160013 f27aae70
[ 2496.425370]  c19de6a0 c1156aa2 f1bc1700 c19de6a0 f67d16a0 f1bb3900 f2babc84 c114d156
[ 2496.425378]  00000246 c10401e9 000401e9 f1bb3900 f1bb3900 00000000 f2babc90 c109ae1c
[ 2496.425381] Call Trace:
[ 2496.425390]  [<c105a260>] ? wq_worker_sleeping+0x10/0x80
[ 2496.425399]  [<c15fca6a>] __schedule+0x53a/0x750
[ 2496.425407]  [<c1156aa2>] ? delete_object_full+0x22/0x30
[ 2496.425415]  [<c114d156>] ? kmem_cache_free+0xf6/0x160
[ 2496.425423]  [<c10401e9>] ? __cleanup_sighand+0x29/0x30
[ 2496.425430]  [<c109ae1c>] ? call_rcu_sched+0x1c/0x20
[ 2496.425437]  [<c1043406>] ? release_task+0x2d6/0x400
[ 2496.425446]  [<c10ff001>] ? account_event_cpu+0x41/0x50
[ 2496.425453]  [<c10b9ccb>] ? cgroup_exit+0x9b/0xc0
[ 2496.425461]  [<c15fcce3>] schedule+0x23/0x60
[ 2496.425468]  [<c10446d7>] do_exit+0x4c7/0x910
[ 2496.425475]  [<c1600975>] oops_end+0x85/0xc0
[ 2496.425483]  [<c15f1942>] no_context+0x1a6/0x1ae
[ 2496.425490]  [<c15f1a6c>] __bad_area_nosemaphore+0x122/0x12a
[ 2496.425498]  [<c15e0be1>] ? rkfree+0x11/0x20
[ 2496.425505]  [<c1046cde>] ? irq_exit+0x5e/0xa0
[ 2496.425512]  [<c1602ee0>] ? __do_page_fault+0x4f0/0x4f0
[ 2496.425519]  [<c15f1a8b>] bad_area_nosemaphore+0x17/0x19
[ 2496.425526]  [<c1602ab4>] __do_page_fault+0xc4/0x4f0
[ 2496.425533]  [<c109ae1c>] ? call_rcu_sched+0x1c/0x20
[ 2496.425540]  [<c1155a8b>] ? put_object+0x2b/0x40
[ 2496.425547]  [<c1156aa2>] ? delete_object_full+0x22/0x30
[ 2496.425554]  [<c1602ee0>] ? __do_page_fault+0x4f0/0x4f0
[ 2496.425561]  [<c1602eeb>] do_page_fault+0xb/0x10
[ 2496.425567]  [<c16001fa>] error_code+0x5a/0x60
[ 2496.425575]  [<c1602ee0>] ? __do_page_fault+0x4f0/0x4f0
[ 2496.425583]  [<c15ff78d>] ? _raw_spin_lock+0xd/0x30
[ 2496.425593]  [<f8d6b536>] dtp_receive+0x226/0x5c0 [rina_personality_default]
[ 2496.425601]  [<c15e69d1>] ? pdu_ser_destroy+0x21/0x30
[ 2496.425610]  [<f8d6c588>] efcp_container_receive+0xc8/0x170 [rina_personality_default]
[ 2496.425618]  [<c15e6118>] ? pdu_is_ok+0x28/0x30
[ 2496.425639]  [<f8d6e928>] receive_worker+0x388/0x5d0 [rina_personality_default]
[ 2496.425646]  [<c15e143e>] rwq_worker+0x1e/0x50
[ 2496.425654]  [<c1059354>] process_one_work+0x114/0x370
[ 2496.425661]  [<c106ddf0>] ? default_wake_function+0x10/0x20
[ 2496.425668]  [<c10596d9>] worker_thread+0xf9/0x310
[ 2496.425675]  [<c10595e0>] ? process_scheduled_works+0x30/0x30
[ 2496.425683]  [<c105f1eb>] kthread+0x9b/0xb0
[ 2496.425690]  [<c100a35e>] ? __switch_to_xtra+0x11e/0x130
[ 2496.425698]  [<c16071c1>] ret_from_kernel_thread+0x21/0x30
[ 2496.425705]  [<c105f150>] ? flush_kthread_worker+0x70/0x70
[ 2496.425721] Code: 8d 74 26 00 64 a1 34 86 9d c1 8b 80 50 03 00 00 5d 8b 40 e4 c1 e8 02 83 e0 01 c3 90 55 89 e5 3e 8d 74 26 00 8b 80 50 03 00 00 5d <8b> 40 ec c3 8d b6 00 00 00 00 8d bc 27 00 00 00 00 55 89 e5 83
[ 2496.425728] EIP: [<c105f30f>] kthread_data+0xf/0x20 SS:ESP 0068:f2babc2c
[ 2496.425732] CR2: 00000000ffffffec
[ 2496.425736] ---[ end trace 55141f6e12d56052 ]---
[ 2496.425740] Fixing recursive fault but reboot is needed!

**Comment by vmaffione** [comment]
Not reproducible anymore
