### ISSUE TITLE
Kernel panic after ARP resolution

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#379]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Monday Sep 08, 2014 at 12:33 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/376_

----

Sep  8 13:47:24 hvb kernel: [13928.360089] rina-arp826-utils: GHA ffff880c66b64840: 03:63:E3:90:25:00
Sep  8 13:47:24 hvb kernel: [13928.360090] rina-rfifo: FIFO ffff880c66b649a0 destroyed successfully
Sep  8 13:47:24 hvb kernel: [13928.360094] rina-arp826-utils: GHA ffff880c6467de80: 03:63:E3:90:25:00
Sep  8 13:47:24 hvb kernel: [13928.360096] rina-rnl-utils: Result of genlmesg_end: 40
Sep  8 13:47:24 hvb kernel: [13928.360097] rina-arp826-arm: Dumping a->tpa
Sep  8 13:47:24 hvb kernel: [13928.360101] rina-rnl-utils: Going to send NL unicast message (type = 13, seq-num 1410176644, port = 1)
Sep  8 13:47:24 hvb kernel: [13928.360105] rina-arp826-utils: GPA ffff880c66b64c80 (11): 0x425244432E44432F312F2F
Sep  8 13:47:24 hvb kernel: [13928.360109] rina-arp826-utils: GPA ffff880c6467d440 (11): 0x425244432E44432F312F2F
Sep  8 13:47:24 hvb kernel: [13928.360111] rina-arp826-arm: Dumping a->spa
Sep  8 13:47:24 hvb kernel: [13928.360113] rina-rnl-utils: Unicast NL message sent (type = 13, seq-num 1410176644, port = 1)
Sep  8 13:47:24 hvb kernel: [13928.360116] rina-arp826-utils: GPA ffff880c66b64620 (10): 0x4856422E44432F312F2F
Sep  8 13:47:24 hvb kernel: [13928.360117] rina-arp826-arm: Notifier called, disposing the leftovers
Sep  8 13:47:24 hvb kernel: [13928.360120] rina-arp826-utils: GPA ffff880c6467da60 (10): 0x4856422E44432F312F2F
Sep  8 13:47:24 hvb kernel: [13928.360122] rina-arp826-arm: Dumping ptype
Sep  8 13:47:24 hvb kernel: [13928.360124] rina-arp826-arm: Found an equal resolution
Sep  8 13:47:24 hvb kernel: [13928.360126] rina-arp826-arm: Calling the notifier hook
Sep  8 13:47:24 hvb kernel: [13928.360129] rina-arp826-arm: Leaving this resolver function
Sep  8 13:47:24 hvb kernel: [13928.360130] rina-shim-eth-vlan: Entered the ARP resolve handler of the shim-eth
Sep  8 13:47:24 hvb kernel: [13928.360132] rina-arp826-arm: Notifier called, disposing the leftovers
Sep  8 13:47:24 hvb kernel: [13928.360142] rina-arp826-rxtx: Processing completed successfully
Sep  8 13:47:24 hvb kernel: [13928.360169] general protection fault: 0000 [#4] SMP 
Sep  8 13:47:24 hvb kernel: [13928.360211] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop joydev hid_generic usbhid hid x86_pkg_temp_thermal coretemp kvm_intel ehci_pci ehci_hcd kvm usbcore ghash_clmulni_intel aesni_intel aes_x86_64 ablk_helper cryptd lrw snd_pcm snd_timer snd ipmi_si soundcore usb_common iTCO_wdt sb_edac ioatdma edac_core iTCO_vendor_support lpc_ich mfd_core gf128mul psmouse i2c_i801 glue_helper pcspkr evdev serio_raw acpi_cpufreq processor tpm_tis wmi thermal_sys tpm ipmi_msghandler microcode button ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common crc32c_intel ixgbe mdio isci ahci libahci libsas igb i2c_algo_bit libata i2c_core dca scsi_transport_sas ptp scsi_mod pps_core
Sep  8 13:47:24 hvb kernel: [13928.360923] CPU: 8 PID: 193 Comm: kworker/u69:0 Not tainted 3.15.0-irati-v0.7.9 #6
Sep  8 13:47:24 hvb kernel: [13928.360983] Hardware name: Supermicro X9DRW-3LN4F+/X9DRW-3TF+/X9DRW-3LN4F+/X9DRW-3TF+, BIOS 3.00 07/05/2013
Sep  8 13:47:24 hvb kernel: [13928.361058] Workqueue: arp826-wq rwq_worker
Sep  8 13:47:24 hvb kernel: [13928.361093] task: ffff880c6453a010 ti: ffff880c64540000 task.ti: ffff880c64540000
Sep  8 13:47:24 hvb kernel: [13928.361153] RIP: 0010:[<ffffffffa04ccaa0>]  [<ffffffffa04ccaa0>] resolver+0x1e8/0x270 [arp826]
Sep  8 13:47:24 hvb kernel: [13928.361224] RSP: 0018:ffff880c64543e08  EFLAGS: 00010246
Sep  8 13:47:24 hvb kernel: [13928.361261] RAX: dead000000200200 RBX: ffff880c66a4ef80 RCX: dead000000100100
Sep  8 13:47:24 hvb kernel: [13928.361299] RDX: dead000000100100 RSI: dead000000200200 RDI: ffffffffa04d12a8
Sep  8 13:47:24 hvb kernel: [13928.361339] RBP: ffff880c66a4ef40 R08: ffffffff817cfff4 R09: 0000000000000000
Sep  8 13:47:24 hvb kernel: [13928.361379] R10: 0000000000000000 R11: ffff880c7fc12e00 R12: ffff880c66a4eb40
Sep  8 13:47:24 hvb kernel: [13928.361417] R13: ffffffffa04d1298 R14: 0000000000000001 R15: 0000000000000000
Sep  8 13:47:24 hvb kernel: [13928.361458] FS:  0000000000000000(0000) GS:ffff880c7fc00000(0000) knlGS:0000000000000000
Sep  8 13:47:24 hvb kernel: [13928.361519] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep  8 13:47:24 hvb kernel: [13928.361562] CR2: 0000000706e99000 CR3: 0000000001610000 CR4: 00000000001407e0
Sep  8 13:47:24 hvb kernel: [13928.361606] Stack:
Sep  8 13:47:24 hvb kernel: [13928.361633]  ffff880c64540000 ffff880c66a4efc0 ffff880c66a4efc0 ffff8806649f8400
Sep  8 13:47:24 hvb kernel: [13928.361703]  ffff880c66934800 ffffffff813833d9 ffff880c6699e4c0 ffffffff8104d5c8
Sep  8 13:47:24 hvb kernel: [13928.361771]  ffff880c6453a010 0000000064543fd8 ffff8806672fe2d0 ffff880c6699e4c0
Sep  8 13:47:24 hvb kernel: [13928.361841] Call Trace:
Sep  8 13:47:24 hvb kernel: [13928.361874]  [<ffffffff813833d9>] ? rwq_worker+0x29/0x44
Sep  8 13:47:24 hvb kernel: [13928.361917]  [<ffffffff8104d5c8>] ? process_one_work+0x191/0x293
Sep  8 13:47:24 hvb kernel: [13928.361957]  [<ffffffff8104d810>] ? worker_thread+0x121/0x1e7
Sep  8 13:47:24 hvb kernel: [13928.361994]  [<ffffffff8104d6ef>] ? process_scheduled_works+0x25/0x25
Sep  8 13:47:24 hvb kernel: [13928.362038]  [<ffffffff810521e6>] ? kthread+0x99/0xa1
Sep  8 13:47:24 hvb kernel: [13928.362076]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
Sep  8 13:47:24 hvb kernel: [13928.362121]  [<ffffffff8139fefc>] ? ret_from_fork+0x7c/0xb0
Sep  8 13:47:24 hvb kernel: [13928.362160]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
Sep  8 13:47:24 hvb kernel: [13928.362198] Code: 72 ec e0 48 c7 c7 a8 12 4d a0 e8 a2 e3 ec e0 48 8b 55 18 48 8b 45 20 48 b9 00 01 10 00 00 00 ad de 48 be 00 02 20 00 00 00 ad de <48> 89 42 08 48 89 10 48 8b 7d 00 48 89 4d 18 48 89 75 20 e8 b4 
Sep  8 13:47:24 hvb kernel: [13928.362486] RIP  [<ffffffffa04ccaa0>] resolver+0x1e8/0x270 [arp826]
Sep  8 13:47:24 hvb kernel: [13928.362530]  RSP <ffff880c64543e08>
Sep  8 13:47:24 hvb kernel: [13928.362987] ---[ end trace c7de57ce0904c00b ]---
Sep  8 13:47:24 hvb kernel: [13928.364690] rina-syscalls: Syscall write management SDU (size = 93, ipcp-id = 3, port-id = 5)
Sep  8 13:47:24 hvb kernel: [13928.364797] rina-syscalls: Handling personality hook mgmt_sdu_write
Sep  8 13:47:24 hvb kernel: [13928.364875] rina-syscalls: Calling personality hook mgmt_sdu_write

Happened during D4.2 tests, this node is connected directly through a LAN with two other nodes. Could be that an Ethernet frame arrived when we were holding a spinlock (first guess)

**Comment by vmaffione** [comment]
Not reproducible anymore.
