### ISSUE TITLE
put Exception class in rina namespace

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#383]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Tuesday Sep 09, 2014 at 12:36 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/380_

----

The file
   librina/include/librina/exceptions.h
declare the RINA exception base class, but the declaration doesn't happen inside the "rina" namespace. Should we move the declaration inside the namespace?

**Comment by sandervrijders** [comment]
Was this resolved in the end?

**Comment by msune** [comment]
Please close
