### ISSUE TITLE
Kernel panic because of null pointer deref in rinarp

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#384]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Wednesday Sep 10, 2014 at 09:45 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/381_

----

Sep 10 10:30:03 brdc kernel: [ 1077.676393] rina-shim-eth-vlan: Created the queue
Sep 10 10:30:03 brdc kernel: [ 1077.676396] rina-rqueue: Entry ffff88062d714e00 tail-pushed into queue ffff88062d714e40 (length = 1)
Sep 10 10:30:03 brdc kernel: [ 1077.676417] BUG: unable to handle kernel NULL pointer dereference at 0000000000000001
Sep 10 10:30:03 brdc kernel: [ 1077.676593] IP: [<ffffffffa044b0e0>] gha_is_ok+0x7/0x11 [arp826]
Sep 10 10:30:03 brdc kernel: [ 1077.676712] PGD 0 
Sep 10 10:30:03 brdc kernel: [ 1077.676818] Oops: 0000 [#4] SMP 
Sep 10 10:30:03 brdc kernel: [ 1077.676970] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 w83781d hwmon_vid i2c_piix4 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop iTCO_wdt iTCO_vendor_support coretemp kvm_intel kvm ioatdma acpi_cpufreq lpc_ich mfd_core i2c_i801 psmouse ehci_pci i7core_edac edac_core snd_pcm tpm_tis processor snd_timer tpm snd microcode thermal_sys button soundcore serio_raw pcspkr evdev joydev ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic ata_generic usbhid hid crc32c_intel ata_piix libata uhci_hcd ehci_hcd scsi_mod usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
Sep 10 10:30:03 brdc kernel: [ 1077.681283] CPU: 6 PID: 151 Comm: kworker/u53:0 Not tainted 3.15.0-irati-v0.7.9 #6
Sep 10 10:30:03 brdc kernel: [ 1077.681369] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1c.t06   07/05/2012
Sep 10 10:30:03 brdc kernel: [ 1077.681443] Workqueue: shim-eth-vlan eth_vlan_rcv_worker [shim_eth_vlan]
Sep 10 10:30:03 brdc kernel: [ 1077.681558] task: ffff880632db8d50 ti: ffff8806316d4000 task.ti: ffff8806316d4000
Sep 10 10:30:03 brdc kernel: [ 1077.681644] RIP: 0010:[<ffffffffa044b0e0>]  [<ffffffffa044b0e0>] gha_is_ok+0x7/0x11 [arp826]
Sep 10 10:30:03 brdc kernel: [ 1077.681780] RSP: 0018:ffff8806316d7db0  EFLAGS: 00010246
Sep 10 10:30:03 brdc kernel: [ 1077.681849] RAX: 0000000000000000 RBX: 0000000000000001 RCX: 0000000000000007
Sep 10 10:30:03 brdc kernel: [ 1077.681920] RDX: 0000000000000006 RSI: 0000000000000001 RDI: 0000000000000001
Sep 10 10:30:03 brdc kernel: [ 1077.681992] RBP: ffff88063128fba0 R08: 0000000000000002 R09: 0000000000000000
Sep 10 10:30:03 brdc kernel: [ 1077.682064] R10: ffff8806301d6700 R11: ffff8806301d6700 R12: ffff8806316785c0
Sep 10 10:30:03 brdc kernel: [ 1077.682136] R13: ffff8806316785c0 R14: ffff8806318e2510 R15: ffff8806301d6040
Sep 10 10:30:03 brdc kernel: [ 1077.682208] FS:  0000000000000000(0000) GS:ffff88063fc00000(0000) knlGS:0000000000000000
Sep 10 10:30:03 brdc kernel: [ 1077.682296] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Sep 10 10:30:03 brdc kernel: [ 1077.682365] CR2: 0000000000000001 CR3: 0000000001610000 CR4: 00000000000007e0
Sep 10 10:30:03 brdc kernel: [ 1077.682437] Stack:
Sep 10 10:30:03 brdc kernel: [ 1077.682499]  ffffffffa03cd04d 0000000000000002 ffff8806301d6740 ffff8806318e24c0
Sep 10 10:30:03 brdc kernel: [ 1077.682758]  ffffffffa04405fe ffff88063fc12e80 ffffffff810594ca ffff880333180990
Sep 10 10:30:03 brdc kernel: [ 1077.683018]  ffffffffa0443380 0000000033180de8 0000000000012e80 ffff880632db8d50
Sep 10 10:30:03 brdc kernel: [ 1077.683278] Call Trace:
Sep 10 10:30:03 brdc kernel: [ 1077.683344]  [<ffffffffa03cd04d>] ? rinarp_find_gpa+0x1b/0x47 [rinarp]
Sep 10 10:30:03 brdc kernel: [ 1077.683417]  [<ffffffffa04405fe>] ? eth_vlan_rcv_worker+0x351/0x5bf [shim_eth_vlan]
Sep 10 10:30:03 brdc kernel: [ 1077.683509]  [<ffffffff810594ca>] ? mmdrop+0xd/0x1c
Sep 10 10:30:03 brdc kernel: [ 1077.683580]  [<ffffffff8104d5c8>] ? process_one_work+0x191/0x293
Sep 10 10:30:03 brdc kernel: [ 1077.683651]  [<ffffffff8104d810>] ? worker_thread+0x121/0x1e7
Sep 10 10:30:03 brdc kernel: [ 1077.683722]  [<ffffffff8104d6ef>] ? process_scheduled_works+0x25/0x25
Sep 10 10:30:03 brdc kernel: [ 1077.683795]  [<ffffffff810521e6>] ? kthread+0x99/0xa1
Sep 10 10:30:03 brdc kernel: [ 1077.683864]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
Sep 10 10:30:03 brdc kernel: [ 1077.683938]  [<ffffffff8139fefc>] ? ret_from_fork+0x7c/0xb0
Sep 10 10:30:03 brdc kernel: [ 1077.684009]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
Sep 10 10:30:03 brdc kernel: [ 1077.684078] Code: e0 31 c0 eb 04 83 c8 ff c3 5a c3 48 85 ff 74 11 48 83 3f 00 74 0b 31 c0 48 83 7f 08 00 0f 95 c0 c3 31 c0 c3 48 85 ff 74 09 31 c0 <83> 3f 00 0f 94 c0 c3 31 c0 c3 55 48 89 f5 53 48 89 fb 51 e8 c8 
Sep 10 10:30:03 brdc kernel: [ 1077.687017] RIP  [<ffffffffa044b0e0>] gha_is_ok+0x7/0x11 [arp826]
Sep 10 10:30:03 brdc kernel: [ 1077.687133]  RSP <ffff8806316d7db0>
Sep 10 10:30:03 brdc kernel: [ 1077.687198] CR2: 0000000000000001
Sep 10 10:30:03 brdc kernel: [ 1077.687263] ---[ end trace 496ca000305d2290 ]---

**Comment by vmaffione** [comment]
Not reproducible anymore
