### ISSUE TITLE
Listipcp in the telnet console sometimes doesn't report a neighbor

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#390]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Monday Sep 15, 2014 at 09:11 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/387_

----

Listipcp lists the neighbors, but sometimes the IPCM is not notified of a neighbor relationship, although it can be found when quering the IPCP. Example:

Queryrib:

Object name: /daf/management/neighbors/F.NORMAL
Object class: neighbor
Object instance: 113830636561
Object value: Address: 6; Average RTT(ms): 11; Is enrolled: 1
Name: Process name: F.NORMAL; Process instance: 1
Entity name: ; Entity instance: 
Supporting DIF in common: 3344; N-1 port-id: 1
List of supporting DIFs: 3337; 3338; 3344; 
Last heard from time (ms): 1410771281074; Number of enrollment attempts: 0

Object name: /daf/management/neighbors/G.NORMAL
Object class: neighbor
Object instance: 113831370131
Object value: Address: 7; Average RTT(ms): 5; Is enrolled: 1
Name: Process name: G.NORMAL; Process instance: 1
Entity name: ; Entity instance: 
Supporting DIF in common: 3345; N-1 port-id: 2
List of supporting DIFs: 3338; 3339; 3345; 
Last heard from time (ms): 1410771281966; Number of enrollment attempts: 0

Listipcp:

Id: 3
    Type: normal-ipc
    Name: Process name: L.NORMAL; Process instance: 1
Entity name: ; Entity instance: 
    Supporting DIFs: 
        3344
        3345
    Member of DIF: SMALLTEST.NORMAL.DIF
        Address: 12
            EFCP Configuration: 
            Data Transfer Constants: 
                Address length: 1
                CEP-id length: 2
                Length length: 2
                QoS-id length: 1
                Sequence number length: 4
                Max PDU lifetime: 30
                Max PDU size: 1477
            QoS Cubes: 
                Name: unreliable
                Id: 1
                Ordered delivery: true
                Partial delivery: true
                EFCP policies: ; Sder time inactivity policy (name/version): default/0; Rcvr time inactivity policy (name/version): default/0
DTCP present: 0; Initial A-timer: 500; Seq. num roll. threshold: 0; Initial seq. num policy (name/version): default/0
; Partial delivery: 0; In order delivery: 0; Max allowed SDU gap: 0
            --------------------: 
        PDUFTableGeneratofConfiguration: 
            PDUFTG policy: LinkState/0
            objectMaximumAge: 100000
            waitUntilReadCDAP: 5001
            waitUntilError: 5001
            waitUntilPDUFTComputation: 103
            waitUntilFSODBPropagation: 101
            waitUntilAgeIncrement: 997
        Neighbors: 
            F.NORMAL-1

**Comment by vmaffione** [comment]
Not reproducible anymore
