### ISSUE TITLE
Soft lockup when trying to reboot machine after killing IPC manager

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#396]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Friday Oct 03, 2014 at 14:41 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/393_

----

Attached is the kernel log. Note that the IPC manager was using the tests/conf/ipcmanager.conf-normalovereth1 config file. This means that the PDU Forwarding Table Generator configuration section was missing. (Why I wanted to reboot) 

Oct  3 16:36:26 m kernel: [  730.677385] rina-kipcm: IPC Manager started. It is listening at NL port-id 1
Oct  3 16:36:33 m pubsubd[2890]: Totals: total:6 current:6 (3) received:0 emitted:0 failed:0
Oct  3 16:36:48 m kernel: [  752.204332] rina-rnl: IPC Manager process has been destroyed
Oct  3 16:37:03 m pubsubd[2890]: Totals: total:6 current:6 (3) received:0 emitted:0 failed:0
Oct  3 16:37:33 m pubsubd[2890]: Totals: total:6 current:6 (3) received:0 emitted:0 failed:0
Oct  3 16:37:54 m shutdown[3951]: shutting down for system reboot
Oct  3 16:37:56 m kernel: [  819.991546] PGD 3365fe067 PUD 33685c067 PMD 0 
Oct  3 16:37:56 m kernel: [  819.991743] Oops: 0002 [#4] SMP 
Oct  3 16:37:56 m kernel: [  819.991893] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 iw_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_r
pcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop snd_pcm iTCO_wdt iTCO_vendor_support snd_timer snd psmouse i7core_edac soundcore lpc_ich edac_core i2c_i801 coretemp ioatdma kvm_intel acpi_cpufreq mfd_core serio_raw pcspkr joydev ehci_pci evdev kvm tpm_tis proces
sor tpm thermal_sys button microcode ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata uhci_hcd scsi_mod ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core [last unloaded: ib_
cm]
Oct  3 16:37:56 m kernel: [  819.995937] CPU: 1 PID: 598 Comm: udevd Tainted: G          I   3.15.0-irati-test5 #11
Oct  3 16:37:56 m kernel: [  819.996024] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
Oct  3 16:37:56 m kernel: [  819.996096] task: ffff88033757a610 ti: ffff880338a18000 task.ti: ffff880338a18000
Oct  3 16:37:56 m kernel: [  819.996181] RIP: 0010:[<ffffffff812cde85>]  [<ffffffff812cde85>] __skb_recv_datagram+0x126/0x3c1
Oct  3 16:37:56 m kernel: [  819.996313] RSP: 0018:ffff880338a1bb58  EFLAGS: 00010096
Oct  3 16:37:56 m kernel: [  819.996381] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
Oct  3 16:37:56 m kernel: [  819.996452] RDX: ffff88033f8728a4 RSI: 0000000000000202 RDI: ffff880338a1bc20
Oct  3 16:37:56 m kernel: [  819.996523] RBP: ffff88033f872890 R08: ffff880338a1bc48 R09: 0000000000000008
Oct  3 16:37:56 m kernel: [  819.996594] R10: 0000000000000008 R11: 0000000000002000 R12: ffff880338a1bc48
Oct  3 16:37:56 m kernel: [  819.996665] R13: ffff88033f872800 R14: ffff8801b832ed00 R15: 0000000000000000
Oct  3 16:37:56 m kernel: [  819.996737] FS:  00007fc7f7fe07c0(0000) GS:ffff8801bfc20000(0000) knlGS:0000000000000000
Oct  3 16:37:56 m kernel: [  819.996824] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Oct  3 16:37:56 m kernel: [  819.996892] CR2: 0000000000000008 CR3: 000000033725e000 CR4: 00000000000007e0
Oct  3 16:37:56 m kernel: [  819.996963] Stack:
Oct  3 16:37:56 m kernel: [  819.997024]  ffff88033f8728a4 0000004000000040 ffff8801b7ea0700 ffff88033f872890
Oct  3 16:37:56 m kernel: [  819.997282]  ffff880338a1bc24 ffff880338a1bfd8 ffff88033757a610 ffff880338a1bc20
Oct  3 16:37:56 m kernel: [  819.997539]  ffff880338a1bfd8 ffff88033757a610 ffff880338a1bf30 ffff8801b832ed00
Oct  3 16:37:56 m kernel: [  819.997796] Call Trace:
Oct  3 16:37:56 m kernel: [  819.997861]  [<ffffffff812ce14c>] ? skb_recv_datagram+0x2c/0x31
Oct  3 16:37:56 m kernel: [  819.997933]  [<ffffffff812f735f>] ? netlink_recvmsg+0x47/0x336
Oct  3 16:37:56 m kernel: [  819.998006]  [<ffffffff812c3307>] ? sock_recvmsg+0x54/0x71
Oct  3 16:37:56 m kernel: [  819.998077]  [<ffffffff81347bc2>] ? unix_dgram_poll+0x21/0x14c
Oct  3 16:37:56 m kernel: [  819.998148]  [<ffffffff812c389c>] ? ___sys_recvmsg+0x151/0x213
Oct  3 16:37:56 m kernel: [  819.998220]  [<ffffffff8113e90c>] ? ep_unregister_pollwait.isra.10+0x65/0x65
Oct  3 16:37:56 m kernel: [  819.998293]  [<ffffffff8113f2b8>] ? ep_scan_ready_list.isra.11+0x165/0x184
Oct  3 16:37:56 m kernel: [  819.998365]  [<ffffffff8113f4f2>] ? ep_poll+0x206/0x277
Oct  3 16:37:56 m kernel: [  819.998434]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
Oct  3 16:37:56 m kernel: [  819.998505]  [<ffffffff810594ca>] ? mmdrop+0xd/0x1c
Oct  3 16:37:56 m kernel: [  819.998573]  [<ffffffff812c4056>] ? __sys_recvmsg+0x39/0x57
Oct  3 16:37:56 m kernel: [  819.998645]  [<ffffffff813a0062>] ? system_call_fastpath+0x16/0x1b
Oct  3 16:37:56 m kernel: [  819.998714] Code: 80 4e 7d 40 f0 41 ff 86 e4 00 00 00 eb 24 41 ff 8d a0 00 00 00 49 8b 0e 49 8b 46 08 49 c7 06 00 00 00 00 49 c7 46 08 00 00 00 00 <48> 89 41 08 48 89 08 48 89 d7 e8 68 d0 0c 00 48 8b 4c 24 20 44 
Oct  3 16:37:56 m kernel: [  820.001782]  RSP <ffff880338a1bb58>
Oct  3 16:37:56 m kernel: [  820.001846] CR2: 0000000000000008
Oct  3 16:37:56 m kernel: [  820.001911] ---[ end trace d9837b90f294c67e ]---
Oct  3 16:38:20 m kernel: [  844.741896] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 iw_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop snd_pcm iTCO_wdt iTCO_vendor_support snd_timer snd psmouse i7core_edac soundcore lpc_ich edac_core i2c_i801 coretemp ioatdma kvm_intel acpi_cpufreq mfd_core serio_raw pcspkr joydev ehci_pci evdev kvm tpm_tis processor tpm thermal_sys button microcode ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata uhci_hcd scsi_mod ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core [last unloaded: ib_cm]
Oct  3 16:38:20 m kernel: [  844.745999] CPU: 2 PID: 4176 Comm: modprobe Tainted: G      D   I   3.15.0-irati-test5 #11
Oct  3 16:38:20 m kernel: [  844.746085] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
Oct  3 16:38:20 m kernel: [  844.746158] task: ffff880337f12990 ti: ffff880337514000 task.ti: ffff880337514000
Oct  3 16:38:20 m kernel: [  844.746243] RIP: 0010:[<ffffffff81088847>]  [<ffffffff81088847>] csd_lock_wait.isra.1+0x4/0xa
Oct  3 16:38:20 m kernel: [  844.751443] RSP: 0018:ffff880337517d50  EFLAGS: 00000202
Oct  3 16:38:20 m kernel: [  844.751512] RAX: 0000000000000001 RBX: ffff8801bfc53948 RCX: 0000000000000001
Oct  3 16:38:20 m kernel: [  844.751583] RDX: ffff8801bfc361c8 RSI: fffffffffffffffe RDI: ffff8801bfc361e0
Oct  3 16:38:20 m kernel: [  844.751654] RBP: 0000000000000001 R08: ffff8801bfc53948 R09: 000000000000ffff
Oct  3 16:38:20 m kernel: [  844.751725] R10: dead000000200200 R11: dead000000200200 R12: 0000000000000202
Oct  3 16:38:20 m kernel: [  844.751796] R13: 0000000000000202 R14: 000000000000000f R15: 0000000000008000
:
Message from syslogd@m at Oct  3 16:41:12 ...
 kernel:[ 1016.841821] BUG: soft lockup - CPU#5 stuck for 23s! [modprobe:4176]
Oct  3 16:38:20 m kernel: [  844.751868] FS:  00007f90cd0ed700(0000) GS:ffff8801bfc40000(0000) knlGS:0000000000000000
Oct  3 16:38:20 m kernel: [  844.751955] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Oct  3 16:38:20 m kernel: [  844.752023] CR2: 00007f90cd0ce598 CR3: 0000000335922000 CR4: 00000000000007e0
Oct  3 16:38:20 m kernel: [  844.752094] Stack:
Oct  3 16:38:20 m kernel: [  844.752155]  ffffffff81088c33 0000000100000000 000000000000000f 000000000000000f
Oct  3 16:38:20 m kernel: [  844.752413]  ffffffff8102ecac ffff880337517d68 ffffffffa03ef000 ffffffff8102ecac
Oct  3 16:38:20 m kernel: [  844.752670]  0000000000000000 0000000000000000 0000000000000000 0000000000000001
Oct  3 16:38:20 m kernel: [  844.752928] Call Trace:
Oct  3 16:38:20 m kernel: [  844.752993]  [<ffffffff81088c33>] ? smp_call_function_many+0x1e0/0x217
Oct  3 16:38:20 m kernel: [  844.753066]  [<ffffffff8102ecac>] ? __cpa_flush_all+0x1b/0x1b
Oct  3 16:38:20 m kernel: [  844.753138]  [<ffffffff8102ecac>] ? __cpa_flush_all+0x1b/0x1b
Oct  3 16:38:20 m kernel: [  844.753209]  [<ffffffff81088c85>] ? smp_call_function+0x1b/0x20
Oct  3 16:38:20 m kernel: [  844.753280]  [<ffffffff81088cb3>] ? on_each_cpu+0x13/0x2e
Oct  3 16:38:20 m kernel: [  844.753351]  [<ffffffff8102ffd7>] ? change_page_attr_set_clr+0x29a/0x308
Oct  3 16:38:20 m kernel: [  844.753427]  [<ffffffff81030302>] ? change_page_attr_set+0x23/0x28
Oct  3 16:38:20 m kernel: [  844.753498]  [<ffffffff81030321>] ? set_memory_rw+0x1a/0x1f
Oct  3 16:38:20 m kernel: [  844.753571]  [<ffffffff8108b63f>] ? free_module+0x214/0x23f
Oct  3 16:38:20 m kernel: [  844.753642]  [<ffffffff8108b7cc>] ? SyS_delete_module+0x162/0x19b
Oct  3 16:38:20 m kernel: [  844.753715]  [<ffffffff8110e2da>] ? fput+0x5c/0x82
Oct  3 16:38:20 m kernel: [  844.753845]  [<ffffffff813a02ea>] ? int_signal+0x12/0x17
Oct  3 16:38:20 m kernel: [  844.753915]  [<ffffffff813a0062>] ? system_call_fastpath+0x16/0x1b
Oct  3 16:38:20 m kernel: [  844.753984] Code: 95 b5 30 00 c3 90 90 90 c3 f3 48 0f b8 c7 c3 ff c7 50 48 89 f0 48 63 d7 be 00 02 00 00 48 89 c7 e8 9b f5 14 00 5a c3 eb 02 f3 90 <f6> 07 01 75 f9 c3 53 48 c7 c3 40 39 01 00 48 03 1c d5 50 9d 69 
Oct  3 16:38:48 m kernel: [  861.937496] ------------[ cut here ]------------
Oct  3 16:38:48 m kernel: [  861.937570] WARNING: CPU: 1 PID: 598 at kernel/watchdog.c:249 watchdog_overflow_callback+0x80/0xa3()
Oct  3 16:38:48 m kernel: [  861.937658] Watchdog detected hard LOCKUP on cpu 1
Oct  3 16:38:48 m kernel: [  861.937711] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 rpcsec_gss_krb5 nfsv4 iw_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop snd_pcm iTCO_wdt iTCO_vendor_support snd_timer snd psmouse i7core_edac soundcore lpc_ich edac_core i2c_i801 coretemp ioatdma kvm_intel acpi_cpufreq mfd_core serio_raw pcspkr joydev ehci_pci evdev kvm tpm_tis processor tpm thermal_sys button microcode ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata uhci_hcd scsi_mod ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core [last unloaded: ib_cm]
Oct  3 16:38:48 m kernel: [  861.941866] CPU: 1 PID: 598 Comm: udevd Tainted: G      D   I   3.15.0-irati-test5 #11
Oct  3 16:38:48 m kernel: [  861.941952] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
Oct  3 16:38:48 m kernel: [  861.942023]  0000000000000000 0000000000000009 ffffffff81395de8 ffff8801bfc27c78
Oct  3 16:38:48 m kernel: [  861.942281]  ffffffff810395fb 0000000000000000 ffffffff810a3f72 0000000000000000
Oct  3 16:38:48 m kernel: [  861.942538]  ffff8801b912dc00 0000000000000000 ffff8801bfc27d78 ffff8801bfc27ef8
Oct  3 16:38:48 m kernel: [  861.942796] Call Trace:
Oct  3 16:38:48 m kernel: [  861.942858]  <NMI>  [<ffffffff81395de8>] ? dump_stack+0x41/0x51
Oct  3 16:38:48 m kernel: [  861.943019]  [<ffffffff810395fb>] ? warn_slowpath_common+0x78/0x90
Oct  3 16:38:48 m kernel: [  861.943090]  [<ffffffff810a3f72>] ? watchdog_overflow_callback+0x80/0xa3
Oct  3 16:38:48 m kernel: [  861.943162]  [<ffffffff810396ab>] ? warn_slowpath_fmt+0x45/0x4a
Oct  3 16:38:48 m kernel: [  861.943232]  [<ffffffff810a3f72>] ? watchdog_overflow_callback+0x80/0xa3
Oct  3 16:38:48 m kernel: [  861.943305]  [<ffffffff810c1ca6>] ? __perf_event_overflow+0x12c/0x1b2
Oct  3 16:38:48 m kernel: [  861.943378]  [<ffffffff81016c7d>] ? intel_pmu_handle_irq+0x26c/0x2f4
Oct  3 16:38:48 m kernel: [  861.943450]  [<ffffffff8139c555>] ? perf_event_nmi_handler+0x24/0x3d
Oct  3 16:38:48 m kernel: [  861.943520]  [<ffffffff8139bf37>] ? nmi_handle.isra.4+0x53/0xf2
Oct  3 16:38:48 m kernel: [  861.943590]  [<ffffffff8139c072>] ? do_nmi+0x9c/0x2a9
:
Message from syslogd@m at Oct  3 16:41:40 ...
 kernel:[ 1044.858108] BUG: soft lockup - CPU#5 stuck for 23s! [modprobe:4176]
...

**Comment by sandervrijders** [comment]
This is still there, but it seems related to memory corruption somewhere...
