### ISSUE TITLE
kernel: Mismatch of the port-id number  

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#397]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Monday Oct 06, 2014 at 09:49 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/394_

----

After running the stack for a while (30 minutes), I noticed some weird behaviour on one of my two nodes. I am running a normal DIF over a shim Ethernet. When I tried to run rina-echo-time it failed. The following was found in the kernel logs on that node:

[ 4413.049037] rina-syscalls: Calling personality hook mgmt_sdu_write
[ 4413.049038] rina-personality-default: Calling wrapped function
[ 4413.049040] rina-normal-ipc: Passing SDU to be written to N-1 port 0 from IPC Process 2
[ 4413.049042] rina-pft: Could not find any entry
[ 4413.049067] rina-rmt: Cannot get the NHOP for this PDU
[ 4413.049092] rina-normal-ipc: Could not send to RMT (using dst_addr
...
[ 4425.387675] rina-personality-default: Calling wrapped function
[ 4425.387678] rina-normal-ipc: Passing SDU to be written to N-1 port 3 from IPC Process 2
[ 4425.387682] rina-normal-ipc: Could not send to RMT (using port_id)
...
[ 4505.458089] rina-kipcm: Binding user IPCP 2' RMT to flow in port 3
[ 4505.458092] rina-shim-eth-vlan: Allocate called in a wrong state, how dare you!
[ 4505.458137] rina-kipcm: Failed allocating flow request
[ 4505.458163] rina-kfa: We are destroying flow 3
...
[ 4498.027918] rina-kfa: Posting SDU to port-id 3 
[ 4498.027920] rina-kfa: There is no flow bound to port-id 3
[ 4498.027948] rina-shim-eth-vlan: Failed to process packet
[ 4498.027950] rina-shim-eth-vlan: Worker finished for now, processed 1 frames

IPCM log:

3838(1412588032)#netlink-manager (DBG): Received 40 bytes, parsing the message
3838(1412588032)#netlink-manager (DBG): Source: 0, Netlink family: 22; Version: 1; Operation code: 30; Flags: 0; Sequence number: 1412583761
3838(1412588032)#core (DBG): Received Netlink message. Family: 22; Operation code: 30_CREATE_EFCP_CONN_RESPONSE; Source port: 0; Destination port: 3838; Sequence Number: 1412583761
Is request message? 0; Is response message? 1; Is notification message? 0
Source IPC Process: 2; Destination IPC Process: 0 
3838(1412588032)#core (DBG): Added event of type 31_CREATE_EFCP_CONN_RESPONSE and sequence number 1412583761 to events queue
3838(1412588032)#core (DBG): Waiting for message 3838
3838(1412588032)#event-loop (DBG): Got event of type 31_CREATE_EFCP_CONN_RESPONSE and sequence number 1412583761
3838(1412588032)#flow-allocator (DBG): Created connection with cep-id 0
3832(1412588032)#ipcm (INFO)[os_process_finalized_handler]: Application test2.IRATI:1::terminated

3832(1412588032)#ipcm (INFO)[deallocate_flow]: Application ::: asks IPC process test-eth:1:: to deallocate flow [port-id = 3]

3832(1412588032)#ipcm (INFO)[unregister_app_from_ipcp]: Requested unregistration of application test2.IRATI:1:: from IPC process test-eth:1::

3832(1412588032)#ipcm (INFO)[ipcm_deallocate_flow_response_event_handler]: Deallocating flow identified by port-id 3 from IPC process test-eth:1:: [success = 1]

3832(1412588032)#ipcm (INFO)[ipcm_unregister_response_common]: IPC process test-eth:1:: informed about unregistration of application test2.IRATI:1:: [success = 1]

3832(1412588051)#ipcm (INFO)[os_process_finalized_handler]: Application rina.apps.echotime.client:1::terminated

3832(1412588051)#netlink-manager (ERR): Error sending Netlink message -1 3838
3832(1412588051)#ipcm (ERR)[deallocate_flow]: : Error while application :::asks IPC process test2.IRATI:1:: to deallocate the flow with port-id 2

3832(1412588051)#netlink-manager (ERR): Error sending Netlink message -1 3838
3832(1412588051)#ipcm (ERR)[deallocate_flow]: : Error while application :::asks IPC process test2.IRATI:1:: to deallocate the flow with port-id 2

3832(1412588051)#netlink-manager (ERR): Error sending Netlink message -1 3838
3832(1412588051)#ipcm (ERR)[deallocate_flow]: : Error while application :::asks IPC process test2.IRATI:1:: to deallocate the flow with port-id 2

3832(1412588051)#netlink-manager (ERR): Error sending Netlink message -1 3838
3832(1412588051)#ipcm (ERR)[deallocate_flow]: : Error while application :::asks IPC process test2.IRATI:1:: to deallocate the flow with port-id 2

3832(1412588051)#netlink-manager (ERR): Error sending Netlink message -1 3838
3832(1412588051)#ipcm (ERR)[deallocate_flow]: : Error while application :::asks IPC process test2.IRATI:1:: to deallocate the flow with port-id 2

3832(1412588051)#netlink-manager (ERR): Error sending Netlink message -1 3838
3832(1412588051)#ipcm (ERR)[deallocate_flow]: : Error while application :::asks IPC process test2.IRATI:1:: to deallocate the flow with port-id 2

Seems to me there is mismatch of the port number in kernel space. After bad cleanup? Bad locking?

**Comment by sandervrijders** [comment]
Not reproducible
