### ISSUE TITLE
IPCP daemon: replace all busy waiting loops with proper event handling/notifications

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#408]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Thursday Oct 23, 2014 at 15:34 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/405_

----

IPC Process makes use of this type of construct

while (true) {
    do_some_processing();
    waitForMilliseconds(100)
}

which should be replaced by something like

register_handler_for_event_x(handler_x);
function handler_x()
{
   do_some_processing();
}

**Comment by sandervrijders** [comment]
Is this the case in current IPCM?

**Comment by msune** [comment]
Invalid
