### ISSUE TITLE
Remove CDAP.pb.cc and .h from librina and add compilation of the .proto file in the make

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#409]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Friday Oct 24, 2014 at 09:31 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/406_

----

Currently, CDAP.pb.cc and CDAP.pb.h are in the librina/src directory and in the repository. These files are autogenerated with the GPB tool, so according to how it is make in rinad, makefile must add a rule to compile the CDAP.proto file ans generate both files when make install is called.

**Comment by sandervrijders** [comment]
I think this happens right now?

**Comment by bernatgaston** [comment]
this can be closed
