### ISSUE TITLE
Refactor routing

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#410]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Friday Oct 24, 2014 at 09:31 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/407_

----

Refactor routing module according to new routing specs.

**Comment by sandervrijders** [comment]
Did this happen? I saw some commits wrt to routing pass by a couple of days ago as well

**Comment by bernatgaston** [comment]
This can be closed
