### ISSUE TITLE
Make enrollment sequence capable of operating over unreliable flows

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#414]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [edugrasa](https://github.com/edugrasa)**
_Tuesday Nov 04, 2014 at 22:23 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/411_

---

Retransmit data if needed (current timers will just abort enrollment).

**Comment by sandervrijders** [comment]
Is this feature implemented?

**Comment by edugrasa** [comment]
First version addressed buy #1093 (upon timeout in any step, procedure is retried from the beginning N times; configurable)
