### ISSUE TITLE
After enrollment use reliable N-flow to transport layer management traffic

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#415]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [edugrasa](https://github.com/edugrasa)**
_Tuesday Nov 04, 2014 at 22:24 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/412_

---

Keep the EFCP layer management PDUs only for enrollment and then transition to the use of a reliable N-flow to carry the layer management traffic (cep-ids could be pre-decided or negotiated during enrollment). This way layer management can operate over unreliable N-1 flows.

**Comment by edugrasa** [comment]
Fixed by #1093
