### ISSUE TITLE
Inconsisten lock in shim-eth and/or arp286 during enrollment

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#416]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Thursday Nov 06, 2014 at 15:33 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/413_

----

The kernel drops a inconsistent lock state message but it gets to survive and continue:

Nov  6 16:23:32 irati-vbox2 kernel: [  293.434965] 
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] =================================
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] [ INFO: inconsistent lock state ]
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] 3.15.0 #406 Not tainted
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] ---------------------------------
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] inconsistent {SOFTIRQ-ON-W} -> {IN-SOFTIRQ-W} usage.
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] swapper/0/0 [HC0[0]:SC1[1]:HE0:SE0] takes:
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  (&(&tables_lock)->rlock){+.?...}, at: [<e114d8c6>] tbls_find+0x26/0x80 [arp826]
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] {SOFTIRQ-ON-W} state was registered at:
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<c1090c3b>] __lock_acquire+0x46b/0x1a20
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<c109277e>] lock_acquire+0x7e/0x100
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<c16622d2>] _raw_spin_lock+0x42/0x70
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<e114dd8c>] tbls_destroy+0x1c/0x90 [arp826]
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<e1159550>] 0xe1159550
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<c100048a>] do_one_initcall+0xda/0x130
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<c10c3934>] load_module+0x1a64/0x21d0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<c10c412e>] SyS_init_module+0x8e/0xc0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   [<c166ad0c>] sysenter_do_call+0x12/0x32
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] irq event stamp: 850867
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] hardirqs last  enabled at (850866): [<c10b0094>] __getnstimeofday+0x64/0x180
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] hardirqs last disabled at (850867): [<c166242e>] _raw_spin_lock_irqsave+0x1e/0x90
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] softirqs last  enabled at (850850): [<c1047caf>] _local_bh_enable+0x1f/0x50
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] softirqs last disabled at (850851): [<c1004049>] do_softirq_own_stack+0x29/0x40
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] 
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] other info that might help us debug this:
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  Possible unsafe locking scenario:
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] 
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]        CPU0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]        ----
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   lock(&(&tables_lock)->rlock);
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]   <Interrupt>
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]     lock(&(&tables_lock)->rlock);
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] 
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  *** DEADLOCK ***
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] 
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] 1 lock held by swapper/0/0:
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  #3:  (rcu_read_lock){......}, at: [<c155b009>] __netif_receive_skb_core+0x49/0x6b0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] 
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] stack backtrace:
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 3.15.0 #406
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] Hardware name: innotek GmbH VirtualBox, BIOS VirtualBox 12/01/2006
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  00000000 00000000 d7c15cdc c1655dfb c1915aa0 d7c15d18 c165285d c1840361
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  c18406c6 00000000 00000000 00000000 00000001 00000001 00000000 00000000
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  c18406c6 00000004 c1916050 00000000 d7c15d50 c108f0dd 00000004 00000000
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872] Call Trace:
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1655dfb>] dump_stack+0x48/0x60
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c165285d>] print_usage_bug+0x1c8/0x1d2
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c108f0dd>] mark_lock+0x27d/0x2e0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c108e590>] ? check_usage_backwards+0x110/0x110
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1090bec>] __lock_acquire+0x41c/0x1a20
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1075aaf>] ? sched_clock_cpu+0xff/0x150
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1075752>] ? sched_clock_local+0xb2/0x1a0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1075aaf>] ? sched_clock_cpu+0xff/0x150
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1090b7d>] ? __lock_acquire+0x3ad/0x1a20
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c109277e>] lock_acquire+0x7e/0x100
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<e114d8c6>] ? tbls_find+0x26/0x80 [arp826]
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1662461>] _raw_spin_lock_irqsave+0x51/0x90
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<e114d8c6>] ? tbls_find+0x26/0x80 [arp826]
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<e114d8c6>] tbls_find+0x26/0x80 [arp826]
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<e114e604>] arp_receive+0xc4/0x610 [arp826]
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c163a19c>] ? vlan_do_receive+0x22c/0x2f0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155b151>] ? __netif_receive_skb_core+0x191/0x6b0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1639c08>] ? vlan_untag+0xf8/0x170
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155b4e3>] __netif_receive_skb_core+0x523/0x6b0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155b009>] ? __netif_receive_skb_core+0x49/0x6b0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155b68d>] __netif_receive_skb+0x1d/0x60
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155b84f>] netif_receive_skb_internal+0x1f/0xf0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155bf95>] ? net_rx_action+0x115/0x210
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155b938>] netif_receive_skb+0x18/0x60
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1494dc5>] virtnet_poll+0x435/0x6f0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155bf95>] ? net_rx_action+0x115/0x210
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c107e918>] ? rebalance_domains+0xe8/0x2a0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c155bf95>] net_rx_action+0x115/0x210
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c10482c3>] __do_softirq+0xf3/0x2a0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c10481d0>] ? perf_trace_irq_handler_exit+0xd0/0xd0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1004049>] do_softirq_own_stack+0x29/0x40
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  <IRQ>  [<c1048705>] irq_exit+0xa5/0xb0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c166b31b>] do_IRQ+0x4b/0xe0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c166b1f1>] common_interrupt+0x31/0x38
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1009fae>] ? default_idle+0x1e/0xc0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c100a73e>] arch_cpu_idle+0xe/0x10
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c1084b20>] cpu_startup_entry+0x1e0/0x370
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c108f3cb>] ? trace_hardirqs_on+0xb/0x10
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c164a9f9>] rest_init+0xb9/0xc0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c164a940>] ? reciprocal_value+0xa0/0xa0
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c19abac9>] start_kernel+0x3e2/0x3e9
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c19ab51c>] ? repair_env_string+0x51/0x51
Nov  6 16:23:32 irati-vbox2 kernel: [  293.438872]  [<c19ab360>] i386_start_kernel+0x12e/0x131
Nov  6 16:23:32 irati-vbox2 kernel: [  294.697735] rina-arp826-rxtx: Processing ARP skb d12fe480
Nov  6 16:23:32 irati-vbox2 kernel: [  294.702466] rina-arp826-rxtx: Decoded ARP header:
Nov  6 16:23:32 irati-vbox2 kernel: [  294.706207] rina-arp826-rxtx:   Hardware type           = 0x0001
Nov  6 16:23:32 irati-vbox2 kernel: [  294.710852] rina-arp826-rxtx:   Protocol type           = 0xD1F0
Nov  6 16:23:32 irati-vbox2 kernel: [  294.715614] rina-arp826-rxtx:   Hardware address length = 6
Nov  6 16:23:32 irati-vbox2 kernel: [  294.719955] rina-arp826-rxtx:   Protocol address length = 15
Nov  6 16:23:32 irati-vbox2 kernel: [  294.724544] rina-arp826-rxtx:   Operation               = 0x0001
Nov  6 16:23:32 irati-vbox2 kernel: [  294.729305] rina-arp826-rxtx: We can handle this ARP
Nov  6 16:23:32 irati-vbox2 kernel: [  294.733221] rina-arp826-rxtx: Fetching addresses
Nov  6 16:23:32 irati-vbox2 kernel: [  294.737182] rina-arp826-rxtx: Shrinking as needed
Nov  6 16:23:32 irati-vbox2 kernel: [  294.740935] rina-arp826-utils: GPA d3968ac8 (15): 0x74657374312E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  294.746881] rina-arp826-utils: Looking for filler 0x00 in GPA (length = 15)
Nov  6 16:23:32 irati-vbox2 kernel: [  294.753539] rina-arp826-utils: GPA doesn't need to be shrinked ...
Nov  6 16:23:32 irati-vbox2 kernel: [  294.758560] rina-arp826-utils: GPA d3968a10 (15): 0x74657374322E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  294.767252] rina-arp826-utils: Looking for filler 0x00 in GPA (length = 15)
Nov  6 16:23:32 irati-vbox2 kernel: [  294.774741] rina-arp826-utils: GPA doesn't need to be shrinked ...
Nov  6 16:23:32 irati-vbox2 kernel: [  294.784964] rina-arp826-tables: Looking for the following address in table
Nov  6 16:23:32 irati-vbox2 kernel: [  294.809914] rina-arp826-utils: GPA d3968ac8 (15): 0x74657374312E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  294.832686] rina-arp826-tables: Showing addresses in table in the meanwhile
Nov  6 16:23:32 irati-vbox2 kernel: [  294.854588] rina-arp826-utils: GPA d39680b8 (15): 0x74657374322E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  294.877976] rina-arp826-tables: Got no matching address
Nov  6 16:23:32 irati-vbox2 kernel: [  294.893000] rina-arp826-rxtx: Adding new entry to the table
Nov  6 16:23:32 irati-vbox2 kernel: [  294.905804] rina-arp826-tables: Creating new table entry
Nov  6 16:23:32 irati-vbox2 kernel: [  294.910154] rina-arp826-tables: Table entry c797c480 created successfully
Nov  6 16:23:32 irati-vbox2 kernel: [  294.915683] rina-arp826-tables: Adding entry c797c480 to the table
Nov  6 16:23:32 irati-vbox2 kernel: [  294.922612] rina-arp826-tables: Entry c797c480 added successfully to the table
Nov  6 16:23:32 irati-vbox2 kernel: [  294.953605] rina-arp826-tables: Looking for the following address in table
Nov  6 16:23:32 irati-vbox2 kernel: [  294.959379] rina-arp826-utils: GPA d3968a10 (15): 0x74657374322E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  294.966370] rina-arp826-tables: Showing addresses in table in the meanwhile
Nov  6 16:23:32 irati-vbox2 kernel: [  294.972004] rina-arp826-utils: GPA d3968958 (15): 0x74657374312E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  294.978203] rina-arp826-utils: GPA d39680b8 (15): 0x74657374322E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  294.984163] rina-arp826-tables: That's the address I need
Nov  6 16:23:32 irati-vbox2 kernel: [  294.995684] rina-arp826-rxtx: Showing the target ha
Nov  6 16:23:32 irati-vbox2 kernel: [  295.003494] rina-arp826-utils: GHA c797c9c0: AE:33:4F:27:00:08
Nov  6 16:23:32 irati-vbox2 kernel: [  295.008136] rina-arp826-rxtx: Sending ARP reply
Nov  6 16:23:32 irati-vbox2 kernel: [  295.011847] rina-arp826-rxtx: Growing addresses to 15
Nov  6 16:23:32 irati-vbox2 kernel: [  295.016933] rina-arp826-utils: GPA d39687e8 (15): 0x74657374322E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  295.022930] rina-arp826-utils: No needs to grow the GPA
Nov  6 16:23:32 irati-vbox2 kernel: [  295.027256] rina-arp826-utils: GPA d39688a0 (15): 0x74657374312E49524154492F312F2F
Nov  6 16:23:32 irati-vbox2 kernel: [  295.048839] rina-arp826-utils: No needs to grow the GPA
Nov  6 16:23:32 irati-vbox2 kernel: [  295.075855] rina-arp826-rxtx: Creating an ARP packet
Nov  6 16:23:32 irati-vbox2 kernel: [  295.092495] rina-arp826-rxtx: ARP packet sent successfully
Nov  6 16:23:32 irati-vbox2 kernel: [  295.103315] rina-arp826-rxtx: Request replied successfully
Nov  6 16:23:32 irati-vbox2 kernel: [  295.109116] rina-arp826-rxtx: Processing completed successfully
Nov  6 16:23:34 irati-vbox2 kernel: [  296.711845] rina-shim-eth-vlan: Worker waking up
Nov  6 16:23:34 irati-vbox2 kernel: [  296.769639] rina-shim-eth-vlan: Have to create a new flow
Nov  6 16:23:34 irati-vbox2 kernel: [  296.814004] BUG: sleeping function called from invalid context at kernel/locking/mutex.c:586
Nov  6 16:23:34 irati-vbox2 kernel: [  296.821468] in_atomic(): 1, irqs_disabled(): 0, pid: 64, name: kworker/u5:0
Nov  6 16:23:34 irati-vbox2 kernel: [  296.827454] INFO: lockdep is turned off.
Nov  6 16:23:34 irati-vbox2 kernel: [  296.830693] CPU: 0 PID: 64 Comm: kworker/u5:0 Not tainted 3.15.0 #406
Nov  6 16:23:34 irati-vbox2 kernel: [  296.836844] Hardware name: innotek GmbH VirtualBox, BIOS VirtualBox 12/01/2006
Nov  6 16:23:34 irati-vbox2 kernel: [  296.842752] Workqueue: shim-eth-vlan eth_vlan_rcv_worker [shim_eth_vlan]
Nov  6 16:23:34 irati-vbox2 kernel: [  296.848357]  00000000 00000000 de89fde4 c1655dfb c40996b0 de89fe08 c106bb89 c1831264
Nov  6 16:23:34 irati-vbox2 kernel: [  296.855179]  00000001 00000000 00000040 c4099a78 de566cc0 de566cc0 de89fe50 c165f203
Nov  6 16:23:34 irati-vbox2 kernel: [  296.862098]  c164cc5c 00008020 00000000 de89fe4c c116831e 00008020 00000000 00000000
Nov  6 16:23:34 irati-vbox2 kernel: [  296.869163] Call Trace:
Nov  6 16:23:34 irati-vbox2 kernel: [  296.871150]  [<c1655dfb>] dump_stack+0x48/0x60
Nov  6 16:23:34 irati-vbox2 kernel: [  296.875065]  [<c106bb89>] __might_sleep+0xe9/0x120
Nov  6 16:23:34 irati-vbox2 kernel: [  296.878996]  [<c165f203>] mutex_lock_nested+0x23/0x370
Nov  6 16:23:34 irati-vbox2 kernel: [  296.883231]  [<c164cc5c>] ? kmemleak_alloc+0x2c/0x60
Nov  6 16:23:34 irati-vbox2 kernel: [  296.887442]  [<c116831e>] ? __kmalloc+0xde/0x1c0
Nov  6 16:23:34 irati-vbox2 kernel: [  296.891232]  [<c164076f>] ? rkzalloc+0x1f/0x60
Nov  6 16:23:34 irati-vbox2 kernel: [  296.895134]  [<e08bb4da>] kfa_port_id_reserve+0x1a/0x90 [rina_personality_default]
Nov  6 16:23:34 irati-vbox2 kernel: [  296.901560]  [<e086eab0>] eth_vlan_rcv_worker+0x2a0/0x6a4 [shim_eth_vlan]
Nov  6 16:23:34 irati-vbox2 kernel: [  296.907809]  [<c105ca2c>] process_one_work+0x19c/0x490
Nov  6 16:23:34 irati-vbox2 kernel: [  296.912494]  [<c105c9b7>] ? process_one_work+0x127/0x490
Nov  6 16:23:34 irati-vbox2 kernel: [  296.917185]  [<c105ce49>] worker_thread+0xf9/0x320
Nov  6 16:23:34 irati-vbox2 kernel: [  296.921825]  [<c105cd50>] ? process_scheduled_works+0x30/0x30
Nov  6 16:23:34 irati-vbox2 kernel: [  296.926929]  [<c106346b>] kthread+0x9b/0xb0
Nov  6 16:23:34 irati-vbox2 kernel: [  296.931526]  [<c1662d07>] ? _raw_spin_unlock_irq+0x27/0x40
Nov  6 16:23:34 irati-vbox2 kernel: [  296.936440]  [<c1060000>] ? alloc_pid+0x320/0x3f0
Nov  6 16:23:34 irati-vbox2 kernel: [  296.941568]  [<c166ac81>] ret_from_kernel_thread+0x21/0x30
Nov  6 16:23:34 irati-vbox2 kernel: [  296.947322]  [<c10633d0>] ? kthread_create_on_node+0x170/0x170
Nov  6 16:23:34 irati-vbox2 kernel: [  296.958828] rina-pidm: The pidm bitmap find returned id 0 (bad = -1)
Nov  6 16:23:34 irati-vbox2 kernel: [  296.975482] rina-pidm: Bitmap allocation completed successfully (id = 0)

**Comment by lbergesio** [comment]
This issue is fix with commit d0b8905a12f5e09c2e0195cb595d3ca3fc2af4d6 and has to be closed
