### ISSUE TITLE
Kernel panic when trying to enroll with dloop code

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#419]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Wednesday Nov 26, 2014 at 16:18 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/416_

----

[  181.761875] rina-rmt: There was a pending work already in the ingress queue
[  181.761877] rina-shim-eth-vlan: Worker finished for now, processed 1 frames
[  181.761879] rina-rmt: Receive worker called
[  181.761882] rina-rqueue: Entry ffff88033ef1f3a0 head-popped from queue ffff880338f24e00 (length = 1)
[  181.761885] rina-shim-eth-vlan: Worker waking up
[  181.761888] rina-shim-eth-vlan: Flow exists, queueing or delivering or dropping
[  181.761891] rina-rqueue: Entry ffff88033ef1f340 tail-pushed into queue ffff8803371e53c0 (length = 1)
[  181.761893] rina-rqueue: Entry ffff8803371e5900 tail-pushed into queue ffff880338f24e00 (length = 2)
[  181.761898] rina-rwq: Work posted on workqueue ffff8803370be400, please wait ...
[  181.761900] rina-shim-eth-vlan: Worker finished for now, processed 1 frames
[  181.761902] rina-normal-ipc: Gonna wake up all waitqueues: 1
[  181.761910] ------------[ cut here ]------------
[  181.761923] WARNING: CPU: 4 PID: 336 at kernel/workqueue.c:610 set_work_data+0x2e/0x40()
[  181.761926] rina-rqueue: Entry ffff88033ef1f340 head-popped from queue ffff8803371e53c0 (length = 0)
[  181.761928] rina-syscalls: Personality returned value 0
[  181.761931] Modules linked in: normal_ipcp shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop iTCO_wdt iTCO_vendor_support coretemp kvm_intel kvm ioatdma lpc_ich acpi_cpufreq mfd_core i2c_i801 ehci_pci psmouse i7core_edac edac_core microcode snd_pcm tpm_tis processor tpm button snd_timer snd soundcore thermal_sys serio_raw pcspkr joydev evdev ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata uhci_hcd ehci_hcd scsi_mod usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
[  181.762052] CPU: 4 PID: 336 Comm: kworker/u50:2 Not tainted 3.15.0-4 #4
[  181.762056] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
[  181.762064] Workqueue: rmt-ingress-wq-ffff8803 rwq_worker
[  181.762067]  0000000000000000 0000000000000009 ffffffff81395e78 0000000000000000
[  181.762072]  ffffffff810395fb 0000000000000000 ffffffff8104af43 ffff8801b9238568
[  181.762077]  ffff8803383e0140 0000000000000640 0000000000000000 ffff88033320fb00
[  181.762082] Call Trace:
[  181.762091]  [<ffffffff81395e78>] ? dump_stack+0x41/0x51
[  181.762099]  [<ffffffff810395fb>] ? warn_slowpath_common+0x78/0x90
[  181.762102] rina-syscalls: Handling personality hook mgmt_sdu_read
[  181.762106]  [<ffffffff8104af43>] ? set_work_data+0x2e/0x40
[  181.762113]  [<ffffffff8104af43>] ? set_work_data+0x2e/0x40
[  181.762118]  [<ffffffff8104d594>] ? process_one_work+0x15d/0x293
[  181.762121] rina-syscalls: Calling personality hook mgmt_sdu_read
[  181.762123] rina-personality-default: Calling wrapped function
[  181.762125] rina-normal-ipc: Trying to read mgmt SDU from IPC Process 2
[  181.762127] rina-normal-ipc: Mgmt read going to sleep...
[  181.762132]  [<ffffffff8104d810>] ? worker_thread+0x121/0x1e7
[  181.762138]  [<ffffffff8104d6ef>] ? process_scheduled_works+0x25/0x25
[  181.762145]  [<ffffffff810521e6>] ? kthread+0x99/0xa1
[  181.762149]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
[  181.762155]  [<ffffffff813a003c>] ? ret_from_fork+0x7c/0xb0
[  181.762159]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
[  181.762162] ---[ end trace e90ca29a9a352fcb ]---
[  181.762164] rina-rmt: Receive worker called
[  181.762167] rina-rqueue: Entry ffff88033ef1fdc0 head-popped from queue ffff880338f24e00 (length = 1)
[  181.762175] rina-rqueue: Entry ffff88033ef1f240 tail-pushed into queue ffff8803371e53c0 (length = 1)
[  181.762176] rina-normal-ipc: Gonna wake up all waitqueues: 1
[  181.762187] rina-rqueue: Entry ffff88033ef1f240 head-popped from queue ffff8803371e53c0 (length = 0)
[  181.762191] rina-syscalls: Personality returned value 0
[  181.762370] rina-syscalls: Handling personality hook mgmt_sdu_read
[  181.762373] rina-syscalls: Calling personality hook mgmt_sdu_read

**Comment by vmaffione** [comment]
Not reproducible anymore
