### ISSUE TITLE
Enrollment fails in be-leonardo-dloop-uwq-ack

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#426]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Friday Dec 05, 2014 at 10:11 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/423_

----

It happens often, but not always. Enrollment timeouts, and sometimes the behaviour after the timeout is incorrect too. Attached the logs of the ipcm in both server and client. Enrollment is in the direction server->client. The kernel does not report any problems. Complete logs available under request.

SERVER:
3353(1417772184)#enrollment-task (DBG): Created a new Enrollment state machine for remote IPC process: test2.IRATI-1--
3353(1417772184)#concurrency (DBG): Lockable created successfully
3353(1417772184)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3353(1417772184)#rib-daemon (DBG): Sent CDAP message of size 102 through port-id 1: 
0_M_CONNECT
Abstract syntax: 115
Authentication mechanism: 0
Source AP name: test1.IRATI
Source AP instance: 1
Source AE name: Management
Destination AP name: test2.IRATI
Destination AP instance: 1
Destination AE name: Management
Invoke id: 1
Version: 1

3353(1417772184)#cdap-manager (DBG): Waiting timeout 180000 to receive a connection response
3353(1417772184)#concurrency (DBG): Lockable created successfully
3353(1417772184)#concurrency (DBG): Lockable created successfully
3353(1417772184)#timer (DBG): Timer with ID 163718240 started
3353(1417772184)#pduft-generator (DBG): flow allocation waiting for enrollment
3353(1417772185)#cdap-manager (DBG): Connection response received
3353(1417772185)#timer (DBG): Waiting for the timer 163718240 to join
3353(1417772185)#timer (DBG): Timer with ID 163718240 ended
3353(1417772185)#rib (DBG): Received CDAP message through portId 1: 
1_M_CONNECT_R
Abstract syntax: 115
Authentication mechanism: 0
Source AP name: test2.IRATI
Source AP instance: 1
Source AE name: Management
Destination AP name: test1.IRATI
Destination AP instance: 1
Destination AE name: Management
Invoke id: 1
Result: 0
Version: 1

3353(1417772185)#enrollment-task (DBG): Received M_CONNECT_R cdapMessage from portId 1
3353(1417772185)#application (DBG): IPCManager.getRegisteredApplications called
3353(1417772185)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3353(1417772185)#rib-daemon (DBG): Sent CDAP message of size 119 through port-id 1: 
14_M_START
Invoke id: 1
Object class: enrollment information
Object name: /daf/management/enrollment
Object value: 0xb6002db0
Scope: 0

3353(1417772185)#enrollment-task (DBG): Sent a M_START Message to portid: 1
3353(1417772185)#syscalls (DBG): Gonna call syscall SYS_readManagementSDU (360)
3353(1417772185)#rib (DBG): Received CDAP message through portId 1: 
15_M_START_r
Invoke id: 1
Object class: enrollment information
Object name: /daf/management/enrollment
Result: 0

3353(1417772185)#syscalls (DBG): Gonna call syscall SYS_readManagementSDU (360)
3353(1417772185)#rib (DBG): Received CDAP message through portId 1: 
4_M_CREATE
Object class: neighbor set
Object name: /daf/management/neighbors
Object value: 0xb6003008
Scope: 0

3353(1417772185)#rib (DBG): Remote operation 4 called on object /daf/management/neighbors
3353(1417772185)#application (DBG): IPCManager.getRegisteredApplications called
3353(1417772185)#rib (INFO): Object with name /daf/management/neighbors/test2.IRATI, class neighbor, instance 18 added to the RIB
3353(1417772185)#syscalls (DBG): Gonna call syscall SYS_readManagementSDU (360)
3347(1417772192)#ipcm (ERR)[enroll_to_dif]: : Timed out

3353(1417772195)#timer (DBG): Waiting for the timer 163729808 to join
3353(1417772196)#rib (DBG): Received CDAP message through portId 1: 
16_M_STOP
Invoke id: 1
Object class: enrollment information
Object name: /daf/management/enrollment
Object value: 0xb6003008
Scope: 0

3353(1417772196)#rib (DBG): Remote operation 16 called on object /daf/management/enrollment
3353(1417772196)#enrollment-task (DBG): No DFT entries to be sent
3353(1417772196)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3353(1417772196)#rib-daemon (DBG): Sent CDAP message of size 58 through port-id 1: 
17_M_STOP_R
Invoke id: 1
Result: 0

3353(1417772196)#timer (DBG): Waiting for the timer 163729808 to join
3353(1417772196)#concurrency (CRIT): Cannot join thread. Error is: 22
3353(1417772196)#enrollment-task (ERR): Problems sending CDAP message: Cannot join thread
3353(1417772196)#enrollment-task (ERR): Problems requesting more information or starting: Cannot send a response for the 16 operation with invokeId 1
3353(1417772196)#concurrency (CRIT): Cannot lock mutex
3353(1417772196)#rib (ERR): Problems processing incoming CDAP request message Cannot lock mutex
3353(1417772196)#syscalls (DBG): Gonna call syscall SYS_readManagementSDU (360)
3353(1417772196)#concurrency (CRIT): Cannot lock mutex
terminate called after throwing an instance of 'rina::ConcurrentException'
  what():  Cannot lock mutex
3347(1417772196)#ipcm (INFO)[os_process_finalized_handler]: Application test1.IRATI:1::terminated

3347(1417772196)#ipcm (INFO)[deallocate_flow]: Application ::: asks IPC process test-eth:1:: to deallocate flow [port-id = 1]

3347(1417772196)#ipcm (INFO)[unregister_app_from_ipcp]: Requested unregistration of application test1.IRATI:1:: from IPC process test-eth:1::

3347(1417772196)#ipcm (INFO)[ipcm_deallocate_flow_response_event_handler]: Deallocating flow identified by port-id 1 from IPC process test-eth:1:: [success = 1]

3347(1417772196)#ipcm (INFO)[ipcm_unregister_response_common]: IPC process test-eth:1:: informed about unregistration of application test1.IRATI:1:: [success = 1]

CLIENT:
3256(1417772185)#concurrency (DBG): Lockable created successfully
3256(1417772185)#cdap-manager (DBG): Created a new CDAP session for port 1
3256(1417772185)#rib (DBG): Received CDAP message through portId 1: 
0_M_CONNECT
Abstract syntax: 115
Authentication mechanism: 0
Source AP name: test1.IRATI
Source AP instance: 1
Source AE name: Management
Destination AP name: test2.IRATI
Destination AP instance: 1
Destination AE name: Management
Invoke id: 1
Version: 1

3256(1417772185)#enrollment-task (DBG): Received M_CONNECT CDAP message from port-id 1
3256(1417772185)#concurrency (DBG): Lockable created successfully
3256(1417772185)#concurrency (DBG): Lockable created successfully
3256(1417772185)#timer (DBG): Timer with ID -1241502408 started
3256(1417772185)#concurrency (DBG): Lockable created successfully
3256(1417772185)#enrollment-task (DBG): Created a new Enrollment state machine for remote IPC process: test1.IRATI-1-Management-
3256(1417772185)#enrollment-task (DBG): Authenticating IPC process test1.IRATI-1 ...
3256(1417772185)#enrollment-task (DBG): Authentication successful, deciding if new member can join the DIF...
3256(1417772185)#security-manager (DBG): Allowing IPC Process test1.IRATI to join the DIF
3256(1417772185)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3256(1417772185)#rib-daemon (DBG): Sent CDAP message of size 102 through port-id 1: 
1_M_CONNECT_R
Abstract syntax: 115
Authentication mechanism: 0
Source AP name: test2.IRATI
Source AP instance: 1
Source AE name: Management
Destination AP name: test1.IRATI
Destination AP instance: 1
Destination AE name: Management
Invoke id: 1
Result: 0
Version: 1

3256(1417772185)#enrollment-task (DBG): M_CONNECT_R sent to portID 1. Waiting for start enrollment request message
3256(1417772185)#syscalls (DBG): Gonna call syscall SYS_readManagementSDU (360)
3256(1417772185)#rib (DBG): Received CDAP message through portId 1: 
14_M_START
Invoke id: 1
Object class: enrollment information
Object name: /daf/management/enrollment
Object value: 0xb6003270
Scope: 0

3256(1417772185)#rib (DBG): Remote operation 14 called on object /daf/management/enrollment
3256(1417772185)#enrollment-task (DBG): Remote IPC Process address: 16
3256(1417772185)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3256(1417772185)#rib-daemon (DBG): Sent CDAP message of size 106 through port-id 1: 
15_M_START_r
Invoke id: 1
Object class: enrollment information
Object name: /daf/management/enrollment
Result: 0

3256(1417772185)#enrollment-task (DBG): No DFT entries to be sent
3256(1417772185)#application (DBG): IPCManager.getRegisteredApplications called
3256(1417772185)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3256(1417772185)#rib-daemon (DBG): Sent CDAP message of size 124 through port-id 1: 
4_M_CREATE
Object class: neighbor set
Object name: /daf/management/neighbors
Object value: 0xb6003170
Scope: 0

3256(1417772185)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3256(1417772185)#rib-daemon (DBG): Sent CDAP message of size 119 through port-id 1: 
16_M_STOP
Invoke id: 1
Object class: enrollment information
Object name: /daf/management/enrollment
Object value: 0xb6003170
Scope: 0

3256(1417772185)#enrollment-task (DBG): Waiting for stop enrollment response message
3256(1417772185)#syscalls (DBG): Gonna call syscall SYS_readManagementSDU (360)
3256(1417772195)#timer (DBG): Waiting for the timer -1241502408 to join
3256(1417772196)#timer (DBG): Timer with ID -1241502408 ended
3256(1417772196)#enrollment-task (ERR): An error happened during enrollment of remote IPC Process test1.IRATI-1-Management- because of Timeout waiting for stop enrollment response
3256(1417772196)#enrollment-task (DBG): Removing enrollment state machine associated to test1.IRATI 1
3256(1417772196)#syscalls (DBG): Gonna call syscall SYS_writeManagementSDU (361)
3256(1417772196)#rib-daemon (DBG): Sent CDAP message of size 58 through port-id 1: 
2_M_RELEASE

3256(1417772196)#application (DBG): Application test2.IRATI requested to deallocate flow with port-id 1
3256(1417772196)#rib (ERR): Error decoding CDAP message: Cannot send a message because the CDAP session is not in CONNECTED state
3256(1417772196)#syscalls (DBG): Gonna call syscall SYS_readManagementSDU (360)
3256(1417772196)#netlink-manager (DBG): Sent message of 76 bytes. Family: 25; Operation code: 42_APP_DEALLOCATE_FLOW_REQUEST; Source port: 3256; Destination port: 1; Sequence Number: 1417772158
Is request message? 1; Is response message? 0; Is notification message? 0
Source IPC Process: 0; Destination IPC Process: 0
3256(1417772196)#netlink-manager (DBG): Sent message of 1688 bytes. Family: 25; Operation code: 8_ENROLL_TO_DIF_RESPONSE; Source port: 3256; Destination port: 1; Sequence Number: 33
Is request message? 0; Is response message? 1; Is notification message? 0
Source IPC Process: 2; Destination IPC Process: 0
3250(1417772196)#ipcm (INFO)[deallocate_flow]: Application test2.IRATI:1:: asks IPC process test-eth:1:: to deallocate flow [port-id = 1]

3250(1417772196)#ipcm (WARN)[enroll_to_dif_response_event_handler]: : Warning: IPC process enrollment response received, but no corresponding pending request

3250(1417772196)#ipcm (INFO)[ipcm_deallocate_flow_response_event_handler]: Deallocating flow identified by port-id 1 from IPC process test-eth:1:: [success = 1]

3256(1417772196)#netlink-manager (DBG): Received 84 bytes, parsing the message
3256(1417772196)#netlink-manager (DBG): Source: 1, Netlink family: 25; Version: 1; Operation code: 43; Flags: 0; Sequence number: 1417772158
3256(1417772196)#core (DBG): Received Netlink message. Family: 25; Operation code: 43_APP_DEALLOCATE_FLOW_RESPONSE; Source port: 1; Destination port: 3256; Sequence Number: 1417772158
Is request message? 0; Is response message? 1; Is notification message? 0
Source IPC Process: 0; Destination IPC Process: 2 
3256(1417772196)#core (DBG): Added event of type 4_DEALLOCATE_FLOW_RESPONSE and sequence number 1417772158 to events queue
3256(1417772196)#core (DBG): Waiting for message 3256
3256(1417772196)#event-loop (DBG): Got event of type 4_DEALLOCATE_FLOW_RESPONSE and sequence number 1417772158
3256(1417772196)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/nminusoneflows/1, class nminusone flow, instance 17 removed from the RIB
3256(1417772196)#rib-daemon (INFO): Event 7_N_MINUS_1_FLOW_DEALLOCATED has just happened. Notifying event listeners.
3256(1417772196)#enrollment-task (DBG): Removing enrollment state machine associated to test1.IRATI 1
3250(1417772196)#ipcm (INFO)[ipcm_deallocate_flow_response_event_handler]: Application test2.IRATI:1:: informed about deallocation of flow identified by port-id 1[success = 1]

**Comment by lbergesio** [comment]
Deprecated. Must be closed
