### ISSUE TITLE
IPCM crashes when no logPath is specified in the config file

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#429]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Friday Jan 16, 2015 at 12:14 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/426_

----

3771(1421406855)#ipcm (INFO)[3771(1421406855)#ipcm (CRIT): Got signal -1
3771(1421406855)#rinad-debug (CRIT): Backtrace:
  ./ipcm() [0x44b269]
  ./ipcm() [0x40e765]
  /lib/x86_64-linux-gnu/libc.so.6(+0x35180) [0x7f2ed4203180]
  /lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x1ce0) [0x7f2ed4215f00]
  /usr/local/irati/lib/librina.so.0(_Z3log9LOG_LEVELPKcz+0x1d6) [0x7f2ed5784da6]
  ./ipcm() [0x41c1ad]
  ./ipcm() [0x42027c]
  ./ipcm() [0x4205ad]
  /lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7f2ed4fbe0a4]
  /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f2ed42b3ccd]
3771(1421406855)#concurrency (CRIT): pc

**Comment by sandervrijders** [comment]
Fixed by #498
