### ISSUE TITLE
Soft lockup when running a perf test directly over shim-eth-vlan

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#430]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Monday Jan 19, 2015 at 16:48 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/427_

----

Jan 19 17:41:28 m /usr/sbin/irqbalance: Load average increasing, re-enabling all cpus for irq balancing
Jan 19 17:41:46 m kernel: [  704.619788] BUG: soft lockup - CPU#3 stuck for 23s! [ipcm:3810]
Jan 19 17:41:46 m kernel: [  704.619847] Modules linked in: shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_re
gistry nfs_acl nfs lockd fscache sunrpc loop coretemp snd_pcm snd_timer snd soundcore iTCO_wdt iTCO_vendor_support kvm_intel pcspkr i2c_i801 psmouse evdev serio_raw joydev kvm lpc_ich mfd_core i7core_edac edac_core ioatdma acpi_cpufreq processor ehci_pci thermal_sys micr
ocode button ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata scsi_mod uhci_hcd ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
Jan 19 17:41:46 m kernel: [  704.619919] CPU: 0 PID: 3810 Comm: ipcm Not tainted 3.15.0-irati-v0.9.11-leo #4
Jan 19 17:41:46 m kernel: [  704.619921] Hardware name: Supermicro X8DTT/X8DTT, BIOS 080015  12/10/2009
Jan 19 17:41:46 m kernel: [  704.619924] task: ffff8801b7d94a90 ti: ffff8800bb260000 task.ti: ffff8800bb260000
Jan 19 17:41:46 m kernel: [  704.619926] RIP: 0010:[<ffffffff8106a12e>]  [<ffffffff8106a12e>] do_raw_spin_lock+0x1d/0x23
Jan 19 17:41:46 m kernel: [  704.619934] RSP: 0018:ffff8801bfc03cc0  EFLAGS: 00000297
Jan 19 17:41:46 m kernel: [  704.619936] RAX: 0000000003c603c5 RBX: 0000000000008020 RCX: ffffffffa042e060
Jan 19 17:41:46 m kernel: [  704.619939] RDX: 00000000000003c6 RSI: 00000000000000b1 RDI: ffff8803382e9800
Jan 19 17:41:46 m kernel: [  704.619941] RBP: ffff880036df4f20 R08: 00000000000000b1 R09: dead000000100100
Jan 19 17:41:46 m kernel: [  704.619943] R10: dead000000100100 R11: dead000000200200 R12: ffff8801bfc03c38
Jan 19 17:41:46 m kernel: [  704.619945] R13: ffffffff813a01ca R14: ffff8801b8b55100 R15: ffffffff81024cc9
Jan 19 17:41:46 m kernel: [  704.619948] FS:  00007f8aa2be5740(0000) GS:ffff8801bfc00000(0000) knlGS:0000000000000000
Jan 19 17:41:46 m kernel: [  704.619951] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 19 17:41:46 m kernel: [  704.619953] CR2: 000000000214c008 CR3: 0000000037408000 CR4: 00000000000007f0
Jan 19 17:41:46 m kernel: [  704.619955] Stack:
Jan 19 17:41:46 m kernel: [  704.619957]  ffffffffa0424f22 ffff8801b8b55100 ffff880036df4f60 ffff880036df4f20
Jan 19 17:41:46 m kernel: [  704.619960]  ffff8801b8c407c0 ffff8801b8c40810 ffffffffa0434845 ffff8801b7d5c000
Jan 19 17:41:46 m kernel: [  704.619964]  ffff8801b8c40818 0000000000000000 ffff8801b7e38240 ffffffff8169f748
Jan 19 17:41:46 m kernel: [  704.619967] Call Trace:
Jan 19 17:41:46 m kernel: [  704.619969]  <IRQ> 
Jan 19 17:41:46 m kernel: [  704.619971]  [<ffffffffa0424f22>] ? kfa_sdu_post+0x6f/0x159 [rina_personality_default]
Jan 19 17:41:46 m kernel: [  704.619985]  [<ffffffffa0434845>] ? eth_vlan_rcv+0x31c/0x389 [shim_eth_vlan]
Jan 19 17:41:46 m kernel: [  704.619990]  [<ffffffff812d4cd4>] ? __netif_receive_skb_core+0x424/0x49c
Jan 19 17:41:46 m kernel: [  704.619994]  [<ffffffff812d575a>] ? netif_receive_skb_internal+0x4c/0x7d
Jan 19 17:41:46 m kernel: [  704.619997]  [<ffffffff812d5f07>] ? napi_gro_receive+0x5a/0xb0
Jan 19 17:41:46 m kernel: [  704.620007]  [<ffffffffa0039c25>] ? igb_poll+0x9ed/0xcac [igb]
Jan 19 17:41:46 m kernel: [  704.620012]  [<ffffffff81066c59>] ? __wake_up+0x35/0x46
Jan 19 17:41:46 m kernel: [  704.620016]  [<ffffffff812d5c3e>] ? net_rx_action+0xa2/0x1c1
Jan 19 17:41:46 m kernel: [  704.620020]  [<ffffffff8103ce77>] ? __do_softirq+0xea/0x243
Jan 19 17:41:46 m kernel: [  704.620023]  [<ffffffff8103d125>] ? irq_exit+0x37/0x7d
Jan 19 17:41:46 m kernel: [  704.620028]  [<ffffffff810037f7>] ? do_IRQ+0x9e/0xb5
Jan 19 17:41:46 m kernel: [  704.620033]  [<ffffffff8139a82a>] ? common_interrupt+0x6a/0x6a
Jan 19 17:41:46 m kernel: [  704.620035]  <EOI> 
Jan 19 17:41:46 m kernel: [  704.620036]  [<ffffffff81382d24>] ? rkmalloc+0x22/0x42
Jan 19 17:41:46 m kernel: [  704.620048]  [<ffffffffa0424afb>] ? atomic_dec_and_test+0x3/0xe [rina_personality_default]
Jan 19 17:41:46 m kernel: [  704.620055]  [<ffffffffa0424fa1>] ? kfa_sdu_post+0xee/0x159 [rina_personality_default]
Jan 19 17:41:46 m kernel: [  704.620059]  [<ffffffffa043540d>] ? eth_vlan_flow_allocate_response+0x127/0x18f [shim_eth_vlan]
Jan 19 17:41:46 m kernel: [  704.620066]  [<ffffffffa0426767>] ? notify_ipcp_allocate_flow_response+0x137/0x175 [rina_personality_default]
Jan 19 17:41:46 m kernel: [  704.620072]  [<ffffffffa0426630>] ? notify_ipc_manager_present+0x21/0x21 [rina_personality_default]
Jan 19 17:41:46 m kernel: [  704.620077]  [<ffffffff81387302>] ? dispatcher+0xb9/0xe1
Jan 19 17:41:46 m kernel: [  704.620082]  [<ffffffff812f9e81>] ? genl_family_rcv_msg+0x238/0x2a5
Jan 19 17:41:46 m kernel: [  704.620086]  [<ffffffff81066a6d>] ? __wake_up_common+0x42/0x78
Jan 19 17:41:46 m kernel: [  704.620090]  [<ffffffff812f9f26>] ? genl_rcv_msg+0x38/0x5b
Jan 19 17:41:46 m kernel: [  704.620096]  [<ffffffff812c9360>] ? __kmalloc_reserve.isra.43+0x2a/0x6d
Jan 19 17:41:46 m kernel: [  704.620100]  [<ffffffff812f9eee>] ? genl_family_rcv_msg+0x2a5/0x2a5
Jan 19 17:41:46 m kernel: [  704.620103]  [<ffffffff812f8d7c>] ? netlink_rcv_skb+0x36/0x7c
Jan 19 17:41:46 m kernel: [  704.620107]  [<ffffffff812f8f4a>] ? genl_rcv+0x1f/0x2c
Jan 19 17:41:46 m kernel: [  704.620111]  [<ffffffff812f882a>] ? netlink_unicast+0xff/0x17f
Jan 19 17:41:46 m kernel: [  704.620114]  [<ffffffff812f8ba9>] ? netlink_sendmsg+0x2ff/0x32d
Jan 19 17:41:46 m kernel: [  704.620120]  [<ffffffff812c325d>] ? sock_sendmsg+0x49/0x64
Jan 19 17:41:46 m kernel: [  704.620125]  [<ffffffff8105d318>] ? try_to_wake_up+0x186/0x198
Jan 19 17:41:46 m kernel: [  704.620129]  [<ffffffff81086395>] ? get_futex_key+0x78/0x210
Jan 19 17:41:46 m kernel: [  704.620133]  [<ffffffff812c3bfd>] ? move_addr_to_kernel+0x2e/0x53
Jan 19 17:41:46 m kernel: [  704.620137]  [<ffffffff812ccf5e>] ? verify_iovec+0x4c/0x9a
Jan 19 17:41:46 m kernel: [  704.620141]  [<ffffffff812c3b45>] ? ___sys_sendmsg+0x1e7/0x271
Jan 19 17:41:46 m kernel: [  704.620144]  [<ffffffff81086618>] ? futex_wake+0xeb/0x103
Jan 19 17:41:46 m kernel: [  704.620148]  [<ffffffff81087bf0>] ? do_futex+0xce/0x7c4
Jan 19 17:41:46 m kernel: [  704.620153]  [<ffffffff8113b194>] ? fsnotify+0x237/0x273
Jan 19 17:41:46 m kernel: [  704.620156]  [<ffffffff8105ffdd>] ? set_next_entity+0x14/0x37
Jan 19 17:41:46 m kernel: [  704.620160]  [<ffffffff812c3ed1>] ? __sys_sendmsg+0x39/0x57
Jan 19 17:41:46 m kernel: [  704.620165]  [<ffffffff8139f622>] ? system_call_fastpath+0x16/0x1b
Jan 19 17:41:46 m kernel: [  704.620167] Code: 0c 31 c0 48 81 ff 3e a7 39 81 0f 92 c0 c3 b8 00 00 01 00 f0 0f c1 07 89 c2 c1 ea 10 66 39 c2 74 0c 66 8b 07 66 39 d0 74 04 f3 90 <eb> f4 c3 90 90 90 c3 48 8b 07 65 48 03 04 25 28 ce 00 00 66 83 
Jan 19 17:41:47 m pubsubd[2877]: Totals: total:6 current:6 (3) received:0 emitted:0 failed:0
Jan 19 17:42:14 m kernel: [  714.775304] ------------[ cut here ]------------
Jan 19 17:42:14 m kernel: [  714.775313] WARNING: CPU: 1 PID: 3975 at kernel/watchdog.c:249 watchdog_overflow_callback+0x80/0xa3()
Jan 19 17:42:14 m kernel: [  714.775316] Watchdog detected hard LOCKUP on cpu 1
Jan 19 17:42:14 m kernel: [  714.775317] Modules linked in: shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop coretemp snd_pcm snd_timer snd soundcore iTCO_wdt iTCO_vendor_support kvm_intel pcspkr i2c_i801 psmouse evdev serio_raw joydev kvm lpc_ich mfd_core i7core_edac edac_core ioatdma acpi_cpufreq processor ehci_pci thermal_sys microcode button ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata scsi_mod uhci_hcd ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
Jan 19 17:42:14 m kernel: [  714.775378] CPU: 1 PID: 3975 Comm: rina-echo-time Not tainted 3.15.0-irati-v0.9.11-leo #4
Jan 19 17:42:14 m kernel: [  714.775380] Hardware name: Supermicro X8DTT/X8DTT, BIOS 080015  12/10/2009
Jan 19 17:42:14 m kernel: [  714.775382]  0000000000000000 0000000000000009 ffffffff81396648 ffff8801bfc47c78
Jan 19 17:42:14 m kernel: [  714.775386]  ffffffff810395fb 0000000000000000 ffffffff810a3f72 0000000000000000
Jan 19 17:42:14 m kernel: [  714.775389]  ffff8801b919cc00 0000000000000000 ffff8801bfc47d78 ffff8801bfc47ef8
Jan 19 17:42:14 m kernel: [  714.775392] Call Trace:
Jan 19 17:42:14 m kernel: [  714.775394]  <NMI>  [<ffffffff81396648>] ? dump_stack+0x41/0x51
Jan 19 17:42:14 m kernel: [  714.775403]  [<ffffffff810395fb>] ? warn_slowpath_common+0x78/0x90
Jan 19 17:42:14 m kernel: [  714.775407]  [<ffffffff810a3f72>] ? watchdog_overflow_callback+0x80/0xa3
Jan 19 17:42:14 m kernel: [  714.775411]  [<ffffffff810396ab>] ? warn_slowpath_fmt+0x45/0x4a
Jan 19 17:42:14 m kernel: [  714.775415]  [<ffffffff810a3f72>] ? watchdog_overflow_callback+0x80/0xa3
Jan 19 17:42:14 m kernel: [  714.775420]  [<ffffffff810c1ca6>] ? __perf_event_overflow+0x12c/0x1b2
Jan 19 17:42:14 m kernel: [  714.775425]  [<ffffffff81016c7d>] ? intel_pmu_handle_irq+0x26c/0x2f4
Jan 19 17:42:14 m kernel: [  714.775429]  [<ffffffff8124613e>] ? ghes_copy_tofrom_phys+0x10d/0x163
Jan 19 17:42:14 m kernel: [  714.775434]  [<ffffffff8139bb15>] ? perf_event_nmi_handler+0x24/0x3d
Jan 19 17:42:14 m kernel: [  714.775437]  [<ffffffff8139b4f7>] ? nmi_handle.isra.4+0x53/0xf2
Jan 19 17:42:14 m kernel: [  714.775440]  [<ffffffff8139b632>] ? do_nmi+0x9c/0x2a9
Jan 19 17:42:14 m kernel: [  714.775443]  [<ffffffff8139ad67>] ? end_repeat_nmi+0x1e/0x2e
Jan 19 17:42:14 m kernel: [  714.775448]  [<ffffffff8139a529>] ? _raw_spin_lock_irqsave+0x20/0x23
Jan 19 17:42:14 m kernel: [  714.775452]  [<ffffffff8139a529>] ? _raw_spin_lock_irqsave+0x20/0x23
Jan 19 17:42:14 m kernel: [  714.775455]  [<ffffffff8139a529>] ? _raw_spin_lock_irqsave+0x20/0x23
Jan 19 17:42:14 m kernel: [  714.775457]  <<EOE>>  [<ffffffffa0425774>] ? kfa_flow_sdu_read+0x1a7/0x2cb [rina_personality_default]
Jan 19 17:42:14 m kernel: [  714.775469]  [<ffffffff81066b3b>] ? bit_waitqueue+0x82/0x82
Jan 19 17:42:14 m kernel: [  714.775475]  [<ffffffffa0427b5f>] ? kipcm_sdu_read+0x49/0x52 [rina_personality_default]
Jan 19 17:42:14 m kernel: [  714.775479]  [<ffffffff8138aad5>] ? SyS_sdu_read+0x6a/0x122
Jan 19 17:42:14 m kernel: [  714.775484]  [<ffffffff8139f622>] ? system_call_fastpath+0x16/0x1b
Jan 19 17:42:14 m kernel: [  714.775486] ---[ end trace d35d9b3178a2b560 ]---

**Comment by sandervrijders** [comment]
Not reproducible
