### ISSUE TITLE
Kernel Oops on client and server running normal over shim-tcp-udp

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#433]
<a href="https://github.com/dstaesse"><img src="https://avatars.githubusercontent.com/u/3341175?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dstaesse](https://github.com/dstaesse)**
_Thursday Jan 22, 2015 at 13:49 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/430_

----

This happens on the wall, sending packets using rina-echo-time in perf mode, between two nodes, using configurations (adapted to correct IP addresses) ipcmanager.conf-normalovertcpudp:
server: sudo ./rina-echo-time -l -t perf --perf-interval 10000 -d normal.DIF
client: sudo ./rina-echo-time -t perf -c 1000000 -s 10 -d normal.DIF (may have run fine)
client: sudo ./rina-echo-time -t perf -c 1000000 -s 20 -d normal.DIF (locked during this run)

using irati/wip sha1: 73edafa722c4a479b02038b8ae2342095f2886fd

server kernel Oops:
[  606.269859] rina-personality: Default personality set to 'default'
[  606.287881] rina-shim-tcp-udp: shim-tcp-udp initialized
[  606.287884] rina-ipcp-factories: Factory 'shim-tcp-udp' registered successfully
[  606.301430] rina-ipcp-factories: Factory 'normal-ipc' registered successfully
[  606.545088] rina-kipcm: IPC Manager started. It is listening at NL port-id 1
[  606.595511] rina-rnl-utils: Missing code in net/rina/rnl-utils.c:1123
[  606.595574] rina-rnl-utils: Missing code in net/rina/rnl-utils.c:1181
[  745.038400] BUG: unable to handle kernel paging request
[  745.038467] rina-rqueue: queue ffff8801b7f028a0 is empty, can't head-pop
[  745.038558]  at 0000000200000009
[  745.038650] IP: [<ffffffff8138fc8d>] dtcp_config_destroy+0x9/0x52
[  745.038754] PGD 338a13067 PUD 0 
[  745.038891] Oops: 0000 [#4] SMP 
[  745.039028] Modules linked in: normal_ipcp shim_tcp_udp rina_personality_default nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop iTCO_wdt iTCO_vendor_support coretemp kvm_intel kvm snd_pcm snd_timer snd acpi_cpufreq processor soundcore i2c_i801 i7core_edac edac_core lpc_ich mfd_core thermal_sys ioatdma ehci_pci psmouse joydev tpm_tis tpm pcspkr microcode serio_raw button evdev ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic ata_generic usbhid hid crc32c_intel ata_piix libata uhci_hcd scsi_mod ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
[  745.042665] CPU: 9 PID: 4412 Comm: rina-echo-time Tainted: G          I   3.15.0-irati-v0.9.13.4-perf #6
[  745.042741] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
[  745.042812] task: ffff8803370ccc50 ti: ffff880338334000 task.ti: ffff880338334000
[  745.042898] RIP: 0010:[<ffffffff8138fc8d>]  [<ffffffff8138fc8d>] dtcp_config_destroy+0x9/0x52
[  745.043030] RSP: 0018:ffff880338337db8  EFLAGS: 00010202
[  745.043098] RAX: 0000000000000000 RBX: 0000000200000001 RCX: 00000000000f4201
[  745.043169] RDX: 0000000000000001 RSI: 0000000000000000 RDI: 0000000200000001
[  745.043240] RBP: ffff8803378cc280 R08: fffffffffffffffe R09: 0000000000000001
[  745.043311] R10: 0000000000000040 R11: 0000000000000001 R12: 0000000000000000
[  745.043383] R13: ffff880338c94440 R14: ffff880338e15ac0 R15: ffff880338c94640
[  745.043454] FS:  00007f7b78c0d700(0000) GS:ffff8801bfca0000(0000) knlGS:0000000000000000
[  745.043541] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[  745.043610] CR2: 0000000200000009 CR3: 0000000338154000 CR4: 00000000000007e0
[  745.043680] Stack:
[  745.043742]  ffff8803329948a0 ffffffff8138ee11 00000000000f4201 ffff8803329948a0
[  745.043999]  0000000000000000 ffffffff8138ee9b ffff880332994960 ffffffffa03bc224
[  745.044257]  fffffffffffffffd 0000000000000000 ffff880337a48f00 ffff880332994960
[  745.044514] Call Trace:
[  745.044581]  [<ffffffff8138ee11>] ? conn_policies_destroy+0x1d/0x7f
[  745.044653]  [<ffffffff8138ee9b>] ? connection_destroy+0x28/0x30
[  745.044729]  [<ffffffffa03bc224>] ? efcp_destroy+0xfc/0x10e [rina_personality_default]
[  745.044821]  [<ffffffffa03bc2b3>] ? efcp_connection_destroy+0x7d/0x9d [rina_personality_default]
[  745.044912]  [<ffffffffa0288a1e>] ? remove_all_cepid.isra.0+0x24/0x4a [normal_ipcp]
[  745.045000]  [<ffffffffa0288a92>] ? normal_deallocate+0x4e/0x78 [normal_ipcp]
[  745.045076]  [<ffffffffa03be97d>] ? kfa_flow_destroy+0xe0/0x102 [rina_personality_default]
[  745.045168]  [<ffffffffa03bf467>] ? kfa_flow_sdu_read+0x285/0x2bb [rina_personality_default]
[  745.045258]  [<ffffffff81066b3b>] ? bit_waitqueue+0x82/0x82
[  745.045331]  [<ffffffffa03c178f>] ? kipcm_sdu_read+0x49/0x52 [rina_personality_default]
[  745.045418]  [<ffffffff8138ff15>] ? SyS_sdu_read+0x6a/0x122
[  745.045491]  [<ffffffff813a4a62>] ? system_call_fastpath+0x16/0x1b
[  745.045559] Code: db e8 f3 fe ff ff 41 5b 48 89 d8 5b 5d c3 bf 20 00 00 00 e9 4f ff ff ff bf d0 00 00 00 e9 45 ff ff ff 48 85 ff 53 48 89 fb 74 44 <48> 8b 7f 08 48 85 ff 74 05 e8 8c fd ff ff 48 8b 7b 18 48 85 ff 
[  745.048482] RIP  [<ffffffff8138fc8d>] dtcp_config_destroy+0x9/0x52
[  745.048596]  RSP <ffff880338337db8>
[  745.048660] CR2: 0000000200000009
[  745.048802] ---[ end trace 4d929e0ef615fd59 ]---

client kernel Oops:
[  613.880100] rina-personality: Default personality set to 'default'
[  613.893536] rina-shim-tcp-udp: shim-tcp-udp initialized
[  613.893540] rina-ipcp-factories: Factory 'shim-tcp-udp' registered successfully
[  613.905087] rina-ipcp-factories: Factory 'normal-ipc' registered successfully
[  614.095289] rina-kipcm: IPC Manager started. It is listening at NL port-id 1
[  614.143300] rina-rnl-utils: Missing code in net/rina/rnl-utils.c:1123
[  614.143363] rina-rnl-utils: Missing code in net/rina/rnl-utils.c:1181
[  743.719710] rina-rqueue: queue ffff8801b77a18c0 is empty, can't head-pop
[  743.719722] general protection fault: 0000 [#4] SMP 
[  743.719866] Modules linked in: normal_ipcp shim_tcp_udp rina_personality_default nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop iTCO_wdt iTCO_vendor_support coretemp kvm_intel kvm microcode psmouse i7core_edac snd_pcm snd_timer snd soundcore edac_core serio_raw lpc_ich mfd_core ehci_pci i2c_i801 pcspkr ioatdma acpi_cpufreq tpm_tis evdev joydev processor button thermal_sys tpm ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata uhci_hcd scsi_mod ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
[  743.723539] CPU: 3 PID: 4469 Comm: ipcp Not tainted 3.15.0-irati-v0.9.13.4-perf #6
[  743.723599] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
[  743.723658] task: ffff880336132550 ti: ffff8803374e8000 task.ti: ffff8803374e8000
[  743.723717] RIP: 0010:[<ffffffff8138fc8d>]  [<ffffffff8138fc8d>] dtcp_config_destroy+0x9/0x52
[  743.723826] RSP: 0018:ffff8803374ebe48  EFLAGS: 00010206
[  743.723895] RAX: 0000000000000000 RBX: 2700800002000200 RCX: 0000000000000001
[  743.723967] RDX: 0000000000000001 RSI: 0000000000000000 RDI: 2700800002000200
[  743.724039] RBP: ffff880037790cc0 R08: fffffffffffffffe R09: 0000000000000001
[  743.724111] R10: 0000000000000040 R11: 0000000000000001 R12: 0000000000000000
[  743.724183] R13: ffff8800ba75cec0 R14: ffff880338e40d40 R15: 00007f45497fa700
[  743.724255] FS:  00007f45497fa700(0000) GS:ffff8801bfc60000(0000) knlGS:0000000000000000
[  743.724343] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[  743.724413] CR2: 000000000123f818 CR3: 00000003389c3000 CR4: 00000000000007e0
[  743.724484] Stack:
[  743.724546]  ffff8801b7eced40 ffffffff8138ee11 0000000000000001 ffff8801b7eced40
[  743.724805]  0000000000000000 ffffffff8138ee9b ffff8801b7ecec60 ffffffffa0401224
[  743.725065]  fffffffffffffffd 0000000000000000 ffff8803387dfd80 ffff8801b7ecec60
[  743.725325] Call Trace:
[  743.725393]  [<ffffffff8138ee11>] ? conn_policies_destroy+0x1d/0x7f
[  743.725465]  [<ffffffff8138ee9b>] ? connection_destroy+0x28/0x30
[  743.725542]  [<ffffffffa0401224>] ? efcp_destroy+0xfc/0x10e [rina_personality_default]
[  743.725635]  [<ffffffffa04012b3>] ? efcp_connection_destroy+0x7d/0x9d [rina_personality_default]
[  743.725727]  [<ffffffffa03d0a1e>] ? remove_all_cepid.isra.0+0x24/0x4a [normal_ipcp]
[  743.725816]  [<ffffffffa03d0a92>] ? normal_deallocate+0x4e/0x78 [normal_ipcp]
[  743.725893]  [<ffffffffa040397d>] ? kfa_flow_destroy+0xe0/0x102 [rina_personality_default]
[  743.725985]  [<ffffffffa0403bef>] ? kfa_flow_deallocate+0xbe/0xfb [rina_personality_default]
[  743.726075]  [<ffffffff81390198>] ? SyS_deallocate_port+0x4e/0x53
[  743.726149]  [<ffffffff813a4a62>] ? system_call_fastpath+0x16/0x1b
[  743.726219] Code: db e8 f3 fe ff ff 41 5b 48 89 d8 5b 5d c3 bf 20 00 00 00 e9 4f ff ff ff bf d0 00 00 00 e9 45 ff ff ff 48 85 ff 53 48 89 fb 74 44 <48> 8b 7f 08 48 85 ff 74 05 e8 8c fd ff ff 48 8b 7b 18 48 85 ff 
[  743.729166] RIP  [<ffffffff8138fc8d>] dtcp_config_destroy+0x9/0x52
[  743.729281]  RSP <ffff8803374ebe48>
[  743.729437] ---[ end trace 08467b351a8c0dc5 ]---

**Comment by sandervrijders** [comment]
Not reproducible
