### ISSUE TITLE
Kernel Oops when allocating - deallocating a lot of flows

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#435]
<a href="https://github.com/dstaesse"><img src="https://avatars.githubusercontent.com/u/3341175?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dstaesse](https://github.com/dstaesse)**
_Thursday Jan 22, 2015 at 18:11 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/432_

----

dmesg on client

[ 1120.145930] BUG: unable to handle kernel NULL pointer dereference at 0000000000000008
[ 1120.146080] IP: [<ffffffff812cfbb0>] sk_stream_wait_memory+0x7d/0x212
[ 1120.146185] PGD 0 
[ 1120.146276] Oops: 0002 [#4] SMP 
[ 1120.146413] Modules linked in: normal_ipcp shim_tcp_udp rina_personality_default nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop iTCO_wdt iTCO_vendor_support lpc_ich mfd_core ehci_pci i2c_i801 coretemp i7core_edac acpi_cpufreq edac_core ioatdma kvm_intel processor psmouse snd_pcm snd_timer snd soundcore serio_raw pcspkr thermal_sys evdev joydev kvm microcode button tpm_tis tpm ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic ata_generic usbhid hid crc32c_intel ata_piix libata scsi_mod uhci_hcd ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
[ 1120.150056] CPU: 1 PID: 115 Comm: kworker/u52:0 Not tainted 3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1120.150117] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
[ 1120.150178] Workqueue: rmt-egress-wq-ffff88033 rwq_worker
[ 1120.150290] task: ffff8801b813b750 ti: ffff8800ba0c8000 task.ti: ffff8800ba0c8000
[ 1120.150376] RIP: 0010:[<ffffffff812cfbb0>]  [<ffffffff812cfbb0>] sk_stream_wait_memory+0x7d/0x212
[ 1120.150510] RSP: 0018:ffff8800ba0cbaa8  EFLAGS: 00010246
[ 1120.150578] RAX: 0000000000000000 RBX: 7fffffffffffffff RCX: 0000000000000000
[ 1120.150651] RDX: 000000000000a310 RSI: 00000000fffffe01 RDI: ffffffff812c770c
[ 1120.150723] RBP: 0000000000000000 R08: ffff8800ba0c8000 R09: 0000000000001268
[ 1120.150795] R10: 0000000000001268 R11: ffff8801bfc32e80 R12: ffff8800ba0cbb70
[ 1120.150866] R13: 7fffffffffffffff R14: ffff8801b813b750 R15: ffff8801b8214100
[ 1120.150939] FS:  0000000000000000(0000) GS:ffff8801bfc20000(0000) knlGS:0000000000000000
[ 1120.151026] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 1120.151095] CR2: 0000000000000008 CR3: 0000000001610000 CR4: 00000000000007e0
[ 1120.151166] Stack:
[ 1120.151228]  0000000000000000 0000000000000000 ffff8801b813b750 ffffffff81066b3b
[ 1120.151486]  ffff8800ba0cbac8 ffff8800ba0cbac8 ffff8800375eec00 ffff8801b8214100
[ 1120.151745]  ffff8800375eec00 0000000000000000 00000000000004e1 00000000000005a8
[ 1120.152003] Call Trace:
[ 1120.152071]  [<ffffffff81066b3b>] ? bit_waitqueue+0x82/0x82
[ 1120.152143]  [<ffffffff8130cd2d>] ? tcp_sendmsg+0x6ba/0x820
[ 1120.152214]  [<ffffffff812c48dd>] ? sock_sendmsg+0x49/0x64
[ 1120.152286]  [<ffffffff813a1414>] ? _raw_write_lock_irqsave+0x9/0xe
[ 1120.152360]  [<ffffffff8110be90>] ? create_object+0x282/0x292
[ 1120.152430]  [<ffffffff812c4927>] ? kernel_sendmsg+0x2f/0x3b
[ 1120.152503]  [<ffffffffa03b4638>] ? send_msg+0x48/0x4d [shim_tcp_udp]
[ 1120.152576]  [<ffffffffa03b478c>] ? tcp_udp_sdu_write+0x14f/0x1af [shim_tcp_udp]
[ 1120.152668]  [<ffffffffa03e416e>] ? kfa_flow_sdu_write+0x1e0/0x254 [rina_personality_default]
[ 1120.152760]  [<ffffffff813898f6>] ? rkzalloc+0x23/0x43
[ 1120.152833]  [<ffffffffa03e20c4>] ? send_worker+0x12c/0x197 [rina_personality_default]
[ 1120.152921]  [<ffffffff81389de8>] ? rwq_worker+0x1f/0x3a
[ 1120.152993]  [<ffffffff8104d5c8>] ? process_one_work+0x191/0x293
[ 1120.153064]  [<ffffffff8104d810>] ? worker_thread+0x121/0x1e7
[ 1120.153134]  [<ffffffff8104d6ef>] ? process_scheduled_works+0x25/0x25
[ 1120.153207]  [<ffffffff810521e6>] ? kthread+0x99/0xa1
[ 1120.153277]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
[ 1120.153348]  [<ffffffff813a65bc>] ? ret_from_fork+0x7c/0xb0
[ 1120.153418]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
[ 1120.153487] Code: fd ff ff 84 c0 74 14 e8 76 71 f0 ff b9 32 00 00 00 31 d2 f7 f1 8d 6a 02 48 89 eb 65 4c 8b 34 25 80 b9 00 00 49 8b 87 30 02 00 00 <f0> 80 48 08 01 49 8b bf e0 00 00 00 48 8d 74 24 08 ba 01 00 00 
[ 1120.156421] RIP  [<ffffffff812cfbb0>] sk_stream_wait_memory+0x7d/0x212
[ 1120.156536]  RSP <ffff8800ba0cbaa8>
[ 1120.156600] CR2: 0000000000000008
[ 1120.156665] ---[ end trace 8a057c85ec3000ce ]---
[ 1120.156788] BUG: unable to handle kernel paging request at ffffffffffffffd8
[ 1120.156951] IP: [<ffffffff81052617>] kthread_data+0x7/0xc
[ 1120.157064] PGD 1611067 PUD 1613067 PMD 0 
[ 1120.157260] Oops: 0000 [#5] SMP 
[ 1120.157410] Modules linked in: normal_ipcp shim_tcp_udp rina_personality_default nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop iTCO_wdt iTCO_vendor_support lpc_ich mfd_core ehci_pci i2c_i801 coretemp i7core_edac acpi_cpufreq edac_core ioatdma kvm_intel processor psmouse snd_pcm snd_timer snd soundcore serio_raw pcspkr thermal_sys evdev joydev kvm microcode button tpm_tis tpm ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common hid_generic ata_generic usbhid hid crc32c_intel ata_piix libata scsi_mod uhci_hcd ehci_hcd usbcore usb_common igb i2c_algo_bit i2c_core dca ptp pps_core
[ 1120.161187] CPU: 1 PID: 115 Comm: kworker/u52:0 Tainted: G      D       3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1120.161277] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
[ 1120.161358] task: ffff8801b813b750 ti: ffff8800ba0c8000 task.ti: ffff8800ba0c8000
[ 1120.161444] RIP: 0010:[<ffffffff81052617>]  [<ffffffff81052617>] kthread_data+0x7/0xc
[ 1120.161575] RSP: 0018:ffff8800ba0cb760  EFLAGS: 00010002
[ 1120.161643] RAX: 0000000000000000 RBX: ffff8801bfc32e80 RCX: ffff8801bfc32ef0
[ 1120.161715] RDX: 0000000000000000 RSI: 0000000000000001 RDI: ffff8801b813b750
[ 1120.161786] RBP: 0000000000000001 R08: ffffffff81869700 R09: 000000000000b8d7
[ 1120.161858] R10: dead000000200200 R11: 000000000000bc67 R12: 0000000000000001
[ 1120.166975] R13: ffff8801b813bba8 R14: ffff8801b813baa0 R15: ffff8801b9235090
[ 1120.167048] FS:  0000000000000000(0000) GS:ffff8801bfc20000(0000) knlGS:0000000000000000
[ 1120.167135] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 1120.167204] CR2: 0000000000000028 CR3: 0000000001610000 CR4: 00000000000007e0
[ 1120.167275] Stack:
[ 1120.167337]  ffffffff8104de1c ffff8801b813b750 ffff8801bfc32e80 ffff8801b813b750
[ 1120.167596]  ffffffff8139efa9 ffff8801b813b750 ffff8801b813b750 0000000000012e80
[ 1120.167855]  0000000000012e80 ffff8801b813b750 ffff8800ba0cbfd8 ffff8801b813b750
[ 1120.168114] Call Trace:
[ 1120.168180]  [<ffffffff8104de1c>] ? wq_worker_sleeping+0xa/0x80
[ 1120.168251]  [<ffffffff8139efa9>] ? __schedule+0x131/0x4f4
[ 1120.168323]  [<ffffffff8103b804>] ? do_exit+0x8f0/0x907
[ 1120.168393]  [<ffffffff813a2417>] ? oops_end+0x9c/0xa1
[ 1120.168463]  [<ffffffff8139a9e4>] ? no_context+0x289/0x2b4
[ 1120.168535]  [<ffffffff8108dc46>] ? is_module_text_address+0x5/0xc
[ 1120.168607]  [<ffffffff810502cd>] ? __kernel_text_address+0x1c/0x39
[ 1120.168679]  [<ffffffff813a4467>] ? __do_page_fault+0x34d/0x3e0
[ 1120.168751]  [<ffffffff81003f4d>] ? dump_trace+0x271/0x280
[ 1120.168822]  [<ffffffff81062f1a>] ? pick_next_task_fair+0x16e/0x32f
[ 1120.168893]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
[ 1120.168964]  [<ffffffff810594ca>] ? mmdrop+0xd/0x1c
[ 1120.169033]  [<ffffffff81059f8a>] ? finish_task_switch+0x7f/0xbf
[ 1120.169104]  [<ffffffff813a1aa2>] ? page_fault+0x22/0x30
[ 1120.169176]  [<ffffffff812c770c>] ? lock_sock_nested+0x26/0x4a
[ 1120.169246]  [<ffffffff812cfbb0>] ? sk_stream_wait_memory+0x7d/0x212
[ 1120.169318]  [<ffffffff812cfc85>] ? sk_stream_wait_memory+0x152/0x212
[ 1120.169390]  [<ffffffff81066b3b>] ? bit_waitqueue+0x82/0x82
[ 1120.169461]  [<ffffffff8130cd2d>] ? tcp_sendmsg+0x6ba/0x820
[ 1120.169531]  [<ffffffff812c48dd>] ? sock_sendmsg+0x49/0x64
[ 1120.169602]  [<ffffffff813a1414>] ? _raw_write_lock_irqsave+0x9/0xe
[ 1120.169674]  [<ffffffff8110be90>] ? create_object+0x282/0x292
[ 1120.169744]  [<ffffffff812c4927>] ? kernel_sendmsg+0x2f/0x3b
[ 1120.169816]  [<ffffffffa03b4638>] ? send_msg+0x48/0x4d [shim_tcp_udp]
[ 1120.169889]  [<ffffffffa03b478c>] ? tcp_udp_sdu_write+0x14f/0x1af [shim_tcp_udp]
[ 1120.169980]  [<ffffffffa03e416e>] ? kfa_flow_sdu_write+0x1e0/0x254 [rina_personality_default]
[ 1120.170071]  [<ffffffff813898f6>] ? rkzalloc+0x23/0x43
[ 1120.170144]  [<ffffffffa03e20c4>] ? send_worker+0x12c/0x197 [rina_personality_default]
[ 1120.170233]  [<ffffffff81389de8>] ? rwq_worker+0x1f/0x3a
[ 1120.170302]  [<ffffffff8104d5c8>] ? process_one_work+0x191/0x293
[ 1120.170373]  [<ffffffff8104d810>] ? worker_thread+0x121/0x1e7
[ 1120.170444]  [<ffffffff8104d6ef>] ? process_scheduled_works+0x25/0x25
[ 1120.170516]  [<ffffffff810521e6>] ? kthread+0x99/0xa1
[ 1120.170586]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
[ 1120.170657]  [<ffffffff813a65bc>] ? ret_from_fork+0x7c/0xb0
[ 1120.170728]  [<ffffffff8105214d>] ? __kthread_parkme+0x59/0x59
[ 1120.170797] Code: c4 88 00 00 00 5b 5d c3 65 48 8b 04 25 80 b9 00 00 48 8b 80 00 04 00 00 48 8b 40 c8 48 c1 e8 02 83 e0 01 c3 48 8b 87 00 04 00 00 <48> 8b 40 d8 c3 48 83 ec 18 48 8b b7 00 04 00 00 ba 08 00 00 00 
[ 1120.173730] RIP  [<ffffffff81052617>] kthread_data+0x7/0xc
[ 1120.173842]  RSP <ffff8800ba0cb760>
[ 1120.173907] CR2: ffffffffffffffd8
[ 1120.173972] ---[ end trace 8a057c85ec3000cf ]---
[ 1120.174039] Fixing recursive fault but reboot is needed!

**Comment by kewinrausch** [comment]
<a href="https://github.com/dstaesse"><img src="https://avatars.githubusercontent.com/u/3341175?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dstaesse](https://github.com/dstaesse)**
_Thursday Jan 22, 2015 at 18:12 GMT_

----

dmesg on server: (after a while when it detects the hanging process)

[ 1201.328930] INFO: task ipcm:3835 blocked for more than 120 seconds.
[ 1201.328992]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.329050] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.329109] ipcm            D ffff88033fc52e80     0  3835   3834 0x00000000
[ 1201.329114]  ffff88033fa890d0 0000000000000086 ffff8801b929e990 ffffffff813a1414
[ 1201.329118]  0000000000012e80 0000000000012e80 ffff88033fa890d0 ffff8803392bffd8
[ 1201.329122]  ffff8803378cb8e8 ffffffffa03920e0 ffffffffa03920e4 ffff88033fa890d0
[ 1201.329126] Call Trace:
[ 1201.329136]  [<ffffffff813a1414>] ? _raw_write_lock_irqsave+0x9/0xe
[ 1201.329141]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.329144]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.329148]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.329154]  [<ffffffffa038e4c3>] ? tcp_udp_flow_deallocate+0x51/0xd4 [shim_tcp_udp]
[ 1201.329161]  [<ffffffffa0376a40>] ? notify_ipcp_deallocate_flow_request+0x90/0xf9 [rina_personality_default]
[ 1201.329167]  [<ffffffffa03769b0>] ? notify_ipcp_update_dif_config_request+0xf8/0xf8 [rina_personality_default]
[ 1201.329173]  [<ffffffffa03769b0>] ? notify_ipcp_update_dif_config_request+0xf8/0xf8 [rina_personality_default]
[ 1201.329179]  [<ffffffff8138de36>] ? dispatcher+0xb9/0xe1
[ 1201.329187]  [<ffffffff812fb505>] ? genl_family_rcv_msg+0x238/0x2a5
[ 1201.329194]  [<ffffffff8110be90>] ? create_object+0x282/0x292
[ 1201.329198]  [<ffffffff812fb5aa>] ? genl_rcv_msg+0x38/0x5b
[ 1201.329205]  [<ffffffff812ca9e0>] ? __kmalloc_reserve.isra.43+0x2a/0x6d
[ 1201.329209]  [<ffffffff812fb572>] ? genl_family_rcv_msg+0x2a5/0x2a5
[ 1201.329213]  [<ffffffff812fa400>] ? netlink_rcv_skb+0x36/0x7c
[ 1201.329217]  [<ffffffff812fa5ce>] ? genl_rcv+0x1f/0x2c
[ 1201.329220]  [<ffffffff812f9eae>] ? netlink_unicast+0xff/0x17f
[ 1201.329224]  [<ffffffff812fa22d>] ? netlink_sendmsg+0x2ff/0x32d
[ 1201.329229]  [<ffffffff812c48dd>] ? sock_sendmsg+0x49/0x64
[ 1201.329234]  [<ffffffff81086395>] ? get_futex_key+0x78/0x210
[ 1201.329237]  [<ffffffff812c527d>] ? move_addr_to_kernel+0x2e/0x53
[ 1201.329241]  [<ffffffff812ce5de>] ? verify_iovec+0x4c/0x9a
[ 1201.329244]  [<ffffffff812c51c5>] ? ___sys_sendmsg+0x1e7/0x271
[ 1201.329248]  [<ffffffff81086618>] ? futex_wake+0xeb/0x103
[ 1201.329252]  [<ffffffff81087bf0>] ? do_futex+0xce/0x7c4
[ 1201.329256]  [<ffffffff8105ffb5>] ? __dequeue_entity+0x19/0x2d
[ 1201.329259]  [<ffffffff8105ffdd>] ? set_next_entity+0x14/0x37
[ 1201.329263]  [<ffffffff81062ee9>] ? pick_next_task_fair+0x13d/0x32f
[ 1201.329267]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
[ 1201.329271]  [<ffffffff812c5551>] ? __sys_sendmsg+0x39/0x57
[ 1201.329275]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.329292] INFO: task ipcp:5073 blocked for more than 120 seconds.
[ 1201.329348]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.329405] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.329463] ipcp            D ffff88033fc32e80     0  5073   3835 0x00000000
[ 1201.329467]  ffff8801b6cb2690 0000000000000082 ffff8801b929f1d0 ffff88033fc32ef0
[ 1201.329470]  0000000000012e80 0000000000012e80 ffff8801b6cb2690 ffff8800b951ffd8
[ 1201.329474]  ffff8803385f9410 7fffffffffffffff 7fffffffffffffff 0000000000000002
[ 1201.329477] Call Trace:
[ 1201.329481]  [<ffffffff8139eb08>] ? put_cred+0x11/0x11
[ 1201.329484]  [<ffffffff8139eb24>] ? schedule_timeout+0x1c/0xf7
[ 1201.329489]  [<ffffffff810594ca>] ? mmdrop+0xd/0x1c
[ 1201.329492]  [<ffffffff81059f8a>] ? finish_task_switch+0x7f/0xbf
[ 1201.329496]  [<ffffffff8139fac6>] ? __wait_for_common+0x120/0x158
[ 1201.329500]  [<ffffffff8105d32a>] ? try_to_wake_up+0x198/0x198
[ 1201.329506]  [<ffffffff8104ce32>] ? flush_workqueue+0x193/0x3c1
[ 1201.329509]  [<ffffffff81389cb2>] ? rwq_flush+0x1e/0x22
[ 1201.329512]  [<ffffffff81389cbf>] ? rwq_destroy+0x9/0x2c
[ 1201.329519]  [<ffffffffa03716a5>] ? dtp_destroy+0x62/0x8a [rina_personality_default]
[ 1201.329527]  [<ffffffffa03721b0>] ? efcp_destroy+0x88/0x10e [rina_personality_default]
[ 1201.329534]  [<ffffffffa03722b3>] ? efcp_connection_destroy+0x7d/0x9d [rina_personality_default]
[ 1201.329539]  [<ffffffffa0338a1e>] ? remove_all_cepid.isra.0+0x24/0x4a [normal_ipcp]
[ 1201.329543]  [<ffffffffa0338a92>] ? normal_deallocate+0x4e/0x78 [normal_ipcp]
[ 1201.329550]  [<ffffffffa037497d>] ? kfa_flow_destroy+0xe0/0x102 [rina_personality_default]
[ 1201.329557]  [<ffffffffa0374bef>] ? kfa_flow_deallocate+0xbe/0xfb [rina_personality_default]
[ 1201.329564]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.329567]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.329570] INFO: task ipcp:5074 blocked for more than 120 seconds.
[ 1201.329626]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.329683] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.329741] ipcp            D ffff88033fcb2e80     0  5074   3835 0x00000000
[ 1201.329745]  ffff8801b84280d0 0000000000000082 ffff8801b92ca1d0 0000000000000000
[ 1201.329748]  0000000000012e80 0000000000012e80 ffff8801b84280d0 ffff880036f13fd8
[ 1201.329752]  ffffffff810015d7 ffff880336ea0480 ffff880336ea0484 ffff8801b84280d0
[ 1201.329755] Call Trace:
[ 1201.329759]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
[ 1201.329762]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.329765]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.329769]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.329775]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.329779]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.329783]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.329786] INFO: task ipcp:5078 blocked for more than 120 seconds.
[ 1201.329842]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.329898] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.329956] ipcp            D ffff88033fcb2e80     0  5078   3835 0x00000000
[ 1201.329960]  ffff8801b7aa9350 0000000000000082 ffff8801b92ca1d0 0000000000000000
[ 1201.329964]  0000000000012e80 0000000000012e80 ffff8801b7aa9350 ffff8800ba94ffd8
[ 1201.329967]  ffffffff810015d7 ffff880336ea0480 ffff880336ea0484 ffff8801b7aa9350
[ 1201.329971] Call Trace:
[ 1201.329974]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
[ 1201.329978]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.329981]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.329984]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.329991]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.329995]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.329998]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.330001] INFO: task ipcp:5079 blocked for more than 120 seconds.
[ 1201.330057]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.330114] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.330200] ipcp            D ffff88033fcb2e80     0  5079   3835 0x00000000
[ 1201.330203]  ffff8801b74ceb90 0000000000000082 ffff8801b92ca1d0 0000000000000000
[ 1201.330207]  0000000000012e80 0000000000012e80 ffff8801b74ceb90 ffff8800baa0ffd8
[ 1201.330210]  ffffffff810015d7 ffff880336ea0480 ffff880336ea0484 ffff8801b74ceb90
[ 1201.330213] Call Trace:
[ 1201.330217]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
[ 1201.330220]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.330224]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.330227]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.330234]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.330238]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.330241]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.330244] INFO: task ipcp:5080 blocked for more than 120 seconds.
[ 1201.330314]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.330384] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.330469] ipcp            D ffff88033fcb2e80     0  5080   3835 0x00000000
[ 1201.330473]  ffff8801b840a050 0000000000000082 ffff8801b92ca1d0 0000000000000000
[ 1201.330477]  0000000000012e80 0000000000012e80 ffff8801b840a050 ffff880036823fd8
[ 1201.330480]  ffffffff810015d7 ffff880336ea0480 ffff880336ea0484 ffff8801b840a050
[ 1201.330484] Call Trace:
[ 1201.330487]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
[ 1201.330490]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.330493]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.330497]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.330503]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.330507]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.330510]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.330514] INFO: task ipcp:5081 blocked for more than 120 seconds.
[ 1201.330584]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.330654] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.330739] ipcp            D ffff8801bfcb2e80     0  5081   3835 0x00000000
[ 1201.330743]  ffff8803311ed2d0 0000000000000082 ffff8801b84108d0 0000000000000000
[ 1201.330746]  0000000000012e80 0000000000012e80 ffff8803311ed2d0 ffff880337bb7fd8
[ 1201.330750]  0000000000000000 ffff880336ea0480 ffff880336ea0484 ffff8803311ed2d0
[ 1201.330753] Call Trace:
[ 1201.330757]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.330760]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.330764]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.330770]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.330774]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.330777]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.330780] INFO: task ipcp:5082 blocked for more than 120 seconds.
[ 1201.330850]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.330921] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.331006] ipcp            D ffff88033fcb2e80     0  5082   3835 0x00000000
[ 1201.331010]  ffff8801b74ce350 0000000000000082 ffff8801b92ca1d0 0000000000000000
[ 1201.331013]  0000000000012e80 0000000000012e80 ffff8801b74ce350 ffff880036f37fd8
[ 1201.331017]  ffffffff810015d7 ffff880336ea0480 ffff880336ea0484 ffff8801b74ce350
[ 1201.331020] Call Trace:
[ 1201.331023]  [<ffffffff810015d7>] ? __switch_to+0x1b1/0x3e0
[ 1201.331027]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.331030]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.331033]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.331040]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.331044]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.331047]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.331050] INFO: task ipcp:5083 blocked for more than 120 seconds.
[ 1201.331120]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.331190] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.331276] ipcp            D ffff8801bfcb2e80     0  5083   3835 0x00000000
[ 1201.331279]  ffff880336b24690 0000000000000082 ffff8801b84108d0 0000000000000000
[ 1201.331283]  0000000000012e80 0000000000012e80 ffff880336b24690 ffff880337b0bfd8
[ 1201.331286]  0000000000000000 ffff880336ea0480 ffff880336ea0484 ffff880336b24690
[ 1201.331289] Call Trace:
[ 1201.331293]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.331296]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.331300]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.331306]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.331310]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.331313]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b
[ 1201.331316] INFO: task ipcp:5084 blocked for more than 120 seconds.
[ 1201.331386]       Tainted: G          I   3.15.0-irati-v0.9.13.6-kmemleak #9
[ 1201.331456] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.331542] ipcp            D ffff8801bfcb2e80     0  5084   3835 0x00000000
[ 1201.331545]  ffff880335712a90 0000000000000082 ffff8801b84108d0 0000000000000000
[ 1201.331549]  0000000000012e80 0000000000012e80 ffff880335712a90 ffff880330ec7fd8
[ 1201.331552]  0000000000000000 ffff880336ea0480 ffff880336ea0484 ffff880335712a90
[ 1201.331555] Call Trace:
[ 1201.331559]  [<ffffffff8139f5ec>] ? schedule_preempt_disabled+0x6/0x8
[ 1201.331563]  [<ffffffff813a0336>] ? __mutex_lock_slowpath+0x16a/0x1c6
[ 1201.331566]  [<ffffffff813a03a8>] ? mutex_lock+0x16/0x25
[ 1201.331573]  [<ffffffffa0374b96>] ? kfa_flow_deallocate+0x65/0xfb [rina_personality_default]
[ 1201.331576]  [<ffffffff81391838>] ? SyS_deallocate_port+0x4e/0x53
[ 1201.331579]  [<ffffffff813a6662>] ? system_call_fastpath+0x16/0x1b

**Comment by sandervrijders** [comment]
Still reproducible?

**Comment by vmaffione** [comment]
Not reproducible
