### ISSUE TITLE
Deadlock in shim-tcp-udp (kernel,sockets,tcp related code) (normal over shim-tcp-udp)

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#436]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Friday Jan 23, 2015 at 10:53 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/433_

----

[ 4953.732019] BUG: soft lockup - CPU#3 stuck for 22s! [kworker/u17:2:3454]
[ 4953.732019] Modules linked in: shim_tcp_udp nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc normal_ipcp shim_dummy rina_personality_default 8021q garp stp llc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbmouse usbhid hid floppy
[ 4953.732019] irq event stamp: 433822
[ 4953.732019] hardirqs last  enabled at (433821): [<c1661277>] _raw_spin_unlock_irq+0x27/0x40
[ 4953.732019] hardirqs last disabled at (433822): [<c1660915>] _raw_spin_lock_irq+0x15/0x80
[ 4953.732019] softirqs last  enabled at (433742): [<c15472f2>] release_sock+0x162/0x1c0
[ 4953.732019] softirqs last disabled at (433740): [<c15471be>] release_sock+0x2e/0x1c0
[ 4953.732019] CPU: 0 PID: 3454 Comm: kworker/u17:2 Not tainted 3.15.0 #493
[ 4953.732019] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[ 4953.732019] Workqueue: shim-tcp-udp-wwq tcp_udp_write_worker [shim_tcp_udp]
[ 4953.732019] task: f4d3c410 ti: ed7ee000 task.ti: ed7ee000
[ 4953.732019] EIP: 0060:[<c131b3d4>] EFLAGS: 00000202 CPU: 0
[ 4953.732019] EIP is at delay_tsc+0x44/0x70
[ 4953.732019] EAX: 2b23cf18 EBX: 00000001 ECX: 00000000 EDX: 00000aec
[ 4953.732019] ESI: 2b23cef4 EDI: 00000000 EBP: ed7efc6c ESP: ed7efc60
[ 4953.732019]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[ 4953.732019] CR0: 8005003b CR2: b7737000 CR3: 2c292000 CR4: 000006d0
[ 4953.732019] Stack:
[ 4953.732019]  ec39dd58 2f6c9cb0 00000000 ed7efc74 c131b30e ed7efc8c c1094fde 8ee928c8
[ 4953.732019]  ec39dd68 ec39dd58 00000000 ed7efcac c1660b84 00000000 00000001 00000000
[ 4953.732019]  c1545a28 ec39dd00 ec39dd58 ed7efcd0 c1545a28 ed7efcc0 c1661312 f0bb0178
[ 4953.732019] Call Trace:
[ 4953.732019]  [<c131b30e>] __delay+0xe/0x10
[ 4953.732019]  [<c1094fde>] do_raw_spin_lock+0x6e/0x150
[ 4953.732019]  [<c1660b84>] _raw_spin_lock_bh+0x64/0x80
[ 4953.732019]  [<c1545a28>] ? lock_sock_nested+0x38/0xb0
[ 4953.732019]  [<c1545a28>] lock_sock_nested+0x38/0xb0
[ 4953.732019]  [<c1661312>] ? _raw_spin_unlock+0x22/0x30
[ 4953.732019]  [<c159c24e>] tcp_sendmsg+0x1e/0xbf0
[ 4953.732019]  [<c16528c4>] ? alloc_debug_processing+0xb9/0xfb
[ 4953.732019]  [<c116e8ee>] ? create_object+0x2e/0x280
[ 4953.732019]  [<c15c5c50>] ? inet_recvmsg+0xe0/0xe0
[ 4953.732019]  [<c15c5cc4>] ? inet_sendmsg+0x74/0xe0
[ 4953.732019]  [<c15c5d02>] inet_sendmsg+0xb2/0xe0
[ 4953.732019]  [<c15c5c50>] ? inet_recvmsg+0xe0/0xe0
[ 4953.732019]  [<c1542315>] sock_sendmsg+0x85/0xc0
[ 4953.732019]  [<c1542389>] kernel_sendmsg+0x39/0x50
[ 4953.732019]  [<f8e735aa>] send_msg+0x4a/0x70 [shim_tcp_udp]
[ 4953.732019]  [<f8e737aa>] tcp_udp_write_worker+0x1da/0x2b4 [shim_tcp_udp]
[ 4953.732019]  [<c105ad9c>] process_one_work+0x19c/0x490
[ 4953.732019]  [<c105ad27>] ? process_one_work+0x127/0x490
[ 4953.732019]  [<c105b25e>] ? worker_thread+0x19e/0x320
[ 4953.732019]  [<c105b1b9>] worker_thread+0xf9/0x320
[ 4953.732019]  [<c105b0c0>] ? process_scheduled_works+0x30/0x30
[ 4953.732019]  [<c10617db>] kthread+0x9b/0xb0
[ 4953.732019]  [<c1661277>] ? _raw_spin_unlock_irq+0x27/0x40
[ 4953.732019]  [<c1060000>] ? SYSC_clock_adjtime+0x60/0xb0
[ 4953.732019]  [<c16691e1>] ret_from_kernel_thread+0x21/0x30
[ 4953.732019]  [<c1061740>] ? kthread_create_on_node+0x170/0x170
[ 4953.732019] Code: a6 c1 8d 76 00 0f ae e8 0f 31 89 c6 eb 15 90 f3 90 64 ff 05 30 37 a6 c1 64 8b 0d 10 30 a6 c1 39 cf 75 1c 8d 76 00 0f ae e8 0f 31 <89> c2 29 f2 64 ff 0d 30 37 a6 c1 39 da 72 d5 5b 5e 5f 5d c3 29
[ 4953.732019] Kernel panic - not syncing: softlockup: hung tasks
[ 4953.732019] CPU: 0 PID: 3454 Comm: kworker/u17:2 Not tainted 3.15.0 #493
[ 4953.732019] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[ 4953.732019] Workqueue: shim-tcp-udp-wwq tcp_udp_write_worker [shim_tcp_udp]
[ 4953.732019]  00000000 00000000 ed7efb1c c1654361 f4d3c410 ed7efb3c c1650016 c182e040
[ 4953.732019]  c1bc1880 c131b3a9 f4d3c410 ee6b2800 00000000 ed7efb6c c10e5841 c1842c6a
[ 4953.732019]  00000000 00000016 f4d3c7d8 00000d7e ed7efc24 000011ef f663e340 ed7efbe8
[ 4953.732019] Call Trace:
[ 4953.732019]  [<c1654361>] dump_stack+0x48/0x60
[ 4953.732019]  [<c1650016>] panic+0x87/0x195
[ 4953.732019]  [<c131b3a9>] ? delay_tsc+0x19/0x70
[ 4953.732019]  [<c10e5841>] watchdog_timer_fn+0x151/0x160
[ 4953.732019]  [<c106425c>] __run_hrtimer+0x6c/0x1c0
[ 4953.732019]  [<c10e56f0>] ? watchdog_enable_all_cpus.part.3+0x40/0x40
[ 4953.732019]  [<c1064dbf>] hrtimer_interrupt+0xff/0x2b0
[ 4953.732019]  [<c10b7969>] ? tick_program_event+0x29/0x30
[ 4953.732019]  [<c102d11f>] local_apic_timer_interrupt+0x2f/0x60
[ 4953.732019]  [<c1669943>] smp_apic_timer_interrupt+0x33/0x50
[ 4953.732019]  [<c1661ac2>] apic_timer_interrupt+0x32/0x38
[ 4953.732019]  [<c131b3d4>] ? delay_tsc+0x44/0x70
[ 4953.732019]  [<c131b30e>] __delay+0xe/0x10
[ 4953.732019]  [<c1094fde>] do_raw_spin_lock+0x6e/0x150
[ 4953.732019]  [<c1660b84>] _raw_spin_lock_bh+0x64/0x80
[ 4953.732019]  [<c1545a28>] ? lock_sock_nested+0x38/0xb0
[ 4953.732019]  [<c1545a28>] lock_sock_nested+0x38/0xb0
[ 4953.732019]  [<c1661312>] ? _raw_spin_unlock+0x22/0x30
[ 4953.732019]  [<c159c24e>] tcp_sendmsg+0x1e/0xbf0
[ 4953.732019]  [<c16528c4>] ? alloc_debug_processing+0xb9/0xfb
[ 4953.732019]  [<c116e8ee>] ? create_object+0x2e/0x280
[ 4953.732019]  [<c15c5c50>] ? inet_recvmsg+0xe0/0xe0
[ 4953.732019]  [<c15c5cc4>] ? inet_sendmsg+0x74/0xe0
[ 4953.732019]  [<c15c5d02>] inet_sendmsg+0xb2/0xe0
[ 4953.732019]  [<c15c5c50>] ? inet_recvmsg+0xe0/0xe0
[ 4953.732019]  [<c1542315>] sock_sendmsg+0x85/0xc0
[ 4953.732019]  [<c1542389>] kernel_sendmsg+0x39/0x50
[ 4953.732019]  [<f8e735aa>] send_msg+0x4a/0x70 [shim_tcp_udp]
[ 4953.732019]  [<f8e737aa>] tcp_udp_write_worker+0x1da/0x2b4 [shim_tcp_udp]
[ 4953.732019]  [<c105ad9c>] process_one_work+0x19c/0x490
[ 4953.732019]  [<c105ad27>] ? process_one_work+0x127/0x490
[ 4953.732019]  [<c105b25e>] ? worker_thread+0x19e/0x320
[ 4953.732019]  [<c105b1b9>] worker_thread+0xf9/0x320
[ 4953.732019]  [<c105b0c0>] ? process_scheduled_works+0x30/0x30
[ 4953.732019]  [<c10617db>] kthread+0x9b/0xb0
[ 4953.732019]  [<c1661277>] ? _raw_spin_unlock_irq+0x27/0x40
[ 4953.732019]  [<c1060000>] ? SYSC_clock_adjtime+0x60/0xb0
[ 4953.732019]  [<c16691e1>] ret_from_kernel_thread+0x21/0x30
[ 4953.732019]  [<c1061740>] ? kthread_create_on_node+0x170/0x170
[ 4953.732019] Kernel Offset: 0x0 from 0xc1000000 (relocation range: 0xc0000000-0xf7ffdfff)
[ 4953.732019] ---[ end Kernel panic - not syncing: softlockup: hung tasks

**Comment by sandervrijders** [comment]
Still there?

**Comment by edugrasa** [comment]
Fixed by #887
