### ISSUE TITLE
Normal over eth, notified about a deallocation of a flow after latest Leo's changes

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#439]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [edugrasa](https://github.com/edugrasa)**
_Friday Jan 23, 2015 at 14:58 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/436_

----

[  394.210780] BUG: spinlock bad magic on CPU#5, ipcp/3796
[  394.214542] BUG: unable to handle kernel paging request at 47464748
[  394.214542] IP: [<c133d780>] spin_dump+0x47/0x7d
[  394.214542] *pdpt = 000000001f0ee001 *pde = 0000000000000000 
[  394.214542] Oops: 0000 [#4] SMP 
[  394.214542] Modules linked in: normal_ipcp shim_tcp_udp shim_eth_vlan rinarp arp826 shim_dummy rina_personality_default 8021q garp stp llc nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc loop snd_pcm snd_timer snd aesni_intel xts aes_i586 i2c_piix4 lrw soundcore i2c_core gf128mul joydev evdev psmouse serio_raw processor ablk_helper pcspkr cryptd parport_pc parport microcode thermal_sys button ext4 crc16 jbd2 mbcache sg sd_mod crc_t10dif crct10dif_common hid_generic usbhid hid ata_generic crc32c_intel e1000 floppy uhci_hcd ehci_hcd ata_piix usbcore libata usb_common scsi_mod
[  394.214542] CPU: 2 PID: 3796 Comm: ipcp Not tainted 3.15.0 #16
[  394.214542] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[  394.214542] task: ef98d450 ti: df0c2000 task.ti: df0c2000
[  394.214542] EIP: 0060:[<c133d780>] EFLAGS: 00010006 CPU: 2
[  394.214542] EIP is at spin_dump+0x47/0x7d
[  394.214542] EAX: 0000002b EBX: 47464544 ECX: f713a2b4 EDX: 43424140
[  394.214542] ESI: de54c7c0 EDI: 00000002 EBP: df0c3ea4 ESP: df0c3e9c
[  394.214542]  DS: 007b ES: 007b FS: 00d8 GS: 0033 SS: 0068
[  394.214542] CR0: 80050033 CR2: 47464748 CR3: 3653a000 CR4: 000006f0
[  394.214542] Stack:
[  394.214542]  de54c7c0 00000282 df0c3eb4 c133d7d3 c148c5b8 de54c7c0 df0c3ecc c1062841
[  394.214542]  00000001 de54c7c0 00000282 00000002 df0c3eec c1342b96 00000000 00000001
[  394.214542]  00000000 c105c322 de54c7c0 ea9766c8 df0c3f04 c105c322 00000000 00000001
[  394.214542] Call Trace:
[  394.214542]  [<c133d7d3>] spin_bug+0x1d/0x21
[  394.214542]  [<c1062841>] do_raw_spin_lock+0x1c/0xed
[  394.214542]  [<c1342b96>] _raw_spin_lock_irqsave+0x31/0x3a
[  394.214542]  [<c105c322>] ? __wake_up+0x15/0x3b
[  394.214542]  [<c105c322>] __wake_up+0x15/0x3b
[  394.214542]  [<f856d744>] kfa_flow_deallocate+0xf3/0xff [rina_personality_default]
[  394.214542]  [<f856a938>] efcp_destroy+0x34/0xe7 [rina_personality_default]
[  394.214542]  [<f856aa55>] efcp_connection_destroy+0x6a/0x8a [rina_personality_default]
[  394.214542]  [<f8608c6b>] remove_all_cepid.isra.0+0x20/0x3f [normal_ipcp]
[  394.214542]  [<f8608ccc>] normal_deallocate+0x42/0x6a [normal_ipcp]
[  394.214542]  [<f856fe03>] kipcm_deallocate_port+0x49/0x6a [rina_personality_default]
[  394.214542]  [<f856ff26>] default_deallocate_port+0x23/0x2d [rina_personality_default]
[  394.214542]  [<f856ff03>] ? default_sdu_write+0x2f/0x2f [rina_personality_default]
[  394.214542]  [<c1338c77>] SyS_deallocate_port+0x46/0x4b
[  394.214542]  [<c1347b8c>] sysenter_do_call+0x12/0x2d
[  394.214542] Code: 5e c1 ff b0 04 02 00 00 05 e4 02 00 00 64 8b 0d 10 50 5e c1 50 51 52 68 31 c5 48 c1 e8 2e 01 00 00 83 c4 14 85 db 8b 56 08 74 0e <8b> 83 04 02 00 00 81 c3 e4 02 00 00 eb 08 83 c8 ff bb e7 e0 4b
[  394.214542] EIP: [<c133d780>] spin_dump+0x47/0x7d SS:ESP 0068:df0c3e9c
[  394.214542] CR2: 0000000047464748
[  394.214542] ---[ end trace 9b8311a38d62af2d ]---
[  394.214542] BUG: sleeping function called from invalid context at kernel/locking/rwsem.c:20
[  394.214542] in_atomic(): 1, irqs_disabled(): 1, pid: 3796, name: ipcp
[  394.214542] INFO: lockdep is turned off.
[  394.214542] CPU: 2 PID: 3796 Comm: ipcp Tainted: G      D       3.15.0 #16
[  394.214542] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[  394.214542]  00000000 00000000 df0c3ce8 c133f0c1 ef98d450 df0c3cfc c104ed0b ef78d010
[  394.214542]  00000009 00000046 df0c3d08 c134243d ef98d450 df0c3d20 c103cca4 ffffffff
[  394.214542]  00000000 ef98d450 00000009 df0c3d68 c103250f 00000000 00000046 df0c3d4c
[  394.214542] Call Trace:
[  394.214542]  [<c133f0c1>] dump_stack+0x48/0x60
[  394.214542]  [<c104ed0b>] __might_sleep+0xd9/0xe1
[  394.214542]  [<c134243d>] down_read+0x17/0x40
[  394.214542]  [<c103cca4>] exit_signals+0x1a/0xff
[  394.214542]  [<c103250f>] do_exit+0xe4/0x837
[  394.214542]  [<c106bd4a>] ? kmsg_dump+0xd4/0xe2
[  394.214542]  [<c1344063>] oops_end+0x8e/0x96
[  394.214542]  [<c133cc07>] no_context+0x1a4/0x1ae
[  394.214542]  [<c133cd00>] __bad_area_nosemaphore+0xef/0xf9
[  394.214542]  [<c133cd17>] bad_area_nosemaphore+0xd/0x10
[  394.214542]  [<c1345e4d>] __do_page_fault+0x32c/0x3ab
[  394.214542]  [<c10ab71d>] ? irq_work_queue+0x72/0x7c
[  394.214542]  [<c106a935>] ? wake_up_klogd+0x2f/0x38
[  394.214542]  [<c106ac70>] ? console_unlock+0x332/0x33a
[  394.214542]  [<c1345ecc>] ? __do_page_fault+0x3ab/0x3ab
[  394.214542]  [<c1345ed7>] do_page_fault+0xb/0xd
[  394.214542]  [<c1343a4e>] error_code+0x5a/0x60
[  394.214542]  [<c13300d8>] ? dcbnl_ieee_fill+0x7b/0x304
[  394.214542]  [<c1345ecc>] ? __do_page_fault+0x3ab/0x3ab
[  394.214542]  [<c133d780>] ? spin_dump+0x47/0x7d
[  394.214542]  [<c133d7d3>] spin_bug+0x1d/0x21
[  394.214542]  [<c1062841>] do_raw_spin_lock+0x1c/0xed
[  394.214542]  [<c1342b96>] _raw_spin_lock_irqsave+0x31/0x3a
[  394.214542]  [<c105c322>] ? __wake_up+0x15/0x3b
[  394.214542]  [<c105c322>] __wake_up+0x15/0x3b
[  394.214542]  [<f856d744>] kfa_flow_deallocate+0xf3/0xff [rina_personality_default]
[  394.214542]  [<f856a938>] efcp_destroy+0x34/0xe7 [rina_personality_default]
[  394.214542]  [<f856aa55>] efcp_connection_destroy+0x6a/0x8a [rina_personality_default]
[  394.214542]  [<f8608c6b>] remove_all_cepid.isra.0+0x20/0x3f [normal_ipcp]
[  394.214542]  [<f8608ccc>] normal_deallocate+0x42/0x6a [normal_ipcp]
[  394.214542]  [<f856fe03>] kipcm_deallocate_port+0x49/0x6a [rina_personality_default]
[  394.214542]  [<f856ff26>] default_deallocate_port+0x23/0x2d [rina_personality_default]
[  394.214542]  [<f856ff03>] ? default_sdu_write+0x2f/0x2f [rina_personality_default]
[  394.214542]  [<c1338c77>] SyS_deallocate_port+0x46/0x4b
[  394.214542]  [<c1347b8c>] sysenter_do_call+0x12/0x2d
[  394.678732] note: ipcp[3796] exited with preempt_count 1

**Comment by sandervrijders** [comment]
Still reproducible?
