### ISSUE TITLE
Deadlock in shim-tcp-udp: tcp_udp_sdu_write vs tcp_udp_rcv_worker

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#440]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Friday Jan 23, 2015 at 18:49 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/437_

----

[  385.163904] 
[  385.164011] =================================
[  385.164011] [ INFO: inconsistent lock state ]
[  385.164011] 3.15.0 #498 Not tainted
[  385.164011] ---------------------------------
[  385.164011] inconsistent {SOFTIRQ-ON-W} -> {IN-SOFTIRQ-W} usage.
[  385.164011] kworker/u17:0/1452 [HC0[0]:SC1[1]:HE0:SE0] takes:
[  385.164011]  (snd_wq_lock){+.?...}, at: [<f80c046b>] tcp_udp_sdu_write+0x4b/0xb0 [shim_tcp_udp]
[  385.164011] {SOFTIRQ-ON-W} state was registered at:
[  385.164011]   [<c108efab>] __lock_acquire+0x46b/0x1a20
[  385.164011]   [<c1090aee>] lock_acquire+0x7e/0x100
[  385.164011]   [<c165fe82>] _raw_spin_lock+0x42/0x70
[  385.164011]   [<f80c2f28>] tcp_udp_write_worker+0x18/0x298 [shim_tcp_udp]
[  385.164011]   [<c105ad9c>] process_one_work+0x19c/0x490
[  385.164011]   [<c105b1b9>] worker_thread+0xf9/0x320
[  385.164011]   [<c10617db>] kthread+0x9b/0xb0
[  385.164011]   [<c1668821>] ret_from_kernel_thread+0x21/0x30
[  385.164011] irq event stamp: 2673675
[  385.164011] hardirqs last  enabled at (2673674): [<c1660136>] _raw_write_unlock_irqrestore+0x36/0x60
[  385.164011] hardirqs last disabled at (2673675): [<c165ffde>] _raw_spin_lock_irqsave+0x1e/0x90
[  385.164011] softirqs last  enabled at (2673546): [<c1545a39>] lock_sock_nested+0x49/0xb0
[  385.232019] softirqs last disabled at (2673547): [<c1004049>] do_softirq_own_stack+0x29/0x40
[  385.232019] 
[  385.232019] other info that might help us debug this:
[  385.232019]  Possible unsafe locking scenario:
[  385.232019] 
[  385.232019]        CPU0
[  385.232019]        ----
[  385.232019]   lock(snd_wq_lock);
[  385.232019]   <Interrupt>
[  385.232019]     lock(snd_wq_lock);
[  385.232019] 
[  385.232019]  *** DEADLOCK ***
[  385.232019] 
[  385.232019] 3 locks held by kworker/u17:0/1452:
[  385.232019]  #3:  (SHIM_NAME_RWQ){.+.+.+}, at: [<c105ad27>] process_one_work+0x127/0x490
[  385.232019]  #4:  ((&rcv_work)){+.+.+.}, at: [<c105ad27>] process_one_work+0x127/0x490
[  385.232019]  #5:  (sk_lock-AF_INET){+.+.+.}, at: [<c159d70c>] tcp_recvmsg+0x6c/0xa80
[  385.232019] 
[  385.232019] stack backtrace:
[  385.232019] CPU: 0 PID: 1452 Comm: kworker/u17:0 Not tainted 3.15.0 #498
[  385.232019] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[  385.232019] Workqueue: shim-tcp-udp-rwq tcp_udp_rcv_worker [shim_tcp_udp]
[  385.232019]  00000000 00000000 f6017dd4 c1654a51 de65ad60 f6017e10 c16514b3 c183d522
[  385.232019]  c183d887 000005ac 00000000 00000000 00000001 00000001 00000000 00000000
[  385.232019]  c183d887 00000004 de65b360 00000000 f6017e48 c108d44d 00000004 f6017e28
[  385.232019] Call Trace:
[  385.232019]  [<c1654a51>] dump_stack+0x48/0x60
[  385.232019]  [<c16514b3>] print_usage_bug+0x1c8/0x1d2
[  385.232019]  [<c108d44d>] mark_lock+0x27d/0x2e0
[  385.232019]  [<c108c900>] ? check_usage_backwards+0x110/0x110
[  385.232019]  [<c108ef5c>] __lock_acquire+0x41c/0x1a20
[  385.232019]  [<c108d509>] ? mark_held_locks+0x59/0x80
[  385.232019]  [<c1660136>] ? _raw_write_unlock_irqrestore+0x36/0x60
[  385.232019]  [<c116ea65>] ? create_object+0x1a5/0x280
[  385.232019]  [<c1090aee>] lock_acquire+0x7e/0x100
[  385.232019]  [<f80c046b>] ? tcp_udp_sdu_write+0x4b/0xb0 [shim_tcp_udp]
[  385.232019]  [<c1660011>] _raw_spin_lock_irqsave+0x51/0x90
[  385.232019]  [<f80c046b>] ? tcp_udp_sdu_write+0x4b/0xb0 [shim_tcp_udp]
[  385.232019]  [<f80c046b>] tcp_udp_sdu_write+0x4b/0xb0 [shim_tcp_udp]
[  385.232019]  [<c164536c>] ? sdu_create_buffer_with_gfp+0x2c/0x50
[  385.232019]  [<f81a45c5>] n1_port_write+0x85/0x120 [rina_personality_default]
[  385.232019]  [<f81a5d9f>] send_worker+0xbf/0x150 [rina_personality_default]
[  385.232019]  [<c1046b7e>] tasklet_hi_action+0x9e/0xb0
[  385.232019]  [<c1046633>] __do_softirq+0xf3/0x2a0
[  385.232019]  [<c1545a39>] ? lock_sock_nested+0x49/0xb0
[  385.232019]  [<c1046540>] ? perf_trace_irq_handler_exit+0xd0/0xd0
[  385.232019]  [<c1004049>] do_softirq_own_stack+0x29/0x40
[  385.232019]  <IRQ>  [<c104689d>] do_softirq+0x5d/0x70
[  385.232019]  [<c1046958>] __local_bh_enable_ip+0xa8/0xb0
[  385.232019]  [<c1545a86>] lock_sock_nested+0x96/0xb0
[  385.232019]  [<c159d70c>] ? tcp_recvmsg+0x6c/0xa80
[  385.232019]  [<c159d70c>] tcp_recvmsg+0x6c/0xa80
[  385.232019]  [<c15c5b70>] ? inet_sendpage+0x100/0x100
[  385.232019]  [<c15c5beb>] ? inet_recvmsg+0x7b/0xe0
[  385.232019]  [<c15c5c34>] inet_recvmsg+0xc4/0xe0
[  385.232019]  [<c1542739>] sock_recvmsg+0x99/0xd0
[  385.232019]  [<c15428bf>] kernel_recvmsg+0x3f/0x50
[  385.232019]  [<f80c2042>] recv_msg+0x52/0x60 [shim_tcp_udp]
[  385.232019]  [<f80c2699>] tcp_process_msg+0x89/0x4f0 [shim_tcp_udp]
[  385.232019]  [<f80c2da6>] tcp_udp_rcv_worker+0x2a6/0x3b0 [shim_tcp_udp]
[  385.232019]  [<c105ad27>] ? process_one_work+0x127/0x490
[  385.232019]  [<c105ad9c>] process_one_work+0x19c/0x490
[  385.232019]  [<c105ad27>] ? process_one_work+0x127/0x490
[  385.232019]  [<c105b1b9>] worker_thread+0xf9/0x320
[  385.232019]  [<c105b0c0>] ? process_scheduled_works+0x30/0x30
[  385.232019]  [<c10617db>] kthread+0x9b/0xb0
[  385.232019]  [<c16608b7>] ? _raw_spin_unlock_irq+0x27/0x40
[  385.232019]  [<c1060000>] ? SYSC_clock_adjtime+0x60/0xb0
[  385.232019]  [<c1668821>] ret_from_kernel_thread+0x21/0x30
[  385.232019]  [<c1061740>] ? kthread_create_on_node+0x170/0x170

**Comment by edugrasa** [comment]
Fixed by #887
