### ISSUE TITLE
Write enable and disable in the kfa produce a bad update of the flow state

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#441]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Friday Jan 23, 2015 at 18:54 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/438_

----

Check the log. It is due to the enabler (triggered by a softirq) taking the lock first, when flow is still ALLOCATED, leaves it like that and releases the lock. It is taken by the disabler (triggered in process context) and puts the flow to DISABLED, then blocking the write.

[ 1424.479726] rina-dtp: Closed Window Queue
[ 1424.479731] rina-dtp: Default Flow Control
[ 1424.479735] rina-dt-utils: Pushing in the Closed Window Queue
[ 1424.479739] rina-rqueue: Entry ffff8801b84824a0 tail-pushed into queue ffff880338177280 (length = 50)
[ 1424.479744] rina-kfa: DISABLED write op

[ 1424.479749] rina-shim-eth-vlan: eth_vlan_rcv started, skb received
[ 1424.479755] rina-shim-eth-vlan: Flow exists, queueing or delivering or dropping
[ 1424.479759] rina-rmt: RMT sent directly to DTP
[ 1424.479764] rina-dtcp: dtcp_common_rcv_control called
[ 1424.479769] rina-dtcp: DTCP Received Contrl PDU 510 at 1422025698717
[ 1424.479772] rina-dtcp: SEQN: 510 N/Ack: 0 SndRWE: 559 SndLWE: 559 RcvRWE: 50 RcvLWE: 0 newRWE: 560 newLWE: 0 myRWE: 50 myLWE: 0 cwqLWE: 0
[ 1424.479776] rina-dtcp: dtcp_common_rcv_control sending to proper function...
[ 1424.479780] rina-rqueue: Entry ffff8801b8482700 head-popped from queue ffff880338177280 (length = 49)
[ 1424.479781] rina-rmt: Gonna send PDU to port-id: 1
[ 1424.479783] rina-serdes: Serialized version 1, with size 1
[ 1424.479784] rina-rmt: Gonna send SDU to port-id 1
[ 1424.479785] rina-shim-eth-vlan: Entered the sdu-write
[ 1424.479787] rina-shim-:qeth-vlan: Packet sent
[ 1424.479788] rina-rmt: RMT: sent and enabling port
[ 1424.479789] rina-dt-utils: CWQ has delivered until 560
[ 1424.479790] rina-kfa: ENABLED write op
[ 1424.479791] rina-kfa: IPCP notified CWQ enabled
[ 1424.479792] rina-rmt: process_dt_pdu internally finished
[ 1424.479793] rina-shim-eth-vlan: eth_vlan_recv_process_packet ends....
[ 1424.479794] rina-shim-eth-vlan: eth_vlan_rcv ends

[ 1424.479795] rina-kfa: IPCP notified CWQ exhausted
[ 1424.479796] rina-kfa: Finishing (write)

**Comment by kewinrausch** [comment]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lbergesio](https://github.com/lbergesio)**
_Friday Jan 23, 2015 at 21:20 GMT_

----

referenced commit fixes shim-tcp-udp with tcp and shim-eth-vlan with rtx control. It is not working with shim-eth-vlan and just flow control

**Comment by sandervrijders** [comment]
@miqueltarzan This is not fixed?

**Comment by miqueltarzan** [comment]
I think so.

**Comment by sandervrijders** [comment]
You think it is or it isn't? :)

**Comment by miqueltarzan** [comment]
I think it's fixed.
