### ISSUE TITLE
Sometimes, the IPC manager bangs during enrollment

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#442]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Friday Jan 23, 2015 at 19:36 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/439_

----

Not very often, the IPC manager of the system NOT triggering the enrollment bangs:

^[[Aroot@irati-vm-leo-2runipcm
3308(1422041623)#concurrency (DBG): Lockable created successfully
3308(1422041623)#concurrency (DBG): Lockable created successfully
3308(1422041623)#ipcm (DBG): Config file is: /usr/local/irati/etc/ipcmanager.conf
3308(1422041623)#concurrency (DBG): Lockable created successfully
3308(1422041623)#concurrency (DBG): Condition variable created successfully
3308(1422041623)#logs (DBG): New log level: INFO
3308(1422041623)#netlink-manager (INFO): Netlink socket connected to local port 1 
Local Configuration
	Installation path: /usr/local/irati/bin
	Library path: /usr/local/irati/lib
	Log path: /usr/local/irati/var/log
	Console port: 32766
	CDAP timeout in ms: 10000
	Enrollment timeout in ms: 10000
	Flow allocator timeout in ms:  15000
	Watchdog period in ms: 60000
	Declared dead interval in ms: 120000
	Neighbors enroller period in ms: 10000
IPC process to create:
	Name: test-tcp:1::
	DIF Name: tcp.DIF:::
	DIFs to register at:
	Host name: 
	SDU protection options:
	Parameters:
IPC process to create:
	Name: test2.IRATI:1::
	DIF Name: normal.DIF:::
	DIFs to register at:
		tcp.DIF:::
	Host name: 
	SDU protection options:
	Parameters:
DIF configuration/properties:
	DIF name: tcp.DIF:::
	DIF type: shim-tcp-udp
	Parameters: 
		dirEntry:2:11:test2.IRATI0:10:10.10.10.24:242711:test1.IRATI0:10:10.10.10.14:2426
		expReg:1:11:test2.IRATI0:4:2427
		hostname:10.10.10.2
DIF configuration/properties:
	DIF name: normal.DIF:::
	DIF type: normal-ipc
	Parameters: 
		bar:foo
Application --> DIF mappings:
	rina.apps.echotime.client-1--: test2.IRATI:::
	rina.apps.echotime.server-1--: test1.IRATI:::

3308(1422041623)#ipcm (INFO)[create_ipcp]: IPC process test-tcp:1:: created [id = 1]

3308(1422041623)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process test-tcp:1:: to DIF tcp.DIF:::

3308(1422041623)#ipcm (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process test-tcp:1:: [success=1]

3308(1422041623)#ipcm (INFO)[create_ipcp]: IPC process test2.IRATI:1:: created [id = 2]

3312(1422041623)#concurrency (DBG): Lockable created successfully
3312(1422041623)#concurrency (DBG): Lockable created successfully
3312(1422041623)#logs (DBG): New log level: INFO
3312(1422041623)#netlink-manager (INFO): Netlink socket connected to local port 3312 
3312(1422041623)#ipc-process (INFO): Librina initialized
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 5_N_MINUS_1_FLOW_ALLOCATED
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 7_N_MINUS_1_FLOW_DEALLOCATED
3312(1422041623)#rib (INFO): Object with name /daf/management/neighbors, class neighbor set, instance 1 added to the RIB
3312(1422041623)#rib (INFO): Object with name /daf/management/enrollment, class enrollment information, instance 2 added to the RIB
3312(1422041623)#rib-daemon (INFO): Starting Management SDU reader ...
3312(1422041623)#rib (INFO): Object with name /daf/management/operationalStatus, class operationstatus, instance 3 added to the RIB
3312(1422041623)#rib (INFO): Object with name /daf/management/naming/address, class address, instance 4 added to the RIB
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 7_N_MINUS_1_FLOW_DEALLOCATED
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 5_N_MINUS_1_FLOW_ALLOCATED
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 6_N_MINUS_1_FLOW_ALLOCATION_FAILED
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 8_NEIGHBOR_DECLARED_DEAD
3312(1422041623)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/difregistrations, class DIF registration set, instance 5 added to the RIB
3312(1422041623)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/nminusoneflows, class nminusone flow set, instance 6 added to the RIB
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 0_CONNECTIVITY_TO_NEIGHBOR_LOST
3312(1422041623)#rib (INFO): Object with name /dif/management/flowallocator/directoryforwardingtableentries, class directoryforwardingtableentry set, instance 7 added to the RIB
3312(1422041623)#rib (INFO): Object with name /daf/management/naming/whatevercastnames, class whatname set, instance 8 added to the RIB
3312(1422041623)#rib (INFO): Object with name /dif/resourceallocation/flowallocator/flows, class flow set, instance 9 added to the RIB
3312(1422041623)#rib (INFO): Object with name /dif/management/flowallocator/qoscubes, class qoscube set, instance 10 added to the RIB
3312(1422041623)#rib (INFO): Object with name /dif/ipc/datatransfer/constants, class datatransfercons, instance 11 added to the RIB
3312(1422041623)#ipc-process (INFO): Initialized IPC Process with name: test2.IRATI, instance 1, id 2 
3312(1422041623)#ipcp-main (INFO): IPC Process name:     test2.IRATI
3312(1422041623)#ipcp-main (INFO): IPC Process instance: 1
3308(1422041623)#ipcm (INFO)[ipc_process_daemon_initialized_event_handler]: IPC process daemon initialized [id = 2]

3308(1422041623)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process test2.IRATI:1:: to DIF normal.DIF:::

3312(1422041623)#ipcp-main (INFO): IPC Process id:       2
3312(1422041623)#ipcp-main (INFO): IPC Manager port:     1
3312(1422041623)#ipcp-main (INFO): IPC Process initialized, executing event loop...
3312(1422041623)#rib (INFO): Object with name /dif/management/pduforwardingtable/linkstate/flowstateobjectgroup, class flowstateobject set, instance 12 added to the RIB
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 7_N_MINUS_1_FLOW_DEALLOCATED
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 5_N_MINUS_1_FLOW_ALLOCATED
3312(1422041623)#rib-daemon (INFO): EventListener subscribed to event 9_NEIGHBOR_ADDED
3312(1422041623)#rib (INFO): Object with name /dif/management/flowallocator/qoscubes/unreliablewithflowcontrol, class qoscube, instance 13 added to the RIB
3312(1422041623)#rib (INFO): Object with name /dif/management/flowallocator/qoscubes/reliablewithflowcontrol, class qoscube, instance 14 added to the RIB
3312(1422041623)#rib (INFO): Object with name /difmanagement/watchdog, class watchdog timer, instance 15 added to the RIB
3308(1422041623)#ipcm (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process test2.IRATI:1:: [success=1]

3308(1422041623)#ipcm (INFO)[register_at_dif]: Requested DIF registration of IPC process test2.IRATI:1:: at DIF tcp.DIF::: through IPC process test-tcp:1::

3308(1422041623)#ipcm (INFO)[ipcm_register_response_ipcp]: IPC process test2.IRATI:1:: informed about its registration to N-1 DIF tcp.DIF:::

3312(1422041623)#resource-allocator (INFO): IPC Process registered to N-1 DIF tcp.DIF
3312(1422041623)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/difregistrations/tcp.DIF, class DIF registration, instance 16 added to the RIB
^[[A3308(1422041660)#ipcm (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between test2.IRATI:1:: and Unknown app:::

3312(1422041660)#resource-allocator (INFO): Accepted new flow from IPC Process Unknown app-
3312(1422041660)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/nminusoneflows/1, class nminusone flow, instance 17 added to the RIB
3312(1422041660)#rib-daemon (INFO): Event 5_N_MINUS_1_FLOW_ALLOCATED has just happened. Notifying event listeners.
3308(1422041660)#ipcm (INFO)[allocate_flow_response_event_handler]: : Informing IPC process test-tcp:1:: about flow allocation from application test2.IRATI:1:: to application Unknown app::: in DIF tcp.DIF::: [success = 1, port-id = 1]

3308(1422041670)#ipcm (INFO)[flow_deallocated_event_handler]: IPC process test-tcp:1:: and local application test2.IRATI:1:: informed that flow with port-id 1 has been deallocated remotely 

3312(1422041670)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/nminusoneflows/1, class nminusone flow, instance 17 removed from the RIB
3312(1422041670)#ipcp-main (CRIT): Got signal 11
3312(1422041670)#rinad-debug (CRIT): Dumping backtrace
3312(1422041670)#rinad-debug (CRIT): ======== CUT HERE ========
  /usr/local/irati/bin/ipcp() [0x80924b8]
  /usr/local/irati/bin/ipcp() [0x805e3ff]
  linux-gate.so.1(__kernel_sigreturn+0) [0xb7719a88]
  /usr/local/irati/bin/ipcp() [0x805f7ed]
  /usr/local/irati/bin/ipcp() [0x8083943]
  /usr/local/irati/bin/ipcp() [0x80928cc]
  /usr/local/irati/bin/ipcp() [0x805ed04]
  /usr/local/irati/bin/ipcp() [0x805c3e5]
  /lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xf3) [0xb71c3a63]
  /usr/local/irati/bin/ipcp() [0x805e2fa]
3312(1422041670)#rinad-debug (CRIT): ======== CUT HERE ========
3308(1422041670)#ipcm (INFO)[os_process_finalized_handler]: Application test2.IRATI:1::terminated

3308(1422041670)#ipcm (INFO)[unregister_app_from_ipcp]: Requested unregistration of application test2.IRATI:1:: from IPC process test-tcp:1::

3308(1422041670)#ipcm (INFO)[ipcm_unregister_response_common]: IPC process test-tcp:1:: informed about unregistration of application test2.IRATI:1:: [success = 1]

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Saturday Jan 24, 2015 at 11:05 GMT_

----

Can you demangle the backtrace provided? (backtrace-demangler in your /usr/local/irati/bin folder)

**Comment by kewinrausch** [comment]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lbergesio](https://github.com/lbergesio)**
_Sunday Jan 25, 2015 at 13:54 GMT_

----

The problem seems to be the ipc process in user space actually;

ipcm.log:

g# cat ipcm.log 
3382(1422193583)#netlink-manager (INFO): Netlink socket connected to local port 1 
3382(1422193583)#ipcm (INFO)[create_ipcp]: IPC process test-eth:1:: created [id = 1]

3382(1422193583)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process test-eth:1:: to DIF 300:::

3382(1422193583)#ipcm (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process test-eth:1:: [success=1]

3382(1422193583)#ipcm (INFO)[create_ipcp]: IPC process test2.IRATI:1:: created [id = 2]

3382(1422193583)#ipcm (INFO)[ipc_process_daemon_initialized_event_handler]: IPC process daemon initialized [id = 2]

3382(1422193583)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process test2.IRATI:1:: to DIF normal.DIF:::

3382(1422193583)#ipcm (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process test2.IRATI:1:: [success=1]

3382(1422193583)#ipcm (INFO)[register_at_dif]: Requested DIF registration of IPC process test2.IRATI:1:: at DIF 300::: through IPC process test-eth:1::

3382(1422193583)#ipcm (INFO)[ipcm_register_response_ipcp]: IPC process test2.IRATI:1:: informed about its registration to N-1 DIF 300:::

3382(1422193602)#ipcm (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between test2.IRATI:1:: and test1.IRATI:1::�������A���c�4e�g���c����?������6����ӖU�}�U�?�U�(�U�%1I���U�3f�I@

3382(1422193602)#ipcm (INFO)[allocate_flow_response_event_handler]: : Informing IPC process test-eth:1:: about flow allocation from application test2.IRATI:1:: to application test1.IRATI:1::�������A���c�4e�g���c����?������6����ӖU�}�U�?�U�(�U�%1I���U�3f�I@ in DIF 300::: [success = 1, port-id = 1]

3382(1422193602)#ipcm (INFO)[os_process_finalized_handler]: Application test2.IRATI:1::terminated

3382(1422193602)#ipcm (INFO)[deallocate_flow]: Application ::: asks IPC process test-eth:1:: to deallocate flow [port-id = 1]

3382(1422193602)#ipcm (INFO)[unregister_app_from_ipcp]: Requested unregistration of application test2.IRATI:1:: from IPC process test-eth:1::

3382(1422193602)#ipcm (INFO)[ipcm_deallocate_flow_response_event_handler]: Deallocating flow identified by port-id 1 from IPC process test-eth:1:: [success = 1]

3382(1422193602)#ipcm (INFO)[ipcm_unregister_response_common]: IPC process test-eth:1:: informed about unregistration of application test2.IRATI:1:: [success = 1]

test2.IRATI-1.log:

3386(1422193583)#netlink-manager (INFO): Netlink socket connected to local port 3386 
3386(1422193583)#ipc-process (INFO): Librina initialized
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 5_N_MINUS_1_FLOW_ALLOCATED
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 7_N_MINUS_1_FLOW_DEALLOCATED
3386(1422193583)#rib (INFO): Object with name /daf/management/neighbors, class neighbor set, instance 1 added to the RIB
3386(1422193583)#rib (INFO): Object with name /daf/management/enrollment, class enrollment information, instance 2 added to the RIB
3386(1422193583)#rib-daemon (INFO): Starting Management SDU reader ...
3386(1422193583)#rib (INFO): Object with name /daf/management/operationalStatus, class operationstatus, instance 3 added to the RIB
3386(1422193583)#rib (INFO): Object with name /daf/management/naming/address, class address, instance 4 added to the RIB
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 7_N_MINUS_1_FLOW_DEALLOCATED
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 5_N_MINUS_1_FLOW_ALLOCATED
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 6_N_MINUS_1_FLOW_ALLOCATION_FAILED
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 8_NEIGHBOR_DECLARED_DEAD
3386(1422193583)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/difregistrations, class DIF registration set, instance 5 added to the RIB
3386(1422193583)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/nminusoneflows, class nminusone flow set, instance 6 added to the RIB
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 0_CONNECTIVITY_TO_NEIGHBOR_LOST
3386(1422193583)#rib (INFO): Object with name /dif/management/flowallocator/directoryforwardingtableentries, class directoryforwardingtableentry set, instance 7 added to the RIB
3386(1422193583)#rib (INFO): Object with name /daf/management/naming/whatevercastnames, class whatname set, instance 8 added to the RIB
3386(1422193583)#rib (INFO): Object with name /dif/resourceallocation/flowallocator/flows, class flow set, instance 9 added to the RIB
3386(1422193583)#rib (INFO): Object with name /dif/management/flowallocator/qoscubes, class qoscube set, instance 10 added to the RIB
3386(1422193583)#rib (INFO): Object with name /dif/ipc/datatransfer/constants, class datatransfercons, instance 11 added to the RIB
3386(1422193583)#ipc-process (INFO): Initialized IPC Process with name: test2.IRATI, instance 1, id 2 
3386(1422193583)#ipcp-main (INFO): IPC Process name:     test2.IRATI
3386(1422193583)#ipcp-main (INFO): IPC Process instance: 1
3386(1422193583)#ipcp-main (INFO): IPC Process id:       2
3386(1422193583)#ipcp-main (INFO): IPC Manager port:     1
3386(1422193583)#ipcp-main (INFO): IPC Process initialized, executing event loop...
3386(1422193583)#rib (INFO): Object with name /dif/management/pduforwardingtable/linkstate/flowstateobjectgroup, class flowstateobject set, instance 12 added to the RIB
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 7_N_MINUS_1_FLOW_DEALLOCATED
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 5_N_MINUS_1_FLOW_ALLOCATED
3386(1422193583)#rib-daemon (INFO): EventListener subscribed to event 9_NEIGHBOR_ADDED
3386(1422193583)#rib (INFO): Object with name /dif/management/flowallocator/qoscubes/unreliablewithflowcontrol, class qoscube, instance 13 added to the RIB
3386(1422193583)#rib (INFO): Object with name /dif/management/flowallocator/qoscubes/reliablewithflowcontrol, class qoscube, instance 14 added to the RIB
3386(1422193583)#rib (INFO): Object with name /difmanagement/watchdog, class watchdog timer, instance 15 added to the RIB
3386(1422193583)#resource-allocator (INFO): IPC Process registered to N-1 DIF 300
3386(1422193583)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/difregistrations/300, class DIF registration, instance 16 added to the RIB
3386(1422193602)#enrollment-task (ERR): Problems: Unknown N-1 flow
3386(1422193602)#enrollment-task (ERR): Problems deallocating N-1 flow: There is no flow at the specified portId
3386(1422193602)#resource-allocator (INFO): Accepted new flow from IPC Process test1.IRATI-1
3386(1422193602)#rib (INFO): Object with name /dif/resourceallocation/nminusoneflowmanager/nminusoneflows/1, class nminusone flow, instance 17 added to the RIB
3386(1422193602)#rib-daemon (INFO): Event 5_N_MINUS_1_FLOW_ALLOCATED has just happened. Notifying event listeners.
3386(1422193602)#concurrency (CRIT): Cannot destroy mutex
3386(1422193602)#ipcp-main (CRIT): Got signal 11
3386(1422193602)#rinad-debug (CRIT): Dumping backtrace
3386(1422193602)#rinad-debug (CRIT): ======== CUT HERE ========
3386(1422193602)#rinad-debug (CRIT): ======== CUT HERE ========
3386(1422193602)#concurrency (CRIT): Cannot destroy condition variable
3386(1422193602)#concurrency (CRIT): Cannot destroy mutex

**Comment by sandervrijders** [comment]
Still happens?

**Comment by sandervrijders** [comment]
Not reproducible
