### ISSUE TITLE
dtp_write: sender inactivity timer invoked twice

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#443]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Sunday Jan 25, 2015 at 14:56 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/440_

----

Currently the timer is restarted both in the dtp_write() function and in default_transmission() (called by dtp_write()). Drop one restart, chosing the right timeout (3*x or 2*x ?)

**Comment by vmaffione** [comment]
Fixed
