### ISSUE TITLE
Bad cleanup in the shim-tcp-udp if the UDP socket fails to bind

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#444]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Jan 27, 2015 at 16:12 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/441_

----

![oopsvm](https://cloud.githubusercontent.com/assets/1212456/5921889/731913f0-a647-11e4-9b0e-5412e590a1e1.png)

Attached a screenshot, since I got this in a VM. Happens after closing the IPCM in user-space. WIP branch.

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Jan 27, 2015 at 16:20 GMT_

----

Sidenote: I assigned the wrong IP to my interface to get this error

**Comment by edugrasa** [comment]
When an application unregister, the UDP socket is not closed, so when it tries to register again it fails.

**Comment by dstaesse** [comment]
The shim-tcp-udp is not correctly cleaned up (zombie thread) after IPCM is shut down either.

**Comment by edugrasa** [comment]
Fixed by #868
