### ISSUE TITLE
Possible improvement in dtp_receive()

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#445]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Thursday Jan 29, 2015 at 10:00 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/442_

----

In the current implementation, when A=0 and RTX_CONTROL=1, incoming PDUs that don't are not allowed by the max_sdu_gap are simply dropped (and the receiver LWE not incremented) This is ok because there is retransmission control, so the dropped PDU will be retransmitted. Note that this situation can happen because of out of order arrival.

However, an alternative (and probably better implementation) is to push the PDU in the sequencing queue (still not incrementing the receiver LWE), so that if some missing gaps are filled soon, the PDU can be acked and delivered.

**Comment by kewinrausch** [comment]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lbergesio](https://github.com/lbergesio)**
_Thursday Jan 29, 2015 at 10:24 GMT_

----

The other alternative is to implement selective ack and use that

**Comment by kewinrausch** [comment]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vmaffione](https://github.com/vmaffione)**
_Thursday Jan 29, 2015 at 10:27 GMT_

----

Yes, but consider that sending a selective ack requires that you put the PDU in the seqqueue, so it's not an alternative to the alternative, but an improvement and complement to the alternative.

**Comment by edugrasa** [comment]
@lbergesio, @miqueltarzan what do you plan to do with this one?

**Comment by lbergesio** [comment]
I would say to close this one and take this into account when redesigning the fast path with sk_buffers. Moreover, the option of A=0 and RTX=1 seems to lack of sense and it should probably be defined as an not allowed combination. I am not sure if this one was one of the combinations, but I think John was inline with the idea of defining the allowed ones.
