### ISSUE TITLE
ipcm: add runtime change of debug level

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#447]
<a href="https://github.com/msune"><img src="https://avatars.githubusercontent.com/u/1881210?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msune](https://github.com/msune)**
_Monday Feb 02, 2015 at 14:28 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/444_

---

As a user, it would be interesting to sometimes change the debug level at runtime (e.g. via the CLI). _Apparently_ there is no such option right now in the `ipcm` CLI:

```
IPCM >>> help
Available commands:
    assign-to-dif
    create-ipcp
    destroy-ipcp
    enroll-to-dif
    exit
    help
    list-ipcp-types
    list-ipcps
    plugin-load
    plugin-unload
    query-rib
    quit
    register-at-dif
    select-policy-set
    set-policy-set-param
    unregister-from-dif
    update-dif-config
```

P.S. Please tag as 'feature' and 'low priority'

**Comment by edugrasa** [comment]
Kernel log level can be tuned via sysfs right now (after modularizing the IRATI kernel code)
