### ISSUE TITLE
librina: simplify API calls (librina state updating callbacks)

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#448]
<a href="https://github.com/msune"><img src="https://avatars.githubusercontent.com/u/1881210?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msune](https://github.com/msune)**
_Monday Feb 02, 2015 at 14:38 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/445_

---

For certain calls like:

``` cpp
rina::ipcManager->requestApplicationRegistration(...); 
//If request was successful
rina::ipcManager->commitPendingRegistration(...); //Unnecessary
```

or on deallocate events:

``` cpp
case rina::DEALLOCATE_FLOW_RESPONSE_EVENT:              
   resp = dynamic_cast<rina::DeallocateFlowResponseEvent*>(event);
   port_id = resp->portId;                         
   rina::ipcManager->flowDeallocationResult(...); //Unnecessary
   break;
```

There are, what it appears to be, unnecessary calls from the app -> librina, to update the internal state of librina, which could be done already by filtering netlink (or whatever type of mechanism is used) incoming events from the IPCM before calling the application code (the one calling e.g. `rina::ipcEventProducer->eventTimedWait()`).

Calls identified so far (will be uptated):
- `rina::ipcManager->commitPendingRegistration()`
- `rina::ipcManager->flowDeallocationResult()`

P.S. label as low priority and "librina" component

**Comment by edugrasa** [comment]
Fixed via the new C RINA application API defined by ARCFIRE and removal of Netlink in the IRATI implementation
