### ISSUE TITLE
ipcm: gracefully stop on SIGTERM (Ctrl+C)

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#453]
<a href="https://github.com/msune"><img src="https://avatars.githubusercontent.com/u/1881210?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msune](https://github.com/msune)**
_Tuesday Feb 03, 2015 at 13:39 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/450_

----

There is the need for the `ipcm` to properly destroy the existing state of the IPCPs prior to completely stop, in order to not leave zombie IPCPs in the system and allow restart of the `ipcm` normally.

I will handle this; 

@edugrasa @salvestrini from which commit shall I branch?

p.s. Label as bug

**Comment by kewinrausch** [comment]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Tuesday Feb 03, 2015 at 13:54 GMT_

----

Probably current wip should be ok, Francesco should confirm.

If you destroy the IPC Processes sequentially using the IPCProcessFactory code the clean-up should be complete.

rina::ipcProcessFactory->destroy(ipcp_id);

**Comment by kewinrausch** [comment]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lbergesio](https://github.com/lbergesio)**
_Tuesday Feb 03, 2015 at 13:58 GMT_

----

I would branch from be-francesco-merge in order to introduce this in v1.0.0, but @salvestrini has the last word

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Wednesday Feb 04, 2015 at 10:24 GMT_

----

Should be a fast-fix. I'd go for landing it in wip first and then port it on be-francesco-merge as well as in open-irati (as soon as it is in wip).

**Comment by kewinrausch** [comment]
<a href="https://github.com/msune"><img src="https://avatars.githubusercontent.com/u/1881210?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msune](https://github.com/msune)**
_Wednesday Feb 04, 2015 at 10:25 GMT_

----

so dana-i2cat/wip. Deal

**Comment by kewinrausch** [comment]
<a href="https://github.com/msune"><img src="https://avatars.githubusercontent.com/u/1881210?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msune](https://github.com/msune)**
_Friday Feb 06, 2015 at 16:29 GMT_

----

Created tag in the private repo, for testing `CTRL+C` patch (please report if you don't see it):

https://github.com/bisdn/rina-sdk/tree/ctrl_c

This branch contains a partial refactor, but after testing it _could_ be integrated in master. Branches from HEAD of dana-i2cat/wip

@dstaesse since you were interested in this feature, could you have a look?

**Comment by msune** [comment]
Please use this repository now:

https://github.com/bisdn/irati/tree/ctrl_c
