### ISSUE TITLE
rinad: backup/don't overwrite ipcmanager.conf on `make install`

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#454]
<a href="https://github.com/msune"><img src="https://avatars.githubusercontent.com/u/1881210?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msune](https://github.com/msune)**
_Wednesday Feb 04, 2015 at 10:53 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/451_

----

During `make install` backup or do not overwrite `INSTALLATION_PATH/etc/ipcmanager.conf`

p.s. label as enhancement or even bug. Low priority

**Comment by msune** [comment]
Discussed here:

https://github.com/IRATI/stack/pull/625

@edugrasa this can be closed, isn't it?
