### ISSUE TITLE
IPCP segfault when propagating routing information

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#455]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Monday Feb 09, 2015 at 12:17 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/452_

----

IPCP with more than one enrollment crashes when updating information from one neighbor to other one. For example when a fallen neighbor reenrolls

**Comment by edugrasa** [comment]
@bernatgaston can this issue be closed?

**Comment by bernatgaston** [comment]
Yes, please close it.

**Comment by edugrasa** [comment]
@vmaffione this issue can be closed
