### ISSUE TITLE
Routing: object propagation send all the flow state objects, not only the modified ones

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#457]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Wednesday Feb 11, 2015 at 11:49 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/454_

----

When propagation of updated objects happen, the receiver recieves all the objects from the sender, not only the ones modified.

**Comment by edugrasa** [comment]
@bernatgaston can this issue be closed?

**Comment by bernatgaston** [comment]
I think this was fixed when the routing graph generation was separated from the forwarding table generation. Seems that to me in https://github.com/IRATI/stack/blob/pristine-1.2/rinad/src/common/encoders/FlowStateMessage.proto no more port sending, so I think it can be closed

**Comment by edugrasa** [comment]
@vmaffione this issue can be closed
