### ISSUE TITLE
Routing deprecte object works wrong

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#459]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Wednesday Feb 11, 2015 at 18:07 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/456_

----

Deprecate FSO sometimes deprecates an object which is not from that ipcprocess

**Comment by sandervrijders** [comment]
Was this fixed?

**Comment by edugrasa** [comment]
@bernatgaston can this issue be closed?

**Comment by bernatgaston** [comment]
Yes please close it

**Comment by edugrasa** [comment]
@vmaffione this issue can be closed
