### ISSUE TITLE
Routing: Propagation is launched before all the objects are sent

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#461]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Thursday Feb 12, 2015 at 10:06 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/458_

----

Sometimes propagation timer is launched before the Neighbor added event arrives to the PDUFT. This behaivour should not happen

**Comment by sandervrijders** [comment]
Was this fixed?

**Comment by bernatgaston** [comment]
this can be closed
