### ISSUE TITLE
Reenrollment problems because of desyncronized states

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#462]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Thursday Feb 12, 2015 at 10:07 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/459_

----

When process A thinks that process B is dead and tries reenrollment, but process B thinks that process A is still its neighbor it discards the M_CONNECT messages.

**Comment by sandervrijders** [comment]
Was this fixed by the 'mouse' experiments?

**Comment by bernatgaston** [comment]
this issue can be closed
