### ISSUE TITLE
Segafault when not finding a valid woscube

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#463]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Tuesday Feb 17, 2015 at 18:14 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/460_

----

Delete of already deleted flow

**Comment by sandervrijders** [comment]
Please, edit the title to be correct and provide more context.

**Comment by edugrasa** [comment]
@vmaffione this issue can be closed
