### ISSUE TITLE
Bug in efcp.c:efcp_connection_create. Sleeping function called from invalid context

### ISSUE THREAD

**Issue by miqueltarzan** [IRATI/stack#495]
efcp_connection_create creates a dtcp instance by calling dtcp_create within a rcu_read critical section. dtcp_create procedures eventually lead to a mutex being held. 

[ 4214.337710] BUG: sleeping function called from invalid context at kernel/lock                                                                                                                                                             ing/mutex.c:586
[ 4214.342970] in_atomic(): 1, irqs_disabled(): 0, pid: 3339, name: ipcp
[ 4214.346452] INFO: lockdep is turned off.
[ 4214.349113] CPU: 1 PID: 3339 Comm: ipcp Not tainted 3.15.0 #20
[ 4214.352553] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[ 4214.355538]  00000000 00000000 f035d8ec c165486f f06a0000 f035d910 c106bb89 c                                                                                                                                                             182ef20
[ 4214.361000]  00000001 00000000 00000d0b f06a03c8 efc12728 efc12730 f035d958 c                                                                                                                                                             165cba3
[ 4214.366693]  f035d924 c108cef2 efc12770 f035d95c c1092892 00000000 00008020 f                                                                                                                                                             8dda014
[ 4214.371853] Call Trace:
[ 4214.373347]  [<c165486f>] dump_stack+0x48/0x60
[ 4214.376064]  [<c106bb89>] __might_sleep+0xe9/0x120
[ 4214.379850]  [<c165cba3>] mutex_lock_nested+0x23/0x370
[ 4214.387683]  [<c108cef2>] ? static_obj+0x32/0x50
[ 4214.390704]  [<c1092892>] ? lockdep_init_map+0x92/0x4d0
[ 4214.395270]  [<f8dd1d4b>] ? ps_lookup+0x3b/0x90 [rina_personality_default]
[ 4214.399617]  [<f8dd1e56>] base_select_policy_set+0x36/0x110 [rina_personality                                                                                                                                                             _default]
[ 4214.403863]  [<c108c6d2>] ? debug_mutex_init+0x32/0x50
[ 4214.406784]  [<f8dc6252>] dtcp_select_policy_set+0x42/0x140 [rina_personality                                                                                                                                                             _default]
[ 4214.410840]  [<f8dc7001>] dtcp_create+0x91/0x240 [rina_personality_default]
[ 4214.414810]  [<f8dc4bda>] ? dt_dtp_bind+0x2a/0x90 [rina_personality_default]
[ 4214.418434]  [<f8dc4bda>] ? dt_dtp_bind+0x2a/0x90 [rina_personality_default]
[ 4214.422270]  [<f8dca126>] ? efcp_connection_create+0xe6/0x480 [rina_personali                                                                                                                                                             ty_default]
[ 4214.426766]  [<f8dca17c>] efcp_connection_create+0x13c/0x480 [rina_personalit                                                                                                                                                             y_default]
[ 4214.431322]  [<f8dca126>] ? efcp_connection_create+0xe6/0x480 [rina_personali                                                                                                                                                             ty_default]
[ 4214.436613]  [<f808829c>] connection_create_arrived+0x6c/0x270 [normal_ipcp]
[ 4214.441944]  [<c1647534>] ? policy_create_gfp+0x14/0x30
[ 4214.444938]  [<c1647582>] ? policy_create+0x12/0x20
[ 4214.447934]  [<c164716a>] ? conn_policies_create+0x4a/0xb0
[ 4214.451139]  [<f8dd0ae9>] notify_ipcp_conn_create_arrived+0x139/0x1d0 [rina_p                                                                                                                                                             ersonality_default]
[ 4214.456954]  [<f8dd09b0>] ? notify_ipcp_conn_update_req+0x170/0x170 [rina_per                                                                                                                                                             sonality_default]
[ 4214.464794]  [<c1643cb0>] dispatcher+0x90/0x140
[ 4214.468648]  [<c15839e9>] genl_rcv_msg+0x209/0x380
[ 4214.471467]  [<c15837e0>] ? genl_lock+0x20/0x20
[ 4214.474029]  [<c1583376>] netlink_rcv_skb+0x86/0xa0
[ 4214.476960]  [<c1583561>] genl_rcv+0x21/0x30
[ 4214.479563]  [<c1582ce5>] netlink_unicast+0x165/0x1c0
[ 4214.482390]  [<c1582f8f>] netlink_sendmsg+0x24f/0x3f0
[ 4214.485238]  [<c1542245>] sock_sendmsg+0x85/0xc0
[ 4214.488784]  [<c1146e8c>] ? might_fault+0x9c/0xb0
[ 4214.492781]  [<c131d73c>] ? _copy_from_user+0x5c/0x70
[ 4214.497250]  [<c154efd0>] ? verify_iovec+0x50/0xc0
[ 4214.501676]  [<c1542b02>] ___sys_sendmsg.part.15+0x272/0x280
[ 4214.506229]  [<c1166dc9>] ? deactivate_slab+0x4f9/0x590
[ 4214.509935]  [<c1166dc9>] ? deactivate_slab+0x4f9/0x590
[ 4214.513041]  [<c1146e42>] ? might_fault+0x52/0xb0
[ 4214.516025]  [<c1146e42>] ? might_fault+0x52/0xb0
[ 4214.518830]  [<c1146e8c>] ? might_fault+0x9c/0xb0
[ 4214.522620]  [<c131d73c>] ? _copy_from_user+0x5c/0x70
[ 4214.525507]  [<c154357a>] __sys_sendmsg+0x4a/0x80
[ 4214.528409]  [<c1543f44>] SYSC_socketcall+0x5d4/0x950

**Comment by sandervrijders** [comment]
@lbergesio This seems like an urgent bug

**Comment by lbergesio** [comment]
Is this still valid and reproducible? It was created on March 20th. I guess it happens using the default dtcp PS.

**Comment by sandervrijders** [comment]
@miqueltarzan Is this reproducible?

**Comment by miqueltarzan** [comment]
I think it's fixed.

**Comment by lbergesio** [comment]
Me too, checking the code it seems ok.
