### ISSUE TITLE
Bug: unable to handle kernel paging request at 6b6b6ba3 when N-1 port is removed

### ISSUE THREAD

**Issue by miqueltarzan** [IRATI/stack#502]
A normal-ipcp IPC process had a flow supported by a shim-eth-vlan IPC process. The shim-eth-vlan was removed (modprobe -r shim-eth-vlan) correctly, but when the normal-ipcp was removed this bug appeared:

 rina-rmt(DBG): Destroying N-1 port f31f4110 (port-id = 1)
Mar 24 10:41:19 irati-vm-miq kernel: [54988.761891] rina-rfifo(DBG): FIFO ed90ada8 destroyed successfully
Mar 24 10:41:19 irati-vm-miq kernel: [54988.765552] rina-rmt(DBG): PFT cache ed959340 destroyed
Mar 24 10:41:19 irati-vm-miq kernel: [54988.768790] rina-rmt(DBG): Destroying N-1 port f31f5dc0 (port-id = 1)
Mar 24 10:41:19 irati-vm-miq kernel: [54988.772580] rina-rfifo(DBG): FIFO ed90a450 destroyed successfully
Mar 24 10:41:19 irati-vm-miq kernel: [54988.776382] BUG: unable to handle kernel paging request at 6b6b6ba3
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] IP: [<f8ff0905>] n1_port_destroy+0x75/0xc0 [rina_personality_default]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] *pde = 00000000
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] Oops: 0000 [#1] SMP
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] Modules linked in: rina_default_plugin normal_ipcp(-) rina_personality_default nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc 8021q garp stp llc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbmouse usbhid hid floppy [last unloaded: arp826]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] CPU: 1 PID: 23104 Comm: modprobe Not tainted 3.15.0 #23
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] task: eddf4410 ti: ef7e4000 task.ti: ef7e4000
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] EIP: 0060:[<f8ff0905>] EFLAGS: 00010202 CPU: 1
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] EIP is at n1_port_destroy+0x75/0xc0 [rina_personality_default]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] EAX: 6b6b6b6b EBX: f31f5dc0 ECX: f518d4e0 EDX: 6b6b6b6b
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] ESI: 00000001 EDI: 00000000 EBP: ef7e5ec0 ESP: ef7e5eac
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  DS: 007b ES: 007b FS: 00d8 GS: 0033 SS: 0068
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] CR0: 8005003b CR2: 6b6b6ba3 CR3: 2d41b000 CR4: 000006d0
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] Stack:
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  f8ffcb38 f31f5dc0 00000001 f31f5dc0 00000001 ef7e5ee4 f8ff0ae7 c1650d3f
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  00000000 ef83f9e0 0000004f ed9592b0 ed959340 c2bc9b98 ef7e5efc f8ff145f
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  f8ffd108 ed959340 c2bc9ba0 c2bc9b98 ef7e5f28 f811ced1 eddf4410 00000246
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] Call Trace:
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<f8ff0ae7>] n1pmap_destroy+0x47/0x90 [rina_personality_default]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<c1650d3f>] ? printk+0x4d/0x4f
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<f8ff145f>] rmt_destroy+0x6f/0x100 [rina_personality_default]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<f811ced1>] normal_destroy+0x121/0x1c0 [normal_ipcp]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<f8ff512c>] kipcm_ipcp_factory_unregister+0x5c/0x110 [rina_personality_default]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<c1043bae>] ? put_online_cpus+0x5e/0x80
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<f811d80f>] mod_exit+0x13/0x804 [normal_ipcp]
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<c10c0f89>] SyS_delete_module+0x119/0x1a0
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<c1060427>] ? task_work_run+0x97/0xb0
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366]  [<c1668dcc>] sysenter_do_call+0x12/0x32
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] Code: 43 28 85 c0 74 0a ba 70 42 64 c1 e8 36 f0 64 c8 8b 43 30 85 c0 74 42 89 f2 84 d2 74 1e 8b 50 2c 85 d2 74 17 8b 40 28 85 c0 74 10 <8b> 4a 38 85 c9 74 09 8b 53 2c ff d1 85 c0 75 10 89 d8 e8 d4 de
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] EIP: [<f8ff0905>] n1_port_destroy+0x75/0xc0 [rina_personality_default] SS:ESP 0068:ef7e5eac
Mar 24 10:41:19 irati-vm-miq kernel: [54988.780366] CR2: 000000006b6b6ba3
Mar 24 10:41:19 irati-vm-miq kernel: [54988.936950] ---[ end trace fba51f1aed50c6a1 ]---

**Comment by edugrasa** [comment]
@lbergesio can this issue be closed?

**Comment by lbergesio** [comment]
Yes, the commit was already merged. @vmaffione please close it
