### ISSUE TITLE
Selection of QoS cube is not working correctly (all configurations) by setting the maxAllowableGap in FlowSpecification

### ISSUE THREAD

**Issue by dstaesse** [IRATI/stack#527]
use any configuration file that has a normal DIF between two hosts

I have the following qos cubes:

"qosCubes": [
                {
                    "name": "reliable",
                    "id": 1,
                    "partialDelivery": false,
                    "orderedDelivery": true
                },
                {
                    "name": "unreliable",
                    "id": 2,
                    "partialDelivery": true,
                    "orderedDelivery": false
                }
            ],

after enrollment run rina-echo-time with -g >= 0 (sets maxAllowableGap)

(rina-echo-time without -g option shown, which works , this sets maxAllowableGap to -1)
```
dstaesse@n:/usr/local/irati/bin$ ./rina-echo-time -c 10
28822(1427818362)#concurrency (DBG): Lockable created successfully
28822(1427818362)#concurrency (DBG): Lockable created successfully
28822(1427818362)#logs (DBG): New log level: INFO
28822(1427818362)#netlink-manager (INFO): Netlink socket connected to local port 28822 
Flow allocation time = 18ms
SDU size = 20, seq = 0, RTT = 254us
SDU size = 20, seq = 1, RTT = 239us

dstaesse@n:/usr/local/irati/bin$ ./rina-echo-time -c 10 -g 0
28849(1427818367)#concurrency (DBG): Lockable created successfully
28849(1427818367)#concurrency (DBG): Lockable created successfully
28849(1427818367)#logs (DBG): New log level: INFO
28849(1427818367)#netlink-manager (INFO): Netlink socket connected to local port 28849 
28849(1427818368)#rina-echo-time (ERR): Failed to allocate a flow
```

error log from IPCP will show " Could not find a QoS Cube"

```
20332(1427816743)#flow-allocator (DBG): Created flow allocator instance to manage the flow identified by portId 5 
20332(1427816743)#flow-allocator (ERR): Problems allocating flow: Could not find a QoS Cube
20332(1427816743)#timer (DBG): Waiting for the timer 7959264 to join
20332(1427816743)#timer (DBG): Timer with ID 7959264 ended
20332(1427816743)#timer (DBG): Waiting for the timer 7954576 to join
20332(1427816744)#timer (DBG): Timer with ID 7954576 ended
20332(1427816744)#syscalls (DBG): Gonna call syscall SYS_deallocatePortId (322)
20332(1427816744)#syscalls (ERR): Syscall deallocate port id failed: -1
20332(1427816744)#flow-allocator (ERR): Problems releasing port-id 5: Problems requesting the allocation/deallocation of a port-id
20332(1427816744)#netlink-manager (DBG): NL msg TX. Fam: 22; Opcode: 13_IPCM_ALLOC_FLOW_REQ_RES; Sport: 20332; Dport: 1; Seqnum: 5; Response; SIPCP: 2; DIPCP: 0
```
reason lies here (rinad/src/ipcp/default-flow-allocator-ps.cc)

```cpp
rina::QoSCube * FlowAllocatorPs::selectQoSCube(
                const rina::FlowSpecification& flowSpec)
{
	std::list<rina::QoSCube*> qosCubes = dm->getQoSCubes();
	if (flowSpec.maxAllowableGap < 0) {
		return *(qosCubes.begin());
	}

	std::list<rina::QoSCube*>::const_iterator iterator;
	rina::QoSCube* cube;
	for (iterator = qosCubes.begin(); iterator != qosCubes.end(); ++iterator) {
		cube = *iterator;
		if (cube->get_efcp_policies().is_dtcp_present()) {
			if (flowSpec.maxAllowableGap >= 0
					&& cube->get_efcp_policies().get_dtcp_configuration().is_rtx_control()) {
				return cube;
			}
		}
	}

	throw rina::Exception("Could not find a QoS Cube");
}
```
configuration has a "reliable" flow, so one of
```cpp
cube->get_efcp_policies().is_dtcp_present()
cube->get_efcp_policies().get_dtcp_configuration().is_rtx_control()
```
is probably not finding the correct information (could be the reliable qos cube not registering).

**Comment by dstaesse** [comment]
NOTE: the first qoscube is always selected, which in most config files is reliable.

**Comment by edugrasa** [comment]
This happens because the information about the qos cubes configuration is incomplete. In none of the qos cubes definition a configuration for DTCP is specified (and the default is DTCP disabled), therefore none of the qos cubes have rtx. control or flow control activated (both are unreliable, regardless of the name you put them). 

The template of the configuration file provides an example of two valid qos cubes configurations, one with flow control only and the other with flow control and retransmission control: https://github.com/IRATI/stack/blob/master/rinad/etc/ipcmanager.conf.in

@vmaffione this issue should be closed.

**Comment by dstaesse** [comment]
Hi Vincenzo, this issue should not be closed. The selection of the QoSCube is incorrect. The current code will select either:
the first QoS Cube 
or a reliable QoS Cube

**Comment by edugrasa** [comment]
If gap < 0 it will choose any QoS cube (since gap < 0 means "I don't care"), so the DIF is free to choose

**Comment by msune** [comment]
@dstaesse  Sorry, I didn't see the amended version. I guess the files in the first reference were mistakenly added

**Comment by edugrasa** [comment]
@vmaffione after the merge this issue can be closed
