### ISSUE TITLE
Bug in IPCM when destroying normal IPC Processes from the console

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#530]
Processing of event OS process finalized doesn't check if the IPCP was already destroy.

**Comment by msune** [comment]
Good catch! Indeed a copy&paste error. **ACK**.

 It was not seen before because probably most testers did not define `-DDEBUG`, and therefore the assertion inside `remove_transaction()` was never happening. We need the developer mode (e.g. `--enable-debug`)
