### ISSUE TITLE
Create Plugin/policy-set catalogue in IPCM to keep track of plugins available in the system

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#546]
IPCM should be instructed with one or more folders to scan for plugin libraries (by default $libraryPath/rinad/ipcp). Each library should have a manifest where it provides information on the policy sets provided by the plugin (list of {component name, policy set name} pairs).

The IPCM should use the information in the manifest to maintain an up-to-date catalogue of the available plugins in the system, with the policy-sets contributed by each plugin.

**Comment by sandervrijders** [comment]
@edugrasa This seems like something that requires discussion on the ML first..

**Comment by edugrasa** [comment]
@sandervrijders  Was already discussed (in the devs chat) what is here are the conclusions of the discussion. It was partially implemented by @vmaffione (manifest in all plugins), IPCM catalogue still to be developed.

**Comment by sandervrijders** [comment]
Ok, don't want to re-open the discussion in that case. However, from now on these things have to be discussed via the ML, since clearly some people missed it.

**Comment by edugrasa** [comment]
@vmaffione can this issue be closed now?
