### ISSUE TITLE
Add support in PDU Forwarding Table for different next_hop policies.

### ISSUE THREAD

**Issue by miqueltarzan** [IRATI/stack#550]
The PDU Forwarding Table main function is to provide a list of next hops for PDUs to be delivered to. Several strategies can be used to choose these next hops, and thus support for plugin policies must be available.

**Comment by edugrasa** [comment]
@vmaffione this issue can be closed, or you prefer doing it when the changes to the PDU Forwarding Function configuration (via Netlink) are finished?

**Comment by vmaffione** [comment]
I think this is related to
https://github.com/IRATI/stack/pull/553
which is already merged. Miquel, can we close it?

**Comment by miqueltarzan** [comment]
Yes, it can be closed
