### ISSUE TITLE
Shim Eth does not destroy eth_flows when destroying the ipcp instance

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#554]
This produces a kernel bang when destroying the upper normal-ipcp which tryes to unbind the lower shim_eth_ipcp:

[  519.680593] rina-rmt(DBG): Destroying N-1 port dfe9e680 (port-id = 1)
[  519.683788] BUG: unable to handle kernel paging request at 6b6b6ba3
[  519.687450] IP: [<f81a1956>] n1_port_destroy+0x66/0xb0 [rina_personality_default]
[  519.687780] *pde = 00000000 
[  519.687780] Oops: 0000 [#1] SMP 
[  519.687780] Modules linked in: shim_eth_vlan rinarp arp826 nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc rina_default_plugin shim_tcp_udp normal_ipcp rina_personality_default 8021q garp stp llc psmouse i2c_piix4 serio_raw pcspkr hid_generic usbmouse usbhid hid floppy
[  519.687780] CPU: 1 PID: 3457 Comm: ipcm Not tainted 3.15.0 #37
[  519.687780] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[  519.687780] task: dc900000 ti: df7c8000 task.ti: df7c8000
[  519.687780] EIP: 0060:[<f81a1956>] EFLAGS: 00010202 CPU: 1
[  519.687780] EIP is at n1_port_destroy+0x66/0xb0 [rina_personality_default]
[  519.687780] EAX: 6b6b6b6b EBX: dfe9e680 ECX: 00000000 EDX: 6b6b6b6b
[  519.687780] ESI: 00000001 EDI: 00000000 EBP: df7c9f18 ESP: df7c9f04
[  519.687780]  DS: 007b ES: 007b FS: 00d8 GS: 0033 SS: 0068
[  519.687780] CR0: 8005003b CR2: b7750000 CR3: 1ffc6000 CR4: 000006d0
[  519.687780] Stack:
[  519.687780]  f81adce0 dfe9e680 00000001 dfe9e680 0000004f df7c9f3c f81a20aa f0921768
[  519.687780]  df7c9f2c f040a880 dd9a0e10 f0921770 f0921768 f0921768 df7c9f68 f8082e49
[  519.687780]  f57d05a0 00000002 00000282 f09217a0 f0921e00 f0921778 f57d05a0 00000002
[  519.687780] Call Trace:
[  519.687780]  [<f81a20aa>] rmt_destroy+0x4a/0x130 [rina_personality_default]
[  519.687780]  [<f8082e49>] normal_destroy+0x129/0x1c0 [normal_ipcp]
[  519.687780]  [<f81a77a3>] kipcm_ipcp_destroy+0x53/0xe0 [rina_personality_default]
[  519.687780]  [<f81a7ed3>] default_ipc_destroy+0x43/0x50 [rina_personality_default]
[  519.687780]  [<c15e9a9f>] SyS_ipc_destroy+0x9f/0xc0
[  519.687780]  [<c1606f0c>] sysenter_do_call+0x12/0x22
[  519.687780] Code: c9 89 08 74 03 89 41 04 c7 43 0c 00 00 00 00 c7 43 10 00 00 00 00 8b 43 08 85 c0 74 48 8b 50 2c 85 d2 74 3f 8b 40 28 85 c0 74 36 <8b> 4a 38 85 c9 74 2d 89 f2 84 d2 74 09 8b 53 04 ff d1 85 c0 75
[  519.687780] EIP: [<f81a1956>] n1_port_destroy+0x66/0xb0 [rina_personality_default] SS:ESP 0068:df7c9f04
[  519.687780] CR2: 000000006b6b6ba3
[  519.827525] ---[ end trace cbf77b3a0da3cf69 ]---
[  570.420398] rina-normal-ipc(DBG): Mgmt queue waken up by interruption, returned error -512
[  570.431189] rina-syscalls(DBG): Personality returned value -512

**Comment by sandervrijders** [comment]
I believe it used to be the KFA's responsibility to clean up the flow. Probably this changed with the distributed loop.
