### ISSUE TITLE
IPC Manager Daemon: Prevent assignment of two IPCPs to the same DIF in the same system

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#558]
IPC Manager Daemon: Prevent assignment of two IPCPs to the same DIF in the same system.

An IPCP is the instantiation of a DIF in a system, only one IPCP can belong to a DIF in a system at a time.

**Comment by dstaesse** [comment]
Can this be undone?

**Comment by edugrasa** [comment]
Yes, undoing the check is very easy, but if you allow multiple IPC Processes per DIF in the same processing systems, there will be a number of implications on mapping applications to DIFs: we will have to map applications to IPC processes, not to DIFs, so the IPCM, which is sitting between applications and IPC Processes, will have to be updated. 

Should be added as a separate issue, and let's see when we have time to implement it. Is it a requirement for iteration 1 experiments?

**Comment by dstaesse** [comment]
It's not a real requirement. Also, I would not explicitly map applications to IPC processes, mapping them to a DIF is fine, there is just an additional mapping/step needed of DIF name to IPCP instance, (which in most cases can be trivial).

It's not a requirement for current experiments, so in the implementation this can be left open for now.

**Comment by edugrasa** [comment]
The IPCM Daemon needs to know what app (including IPCPs) is registered to what DIF and what app (including IPCPs) has allocated flows in what DIFs, because it redirects operations on flows to IPCP process daemons (he is the broker). So, if there can be multiple IPCPs in the same DIF, now the IPCM will have to remember which IPCP was used for the flow or the registration (right now the IPCM just remembers the DIF, since only one IPCP per DIF per system is allowed).

**Comment by msune** [comment]
@dstaesse I think before reverting any change and implementing anything fancy like Eduard says in the very last message, we should discuss architecturally (in RINA) if it makes sense.

You seem to have 2 different opinions on whether a processing system can have 2 IPCPs in the same DIF, and we should check this against specs and John if necessary, before touching (again) any code.

**Comment by edugrasa** [comment]
We have checked with John in a private conversation, although there are no super clear use cases that really require this feature otherwise they can't be done, there is also no reason right now why this shouldn't be allowed by the architecture.

**Comment by dstaesse** [comment]
@msune: it depends on the intricacies of the current implementation. You guys know whether it's something that can be done easily or would require a lot of changes. My take: it's closer to the architecture as it is currently specified. If it takes a lot of changes, it could reveal that something else may be off and the exercise may be worth it from that perspective as well. It's up to you IPCM guys.

**Comment by edugrasa** [comment]
It's not a ton of work and it is only in the IPCM, but we have a lot of development to do for this period. That is why I'm asking if it is required for experimentation during this first iteration. Otherwise we can fix this later, after the review (I would add another ticket to avoid forgetting).

**Comment by dstaesse** [comment]
OK, I'll add a ticket :)
