### ISSUE TITLE
IPCP: flow allocation logic

### ISSUE THREAD

**Issue by vmaffione** [IRATI/stack#560]
Here

https://github.com/IRATI/stack/blob/pristine-1.2/rinad/src/ipcp/flow-allocator.cc#L717-L744

flow allocation is ongoing (on the initiator side), we've already used the DFT to get the remote address from the destination application name. As of my understanding, what we should do here is find the CDAP session towards the neighbor that is the next hop towards the remote address - in general next-hop != remote_address.

But from the code it seems that a "random" (the first one in a list) cdap session (e.g. a port_id) is selected.. this will work only if you have one neigbhor - unless I'm missing something.

**Comment by edugrasa** [comment]
Flow Allocator Instance doesn't send the request to the nearest neighbor, it sends it directly (meaning it is not forwarded by intermediate flow allocators) to the address of the IPCP returned by the DFT. The "kernel IPCP" exposes two operations to send layer management messages to other IPCPs: sendToN-1Port (delivered to a nearest neighbor, uses the CDAP session), and sendToAddress (CDAP session is irrelevant), in which the RMT checks the forwarding policy and forwards the PDU to the N-1 port returned by the policy.

Flow allocation works regardless the number of neighbors, that has been tested.

**Comment by vmaffione** [comment]
Ok, so for flow allocation we use A-DATA M_CREATE(Flow)/M_CREATE_R(Flow) PDUs that can be forwarded without using existing CDAP sessions. Therefore, you don't need to lookup any port-id (in userspace) to transmit the CDAP message --> getALLCDAPSessions() should not be called and cdapSession[0] (basically, a possibly random port-id) not dereferenced.

**Comment by edugrasa** [comment]
This issue can be closed @vmaffione
