### ISSUE TITLE
Re-arrangement of RINA kernel sources

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#565]
The kernel RINA source file organization is becoming a bit of a mess, I propose the following re-structuring (or something similar):
  * linux/net/rina/ -> only common headers in the main folder (could even go to /common/)
     * linux/net/rina/utils/ -> General utilities  (timers, queues, etc..)
     * linux/net/rina/kuinterface/ -> Kernel/user-space interface related classes (Netlink, syscalls)
     * linux/net/rina/kipcm/ -> KIPCM implementation
     * linux/net/rina/kfa/ -> KFA implementation
     * linux/net/rina/plugins/ -> RINA kernel plugins
     * linux/net/rina/ipcp/ -> all the normal IPCP-related sources, structured the following way
        * linux/net/rina/ipcp/efcp/ -> all EFCP-related sources, except policy set implementations
           * linux/net/rina/ipcp/efcp/policies/ -> EFCP policy set implementations
        * linux/net/rina/ipcp/rmt/ -> all RMT-related sources, except policy set implementations
           * linux/net/rina/ipcp/rmt/policies/ -> RMT policy set implementations
        * linux/net/rina/ipcp/sdup/ -> all SDU Protection-related sources, except policy set implementations
           * linux/net/rina/ipcp/sdup/policies/ -> SDU Protection policy set implementations
     * linux/net/rina/shims/ -> All Shim-related sources, structured the following way
        * linux/net/rina/shims/tcp-udp/ -> Shim DIF over TCP/UDP
        * linux/net/rina/shims/eth-vlan/ -> Shim Eth vlan (including ARP implementation)
        * linux/net/rina/shims/hv/ -> Shim DIF for HV (including VMPI)

**Comment by msune** [comment]
+1

**Comment by dstaesse** [comment]
shims should be under ipcp, no?

**Comment by sandervrijders** [comment]
I'd avoid to have too many folders there. Agreed that policies should be in a different folder. But for instance, the shim tcp-udp is a single source file. To me that doesn't merit a subfolder.

**Comment by dstaesse** [comment]
Agree with sander, let's put all ipcp related stuff in ipcp/normal/ and the shims as single source files in the ipcp/shims folder.
Not sure but it may be better to organize the policies differently: so ../policies/rmt, /policies/sdup instead of ../rmt/policies, ../sdup/policies.. this way all policies are in a single tree and do not intertwine with the tree for the mechanisms... just a thought

**Comment by edugrasa** [comment]
@dstaesse  No, shims should not be under IPCP imho because the normal IPCP code doesn't depend on the shims. It's a structure to faciilty working with the kernel sources and their dependencies (finding stuff). I tagged the folder "ipcp" to make it shorter (it is just the normal IPCP code).

@sandervrijders Depending on the shim implementation. The shim-hv has all the VMPI stuff, the shim-eth-vlan has all the ARP stuff. Folders are to facilitate finding the code.

@dstaesse A developer developing an RMT policy will probably want to look at the RMT code, that is why they should be close (same for EFCP, RMT, etc).

**Comment by sandervrijders** [comment]
Well, the same goes for /kfa/ for instance. This is more an object oriented way to structure the source files. I'd try to stick to the Linux style.

**Comment by sandervrijders** [comment]
A subfolder /policies with subfolders for each component is a good idea though.

**Comment by msune** [comment]
I disagree that this is object oriented. This is module oriented and the degree of "folderization" depends on taste.

I strongly agree that, at least, the first level should be implemented. It gives hints to the developers what they will find there. Perhaps having a folder per shim or even plugin is too much, so I would leave it in this first level.

**Comment by edugrasa** [comment]
@sandervrijders It's not about object-orientation, it's about making it easy to find things that are related to each other. For example, the normal IPCP in the kernel has EFCP, the RMT and SDU Protection, each one with multiple source files, makes sense to group them together.

**Comment by sandervrijders** [comment]
Yes, I agree that they should be grouped together. I'd just avoid to have such a deep folder structure. One level is enough imho. Files can be prefixed in their names as is done in the rest of the kernel (for instance  ip_fragment.c,  ip_tunnel.c etc. in net/ipv4/)

**Comment by edugrasa** [comment]
@vmaffione, do you think that this is worth implementing or let's close this issue? Based on the received feedback, we could have this scheme:

* linux/net/rina/ -> only common headers in the main folder (could even go to /common/)
** linux/net/rina/utils/ -> General utilities (timers, queues, etc..)
** linux/net/rina/kuinterface/ -> Kernel/user-space interface related classes (Netlink, syscalls)
** linux/net/rina/kipcm/ -> KIPCM implementation
** linux/net/rina/kfa/ -> KFA implementation
** linux/net/rina/ipcp/ -> all the normal IPCP-related sources
** linux/net/rina/shims/ -> All Shim-related sources

**Comment by vmaffione** [comment]
I would close the issue, It is just a rearrangements. I'm not against it if someone volunteers to do it, but not important for now, I would say.

**Comment by edugrasa** [comment]
ok, closing for now, we have enough to do!
