### ISSUE TITLE
Replace LOG_MISSING in netlink code with a warning

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#574]
Right now it is flagged as an error, and logs to tty.

**Comment by sandervrijders** [comment]
@lbergesio Can you provide a PR?

**Comment by msune** [comment]
what is the exact line of this?

**Comment by dstaesse** [comment]
[   79.339457] rina-rnl-utils(ERR): Missing code in net/rina/rnl-utils.c:1395

**Comment by msune** [comment]
+1 then

This trace should be either removed or the "code missing" implemented. It makes no sense.

**Comment by lbergesio** [comment]
This one should be closed
