### ISSUE TITLE
pristine-1.3 Support for configuring RMT policies via DIF configuration

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#583]
There is some work started on that, but it needs to be completed. Includes:

* Support for RMT configuration in the config file (if configuration is not present defaults will be used)
* Update Netlink messages if necessary
* Update the RMT's kernel code to instantiate the requested policies

**Comment by sandervrijders** [comment]
@edugrasa What's the status of this? Maintainers: @miqueltarzan @lbergesio

**Comment by edugrasa** [comment]
This is already merged in pristine-1.3
