### ISSUE TITLE
pristine-1.3 Improve config file for defining DIFs

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#585]
Improvements:

* Define DIFs as templates in separate files, within the /dif-templates folder relative to the main configuration files.
* When defining a DIF in the config file we only need to fill in the DIF name and the template name (different DIFs can have the same template)
* DIF configurations only need to define the changes with respect to a basic template (included in dif-templates/default.dif)
* All DIF configurations can be updated while the IPCM is running (no need to reboot)

**Comment by sandervrijders** [comment]
I'd avoid "All DIF configurations can be updated while the IPCM is running (no need to reboot)". Better to just restart the IPCM (eventually a system daemon) imho.

**Comment by edugrasa** [comment]
Let the user choose what to do ;) If you want to restart the IPCM do it, otherwise now you'll have an option.

**Comment by sandervrijders** [comment]
Wait, are you talking about watching the files with inotify to reload them upon save? Or I may be misunderstanding what you are proposing.

**Comment by edugrasa** [comment]
Yeap, so after changing a file you could create a DIF with a new configuration (without affecting the DIFs already instantiated, of course).

**Comment by sandervrijders** [comment]
Ok, that sounds reasonable. However, changing DIF description files of already instantiated DIFs (IPCPs in the system that have already joined that DIF) seems dangerous.

**Comment by edugrasa** [comment]
Yes, I'm just talking about the DIF config *templates* (which are used to create new DIFs).

Existing DIFs will already have its own configurations, to be updated via the Manager when needed.
