### ISSUE TITLE
pristine1-3: Move common functionality of the default policy sets to the the stack internals so that common policies can be reutilized

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#588]
In order to allow custom policy sets to take advantange of common policies of the default policy set without having to copy-pase or reimplement the code, the common functions will be moved to a <component-ps-common>.c file exporting them. Custom policy sets will only have to wrap these functions. This is a workaround before changing the granularity of the policy set.

**Comment by sandervrijders** [comment]
@lbergesio This was not discussed on the ML AFAIK... Please send an e-mail explaining this, so we can discuss it.

**Comment by lbergesio** [comment]
This was discussed and agreed in the dev chat (skype) with @vmaffione. It is already developed and merged. So, I would close this issue, and discuss if this "common" functionalities make sense or not. I have found at least a couple of cases where it was useful to me, but it will not be useful most of of the times you need to use a custom data model for your PS. If you think we need to rollback this it may be good to start a ML discussion about it.
