### ISSUE TITLE
pristine-1.3: Allow IPC Manager in java bindings.

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#589]
Needs an additional header include in swig.

**Comment by sandervrijders** [comment]
@edugrasa Can you have a look at this issue?

@mcrotty Can you provide more context?

**Comment by mcrotty** [comment]
IPCManager and IPCManagerSingleton (java classes) are missing in generated API.

**Comment by edugrasa** [comment]
Closing, this should already be available in the latest pristine-1.4.
