### ISSUE TITLE
pristine1.3: Implement policy set for programmable congestion control

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#591]
Implement the custom policy set according to https://wiki.ict-pristine.eu/wp3/d32/D32-ProgrammableCC for programmable congestion control

**Comment by edugrasa** [comment]
@lbergesio I think that this can be closed now?

**Comment by lbergesio** [comment]
We have something similar to what is described in the wiki. We need to discuss with UiO but I would close this issue anyway.
