### ISSUE TITLE
Bug in EFCP/KFA destruction

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#593]
In last implementation when the efcp is not destroyed until pending operations are finished. Nevertheless its state is changed to DEALLOCATED. If another PDU arrives to the EFCP in this state and the pending operations finally arrived to 0 the unbinding op of the ipcp on top is called. If this is a KFA a wake_up is called from interrupt context and it crashed.

The unbinding op of the KFA must defer this work in a workqueue to process the task in process context.

LOG:

[  164.361202] rina-efcp(DBG): EFCP connection destroy called
[  164.361222] rina-syscalls(DBG): Exiting SYSC_deallocate_port syscall body
[  164.399903] rina-dtcp(DBG): DTCP received FC (CPU: 1)
[  164.405965] rina-dtcp(DBG): SEQN: 60 N/Ack: 0 SndRWE: 1030087219 SndLWE: 0 RcvRWE: 50 RcvLWE: 0 newRWE: 1030087219 newLWE: 0 myRWE: 2496068818 myLWE: 0
[  164.425841] rina-kfa(CRIT): Do not call kfa_flow_deallocate in IRQ context
[  164.443130] ------------[ cut here ]------------
[  164.447086] kernel BUG at net/rina/kfa.c:198!
[  164.447086] invalid opcode: 0000 [#1] SMP 
[  164.447086] Modules linked in: shim_eth_vlan rinarp arp826 nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc rina_default_plugin shim_tcp_udp normal_ipcp rina_personality_default 8021q garp stp llc psmouse i2c_piix4 serio_raw pcspkr hid_generic usbmouse usbhid hid floppy
[  164.447086] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 3.15.0 #56
[  164.447086] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[  164.447086] task: f5bb8e40 ti: f5be6000 task.ti: f5be6000
[  164.447086] EIP: 0060:[<f81afff7>] EFLAGS: 00210296 CPU: 1
[  164.447086] EIP is at kfa_flow_deallocate+0x157/0x170 [rina_personality_default]
[  164.447086] EAX: 0000003e EBX: dd288270 ECX: 00001808 EDX: 00200046
[  164.447086] ESI: 00000000 EDI: 00000002 EBP: f5407dec ESP: f5407dd4
[  164.447086]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[  164.447086] CR0: 8005003b CR2: b22fcdb0 CR3: 1d86d000 CR4: 000006d0
[  164.447086] Stack:
[  164.447086]  f81badc0 f81b5887 c15e5c4d dd288270 00000000 eb4a2aa4 f5407e0c f81abf2c
[  164.447086]  002002c4 00200282 3d65e229 dd288270 00000000 eb4a2aa4 f5407e30 f81aca96
[  164.447086]  00000000 f5407e24 00200202 00000000 f4f0e730 00000000 f0b5e660 f5407e68
[  164.447086] Call Trace:
[  164.447086]  [<c15e5c4d>] ? pdu_destroy+0x2d/0x40
[  164.447086]  [<f81abf2c>] efcp_destroy+0x2c/0x120 [rina_personality_default]
[  164.447086]  [<f81aca96>] efcp_container_receive+0xf6/0x220 [rina_personality_default]
[  164.447086]  [<f81aeffa>] rmt_receive+0x22a/0x3f0 [rina_personality_default]
[  164.447086]  [<f805d38a>] normal_sdu_enqueue+0x1a/0x40 [normal_ipcp]
[  164.447086]  [<f805d370>] ? normal_mgmt_sdu_write+0x160/0x160 [normal_ipcp]
[  164.447086]  [<f80b15e1>] eth_vlan_rcv+0x401/0x440 [shim_eth_vlan]
[  164.447086]  [<c1510503>] __netif_receive_skb_core+0x4c3/0x650
[  164.447086]  [<c15106ad>] __netif_receive_skb+0x1d/0x60
[  164.447086]  [<c151083f>] netif_receive_skb_internal+0x1f/0x80
[  164.447086]  [<c13885c2>] ? virtqueue_get_buf+0x62/0x100
[  164.447086]  [<c15108b8>] netif_receive_skb+0x18/0x50
[  164.447086]  [<c1450465>] virtnet_poll+0x3f5/0x6b0
[  164.447086]  [<c114d156>] ? kmem_cache_free+0xf6/0x160
[  164.447086]  [<c1510e15>] net_rx_action+0x105/0x1d0
[  164.447086]  [<c10469b3>] __do_softirq+0xc3/0x230
[  164.447086]  [<c10468f0>] ? perf_trace_softirq+0xd0/0xd0
[  164.447086]  [<c1003f59>] do_softirq_own_stack+0x29/0x40
[  164.447086]  <IRQ> 
[  164.447086]  [<c1046d15>] irq_exit+0x95/0xa0
[  164.447086]  [<c160743b>] do_IRQ+0x4b/0xe0
[  164.447086]  [<c160730c>] common_interrupt+0x2c/0x34
[  164.447086]  [<c1009cb9>] ? default_idle+0x19/0xa0
[  164.447086]  [<c100a3ae>] arch_cpu_idle+0xe/0x10
[  164.447086]  [<c107ed7a>] cpu_startup_entry+0x1ca/0x330
[  164.447086]  [<c10a59fa>] ? clockevents_register_device+0xaa/0x100
[  164.447086]  [<c102cf7b>] ? setup_APIC_timer+0xab/0x130
[  164.447086]  [<c102bad4>] start_secondary+0x184/0x210

**Comment by miqueltarzan** [comment]
ACK: tested for concurrent flows.
