### ISSUE TITLE
Possible memory leak in rmt-ps-default

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#608]
Branch: integration-1.2

The default rmt-ps, during port creation operations, does not correctly releases the reserved resources in case of error. Before linux/net/rina/rmt-ps-default.c, line 104, "return -1" command it shall be inserted a rmt_qgroup_destroy() order of the previously created queue group.

This shall be enough to fix it.

**Comment by lbergesio** [comment]
Since it is not a blocking bug it will be fixed in pristine-1.3 since the buggy code has been moved to a different file.

**Comment by sandervrijders** [comment]
@lbergesio This has been fixed or not?

**Comment by lbergesio** [comment]
yes, can be closed
