### ISSUE TITLE
Bug when creating an efcp connection

### ISSUE THREAD

**Issue by bernatgaston** [IRATI/stack#612]
There is a bug when you try to create an efcp connection at app level, local flows.

May 25 14:38:12 irati-vm-bernat kernel: [   84.160624] rina-syscalls(DBG): Handling personality hook deallocate_port
May 25 14:38:12 irati-vm-bernat kernel: [   84.167817] rina-syscalls(DBG): Calling personality hook deallocate_port
May 25 14:38:12 irati-vm-bernat kernel: [   84.171920] rina-personality-default(DBG): Calling wrapped function
May 25 14:38:12 irati-vm-bernat kernel: [   84.176877] rina-kfa(DBG): Destroying kfa flow now...
May 25 14:38:13 irati-vm-bernat kernel: [   84.180865] rina-kfa(DBG): We are destroying flow 1
May 25 14:38:13 irati-vm-bernat kernel: [   84.180865] rina-kfa(WARN): Instance f0bd5100 SDU-ready FIFO is NULL
May 25 14:38:13 irati-vm-bernat kernel: [   84.180865] rina-pidm(DBG): Bitmap release completed successfully (port_id: 1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.619440] rina-ipcp-utils(DBG): Name at f0e45980 finalized successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.623893] rina-syscalls(DBG): Handling personality hook allocate_port
May 25 14:38:13 irati-vm-bernat kernel: [   84.628516] rina-syscalls(DBG): Calling personality hook allocate_port
May 25 14:38:13 irati-vm-bernat kernel: [   84.632617] rina-personality-default(DBG): Calling wrapped function
May 25 14:38:13 irati-vm-bernat kernel: [   84.636834] rina-pidm(DBG): The pidm bitmap find returned id 0 (bad = -1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.640483] rina-pidm(DBG): Bitmap allocation completed successfully (id = 0)
May 25 14:38:13 irati-vm-bernat kernel: [   84.644418] rina-kfa(DBG): Flow pre-bound to port-id 1
May 25 14:38:13 irati-vm-bernat kernel: [   84.647802] rina-ipcp-utils(DBG): Name at f0e45980 finalized successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.651793] rina-ipcp-utils(DBG): Name at f0e45980 destroyed successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.655859] rina-rnl(DBG): Dispatching message (skb-in=f03ec600, info=c2285b44, attrs=c2045b20)
May 25 14:38:13 irati-vm-bernat kernel: [   84.662606] rina-rnl(DBG): Multiplexing message type 29
May 25 14:38:13 irati-vm-bernat kernel: [   84.666137] rina-rnl(DBG): Fetching handler callback and data
May 25 14:38:13 irati-vm-bernat kernel: [   84.669577] rina-rnl(DBG): Gonna call f8f9df20(f01d6040, f03ec600, c2285b44)
May 25 14:38:13 irati-vm-bernat kernel: [   84.674338] rina-rnl-utils(DBG): RINA Netlink parser started ...
May 25 14:38:13 irati-vm-bernat kernel: [   84.680204] rina-rnl-utils(DBG): msg at f03bfbc0 / msg->attrs at ef085f40
May 25 14:38:13 irati-vm-bernat kernel: [   84.684402] rina-rnl-utils(DBG):   src-ipc-id: 3
May 25 14:38:13 irati-vm-bernat kernel: [   84.687470] rina-rnl-utils(DBG):   dst-ipc-id: 3
May 25 14:38:13 irati-vm-bernat kernel: [   84.690561] rina-efcp(DBG): Instance ef085ec0 initialized successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.696136] rina-cidm(DBG): The cidm bitmap find returned id 0 (bad = -1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.702185] rina-cidm(DBG): Bits in bitmap 2048
May 25 14:38:13 irati-vm-bernat kernel: [   84.705042] rina-cidm(DBG): Bitmap allocation completed successfully (id = 0)
May 25 14:38:13 irati-vm-bernat kernel: [   84.709639] rina-rtimer(DBG): Timer f03bff00 created
May 25 14:38:13 irati-vm-bernat kernel: [   84.712842] rina-rtimer(DBG): Timer f03bf840 created
May 25 14:38:13 irati-vm-bernat kernel: [   84.717690] rina-rtimer(DBG): Timer f03bf3c0 created
May 25 14:38:13 irati-vm-bernat kernel: [   84.721390] rina-dtp-ps-common(DBG): initial_seq_number reset
May 25 14:38:13 irati-vm-bernat kernel: [   84.725230] rina-dtp(DBG): Instance f03bfcc0 created successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.729038] rina-dtcp(DBG): DTCP SV initialized with dtcp_conf:
May 25 14:38:13 irati-vm-bernat kernel: [   84.733128] rina-dtcp(DBG):   data_retransmit_max: 0
May 25 14:38:13 irati-vm-bernat kernel: [   84.737606] rina-dtcp(DBG):   sndr_credit:         50
May 25 14:38:13 irati-vm-bernat kernel: [   84.741598] rina-dtcp(DBG):   snd_rt_wind_edge:    3727426053
May 25 14:38:13 irati-vm-bernat kernel: [   84.744978] rina-dtcp(DBG):   rcvr_credit:         50
May 25 14:38:13 irati-vm-bernat kernel: [   84.748235] rina-dtcp(DBG):   rcvr_rt_wind_edge:   50
May 25 14:38:13 irati-vm-bernat kernel: [   84.751806] rina-dtcp(DBG): Instance f03bfac0 created successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.756034] rina-efcp(DBG): DT SV initialized with:
May 25 14:38:13 irati-vm-bernat kernel: [   84.760571] rina-efcp(DBG):   MFPS: 10000, MFSS: 10000
May 25 14:38:13 irati-vm-bernat kernel: [   84.763821] rina-efcp(DBG):   A: 300, R: 0, TR: 0
May 25 14:38:13 irati-vm-bernat kernel: [   84.767106] rina-efcp(DBG): Connection created (Source address 16,Destination address 16, Destination cep-id -1, Source cep-id 0)
May 25 14:38:13 irati-vm-bernat kernel: [   84.774432] rina-rnl-utils(DBG): Result of genlmesg_end: 40
May 25 14:38:13 irati-vm-bernat kernel: [   84.777617] rina-rnl-utils(DBG): Going to send NL unicast message (type = 30, seq-num 1432557486, port = 3302)
May 25 14:38:13 irati-vm-bernat kernel: [   84.783559] rina-rnl-utils(DBG): Unicast NL message sent (type = 30, seq-num 1432557486, port = 3302)
May 25 14:38:13 irati-vm-bernat kernel: [   84.788587] rina-rnl(DBG): Message 29 handled successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.793571] rina-ipcp-utils(DBG): Name at f0e45ae0 finalized successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.797719] rina-syscalls(DBG): Handling personality hook allocate_port
May 25 14:38:13 irati-vm-bernat kernel: [   84.801731] rina-syscalls(DBG): Calling personality hook allocate_port
May 25 14:38:13 irati-vm-bernat kernel: [   84.805641] rina-personality-default(DBG): Calling wrapped function
May 25 14:38:13 irati-vm-bernat kernel: [   84.811194] rina-pidm(DBG): The pidm bitmap find returned id 1 (bad = -1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.814999] rina-pidm(DBG): Bitmap allocation completed successfully (id = 1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.819697] rina-kfa(DBG): Flow pre-bound to port-id 2
May 25 14:38:13 irati-vm-bernat kernel: [   84.823198] rina-ipcp-utils(DBG): Name at f0e45ae0 finalized successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.827002] rina-ipcp-utils(DBG): Name at f0e45ae0 destroyed successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.834073] rina-rnl(DBG): Dispatching message (skb-in=f03ecd80, info=c2285b44, attrs=c2045b20)
May 25 14:38:13 irati-vm-bernat kernel: [   84.839023] rina-rnl(DBG): Multiplexing message type 31
May 25 14:38:13 irati-vm-bernat kernel: [   84.842700] rina-rnl(DBG): Fetching handler callback and data
May 25 14:38:13 irati-vm-bernat kernel: [   84.846394] rina-rnl(DBG): Gonna call f8f9dd50(f01d6040, f03ecd80, c2285b44)
May 25 14:38:13 irati-vm-bernat kernel: [   84.851096] rina-rnl-utils(DBG): RINA Netlink parser started ...
May 25 14:38:13 irati-vm-bernat kernel: [   84.855707] rina-rnl-utils(DBG): msg at f03bf180 / msg->attrs at ef085f40
May 25 14:38:13 irati-vm-bernat kernel: [   84.859414] rina-rnl-utils(DBG):   src-ipc-id: 3
May 25 14:38:13 irati-vm-bernat kernel: [   84.862644] rina-rnl-utils(DBG):   dst-ipc-id: 3
May 25 14:38:13 irati-vm-bernat kernel: [   84.865631] rina-efcp(DBG): Instance ef085bc0 initialized successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.871006] rina-cidm(DBG): The cidm bitmap find returned id 1 (bad = -1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.874743] rina-cidm(DBG): Bits in bitmap 2048
May 25 14:38:13 irati-vm-bernat kernel: [   84.877859] rina-cidm(DBG): Bitmap allocation completed successfully (id = 1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.881682] rina-rtimer(DBG): Timer f03bf8c0 created
May 25 14:38:13 irati-vm-bernat kernel: [   84.885981] rina-rtimer(DBG): Timer f03bfe80 created
May 25 14:38:13 irati-vm-bernat kernel: [   84.889663] rina-rtimer(DBG): Timer f02fe440 created
May 25 14:38:13 irati-vm-bernat kernel: [   84.892867] rina-dtp-ps-common(DBG): initial_seq_number reset
May 25 14:38:13 irati-vm-bernat kernel: [   84.897067] rina-dtp(DBG): Instance f03bf600 created successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.901420] rina-dtcp(DBG): DTCP SV initialized with dtcp_conf:
May 25 14:38:13 irati-vm-bernat kernel: [   84.906917] rina-dtcp(DBG):   data_retransmit_max: 0
May 25 14:38:13 irati-vm-bernat kernel: [   84.910037] rina-dtcp(DBG):   sndr_credit:         50
May 25 14:38:13 irati-vm-bernat kernel: [   84.913348] rina-dtcp(DBG):   snd_rt_wind_edge:    2735209132
May 25 14:38:13 irati-vm-bernat kernel: [   84.917564] rina-dtcp(DBG):   rcvr_credit:         50
May 25 14:38:13 irati-vm-bernat kernel: [   84.921386] rina-dtcp(DBG):   rcvr_rt_wind_edge:   50
May 25 14:38:13 irati-vm-bernat kernel: [   84.924667] rina-dtcp(DBG): Instance f02fe6c0 created successfully
May 25 14:38:13 irati-vm-bernat kernel: [   84.929045] rina-efcp(DBG): DT SV initialized with:
May 25 14:38:13 irati-vm-bernat kernel: [   84.934399] rina-efcp(DBG):   MFPS: 10000, MFSS: 10000
May 25 14:38:13 irati-vm-bernat kernel: [   84.937838] rina-efcp(DBG):   A: 300, R: 0, TR: 0
May 25 14:38:13 irati-vm-bernat kernel: [   84.943431] rina-efcp(DBG): Connection created (Source address 16,Destination address 16, Destination cep-id 0, Source cep-id 1)
May 25 14:38:13 irati-vm-bernat kernel: [   84.950089] rina-normal-ipc(DBG): Cep_id allocated for the arrived connection request: 1
May 25 14:38:13 irati-vm-bernat kernel: [   84.955999] BUG: sleeping function called from invalid context at kernel/locking/mutex.c:103
May 25 14:38:13 irati-vm-bernat kernel: [   84.963225] in_atomic(): 1, irqs_disabled(): 0, pid: 3302, name: ipcp
May 25 14:38:13 irati-vm-bernat kernel: [   84.967763] CPU: 0 PID: 3302 Comm: ipcp Not tainted 3.15.0 #23
May 25 14:38:13 irati-vm-bernat kernel: [   84.971244] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
May 25 14:38:13 irati-vm-bernat kernel: [   84.974959]  00000000 00000000 c2285a24 c1604eaf 00000ce6 c2285a44 c1068df7 c17d69d4
May 25 14:38:13 irati-vm-bernat kernel: [   84.986913]  00000001 00000000 00000ce6 c2255528 f01d6040 c2285a54 c160d924 f01d6040
May 25 14:38:13 irati-vm-bernat kernel: [   84.995902]  ef085be0 c2285a70 f8f9c56e c15f058f 00000000 ef085c40 ef085be0 00000002
May 25 14:38:13 irati-vm-bernat kernel: [   85.004821] Call Trace:
May 25 14:38:13 irati-vm-bernat kernel: [   85.008088]  [<c1604eaf>] dump_stack+0x48/0x60
May 25 14:38:13 irati-vm-bernat kernel: [   85.011260]  [<c1068df7>] __might_sleep+0xc7/0x100
May 25 14:38:13 irati-vm-bernat kernel: [   85.015507]  [<c160d924>] mutex_lock+0x24/0x48
May 25 14:38:13 irati-vm-bernat kernel: [   85.018241]  [<f8f9c56e>] kipcm_find_ipcp+0x1e/0x60 [rina_personality_default]
May 25 14:38:13 irati-vm-bernat kernel: [   85.024227]  [<c15f058f>] ? rkzalloc+0x1f/0x60
May 25 14:38:13 irati-vm-bernat kernel: [   85.027146]  [<f813e5a3>] connection_create_arrived+0x113/0x210 [normal_ipcp]
May 25 14:38:13 irati-vm-bernat kernel: [   85.030992]  [<f8f9de89>] notify_ipcp_conn_create_arrived+0x139/0x1d0 [rina_personality_default]
May 25 14:38:13 irati-vm-bernat kernel: [   85.036917]  [<f8f9dd50>] ? notify_ipcp_conn_update_req+0x170/0x170 [rina_personality_default]
May 25 14:38:13 irati-vm-bernat kernel: [   85.047639]  [<c15f5317>] dispatcher+0x127/0x1a0
May 25 14:38:13 irati-vm-bernat kernel: [   85.050553]  [<f8f9dd50>] ? notify_ipcp_conn_update_req+0x170/0x170 [rina_personality_default]
May 25 14:38:13 irati-vm-bernat kernel: [   85.056005]  [<f8f9dd50>] ? notify_ipcp_conn_update_req+0x170/0x170 [rina_personality_default]
May 25 14:38:13 irati-vm-bernat kernel: [   85.061080]  [<c15471b9>] genl_rcv_msg+0x209/0x380
May 25 14:38:13 irati-vm-bernat kernel: [   85.064832]  [<c1546fb0>] ? genl_lock+0x20/0x20
May 25 14:38:13 irati-vm-bernat kernel: [   85.069110]  [<c1546b76>] netlink_rcv_skb+0x86/0xa0
May 25 14:38:13 irati-vm-bernat kernel: [   85.073050]  [<c1546d51>] genl_rcv+0x21/0x30
May 25 14:38:13 irati-vm-bernat kernel: [   85.076730]  [<c15464e5>] netlink_unicast+0x165/0x1c0
May 25 14:38:13 irati-vm-bernat kernel: [   85.080286]  [<c154678f>] netlink_sendmsg+0x24f/0x3f0
May 25 14:38:13 irati-vm-bernat kernel: [   85.083685]  [<c15088e5>] sock_sendmsg+0x85/0xc0
May 25 14:38:13 irati-vm-bernat kernel: [   85.086752]  [<c12f771c>] ? _copy_from_user+0x5c/0x70
May 25 14:38:13 irati-vm-bernat kernel: [   85.089858]  [<c1514b90>] ? verify_iovec+0x50/0xc0
May 25 14:38:13 irati-vm-bernat kernel: [   85.093007]  [<c1508b92>] ___sys_sendmsg.part.16+0x272/0x280
May 25 14:38:13 irati-vm-bernat kernel: [   85.098316]  [<c1075f70>] ? update_curr+0xb0/0x210
May 25 14:38:13 irati-vm-bernat kernel: [   85.101904]  [<c1075f70>] ? update_curr+0xb0/0x210
May 25 14:38:13 irati-vm-bernat kernel: [   85.105051]  [<c10732b0>] ? __enqueue_entity+0x70/0x80
May 25 14:38:13 irati-vm-bernat kernel: [   85.108487]  [<c12f771c>] ? _copy_from_user+0x5c/0x70
May 25 14:38:13 irati-vm-bernat kernel: [   85.111582]  [<c150988a>] __sys_sendmsg+0x4a/0x80
May 25 14:38:13 irati-vm-bernat kernel: [   85.114291]  [<c150a254>] SYSC_socketcall+0x5d4/0x950
May 25 14:38:13 irati-vm-bernat kernel: [   85.118027]  [<c106f97b>] ? try_to_wake_up+0x19b/0x240
May 25 14:38:13 irati-vm-bernat kernel: [   85.121803]  [<c106fa7f>] ? wake_up_process+0x1f/0x40
May 25 14:38:13 irati-vm-bernat kernel: [   85.125914]  [<c1075ffb>] ? update_curr+0x13b/0x210
May 25 14:38:13 irati-vm-bernat kernel: [   85.129208]  [<c105a14b>] ? __queue_work+0xfb/0x2e0
May 25 14:38:13 irati-vm-bernat kernel: [   85.132404]  [<c105a14b>] ? __queue_work+0xfb/0x2e0
May 25 14:38:13 irati-vm-bernat kernel: [   85.135524]  [<c10732b0>] ? __enqueue_entity+0x70/0x80
May 25 14:38:13 irati-vm-bernat kernel: [   85.139059]  [<c1077c64>] ? put_prev_entity+0xc4/0x400
May 25 14:38:13 irati-vm-bernat kernel: [   85.142304]  [<c1073225>] ? __dequeue_entity+0x25/0x40
May 25 14:38:13 irati-vm-bernat kernel: [   85.145506]  [<c1074b06>] ? set_next_entity+0xa6/0xc0
May 25 14:38:13 irati-vm-bernat kernel: [   85.149349]  [<c107af4f>] ? pick_next_task_fair+0x41f/0x4a0
May 25 14:38:13 irati-vm-bernat kernel: [   85.153777]  [<c160c4b4>] ? __schedule+0x324/0x790
May 25 14:38:13 irati-vm-bernat kernel: [   85.157175]  [<c115ee24>] ? vfs_write+0x144/0x1b0
May 25 14:38:13 irati-vm-bernat kernel: [   85.160279]  [<c115f227>] ? SyS_write+0x77/0x90
May 25 14:38:13 irati-vm-bernat kernel: [   85.163023]  [<c150a6a3>] SyS_socketcall+0x13/0x20
May 25 14:38:13 irati-vm-bernat kernel: [   85.166509]  [<c161738c>] sysenter_do_call+0x12/0x22

**Comment by lbergesio** [comment]
This issue can be closed
