### ISSUE TITLE
pristine-1.2: Wrong plugindir used in ipcp

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#613]
An error like is seen in the ipcp log file:

1009(1432652527)#plugin-info (ERR): Failed to open manifest file for plugin default
1009(1432652527)#librina.application (ERR): Failed to load manifest for plugin default
1009(1432652527)#ipcp[2] (ERR): Got unhandled exception (Failed to load default plugin)

**Comment by bernatgaston** [comment]
Did you load the default pluguins mod? seems that you don't have it loaded

**Comment by mcrotty** [comment]
lsmod says I do.  There is a "bug" in the way the pluginsdir is configured. Its set at configure time (with a define to the compiler) and not at runtime. 
So if any part of the lib path changes at runtime -> no plugins are loaded (affects IPCM and IPCP).

**Comment by sandervrijders** [comment]
Should be fixed by the plugins catalog. @vmaffione Can you confirm?

**Comment by vmaffione** [comment]
I've never seen this error. Certainly the catalog patch improves the situation, but there is not enough information to understand what is happening here.
