### ISSUE TITLE
kernel bug when killing IPCM (2)

### ISSUE THREAD

**Issue by bernatgaston** [IRATI/stack#618]
When an app has been killed (ctrl+c) and then the IPCM is killed (ctrl+C) it gets stuck in an infit loop. At the begining there is a kernel bug, I think that this is the problem

[  966.373859] rina-kfa(DBG): Queue-ready check called
[  966.376931] rina-kfa(DBG): Read woken up (-512)
[  966.379593] rina-kfa(DBG): Wait-event interrupted (-512)
[  966.383359] rina-kfa(DBG): A signal is pending
[  966.386534] rina-kfa(DBG): Finishing (read)
[  966.389165] rina-kipcm(DBG): Failed to read sdu
[  966.391537] rina-syscalls(DBG): Personality returned value -1
[  966.396570] rina-syscalls(DBG): Exiting SYSC_sdu_read syscall body
[  970.574219] rina-syscalls(DBG): Entered SYSC_ipc_destroy syscall body
[  970.578191] rina-syscalls(DBG): Handling personality hook ipc_destroy
[  970.581780] rina-syscalls(DBG): Calling personality hook ipc_destroy
[  970.585155] rina-personality-default(DBG): Calling wrapped function
[  970.591621] rina-kipcm(DBG): KIPCM instance f08d9e00 locking ...
[  970.607104] rina-kipcm(DBG): KIPCM instance f08d9e00 locked
[  970.611393] rina-shim-eth-vlan(DBG): Looking for the eth-vlan-instance to destroy
[  970.628063] rina-ipcp-utils(DBG): Name at ef519f70 finalized successfully
[  970.631443] rina-ipcp-utils(DBG): Name at ef519f70 destroyed successfully
[  970.634809] rina-ipcp-utils(DBG): Name at ef519fd0 finalized successfully
[  970.640345] rina-ipcp-utils(DBG): Name at ef519fd0 destroyed successfully
[  970.651173] rina-ipcp-utils(DBG): Name at f080e080 finalized successfully
[  970.655206] rina-ipcp-utils(DBG): Name at f080e080 destroyed successfully
[  970.669184] rina-shim-eth-vlan(DBG): removing mapping from list
[  970.679217] rina-shim-eth-vlan(DBG): Eth-vlan instance destroyed, returning
[  970.689291] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocking ...
[  970.700196] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocked
[  970.714554] rina-syscalls(DBG): Exiting SYSC_ipc_destroy syscall body
[  970.722039] rina-syscalls(DBG): Entered SYSC_ipc_destroy syscall body
[  970.727166] rina-syscalls(DBG): Handling personality hook ipc_destroy
[  970.733251] rina-syscalls(DBG): Calling personality hook ipc_destroy
[  970.741454] rina-personality-default(DBG): Calling wrapped function
[  970.745296] rina-kipcm(DBG): KIPCM instance f08d9e00 locking ...
[  970.750635] rina-kipcm(DBG): KIPCM instance f08d9e00 locked
[  970.754068] rina-shim-eth-vlan(DBG): Looking for the eth-vlan-instance to destroy
[  970.758240] rina-ipcp-utils(DBG): Name at ef519f90 finalized successfully
[  970.761766] rina-ipcp-utils(DBG): Name at ef519f90 destroyed successfully
[  970.775512] rina-ipcp-utils(DBG): Name at ef519cd0 finalized successfully
[  970.783850] rina-ipcp-utils(DBG): Name at ef519cd0 destroyed successfully
[  970.790974] rina-ipcp-utils(DBG): Name at f569cbc0 finalized successfully
[  970.798219] rina-ipcp-utils(DBG): Name at f569cbc0 destroyed successfully
[  970.806172] rina-shim-eth-vlan(DBG): removing mapping from list
[  970.812595] rina-shim-eth-vlan(DBG): Eth-vlan instance destroyed, returning
[  970.824707] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocking ...
[  970.836989] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocked
[  970.844991] rina-syscalls(DBG): Exiting SYSC_ipc_destroy syscall body
[  970.855257] rina-syscalls(DBG): Entered SYSC_ipc_destroy syscall body
[  970.861333] rina-syscalls(DBG): Handling personality hook ipc_destroy
[  970.869092] rina-syscalls(DBG): Calling personality hook ipc_destroy
[  970.877098] rina-personality-default(DBG): Calling wrapped function
[  970.888125] rina-kipcm(DBG): KIPCM instance f08d9e00 locking ...
[  970.899580] rina-kipcm(DBG): KIPCM instance f08d9e00 locked
[  970.910799] rina-efcp(DBG): EFCP connection destroy called
[  970.914772] rina-kfa(DBG): Destroying kfa flow now...
[  970.914772] rina-kfa(DBG): We are destroying flow 2
[  970.914772] rina-rfifo(DBG): FIFO f4c7b6f0 destroyed successfully
[  970.914772] rina-pidm(DBG): Bitmap release completed successfully (port_id: 2)
[  970.914772] rina-rtimer(DBG): Timer f2dc1800 is not pending, can't stop it
[  970.914772] rina-rtimer(DBG): Timer f2dc1800 destroyed
[  970.914772] rina-rtimer(DBG): Timer f2dc1440 stopped
[  970.914772] rina-rtimer(DBG): Timer f2dc1440 destroyed
[  970.914772] rina-rtimer(DBG): Timer f2dc1600 stopped
[  970.914772] rina-rtimer(DBG): Timer f2dc1600 destroyed
[  970.914772] BUG: sleeping function called from invalid context at kernel/locking/mutex.c:103
[  970.914772] in_atomic(): 1, irqs_disabled(): 1, pid: 3357, name: ipcm
[  970.914772] CPU: 0 PID: 3357 Comm: ipcm Not tainted 3.15.0 #27
[  970.914772] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[  970.914772]  00000000 00000000 c235fe88 c160512f 00000d1d c235fea8 c1068df7 c17d6ad8
[  970.914772]  00000001 00000001 00000d1d f2df7048 f2dc1f90 c235feb8 c160dba4 f2dc1f88
[  970.914772]  f2dc1f90 c235fec8 f8f9d82d f2dc1f80 f4c7b3e0 c235fedc f8f93786 f0b07860
[  970.914772] Call Trace:
[  970.914772]  [<c160512f>] dump_stack+0x48/0x60
[  970.914772]  [<c1068df7>] __might_sleep+0xc7/0x100
[  970.914772]  [<c160dba4>] mutex_lock+0x24/0x48
[  970.914772]  [<f8f9d82d>] rina_component_fini+0x1d/0x60 [rina_personality_default]
[  970.914772]  [<f8f93786>] dtp_destroy+0x56/0x90 [rina_personality_default]
[  970.914772]  [<f8f94a80>] efcp_destroy+0x70/0x110 [rina_personality_default]
[  970.914772]  [<f8f953af>] efcp_connection_destroy+0x7f/0x130 [rina_personality_default]
[  970.914772]  [<f814aac1>] remove_all_cepid.isra.0+0x31/0x70 [normal_ipcp]
[  970.914772]  [<f814af53>] normal_destroy+0xa3/0x1c0 [normal_ipcp]
[  970.914772]  [<f8f9ca5b>] kipcm_ipcp_destroy+0x9b/0x120 [rina_personality_default]
[  970.914772]  [<f8f9d223>] default_ipc_destroy+0x43/0x50 [rina_personality_default]
[  970.914772]  [<c15fa0c9>] SyS_ipc_destroy+0x99/0xc0
[  970.914772]  [<c161760c>] sysenter_do_call+0x12/0x22
[  970.914772] rina-dtp(DBG): Instance f2dc1f80 destroyed successfully
[  970.914772] rina-rtimer(DBG): Timer f2dc1100 is not pending, can't stop it
[  970.914772] rina-rtimer(DBG): Timer f2dc1100 destroyed
[  970.914772] rina-dtcp(DBG): Instance f2dc1700 destroyed successfully
[  970.914772] rina-dt(DBG): Instance f0b07840 destroyed successfully
[  970.914772] rina-cidm(DBG): Bitmap release completed successfully
[  970.914772] rina-efcp(DBG): EFCP instance f0b07860 finalized successfully
[  970.914772] rina-efcp(DBG): EFCP connection destroy called
[  970.914772] rina-kfa(DBG): Destroying kfa flow now...
[  970.914772] rina-kfa(DBG): We are destroying flow 1
[  970.914772] rina-rfifo(DBG): FIFO f0a0e698 destroyed successfully
[  970.914772] rina-pidm(DBG): Bitmap release completed successfully (port_id: 1)
[  970.914772] rina-rtimer(DBG): Timer f2dc1840 is not pending, can't stop it
[  970.914772] rina-rtimer(DBG): Timer f2dc1840 destroyed
[  970.914772] rina-rtimer(DBG): Timer f2dc1640 stopped
[  970.914772] rina-rtimer(DBG): Timer f2dc1640 destroyed
[  970.914772] rina-rtimer(DBG): Timer f2dc1c80 stopped
[  970.914772] rina-rtimer(DBG): Timer f2dc1c80 destroyed
[  970.914772] rina-dtp(DBG): Instance ef5c3ec0 destroyed successfully
[  970.914772] rina-rtimer(DBG): Timer f2dc1b00 is not pending, can't stop it
[  970.914772] rina-rtimer(DBG): Timer f2dc1b00 destroyed
[  970.914772] rina-dtcp(DBG): Instance f2dc1a80 destroyed successfully
[  970.914772] rina-dt(DBG): Instance f0b076c0 destroyed successfully
[  970.914772] rina-cidm(DBG): Bitmap release completed successfully
[  970.914772] rina-efcp(DBG): EFCP instance f0b07c60 finalized successfully
[  971.126427] rina-ipcp-utils(DBG): Name at f569cb80 finalized successfully
[  971.129747] rina-ipcp-utils(DBG): Name at f569cb80 destroyed successfully
[  971.133358] rina-ipcp-utils(DBG): Name at ef519de0 finalized successfully
[  971.136869] rina-ipcp-utils(DBG): Name at ef519de0 destroyed successfully
[  971.140076] rina-rmt(DBG): PFT cache f1f3bd70 destroyed
[  971.143842] rina-rmt(DBG): Instance f1f3bd20 finalized successfully
[  971.147144] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocking ...
[  971.147157] rina-normal-ipc(DBG): Mgmt data destroyed, waitqueue return code 0
[  971.147159] rina-rfifo(DBG): FIFO f4c7b7b8 destroyed successfully
[  971.147161] rina-syscalls(DBG): Personality returned value -1
[  971.147162] rina-syscalls(DBG): Exiting SYSC_management_sdu_read syscall body
[  971.147247] rina-syscalls(DBG): Entered SYSC_management_sdu_read syscall body
[  971.147247] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.147248] rina-syscalls(DBG): Calling personality hook mgmt_sdu_read
[  971.147249] rina-personality-default(DBG): Calling wrapped function
[  971.147250] rina-kipcm(DBG): KIPCM instance f08d9e00 locking ...
[  971.182630] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocked
[  971.182745] rina-kipcm(DBG): KIPCM instance f08d9e00 locked
[  971.182747] rina-kipcm(ERR): Could not find IPC Process with id 3
[  971.182747] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocking ...
[  971.183123] rina-syscalls(DBG): Entered SYSC_management_sdu_read syscall body
[  971.186815] rina-personality-default(DBG): Calling wrapped function
[  971.188563] rina-syscalls(DBG): Entered SYSC_management_sdu_read syscall body
[  971.190019] rina-kipcm(DBG): KIPCM instance f08d9e00 locking ...
[  971.191190] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.192896] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.194275] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.195608] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.196982] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.198243] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.199540] rina-personality-default(DBG): Calling wrapped function
[  971.204554] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.208357] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.211457] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.214569] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.217761] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.221618] rina-syscalls(DBG): Exiting SYSC_management_sdu_read syscall body
[  971.225058] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.228174] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.231530] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.234888] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.238249] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.241445] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.244467] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.249329] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.252692] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.256119] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.259225] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.262251] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.265439] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.268964] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.280915] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.285189] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.288355] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.291759] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.295128] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.309955] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.322594] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.326180] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.329254] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.332254] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.335399] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.338643] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.341641] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.344539] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.347257] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.350499] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.355888] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.360205] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.363523] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.367736] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.371428] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.375173] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.378402] rina-syscalls(DBG): Entered SYSC_management_sdu_read syscall body
[  971.382273] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.385597] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.389475] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.393198] rina-kipcm(ERR): Could not find IPC Process with id 3
[  971.396512] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.401112] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.406544] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.410447] rina-syscalls(DBG): Calling personality hook mgmt_sdu_read
[  971.413576] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.417095] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.420912] rina-syscalls(DBG): Calling personality hook mgmt_sdu_read
[  971.424152] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.427448] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.430753] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.434892] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.438030] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.441459] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.445001] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.448236] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.451991] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.455149] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.458320] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.461713] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.465111] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.468248] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.471620] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.474850] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.479011] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.482404] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.489272] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.497840] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.509790] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.520119] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.523677] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.524744] rina-syscalls(DBG): Handling personality hook mgmt_sdu_read
[  971.524745] rina-syscalls(DBG): Calling personality hook mgmt_sdu_read
[  971.524745] rina-personality-default(DBG): Calling wrapped function
[  971.524746] rina-kipcm(DBG): KIPCM instance f08d9e00 locking ...
[  971.524746] rina-kipcm(DBG): KIPCM instance f08d9e00 locked
[  971.524746] rina-kipcm(ERR): Could not find IPC Process with id 3
[  971.524747] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocking ...
[  971.524747] rina-kipcm(DBG): KIPCM instance f08d9e00 unlocked

**Comment by msune** [comment]
I need more info.

**Comment by edugrasa** [comment]
Closing, not reproducible anymore (Bernat has no seen it anymore also)
