### ISSUE TITLE
Cherish/urgency multiplexing

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#659]
Cherish/urgency multiplexing

@miqueltarzan Can you provide some more detail about this feature?

**Comment by edugrasa** [comment]
Implementation of the delay-loss scheduler. Code is done, @miqueltarzan is debugging and testing. Should be closed (pull request to be issued) by the end of next week.

**Comment by edugrasa** [comment]
Initial implementation merged into pristine-1.3 and pristine-1.4.
