### ISSUE TITLE
Transmission control policy (rate-based flow control)

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#661]
Transmission control policy (rate-based flow control)

**Comment by edugrasa** [comment]
There is a working version, @kewinrausch will clean the code and issue a pull request in short

**Comment by edugrasa** [comment]
@kewinrausch can this issue be closed?

**Comment by kewinrausch** [comment]
Yes... completed and merged with 1.3 and so 1.4, so i guess this has been done :)
