### ISSUE TITLE
ipcm: Load a default config file

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#672]
Upon start, the ipcm requires a config file. Currently one always has to specify it:

```
   -c <string>,  --config <string>
     (required)  Configuration file to load
 ```

It would be handy for testing purposes to have it point to a default location, such as /etc/ipcmanager.conf, or $SANDBOXED_ENVIRONMENT/etc/ipcmanager.conf.

**Comment by msune** [comment]
+1

Happy to review patches in this direction
