### ISSUE TITLE
Memory corruption in the kernel space parts

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#676]
When testing PR #670, @vmaffione and myself stumbled upon a memory corruption problem not related to that PR. It seems it is present somewhere else, in the current pristine-1.3. Maybe even pristine-1.2? Refer to the PR for more explanation.

**Comment by edugrasa** [comment]
Have you got more information/conclusions after your investigations? In all our recent tests I have not seen any other symptoms of this problem (no kernel panics, errors, etc..) Did you see anything like this?
Also, what tests did you perform? Did you try to modify the pff policy set?

**Comment by sandervrijders** [comment]
Well, we've never seen it before either. I just performed enrollment between 2 nodes. Then I brought the interface down on one of the nodes, and then it happens. Maybe it's related to clean up of SDUs in the fast path? Since in-kernel packets are dropped once the interface is down.

**Comment by vmaffione** [comment]
We could try to see if the same problem happens with just one node - or
just not performing enrollment.

2015-07-09 21:33 GMT+02:00 Sander Vrijders <notifications@github.com>:

> Well, we've never seen it before either. I just performed enrollment
> between 2 nodes. Then I brought the interface down on one of the nodes, and
> then it happens. Maybe it's related to clean up of SDUs in the fast path?
> Since in-kernel packets are dropped once the interface is down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/676#issuecomment-120120826>.
>



-- 
Vincenzo Maffione

**Comment by sandervrijders** [comment]
Just tried it without enrollment, but then the normal-ipcp is not notified.

**Comment by vmaffione** [comment]
Yeah, because no flow is created to be used by the normal and supported by
the shim.

2015-07-09 23:12 GMT+02:00 Sander Vrijders <notifications@github.com>:

> Just tried it without enrollment, but then the normal-ipcp is not
> notified.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/676#issuecomment-120145472>.
>



-- 
Vincenzo Maffione

**Comment by edugrasa** [comment]
I could be wrong but I don't think it is related to clean-up of SDUs in the shim.. If the interface is down dev_queue_xmit will return -ENETDOWN, previously having destroyed the skb. The SDU is destroyed by the shim-eth-vlan before calling dev_queue_xmit.

**Comment by sandervrijders** [comment]
Yeah, it's just a hypothesis, but the point is that I don't observe it in the "normal" fast path.

**Comment by vmaffione** [comment]
Sometimes I also see the "rmt" pointer in the normal IPCP set to zero --> this smells like a bad memory corruption problem.

**Comment by sandervrijders** [comment]
Hmm, yeah, and that pointer is not used when sending/receiving SDUs IIRC. So probably that's why the problem surfaces just now

**Comment by edugrasa** [comment]
Yes, the RMT pointer in the normal IPCP is used when sending/receiving SDUs at least when N-ports are enabled/disabled due to EFCP closed windows. It is also used when flows are deallocated in the N-1 DIF. Maybe the error is due to some recent change? Otherwise it seems we should have seen crashes in the kernel.

**Comment by msune** [comment]
Try using git bisect to identify the offending commit, if that's the case

**Comment by edugrasa** [comment]
@sandervrijders what are the steps to reproduce this in pristine-1.3? Enrollment and bringing an interface down also?

**Comment by vmaffione** [comment]
@edugrasa It's not pristine-1.3, it's vmaffione/lfa (https://github.com/IRATI/stack/pull/670)
Yes, Enrollment and bringing an interface down is ok.

@msune: unfortunately it seems that my PR (one commit) introduces the bug, but I don't see how it can be (please have a look at that commit). It seems more that a 0-day bug is seldomly revealed by this commit (I wish I were wrong)
