### ISSUE TITLE
IPCM: get_dif_template() shall not return a pointer

### ISSUE THREAD

**Issue by msune** [IRATI/stack#677]
With the current `DIFTemplateManager::get_dif_template()` routine, the template manager exposes a pointer to the DIF template (internal pointer). Since the `DIFTemplateManager` exposes an API to remove templates, the pointer may not be valid once used. APIs like assignToDIF make use of these of pointers too.

The question that I have are:
- Is really necessary that the IPCM exposes an API to recover a DIF template object? Is it enough that IPCM exposes APIs like: 
  - `template_exists(const std::string& template_name)`
  - Use in all IPCM API calls `const std::string& template_name` as a handle for the template
  - [only if it is necessary]  get_template_info(): gets a copy of the template object

To fix the underlying problem, which can also be happening internally between `IPCManager` and `DIFTemplateManager`, options that I see:
- Do not allow to delete templates (in-memory)
- Expose a copy of the template always
- Implement ref count

**Comment by msune** [comment]
@edugrasa thoughts?

**Comment by edugrasa** [comment]
Fixed by #1086
