### ISSUE TITLE
Java bindings: issues with CDAP message opcodes

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#685]

**Comment by mcrotty** [comment]
INFO calls are manager code, between readSDU() call and process_message() calls. 

1. Code (java)  :
 	IPCManagerSingleton ipc = rina.getIpcManager();
        while (keep_running) {
		        int bytesRead = ipc.readSDU(port_id, sdu, max_sdu_size_in_bytes)
		        info("Read" + bytesRead + " into the sdu buffer");
		    
		        ser_obj_t message = new ser_obj_t();
			message.setMessage_(sdu);
			message.setSize_(bytesRead);
			
			info("Calling process message");
			// Ask CDAP Processor to process the message
			provider.process_message(message, port_id);		    
		}


2. Console (manager) log: 

INFO:Read109 into the sdu buffer
INFO:Calling process message
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "rina.cdap.impl.googleprotobuf.CDAPMessage" because it is missing required fields: opCode                  
terminate called after throwing an instance of 'rina::CDAPException'                                                                                                                           
  what():  Receive a 18 CDAP message on a CDAP session that is not open, over flow 2                                                                                                           
Aborted (core dumped)                                                                                                                                                    
3. tail -f NMS1-1.log :

1723(1436955302)#ipcp[1].flow-allocator (ERR): Problems allocating flow: Could not find entry in DFT for application rina.apps.manager:1::
1723(1436955302)#ipcp[1].namespace-manager (INFO): Successfully registered application rina.apps.manager-1-- with IPC Process id 1s
1723(1436955302)#librina.rib (INFO): Object with name /dif/dif_management/directoryforwardingtableentries/rina.apps.manager-1--, class directoryforwardingtableentry, instance 16 added to the RIB
1723(1436955303)#librina.rib (INFO): Object with name /dif/flowallocator/flows/16-1, class flow, instance 17 added to the RIB

4. tail -f ipcm.log

1718(1436955303)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Applications rina.apps.mad.1:1:: and rina.apps.manager:1:: informed about flow allocation result
1718(1436955303)#ipcm.mad.flowm (INFO): [w:1] Flow allocated, port id = 1
1718(1436955304)#ipcm.app (INFO)[os_process_finalized_handler]: Application rina.apps.manager:1::terminated
1718(1436955304)#ipcm.flow-alloc (INFO)[deallocate_flow]: Application ::: asks IPC process NMS1:1:: to deallocate flow [port-id = 2]
1718(1436955304)#ipcm (INFO)[unregister_app_from_ipcp]: Requested unregistration of application rina.apps.manager:1:: from IPC process NMS1:1::
1718(1436955305)#cdap (ERR): M_CONNECT_R message not received within 2000 ms. Reseting the connection

**Comment by edugrasa** [comment]
@mcrotty I guess this issue can be closed?
