### ISSUE TITLE
Registration with an IPCP fails because the IPCP is created only afterwards

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#711]
Normal IPCP ipcp.a is created. It tries to register with the DIF '2', which is created only afterwards:

```
3642(1439305366)#ipcm-catalog (INFO): Plugin 'default' successfully loaded
3642(1439305366)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process ipcp.a:1:: to DIF normal.DIF:::

3642(1439305366)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process ipcp.a:1:: [success=1]

3642(1439305366)#ipcm (ERR)[register_at_dif]: Cannot find any IPC process belonging to DIF 2:::

3642(1439305366)#ipcm (ERR)[register_at_dif]: : Error while requesting registration: 

3642(1439305366)#ipcm (ERR)[apply_configuration]: Problems registering IPCP 1 to DIF 2

3642(1439305366)#ipcm (INFO)[create_ipcp]: IPC process test-eth:1:: created [id = 2]

3642(1439305366)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process test-eth:1:: to DIF 2:::

3642(1439305366)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process test-eth:1:: [success=1]
```

ipcmanager.conf:
```
{
    "localConfiguration": {
        "logPath": "/usr/local/irati/var/log",
        "pluginsPaths": [
            "/usr/local/irati/lib/rinad/ipcp"
        ],
        "libraryPath": "/usr/local/irati/lib",
        "consolePort": 32766,
        "installationPath": "/usr/local/irati/bin"
    },
    "applicationToDIFMappings": [
        {
            "encodedAppName": "rina.apps.echotime.server-1--",
            "difName": "normal.DIF"
        }
    ],
    "ipcProcessesToCreate": [
        {
            "difName": "normal.DIF",
            "difsToRegisterAt": [
                "2"
            ],
            "type": "normal-ipc",
            "apName": "ipcp.a",
            "apInstance": "1"
        },
        {
            "difName": "2",
            "difsToRegisterAt": [],
            "type": "shim-eth-vlan",
            "apName": "test-eth",
            "apInstance": "1"
        }
    ],
    "difConfigurations": [
        {
            "name": "normal.DIF",
            "template": "default.dif"
        },
        {
            "name": "2",
            "template": "shim-eth-vlan-2.dif"
        }
    ]
}
```

**Comment by nacarino** [comment]
Mind if I take a stab at this?

**Comment by vmaffione** [comment]
Sure, please go on!

**Comment by nacarino** [comment]
@vmaffione Have you been working on this issue? Do you have any pointers?

**Comment by vmaffione** [comment]
No, I haven't. But I guess you can just try to see if you are able to replicate the problem on your test machine (VM), using the very same IPCM configuration file provided here.

The problem here could be that IPCPs are created in the order specified in the configuration file, whereas they should follow the dependencies - e.g. the normal IPCP depends on the shim-eth-vlan IPCP, so the latter must be created first.

**Comment by dstaesse** [comment]
@nacarino: yes, the problem probably lies in the IPCPs being created in order specified in the IPCM configuration file. A solution could be to first build a dependency graph (likely a directed acyclic graph) for the IPCP registration and then maintain it (as IPCPs can register/unregister) during the IPCM's lifetime.

**Comment by nacarino** [comment]
@vmaffione @dstaesse I have been thinking about this for a month. A DAG would definitely help as I think that some of the issues that are also being seen in the CTRL-C stopping of the IPCM might be linked to not having a structure to recognize running IPCP.

An interesting effect of a DAG is that it would impose a topology on the IPCP names, making search interestingly optimizable. Are current IPCP names globally unique? Would we want them to stay globally unique? The other question I have is that if the DAG becomes part of the stack, shouldn't this structure be part of the kernel code? I am imagining a world in which one has hundreds of DIFs running. For speed purposes being part of the kernel seem appropriate.

The offending code is in IPCManager_::apply_configuration() where the configuration file is read as it was written in a for loop.

Any comments on IPCP naming and the DAG would be very welcome.

**Comment by vmaffione** [comment]
2015-09-28 2:04 GMT+02:00 Jairo Eduardo Lopez <notifications@github.com>:

> @vmaffione <https://github.com/vmaffione> @dstaesse
> <https://github.com/dstaesse> I have been thinking about this for a
> month. A DAG would definitely help as I think that some of the issues that
> are also being seen in the CTRL-C stopping of the IPCM might be linked to
> not having a structure to recognize running IPCP.
>
Yes, a DAG is needed here.


> An interesting effect of a DAG is that it would impose a topology on the
> IPCP names, making search interestingly optimizable. Are current IPCP names
> globally unique? Would we want them to stay globally unique?
>
IPCP names are unique within the DIF they are part of.  So the same name
may be used in different DIFs.


> The other question I have is that if the DAG becomes part of the stack,
> shouldn't this structure be part of the kernel code? I am imagining a world
> in which one has hundreds of DIFs running. For speed purposes being part of
> the kernel seem appropriate.
>
In general, things don't go faster just because you put them in
kernelspace. What would be the point of having this DAG in kernelspace? To
me it seems that is just needed in user space to properly order the
creation, registration and enrollment operations.


> The offending code is in IPCManager_::apply_configuration() where the
> configuration file is read as it was written in a for loop.
>
Yes, here one should read the DAG-related operations (creation,
registration, enrollment) and build the DAG. After the DAG is built, visit
it and perform the operation in the right order.


> Any comments on IPCP naming and the DAG would be very welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/711#issuecomment-143605871>.
>



-- 
Vincenzo Maffione

**Comment by nacarino** [comment]
@vmaffione Thanks for the quick reply and for clarifying the uniqueness of names within the DIF structure.

I have found no extra advantage in having the DAG in user space, so I wanted to know someone else's opinion on the matter.

If the DAG is created in user space, I am guessing an implementation in C++ would be preferred. Apart from creation, registration and enrollment should other methods be created for the DAG?

**Comment by edugrasa** [comment]
@nacarino @vmaffione just one small correction, IPCP names are application names, and unique across a set of DIFs. They are unique within a certain namespace, whose scope is a matter of design. For example, some IPC Process names may be unique within a single network provider  (if the IPCPs these names are assigned to just belong to DIFs that are internal within the provider), or unique within a group of providers that come together to operate DIFs in common.

**Comment by lbergesio** [comment]
@nacarino @vmaffione another point regarding the DAG and its location (userspace or kernel). We already have a list in the KIPCM with the existing IPCPs in the system. This list is populated after IPCP creation and is constantly used to retrieve the IPCP data in later operations. I always thought about this list as the red-black tree the kernel maintains with the system processes. I know this is not exactly the same, could we use the same variable to keep the topology and order of creation-dependencies or it makes sense to maintain a DAG in user space and this list (probably evolved to something else in the future) in kernel space?

**Comment by nacarino** [comment]
@edugrasa Thank you for the comment.

The uniqueness of the IPCP is an interesting topic. Given the current structure, do you think that the DAG in question should use it's own internal identifier and keep a mapping for the IPCP name list?

**Comment by nacarino** [comment]
@lbergesio Thank you for your comment! I was wondering about this before the prior post. 

@vmaffione If you already have a tree like structure in the KIPCM, completely adding DAG qualities would only make the list a more restricted type of tree. @edugrasa  If you already have strict rules for IPCP naming, then I don't think this is exceptionally hard to create, as the DAG would impose globally unique paths to IPCPs and these paths could later map to globally unique IPCPs.

If you already are keeping track of all IPCPs in a system in kernelspace, then I do think that having the topology integrated would be a more sane approach. My only concern now would be how much more weight the DAG properties would add to the list structure you are currently using.

**Comment by vmaffione** [comment]
@nacarino, that kernelspace list if for different purposes than tracking
dependencies.
Dependencies are useful to userspace parts (i.e. IPCM), that's why I'm
pointing at having the DAG there.

Moreover, consider that a DAG is useful for local IPC process, which are
the ones involved in IPCP registration and IPCP creation.

2015-09-28 10:13 GMT+02:00 Jairo Eduardo Lopez <notifications@github.com>:

> @lbergesio <https://github.com/lbergesio> Thank you for your comment! I
> was wondering about this before the prior post.
>
> @vmaffione <https://github.com/vmaffione> If you already have a tree like
> structure in the KIPCM, completely adding DAG qualities would only make the
> list a more restricted type of tree. @edugrasa
> <https://github.com/edugrasa> If you already have strict rules for IPCP
> naming, then I don't think this is exceptionally hard to create, as the DAG
> would impose globally unique paths to IPCPs and these paths could later map
> to globally unique IPCPs.
>
> If you already are keeping track of all IPCPs in a system in kernelspace,
> then I do think that having the topology integrated would be a more sane
> approach. My only concern now would be how much more weight the DAG
> properties would add to the list structure you are currently using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/711#issuecomment-143669488>.
>



-- 
Vincenzo Maffione

**Comment by edugrasa** [comment]
What should we do with this? At the end isn't it a problem of executing operations in the right order? (if you want to register to an N-1 DIF, or course first the IPCP of the N-1 DIF needs to exist). Is this really a bug?

**Comment by vmaffione** [comment]
Sure, it is important to have the correct order. This thread was just some
food for thoughts. We can close it, imho.

2016-02-09 16:55 GMT+01:00 Eduard Grasa <notifications@github.com>:

> What should we do with this? At the end isn't it a problem of executing
> operations in the right order? (if you want to register to an N-1 DIF, or
> course first the IPCP of the N-1 DIF needs to exist). Is this really a bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/711#issuecomment-181924813>.
>



-- 
Vincenzo Maffione
