### ISSUE TITLE
rina-echo-time calculates wrong RTT upon SDU lost

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#714]
Simulated packet drop with `tc`. One SDU is lost, and the next RTT is way too high to be correct.

```
sander@n:/usr/local/irati/bin$ ./rina-echo-time -s 100 -c 10 -w 20 
5584(1439817985)#librina.logs (DBG): New log level: INFO
5584(1439817985)#librina.nl-manager (INFO): Netlink socket connected to local port 5584 
Flow allocation time = 3.5077 ms
SDU size = 100, seq = 0, RTT = 0.22989 ms
SDU size = 100, seq = 1, RTT = 0.24195 ms
SDU size = 100, seq = 2, RTT = 0.25085 ms
SDU size = 100, seq = 3, RTT = 0.25033 ms
5584(1439817987)#rina-echo-time (WARN): Timeout waiting for reply, SDU considered lost
SDU size = 100, seq = 5, RTT = 297.02 ms
SDU size = 100, seq = 6, RTT = 0.23105 ms
SDU size = 100, seq = 7, RTT = 0.22669 ms
SDU size = 100, seq = 8, RTT = 0.23282 ms
SDU size = 100, seq = 9, RTT = 0.24563 ms
SDUs sent: 10; SDUs received: 9; 10% SDU loss
Minimum RTT: 0.22669 ms; Maximum RTT: 297.02 ms; Average RTT:33.215 ms; Standard deviation: 98.929 ms
```

**Comment by nacarino** [comment]
I would like to take a go at this bug. Could you show me the settings you made on tc to reproduce the environment?

**Comment by sandervrijders** [comment]
Just did a ```sudo tc qdisc add dev ethX root netem loss 10%```

**Comment by nacarino** [comment]
Thanks for the info. Will attempt to tackle it.

**Comment by sandervrijders** [comment]
If you submit a PR, please run check_maintainers.py to check the maintainers of the files you touched and include them in the PR. Also, take a look at the git history on how to write the commit message (check for instance one of Marc's commits). Thanks.

**Comment by nacarino** [comment]
I attempted to see if there was an error in the calculation and I don't find it. I made some modifications to the pristine-1.3 branch to output the times used to read and write SDUs. I used the tc configuration give to me by @sandervrijders. In the most interesting run of the code I got a lost SDU in SDU 0 (first) and then for SDU 6:

    SDU 0 -> sent at: 1440924164143.82861
    SDU 0 -> send difference: 0.02949
    SDU Attempted reads: 8421830
    SDU read/result difference: 2001.00005
    8305(1440924166)#rina-echo-time (WARN): Timeout waiting for reply, SDU considered lost
    SDU 1 -> sent at: 1440924166145.07422
    SDU 1 -> send difference: 0.16608
    SDU Attempted reads: 6708
    SDU read/result difference: 1.74070
    SDU 1 -> start: 1440924166144.90820
    SDU 1 -> write to read: 1440924166145.07422
    SDU 1 -> stop: 1440924166147.14868
    SDU 1 -> read difference: 2.07446
    SDU 1 -> calculated rtt: 2.24048
    SDU size = 20, seq = 1, RTT = 2.24044 ms`

Note that the "Attempted reads" shows us the number of cycles the readSDU function in et-client.cc is running. As required, the read timeouts after 2000 ms, shown by the "read/result difference line". The following SDU is written and read relatively quickly giving a slight higher RTT but not excessively high. Next I will show the log for SDU 6 and 7:

    SDU 6 -> sent at: 1440924171154.94824
    SDU 6 -> send difference: 0.03722
    SDU Attempted reads: 8399205
    SDU read/result difference: 2001.00004
    8305(1440924173)#rina-echo-time (WARN): Timeout waiting for reply, SDU considered lost
    SDU 7 -> sent at: 1440924173156.16724
    SDU 7 -> send difference: 0.11903
    SDU Attempted reads: 1283629
    SDU read/result difference: 298.47979
    SDU 7 -> start: 1440924173156.04834
    SDU 7 -> write to read: 1440924173156.16724
    SDU 7 -> stop: 1440924173454.82446
    SDU 7 -> read difference: 298.65723
    SDU 7 -> calculated rtt: 298.77612
    SDU size = 20, seq = 7, RTT = 298.77610 ms

Interestingly, for the SDU 6, a similar pattern to SDU 0 arises. The attempted reads are similar and cut off at slightly over 2000 ms. For the SDU 7, something strange occurs. The "send difference", or how long the writeSDU function takes is similar to the SDU 0, but the time it takes to read is high, with 1283629 read attempts and a delay of 298.47979 ms, giving the same results as the bug states.

The calculations itself seems fine as the calculation of SDU 1 demonstrates. It seems to be how the buffer and queue for SDUs is handled at kernel level that is causing the issue. 

I am new to how you are handling the actual sending and reading of data at the kernel level, so any ideas as to how I can check the running flow would be of great help. I hope that the data displayed here is of help.

**Comment by dstaesse** [comment]
@nacarino: Thanks for helping out!

I am revising the kernel I/O at this point. But I doubt the issue lies there.

I think the issue lies in the application. The read and write calls are in the same thread, but one waits for the other to finish. You can try to put both the read and write call in a while loop and check if either succeeds and then process the result.

loop something like (bad pseudocode, sorry) 
```
while (!written and !read) {
        read = ipcManager->readSDU(port_id, inputbuffer, data_size);
        written = ipcManager->writeSDU(port_id, outputbuffer, data_size);
}
if (written)
        /* handle output code */
if (read)
        /* handle input code */
```

does this make sense?

cheers,

Dimitri

**Comment by dstaesse** [comment]
Actually, we need to keep track of the sent sdu's (a "pending" map <sdu seq nr, timespec>). Add an entry when an sdu is sent, and remove the entry when received. When removing stale entries (older than a certain threshold) can be removed as well and reported as lost. This would make the implementation able to deal with jitter (out-of-order packets) as well.

**Comment by edugrasa** [comment]
It depends what you want the implementation to do. Right now it waits 2xMPL
for each packet (MPL is confogurable by user), and considers the packet
lost afterwards (same as ping does). There cant be out of order packets
because until the echo response is received or considered lost the next
request is not sent.

But if we want a different behavior for reason X lets talk about it!

**Comment by dstaesse** [comment]
In that case your implementation should work, but I don't think this is the "same as ping does"...

ping doesn't seem to wait between sending pings. If I ping
```
dstaesse@m:~$ sudo ping n -i 0.001 -c 10000
PING n-link0 (10.1.1.3) 56(84) bytes of data.
64 bytes from n-link0 (10.1.1.3): icmp_req=1 ttl=64 time=0.203 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=2 ttl=64 time=0.169 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=3 ttl=64 time=0.164 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=4 ttl=64 time=0.167 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=5 ttl=64 time=0.170 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=6 ttl=64 time=0.142 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=7 ttl=64 time=0.132 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=8 ttl=64 time=0.125 ms
...
64 bytes from n-link0 (10.1.1.3): icmp_req=9994 ttl=64 time=0.079 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=9995 ttl=64 time=0.074 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=9996 ttl=64 time=0.077 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=9997 ttl=64 time=0.075 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=9998 ttl=64 time=0.078 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=9999 ttl=64 time=0.075 ms
64 bytes from n-link0 (10.1.1.3): icmp_req=10000 ttl=64 time=0.074 ms
--- n-link0 ping statistics ---
10000 packets transmitted, 10000 received, 0% packet loss, time 9998ms
rtt min/avg/max/mdev = 0.054/0.078/0.193/0.013 ms
```

``` 
It took around 10 seconds to send all those 10000 pings. If ping did what you say, it would take at around 780 seconds as the average RTT is 78 ms. Sander wanted to ping with 1ms interval, which doesn't work right now. So what I suggest is probably closer to how ping actually works.

**Comment by dstaesse** [comment]
crapping up, the rtt on the wall is 78 microseconds

**Comment by dstaesse** [comment]
Anyway, @sandervrijders requested that function, so I think we could implement it... even if ping isn't doing it

**Comment by dstaesse** [comment]
apparently ping is a more interesting application than I thought. There is an adaptive function which does something like rina-echo-time does now (from manpages):
-A Adaptive ping. Interpacket interval adapts to round-trip time, so that effectively not more than one (or more, if preload is set) unanswered probes present in the network. Minimal interval is 200msec for not super-user. On networks with low rtt this mode is essentially equivalent to flood mode. 

-l preload If preload is specified, ping sends that many packets not waiting for reply. Only the super-user may select preload more than 3. 

-W timeout Time to wait for a response, in seconds. The option affects only timeout in absense of any responses, otherwise ping waits for two RTTs.

however, I would expect the command 
```
dstaesse@n:~$ sudo ping m -A -i 0.001 -c 10 -W 10
PING m-link0 (10.1.1.2) 56(84) bytes of data.
64 bytes from m-link0 (10.1.1.2): icmp_req=1 ttl=64 time=0.156 ms
64 bytes from m-link0 (10.1.1.2): icmp_req=4 ttl=64 time=0.171 ms
64 bytes from m-link0 (10.1.1.2): icmp_req=5 ttl=64 time=0.156 ms
64 bytes from m-link0 (10.1.1.2): icmp_req=6 ttl=64 time=0.171 ms
64 bytes from m-link0 (10.1.1.2): icmp_req=7 ttl=64 time=0.182 ms
64 bytes from m-link0 (10.1.1.2): icmp_req=8 ttl=64 time=0.157 ms
64 bytes from m-link0 (10.1.1.2): icmp_req=9 ttl=64 time=0.187 ms
64 bytes from m-link0 (10.1.1.2): icmp_req=10 ttl=64 time=0.049 ms

--- m-link0 ping statistics ---
10 packets transmitted, 8 received, 20% packet loss, time 22ms
rtt min/avg/max/mdev = 0.049/0.153/0.187/0.043 ms, ipg/ewma 2.489/0.150 ms
```
to take 20s, since there's a 10 second wait and 2 packets were lost (2 and 3)...
so ping seems do something else than expected :)

**Comment by edugrasa** [comment]
ok, probably ping doesn't work this way then :). If we need this
functionality (send echo requests at a certain rate) then the
implementation needs to be changed for sure, it wasn't designed like this.
What you suggest makes sense, keep in memory the window of echo requests in
flight that have not been acked by a response.

2015-08-30 21:33 GMT+02:00 Dimitri Staessens <notifications@github.com>:

**Comment by dstaesse** [comment]
@edugrasa. yep, let's see how to extend the app, keeping track of in-flight packets will give us more detailed info that could prove useful.  

But the reported bug bugs me (pun intended). I find it weird that a bump (and a significant one) in processing would only happen after a lost packet and not completely at random if it were a kernel I/O bug in our code.

@nacarino: some questions:
Did you track the actual sdu's (packets) with tcpdump? Can you see if this issue remains the same if you run the ```tc``` command both server side and client side?
Again, Many thanks for helping us out!

**Comment by sandervrijders** [comment]
Hmm, could it be that this is due to the A-timer in EFCP? If you request in-order delivery, it waits for a time of A before delivering the packet to the layer above IIRC, in case the lost packet still arrives and in-order delivery is maintained. @miqueltarzan Can you confirm this? Which would mean the solution is to disable in-order delivery if you have a time-constrained application, or just set the A-timer to a very low value. Currently in default.dif it is 300 (ms?)

**Comment by dstaesse** [comment]
@sandervrijders: I hear the sound of a bug squashing coming from your realms...

**Comment by sandervrijders** [comment]
@dstaesse Yes, after first creating the "bug" myself :)

**Comment by sandervrijders** [comment]
The cuplrit is indeed the A-timer. With an A-timer of 10ms:

```
Flow allocation time = 3.551 ms
SDU size = 100, seq = 0, RTT = 0.29143 ms
5048(1441014724)#rina-echo-time (WARN): Timeout waiting for reply, SDU considered lost
SDU size = 100, seq = 2, RTT = 14.357 ms
SDU size = 100, seq = 3, RTT = 0.34658 ms
SDU size = 100, seq = 4, RTT = 0.33012 ms
SDU size = 100, seq = 5, RTT = 0.34071 ms
SDU size = 100, seq = 6, RTT = 0.33843 ms
5048(1441014731)#rina-echo-time (WARN): Timeout waiting for reply, SDU considered lost
SDU size = 100, seq = 8, RTT = 12.881 ms
SDU size = 100, seq = 9, RTT = 0.35087 ms
SDUs sent: 10; SDUs received: 8; 20% SDU loss
Minimum RTT: 0.29143 ms; Maximum RTT: 14.357 ms; Average RTT:3.6544 ms; Standard deviation: 6.1627 ms
```

**Comment by nacarino** [comment]
@sandervrijders @dstaesse I am glad that my data was of help.
