### ISSUE TITLE
pristine-1.3: soft lock up while enabling/disabling N-1 port

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#716]
I just got the trace error attached here. There was a case where the shim-eth interrupt can lockup the code getting the lock of the n1_ports/n1_port structs.

[  488.212057] BUG: soft lockup - CPU#0 stuck for 22s! [rina-tgen:4110]
[  488.212057] Modules linked in: red_plugin(O) normal_ipcp rina_default_plugin shim_eth_vlan rinarp arp826 rina_personality_default 8021q garp stp llc nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc psmouse i2c_piix4 pcspkr serio_raw hid_generic usbmouse usbhid hid floppy
[  488.212057] CPU: 0 PID: 4110 Comm: rina-tgen Tainted: G           O  3.15.0 #19
[  488.212057] Hardware name: Xen HVM domU, BIOS 4.1.4 08/17/2014
[  488.212057] task: ffff880029e09840 ti: ffff88002ba3c000 task.ti: ffff88002ba3c000
[  488.212057] RIP: 0010:[<ffffffff810013a8>]  [<ffffffff810013a8>] xen_hypercall_sched_op+0x8/0x20
[  488.212057] RSP: 0018:ffff88003fc03a08  EFLAGS: 00200206
[  488.212057] RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffff88003dc004e0
[  488.212057] RDX: 0000000000000000 RSI: ffff88003fc03a18 RDI: 0000000000000003
[  488.212057] RBP: ffff88003fc03a38 R08: 0000000000000000 R09: ffff88003dc00490
[  488.212057] R10: 0000000000000000 R11: 0000000000000000 R12: ffff88003fc03978
[  488.212057] R13: ffffffff8171b8ad R14: ffff88003fc03a38 R15: 0000000000000000
[  488.212057] FS:  0000000000000000(0000) GS:ffff88003fc00000(0063) knlGS:00000000f6e1c700
[  488.212057] CS:  0010 DS: 002b ES: 002b CR0: 0000000080050033
[  488.212057] CR2: 000000000906f000 CR3: 00000000302d8000 CR4: 00000000001006f0
[  488.212057] Stack:
[  488.212057]  ffffffff814300ee 00000009810c03e7 ffff88003fc03a14 ffffffff00000001
[  488.212057]  0000000000000000 0000000000000045 ffff88003fc03a48 ffffffff81431220
[  488.212057]  ffff88003fc03aa0 ffffffff81010dd5 ffffffff81e77f40 0000000000200246
[  488.212057] Call Trace:
[  488.212057]  <IRQ> 
[  488.212057]  [<ffffffff814300ee>] ? xen_poll_irq_timeout+0x3e/0x50
[  488.212057]  [<ffffffff81431220>] xen_poll_irq+0x10/0x20
[  488.212057]  [<ffffffff81010dd5>] xen_lock_spinning+0xd5/0x270
[  488.212057]  [<ffffffff81010bd1>] __raw_callee_save_xen_lock_spinning+0x11/0x20
[  488.212057]  [<ffffffff816eb52e>] ? rkfree+0xe/0x10
[  488.212057]  [<ffffffff81710ab8>] ? _raw_spin_lock+0x48/0x50
[  488.212057]  [<ffffffffa0197d65>] rmt_enable_port_id+0x75/0x110 [rina_personality_default]
[  488.212057]  [<ffffffffa01de280>] ? disable_write+0x20/0x20 [normal_ipcp]
[  488.212057]  [<ffffffffa01de292>] enable_write+0x12/0x20 [normal_ipcp]
[  488.212057]  [<ffffffffa0195449>] efcp_enable_write+0x49/0x70 [rina_personality_default]
[  488.212057]  [<ffffffffa018fa78>] enable_write+0x78/0x80 [rina_personality_default]
[  488.212057]  [<ffffffffa0190296>] cwq_deliver+0x186/0x200 [rina_personality_default]
[  488.212057]  [<ffffffff816eb549>] ? rkmalloc+0x19/0x50
[  488.212057]  [<ffffffffa01917de>] push_pdus_rmt.isra.8+0x5e/0xa0 [rina_personality_default]
[  488.212057]  [<ffffffffa0191a8a>] dtcp_common_rcv_control+0x22a/0x4b0 [rina_personality_default]
[  488.212057]  [<ffffffffa019486c>] efcp_container_receive+0xcc/0x250 [rina_personality_default]
[  488.212057]  [<ffffffffa0197b7a>] rmt_receive+0x2aa/0x3e0 [rina_personality_default]
[  488.212057]  [<ffffffffa01deae9>] normal_sdu_enqueue+0x19/0x40 [normal_ipcp]
[  488.212057]  [<ffffffffa01b7e03>] eth_vlan_rcv+0x2d3/0x470 [shim_eth_vlan]
[  488.212057]  [<ffffffff81605f72>] __netif_receive_skb_core+0x572/0x820
[  488.212057]  [<ffffffff81009f10>] ? xen_clocksource_get_cycles+0x20/0x30
[  488.212057]  [<ffffffff81606236>] __netif_receive_skb+0x16/0x70
[  488.212057]  [<ffffffff816062b3>] netif_receive_skb_internal+0x23/0x90
[  488.212057]  [<ffffffff81606d30>] napi_gro_receive+0xc0/0xf0
[  488.212057]  [<ffffffff81527d27>] xennet_poll+0xaf7/0xb90
[  488.212057]  [<ffffffff81606682>] net_rx_action+0x142/0x250
[  488.212057]  [<ffffffff8106b31a>] __do_softirq+0x12a/0x2a0
[  488.212057]  [<ffffffff8106b605>] irq_exit+0x95/0xa0
[  488.212057]  [<ffffffff814310e8>] xen_evtchn_do_upcall+0x38/0x50
[  488.212057]  [<ffffffff8171b8ad>] xen_hvm_callback_vector+0x6d/0x80
[  488.212057]  <EOI> 
[  488.212057]  [<ffffffff816eb52e>] ? rkfree+0xe/0x10
[  488.212057]  [<ffffffff81710a82>] ? _raw_spin_lock+0x12/0x50
[  488.212057]  [<ffffffffa0196a91>] rmt_disable_port_id+0x71/0xf0 [rina_personality_default]
[  488.212057]  [<ffffffffa01de260>] ? connection_destroy_request+0x1b0/0x1b0 [normal_ipcp]
[  488.212057]  [<ffffffffa01de272>] disable_write+0x12/0x20 [normal_ipcp]
[  488.212057]  [<ffffffffa0194469>] efcp_disable_write+0x49/0x70 [rina_personality_default]
[  488.212057]  [<ffffffffa01cf8bd>] common_flow_control_overrun+0x5d/0xc0 [rina_default_plugin]
[  488.212057]  [<ffffffffa01cfc3e>] default_flow_control_overrun+0xe/0x10 [rina_default_plugin]
[  488.212057]  [<ffffffffa01cf7e7>] common_closed_window+0xa7/0x120 [rina_default_plugin]
[  488.212057]  [<ffffffffa01cfc4e>] default_closed_window+0xe/0x10 [rina_default_plugin]
[  488.212057]  [<ffffffffa019339a>] dtp_write+0x2ea/0x4b0 [rina_personality_default]
[  488.212057]  [<ffffffffa0194669>] efcp_container_write+0xa9/0x1e0 [rina_personality_default]
[  488.212057]  [<ffffffffa01df335>] normal_sdu_write+0xa5/0xd0 [normal_ipcp]
[  488.212057]  [<ffffffffa0196698>] n1_port_write_noclean+0xe8/0x250 [rina_personality_default]
[  488.212057]  [<ffffffffa0196943>] rmt_send_port_id+0x143/0x220 [rina_personality_default]
[  488.212057]  [<ffffffffa0196b9d>] rmt_send+0x8d/0x130 [rina_personality_default]
[  488.212057]  [<ffffffffa018f70a>] common_efcp_pdu_send+0x5a/0x100 [rina_personality_default]
[  488.212057]  [<ffffffffa01cf6e7>] common_transmission_control+0xa7/0x100 [rina_default_plugin]
[  488.212057]  [<ffffffffa01cfc5e>] default_transmission_control+0xe/0x10 [rina_default_plugin]
[  488.212057]  [<ffffffffa01932dc>] dtp_write+0x22c/0x4b0 [rina_personality_default]
[  488.212057]  [<ffffffffa0194669>] efcp_container_write+0xa9/0x1e0 [rina_personality_default]
[  488.212057]  [<ffffffffa01df335>] normal_sdu_write+0xa5/0xd0 [normal_ipcp]
[  488.212057]  [<ffffffffa0198c02>] kfa_flow_sdu_write+0x212/0x560 [rina_personality_default]
[  488.212057]  [<ffffffff810128a5>] ? __switch_to+0x405/0x500
[  488.212057]  [<ffffffff811a363a>] ? __kmalloc+0x19a/0x1a0
[  488.212057]  [<ffffffff816eb59f>] ? rkzalloc+0x1f/0x60
[  488.212057]  [<ffffffffa019d07b>] kipcm_sdu_write+0x5b/0xd0 [rina_personality_default]
[  488.212057]  [<ffffffffa019d595>] default_sdu_write+0x35/0x40 [rina_personality_default]
[  488.212057]  [<ffffffff816f8c3c>] SyS_sdu_write+0x8c/0x110
[  488.212057]  [<ffffffff8171b96c>] sysenter_dispatch+0x7/0x21
[  488.212057] Code: cc cc cc b8 1c 00 00 00 0f 01 c1 c3 cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc b8 1d 00 00 00 0f 01 c1 <c3> cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc

**Comment by sandervrijders** [comment]
@lbergesio Please use ``` when pasting code

**Comment by edugrasa** [comment]
Closing after merging the code of #718
