### ISSUE TITLE
rinad: installing should not overwrite existing configuration

### ISSUE THREAD

**Issue by dstaesse** [IRATI/stack#717]
it's really annoying that installing a newer version of user space replaces the existing configuration.
the build system should be upgraded to either
- save existing configuration files to *.old
- save the new configuration files to a $prefix$/etc/ex/ folder (my preferred solution)

while at it, it may be better to move the entire configuration out of the global /etc/ folder into something like /etc/ipcm.d/*

**Comment by msune** [comment]
The solution was discussed here:

https://github.com/IRATI/stack/pull/625

But I did not realise I was actually not implemented; correct @edugrasa ? Or was it part of another PR?

**Comment by dstaesse** [comment]
doesn't seem to be implemented yet...

**Comment by nacarino** [comment]
I have been working on the user space tools on the pristine-1.3 branch. I can attest that it is not implemented.

**Comment by dstaesse** [comment]
@msune, @edugrasa: are you guys looking into this?

**Comment by edugrasa** [comment]
Not yet, will try to address it during this week..

**Comment by edugrasa** [comment]
It took a bit more time :P Fixed by #1223
