### ISSUE TITLE
Policy(DTP) apparently is not selected for intermediary ipcps.

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#720]
Branch: pristine-1.3
Configuration: (client) Alpha <--> Charlie (server)
DIF view:

Tenant DIF [uppermost] <--- DTP policy tried to be loaded here, works.
Dc DIF [intermediate] <--- DTP policy tried to be loaded here, does not work.
Lim DIF [intermediate]
Shim_eth 100 DIF [lower shim]

Description of the problem:
The DTP policy(in my case) which is loaded on an intermediate IPCP is never used/assigned to the flow. If I assign the policy using the .dif files to the uppermost DIF then the policy is well handled and works. The policy is present in the catalog and published in the kernel(kernel logs of publishing are present).

**Comment by sandervrijders** [comment]
@vmaffione Can you take a look at this?

**Comment by kewinrausch** [comment]
I'm investigating further on this, but can simply be that this error was due a not-updated config file I had in the testing machine.

**Comment by kewinrausch** [comment]
We can close this; I'm did not have this problem anymore and probably was due a mis-alignment of the .DIF files between the nodes on vWall and my local files. :expressionless:
