### ISSUE TITLE
install-user-from-scratch doesn't warn that proxy settings may be required

### ISSUE THREAD

**Issue by nacarino** [IRATI/stack#733]
This is mostly an enhancement. In the install-user-from-scratch script, maven is used for a section of the user-space installation. If a person is behind a proxy, the installation fails. Until you realize that maven requires a specific [.m2/settings.xml](https://maven.apache.org/guides/mini/guide-proxies.html) things can be a little puzzling.

**Comment by dstaesse** [comment]
@vmaffione @salvestrini: how do we handle this? I saw this as well (our testbed requires a proxy), following maven documentation led to that settings.xml file quite fluently... 
Other option is to remove the java bindings and maven stuff from the install-user-from-scratch script... people shouldn't be using well-identified lousiness [1] :)

[1] Edsger W. Dijkstra, "To the members of the budget council". Austin, TX
