### ISSUE TITLE
Use sysfs to export state of IPCP kernel components

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#747]
Use sysfs to allow experimenters/debuggers to access some of the information about the internal state of the kernel IPCP components. This issue is mostly a placeholder and should probably be partitioned into smaller issues.

* EFCP, for each EFCP connection:
** static data such as CEP-ids, addresses, qos-id, etc.
** dynamic data such as tx/rcvd PDUs, credit, closed window queue size, number of rtx., etc..

* RMT, for each N-1 port:
** static data such as number of queues, max queue size, etc..
** dynamic data such as current queue size, number of PDUs tx/rx, number of PDUs dropped, etc..

* PFF
** dynamic data such as entries in the PFF

other? (SDU protection related)

**Comment by edugrasa** [comment]
After the refactored user-space components are merged (PR #787), the IPCP Daemon is ready to include RIB objects that watch sysfs for updates on the IPCP kernel info (rmt, efcp, pff, sdu protection). We need to export this information to network management, therefore this issue is becoming a priority. 

Who would volunteer to work on it? @vmaffione I recall you were interested. I don't know if @lbergesio and/or @miqueltarzan would have the time as well? I can also look into it.

**Comment by vmaffione** [comment]
@edugrasa, yes I'm interested to work on it, but currently my focus is SDK and D2.5, so I can't commit to it right now. If you can wait, I'll work on it it after D2.5, otherwise someone could start the implementation and i will join/improve/debug/fix later.

**Comment by lbergesio** [comment]
I can give it a look next week. Let's discuss it today to gather requirements and do some design

**Comment by edugrasa** [comment]
Ok, we may start drafting the design with Leo and Miquel once they are available, and comment it with you Vincenzo.

**Comment by lbergesio** [comment]
Implemented in #820

**Comment by lbergesio** [comment]
This one should be closed after #820 has been merged
