### ISSUE TITLE
Improve configuration of rate-based flow control

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#758]
Remove hardcoded parameters and get the information from the QoS cubes definition.

**Comment by kewinrausch** [comment]
Actually the QoS values of the defined QoS cubes in the .dif files are already correctly moved/saved to the dtp/dtcp configuration. 

What is necessary to do it simply adjust the procedure
```serdes.c: int serdes_pci_size(pdu_type_t type)```

which provides the length in bytes of the pci using the DIF configuration.
I probably explain the problem in a wrong way during the meeting.
