### ISSUE TITLE
pristine-1.3: Misleading message (missing maven support) on configure

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#773]
Severity: Annoyance
Description: Configure emits a misleading message when maven is available:
"Your system lacks of maven support, Java parts will not be built/installed"

Maven is installed as can be verified by
mcrotty@inishoonua:~/irati$ which mvn
/usr/bin/mvn

**Comment by edugrasa** [comment]
Closing since it was fixed by @mcrotty
