### ISSUE TITLE
pristine-1.3 ASSERT producing BUG on shim-eth-vlan IPCP destruction

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#776]
The bug is produced by the ASSERT on the name struct on ipcp_imap_find_by_name when a shim-eth-vlan worker is triggered after the IPCP was destroyed.

[ 2006.828175] BUG: unable to handle kernel NULL pointer dereference at           (null)
[ 2006.832142] IP: [<ffffffff811fb92d>] strcmp+0x9/0x20
[ 2006.832142] PGD 7adad067 PUD 7bf58067 PMD 0 
[ 2006.832142] Oops: 0000 [#1] SMP 
[ 2006.832142] Modules linked in: shim_eth_vlan rinarp arp826 nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc rina_default_plugin shim_tcp_udp normal_ipcp rina_personality_default 8021q garp stp llc loop ohci_pci kvm_amd ohci_hcd ehci_pci ehci_hcd kvm usbcore nv_tco radeon amd64_edac_mod i2c_nforce2 snd_pcm ttm snd_timer snd drm_kms_helper soundcore drm psmouse k8temp i2c_algo_bit processor parport_pc parport edac_mce_amd edac_core i2c_core serio_raw evdev shpchp usb_common pcspkr thermal_sys button ext3 mbcache jbd dm_mod sg sd_mod crc_t10dif crct10dif_common ata_generic pata_amd sata_nv e1000e ptp pps_core libata forcedeth scsi_mod
[ 2006.832142] CPU: 0 PID: 1454 Comm: kworker/u28:0 Not tainted 3.15.0-irati-vleo9 #63
[ 2006.832142] Hardware name: Supermicro H8DMR-82/H8DMR-82, BIOS 080014  09/24/2009
[ 2006.832142] Workqueue: shim-eth-vlan rwq_worker
[ 2006.832142] task: ffff88007b9fc250 ti: ffff880037250000 task.ti: ffff880037250000
[ 2006.832142] RIP: 0010:[<ffffffff811fb92d>]  [<ffffffff811fb92d>] strcmp+0x9/0x20
[ 2006.832142] RSP: 0018:ffff880037253cd0  EFLAGS: 00010246
[ 2006.832142] RAX: 0000000000000000 RBX: 00000000000000f0 RCX: ffffffffa027f040
[ 2006.832142] RDX: ffff88007c1a3274 RSI: 0000000000000000 RDI: ffff88007c1a3260
[ 2006.832142] RBP: ffff880037253cd0 R08: 0000000000000001 R09: 0000000000000001
[ 2006.832142] R10: ffff880037253d20 R11: 0000000000000000 R12: ffff88007c1a32a0
[ 2006.832142] R13: ffff8800da87da00 R14: ffff88007b5e7940 R15: ffff880037211800
[ 2006.832142] FS:  00007fbaeb3de700(0000) GS:ffff88007d200000(0000) knlGS:0000000000000000
[ 2006.832142] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[ 2006.832142] CR2: 0000000000000000 CR3: 0000000037020000 CR4: 00000000000007f0
[ 2006.832142] Stack:
[ 2006.832142]  ffff880037253d10 ffffffffa03d1e4a 0000000000000000 ffff88007b52c100
[ 2006.832142]  ffff8800da87da00 ffff88007b294000 0000000000000000 ffff88003727bc00
[ 2006.832142]  ffff880037253d38 ffffffffa03d31e3 000077ff80000000 ffff88003738ae00
[ 2006.832142] Call Trace:
[ 2006.832142]  [<ffffffffa03d1e4a>] ipcp_imap_find_by_name+0x73/0xbf [rina_personality_default]
[ 2006.832142]  [<ffffffffa03d31e3>] kipcm_find_ipcp_by_name+0x4a/0x60 [rina_personality_default]
[ 2006.832142]  [<ffffffffa0651537>] eth_vlan_rcv_worker+0x4c/0x274 [shim_eth_vlan]
[ 2006.832142]  [<ffffffff813c6cbf>] rwq_worker+0x26/0x70
[ 2006.832142]  [<ffffffff81053688>] process_one_work+0x1da/0x395
[ 2006.832142]  [<ffffffff810540f4>] worker_thread+0x13e/0x1d7
[ 2006.832142]  [<ffffffff81053fb6>] ? cancel_delayed_work_sync+0x10/0x10
[ 2006.832142]  [<ffffffff810592ec>] kthread+0xc7/0xcf
[ 2006.832142]  [<ffffffff81067a18>] ? sched_clock_cpu+0xa0/0xb5
[ 2006.832142]  [<ffffffff81059225>] ? __kthread_parkme+0x62/0x62
[ 2006.832142]  [<ffffffff813e5d7c>] ret_from_fork+0x7c/0xb0
[ 2006.832142]  [<ffffffff81059225>] ? __kthread_parkme+0x62/0x62
[ 2006.832142] Code: f9 48 89 e5 80 39 00 74 05 48 ff c1 eb f6 31 d2 40 8a 3c 16 40 88 3c 11 48 ff c2 40 84 ff 75 f0 5d c3 55 31 c0 48 89 e5 8a 14 07 <3a> 14 06 74 07 19 c0 83 c8 01 eb 09 48 ff c0 84 d2 75 ea 31 c0 
[ 2006.832142] RIP  [<ffffffff811fb92d>] strcmp+0x9/0x20
[ 2006.832142]  RSP <ffff880037253cd0>
[ 2006.832142] CR2: 0000000000000000

**Comment by edugrasa** [comment]
Fixed by PR #781
