### ISSUE TITLE
pristine-1.3: BUG sleeping while atomic in rmt binding

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#777]
Bug existing for long time but very strangely never discovered.
Scenario normal over normal over shim-eth-vlan: 
norma-ipc.c, connection_create_arrived takes a spin_lock and calls user_ipcp->ops->flow_binding_ipcp which is rmt_n1port_bind.
rmt_n1port_bind calls n1port_create which allocates memory with GFP_KERNEL flag.

[  296.053711] BUG: sleeping function called from invalid context at mm/slab.c:2959
[  296.056531] in_atomic(): 1, irqs_disabled(): 1, pid: 3627, name: ipcp
[  296.056820] INFO: lockdep is turned off.
[  296.056820] irq event stamp: 176
[  296.056820] hardirqs last  enabled at (175): [<ffffffff813e0128>] _raw_spin_unlock_irqrestore+0x3a/0x49
[  296.056820] hardirqs last disabled at (176): [<ffffffff813dffb1>] _raw_spin_lock_irq+0x10/0x6d
[  296.056820] softirqs last  enabled at (0): [<ffffffff8103b207>] copy_process.part.33+0x5c8/0x18dc
[  296.056820] softirqs last disabled at (0): [<          (null)>]           (null)
[  296.056820] CPU: 0 PID: 3627 Comm: ipcp Not tainted 3.15.0-irati-vleo9 #67
[  296.056820] Hardware name: Supermicro H8DMR-82/H8DMR-82, BIOS 080014  04/01/2008
[  296.056820]  0000000000000000 ffff8800367a7890 ffffffff813db40b 0000000000000e2b
[  296.056820]  ffff8800367a78b0 ffffffff8106124f 0000000000000000 ffff88007d000140
[  296.056820]  ffff8800367a78c0 ffffffff8111bcf7 ffff8800367a7908 ffffffff8111e069
[  296.056820] Call Trace:
[  296.056820]  [<ffffffff813db40b>] dump_stack+0x4d/0x66
[  296.056820]  [<ffffffff8106124f>] __might_sleep+0x120/0x125
[  296.056820]  [<ffffffff8111bcf7>] cache_alloc_debugcheck_before.isra.42+0x1d/0x24
[  296.056820]  [<ffffffff8111e069>] __kmalloc+0x4c/0x11e
[  296.056820]  [<ffffffff813c66d2>] ? rkzalloc+0x2c/0x4d
[  296.056820]  [<ffffffff813c66d2>] rkzalloc+0x2c/0x4d
[  296.056820]  [<ffffffffa030eb75>] rmt_n1port_bind+0x108/0x251 [rina_personality_default]
[  296.056820]  [<ffffffffa02ef998>] ipcp_flow_binding+0xd/0xf [normal_ipcp]
[  296.056820]  [<ffffffffa02efcbd>] connection_create_arrived+0x11b/0x191 [normal_ipcp]
[  296.056820]  [<ffffffffa0312d25>] notify_ipcp_conn_create_arrived+0xf4/0x1d1 [rina_personality_default]
[  296.056820]  [<ffffffff813cbba4>] dispatcher+0xc7/0xee
[  296.056820]  [<ffffffffa0312c31>] ? notify_ipcp_conn_create_req+0x165/0x165 [rina_personality_default]
[  296.056820]  [<ffffffff81335870>] genl_family_rcv_msg+0x236/0x286
[  296.056820]  [<ffffffff813358ff>] genl_rcv_msg+0x3f/0x58
[  296.056820]  [<ffffffff813358c0>] ? genl_family_rcv_msg+0x286/0x286
[  296.056820]  [<ffffffff813340cb>] netlink_rcv_skb+0x42/0x85
[  296.056820]  [<ffffffff81334562>] genl_rcv+0x23/0x32
[  296.056820]  [<ffffffff81333c00>] netlink_unicast+0xfd/0x173
[  296.056820]  [<ffffffff81333f8b>] netlink_sendmsg+0x315/0x33c
[  296.056820]  [<ffffffff812f745c>] __sock_sendmsg_nosec+0x25/0x27
[  296.056820]  [<ffffffff812f8861>] sock_sendmsg+0x69/0x90
[  296.056820]  [<ffffffff810fd3b3>] ? might_fault+0xad/0xaf
[  296.056820]  [<ffffffff812f8b07>] ___sys_sendmsg+0x233/0x2c9
[  296.056820]  [<ffffffff812f8b07>] ? ___sys_sendmsg+0x233/0x2c9
[  296.056820]  [<ffffffff81073a2d>] ? arch_local_irq_save+0x9/0xc
[  296.056820]  [<ffffffff81077a55>] ? lock_acquire+0x94/0x102
[  296.056820]  [<ffffffff8113ff84>] ? rcu_read_unlock+0x26/0x26
[  296.056820]  [<ffffffff8113ff7a>] ? rcu_read_unlock+0x1c/0x26
[  296.056820]  [<ffffffff8114001c>] ? __fget+0x69/0x73
[  296.056820]  [<ffffffff812fae34>] __sys_sendmsg+0x3d/0x5b
[  296.056820]  [<ffffffff812fae34>] ? __sys_sendmsg+0x3d/0x5b
[  296.056820]  [<ffffffff812fae66>] SyS_sendmsg+0x14/0x16
[  296.056820]  [<ffffffff813e5e22>] system_call_fastpath+0x16/0x1b

**Comment by edugrasa** [comment]
Fixed by PR #781
