### ISSUE TITLE
Pristine-1.3: Poor Performances with ethtool restrictions

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#783]
**Where:**
Branch Pristine-1.3

**What:**
Using IRATI on real machine(not VMs) leads at some really poor performance. 
The test were executed on a very simple topology with 1Gb/s link connection between each connected node. The topology was a 4 node one, like:
A
 |
C ---- D
 |
B
Server on D, client on A. 
Only one DIF over the shims.

Test 1: Ethtool **ON**
Ethtool set the interface of every node as:
```sudo ethtool -s ethX speed 100 autoneg off```
Iperf test generate a traffic of about 95.6Mb/s, so the restriction is good.
Client-Server test (and additional node in between) with a **not** restricted(in term of bandwidth) traffic generator and 500 sized window(window-based flow control) lead to the following result:
```12204(1446479268)#traffic-generator (INFO): Port  3: 4385 SDUs, 2192500 bytes in 30220 ms, 0.5804 Mb/s```

Test2: Ethtool **OFF**
lient-Server test (and additional node in between) with a **not** restricted(in term of bandwidth) traffic generator and 500 sized window(window-based flow control) lead to the following result:
```3690(1446479673)#traffic-generator (INFO): Port    2:   1550362 SDUs,    775181000 bytes in     30000 ms, 206.7149 Mb/s```

**NOTE:** *~200 Mb/s is the max rate i can accomplish on vWall, so it's considered ok here. Still probably these slow performances are due to the maturity of the stack.*

**Comment by edugrasa** [comment]
VWall tests have reported line-rate throughputs (950 Mbps ...)

Have you tried with credit 30 and close-window queue 20 or so? Making the credit very high will lead to poor performance..

**Comment by kewinrausch** [comment]
I tried with credit 50 and credit 500, and with ethtool imposed limit I always got the same result (around 0.5 Mb/s). 

I never reached more than about 250Mb/s with both window-based and rate-based mechanisms (with 1Gb/s channel on vwall). The test I did were both with original tgen and a branch I'm using which has additional functionalities. 

I'm actually using pristine-1.3 which has the 3.15.0 kernel (updated 12 days ago). 
Can be that a newer update resolve this problem? When did you do such tests?

**Comment by vmaffione** [comment]
Kevin, I'm pretty sure an update won't resolve the problem. The limitation
is likely to come from the EFCP implementation.

2015-11-03 8:35 GMT+01:00 Kewin Rausch <notifications@github.com>:

> I tried with credit 50 and credit 500, and with ethtool imposed limit I
> always got the same result (around 0.5 Mb/s).
>
> I never reached more than about 250Mb/s with both window-based and
> rate-based mechanisms (with 1Gb/s channel on vwall). The test I did were
> both with original tgen and a branch I'm using which has additional
> functionalities.
>
> I'm actually using pristine-1.3 which has the 3.15.0 kernel (updated 12
> days ago).
> Can be that a newer update resolve this problem? When did you do such
> tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/783#issuecomment-153280222>.
>



-- 
Vincenzo Maffione

**Comment by edugrasa** [comment]
Hi Kewin,

What are you testing, two systems directly connected? If so I've got up to 1 Gbps in XEN VMs (which are 1 CPU and 512 MB of RAM). 50 PDUs for the credit is already too much, try with less, start with 20, then go to 25, 30 and so on (at some point you'll see the goodput decrease a lot). In my tests (VMs and VWall, 50 is already too much credit to get the optimum goodput). 

I don't think it is the EFCP implementation alone, imho (in addition of too much copying in a number of places) it's the combination of the default policies of EFCP and the RMT, but we'll be in a much better position to understand what is going on when we can export kernel stats via sysfs.

**Comment by kewinrausch** [comment]
I'm testing the topology you can see in the first post:

A <--- client
|
C ---- D <--- server
|
B

So they are **NOT** directly connected.

I use real nodes (**not** VMs, which can be located on the same machine) that communicates between them and have a node in between which performs relaying. I don't have control over the RAM or CPU (free command told me i have 4GB RAM now).

512 Mb RAM VMs? This is strange; when i try to run a 512 Mb under Virtual Box (always pristine-1.3) i always got the kernel blocked during boot time (because of not enough memory). I reported this to Francesco months ago, while he still was in the project, and he said was no urgent. 

I can open another issue about this if you want.

**Comment by edugrasa** [comment]
Ok, if not back to back then I got maximum 300 Mbps (in a setup like your scenario). Still, you should reduce the credit to 30-40 to get these 300 Mbps.

**Comment by kewinrausch** [comment]
No, wait.

I remember you that the issue was:
*regardless of that performances we spoke (about 250 Mb/s), if you setup the interface with ethtool BW restrictions, the current problems happens:*

100 Mb/s restriction ---> veeeery low perfomances, which are in the orders of ~3Mb/s
10 Mb/s restriction ---> does not work, only enrolls...

**Comment by edugrasa** [comment]
Just tested it on the Vwall, the "issue" is that with window-based flow control you can only go up to 30 Mbps (using closed window queue = 1, credit = 2), in the case that the Ethernet card is limited to 100 Mbps.

''''
root@br1:/usr/local/irati/bin# ./rina-tgen -l
5041(1447109623)#librina.logs (DBG): New log level: INFO
5041(1447109623)#librina.nl-manager (INFO): Netlink socket connected to local port 5041 
5041(1447109626)#traffic-generator (INFO): New flow allocated [port-id = 6]
5041(1447109626)#traffic-generator (INFO): Starting test from client traffic.generator.client-1 on port-id 6
5041(1447109626)#traffic-generator (INFO): Duration: 20 s, count: 0 sdus, sdu size: 1450 bytes, reporting interval: 1000 ms
5041(1447109627)#traffic-generator (INFO): Port    6:      1874 SDUs (     2717300 bytes) in      1000207 us => 1873.6122 p/s,   21.7339 Mb/s
5041(1447109628)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000121 us => 2667.6770 p/s,   30.9451 Mb/s
5041(1447109629)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000030 us => 2667.9199 p/s,   30.9479 Mb/s
5041(1447109630)#traffic-generator (INFO): Port    6:      2670 SDUs (     3871500 bytes) in      1000693 us => 2668.1509 p/s,   30.9506 Mb/s
5041(1447109631)#traffic-generator (INFO): Port    6:      2647 SDUs (     3838150 bytes) in      1291458 us => 2049.6213 p/s,   23.7756 Mb/s
5041(1447109632)#traffic-generator (INFO): Port    6:      1095 SDUs (     1587750 bytes) in      1000016 us => 1094.9825 p/s,   12.7018 Mb/s
5041(1447109633)#traffic-generator (INFO): Port    6:      2670 SDUs (     3871500 bytes) in      1000669 us => 2668.2148 p/s,   30.9513 Mb/s
5041(1447109634)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000583 us => 2666.4456 p/s,   30.9308 Mb/s
5041(1447109635)#traffic-generator (INFO): Port    6:      1876 SDUs (     2720200 bytes) in      1000489 us => 1875.0831 p/s,   21.7510 Mb/s
5041(1447109636)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000404 us => 2666.9226 p/s,   30.9363 Mb/s
5041(1447109637)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000316 us => 2667.1572 p/s,   30.9390 Mb/s
5041(1447109638)#traffic-generator (INFO): Port    6:      2667 SDUs (     3867150 bytes) in      1000231 us => 2666.3840 p/s,   30.9301 Mb/s
5041(1447109639)#traffic-generator (INFO): Port    6:      2667 SDUs (     3867150 bytes) in      1000140 us => 2666.6267 p/s,   30.9329 Mb/s
5041(1447109640)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000050 us => 2667.8667 p/s,   30.9473 Mb/s
5041(1447109641)#traffic-generator (INFO): Port    6:      1877 SDUs (     2721650 bytes) in      1003456 us => 1870.5354 p/s,   21.6982 Mb/s
5041(1447109642)#traffic-generator (INFO): Port    6:      2659 SDUs (     3855550 bytes) in      1000369 us => 2658.0190 p/s,   30.8330 Mb/s
5041(1447109643)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000280 us => 2667.2532 p/s,   30.9401 Mb/s
5041(1447109644)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000434 us => 2666.8428 p/s,   30.9354 Mb/s
5041(1447109645)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000350 us => 2667.0667 p/s,   30.9380 Mb/s
5041(1447109646)#traffic-generator (INFO): Port    6:      2668 SDUs (     3868600 bytes) in      1000254 us => 2667.3225 p/s,   30.9409 Mb/s
5041(1447109646)#traffic-generator (INFO): Port    6:     49382 SDUs,     71603900 bytes in     20000 ms, 28.6416 Mb/s
 
If we remove flow control, performance gets up to 90 Mbps. With rate-based flow control (which, unlike window-based does not depend on feedback), you should be able to get that performances also.

''''
6731(1447110036)#traffic-generator (INFO): Port    8:      8277 SDUs (    12249960 bytes) in      1192759 us => 6939.3735 p/s,   82.1622 Mb/s
6731(1447110037)#traffic-generator (INFO): Port    8:      8957 SDUs (    13256360 bytes) in      1308737 us => 6844.0034 p/s,   81.0330 Mb/s
6731(1447110038)#traffic-generator (INFO): Port    8:      8045 SDUs (    11906600 bytes) in      1288611 us => 6243.1562 p/s,   73.9190 Mb/s
6731(1447110039)#traffic-generator (INFO): Port    8:      8857 SDUs (    13108360 bytes) in      1308457 us => 6769.0415 p/s,   80.1455 Mb/s
6731(1447110040)#traffic-generator (INFO): Port    8:      8437 SDUs (    12486760 bytes) in      1424859 us => 5921.2876 p/s,   70.1080 Mb/s
6731(1447110041)#traffic-generator (INFO): Port    8:      6763 SDUs (    10009240 bytes) in      1000003 us => 6762.9795 p/s,   80.0737 Mb/s
6731(1447110042)#traffic-generator (INFO): Port    8:      6640 SDUs (     9827200 bytes) in      1004392 us => 6610.9644 p/s,   78.2738 Mb/s
6731(1447110043)#traffic-generator (INFO): Port    8:      8672 SDUs (    12834560 bytes) in      1108572 us => 7822.6768 p/s,   92.6205 Mb/s
6731(1447110044)#traffic-generator (INFO): Port    8:      9204 SDUs (    13621920 bytes) in      1232309 us => 7468.9058 p/s,   88.4318 Mb/s
6731(1447110045)#traffic-generator (INFO): Port    8:      9053 SDUs (    13398440 bytes) in      1393052 us => 6498.6807 p/s,   76.9444 Mb/s
6731(1447110046)#traffic-generator (INFO): Port    8:      7175 SDUs (    10619000 bytes) in      1248661 us => 5746.1553 p/s,   68.0345 Mb/s
6731(1447110047)#traffic-generator (INFO): Port    8:      9015 SDUs (    13342200 bytes) in      1356523 us => 6645.6670 p/s,   78.6847 Mb/s
6731(1447110048)#traffic-generator (INFO): Port    8:      9053 SDUs (    13398440 bytes) in      1424423 us => 6355.5557 p/s,   75.2498 Mb/s
6731(1447110049)#traffic-generator (INFO): Port    8:      4993 SDUs (     7389640 bytes) in      1000001 us => 4992.9951 p/s,   59.1171 Mb/s
6731(1447110050)#traffic-generator (INFO): Port    8:      8391 SDUs (    12418680 bytes) in      1124323 us => 7463.1577 p/s,   88.3638 Mb/s
6731(1447110051)#traffic-generator (INFO): Port    8:      8927 SDUs (    13211960 bytes) in      1257737 us => 7097.6685 p/s,   84.0364 Mb/s
6731(1447110052)#traffic-generator (INFO): Port    8:      9390 SDUs (    13897200 bytes) in      1424540 us => 6591.6011 p/s,   78.0446 Mb/s
6731(1447110053)#traffic-generator (INFO): Port    8:      4771 SDUs (     7061080 bytes) in      1008833 us => 4729.2266 p/s,   55.9940 Mb/s
6731(1447110054)#traffic-generator (INFO): Flow torn down remotely [port-id = 8]
6731(1447110054)#traffic-generator (INFO): Port    8:      8953 SDUs (    13250440 bytes) in      1079993 us => 8289.8691 p/s,   98.1520 Mb/s
6731(1447110054)#traffic-generator (INFO): Port    8:    155950 SDUs,    230806000 bytes in     20080 ms, 91.9546 Mb/s

**Comment by edugrasa** [comment]
@kewinrausch do you think I can close this issue?

**Comment by kewinrausch** [comment]
Let me try with up-to-date 4.x branch et all first.

**Comment by kewinrausch** [comment]
After ethtool setting i got:
```
-------------------------> alpha <-------------------------

Settings for eth15:
        Supported ports: [ TP ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: Yes
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Speed: 100Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: off
        MDI-X: off (auto)
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes


-------------------------> bravo <-------------------------

Settings for eth13:
        Supported ports: [ MII ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: Yes
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Speed: 100Mb/s
        Duplex: Full
        Port: MII
        PHYAD: 3
        Transceiver: external
        Auto-negotiation: off
        Supports Wake-on: g
        Wake-on: d
        Link detected: yes


-------------------------> charlie <-------------------------

Settings for eth13:
        Supported ports: [ TP ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: Yes
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Speed: 100Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 1
        Transceiver: internal
        Auto-negotiation: off
        MDI-X: off (auto)
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes


-------------------------> charlie <-------------------------

Settings for eth14:
        Supported ports: [ TP ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: Yes
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Speed: 100Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 1
        Transceiver: internal
        Auto-negotiation: off
        MDI-X: off (auto)
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes


-------------------------> charlie <-------------------------

Settings for eth12:
        Supported ports: [ TP ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: Yes
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Speed: 100Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 1
        Transceiver: internal
        Auto-negotiation: off
        MDI-X: off (auto)
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes


-------------------------> delta <-------------------------

Settings for eth14:
        Supported ports: [ MII ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: Yes
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Speed: 100Mb/s
        Duplex: Full
        Port: MII
        PHYAD: 3
        Transceiver: external
        Auto-negotiation: off
        Supports Wake-on: g
        Wake-on: d
        Link detected: yes
```

Configuration:
```
{
                "name" : "unreliablewithflowcontrol",
                "id" : 1,
                "partialDelivery" : false,
                "orderedDelivery" : true,
                "efcpPolicies" :
                {
                        "dtpPolicySet" :
                        {
                                "name" : "default",
                                "version" : "1"
                        },
                        "initialATimer" : 300,
                        "dtcpPresent" : true,
                        "dtcpConfiguration" :
                        {
                                "dtcpPolicySet" :
                                {
                                        "name" : "default",
                                        "version" : "1"
                                },
                                "rtxControl" : false,
                                "flowControl" : false
                        }
                }
        },
```
Still getting, on server:
```
4608(1447411620)#traffic-generator (INFO): Port    2:    732781 SDUs,    366390500 bytes in     60087 ms, 48.7813 Mb/s
```
while the client reported:
```
22736(1447415163)#traffic-generator (INFO): sent statistics:   6298034 SDUs,   3149017000 bytes in  60002443 us, 419.8518 Mb/s
```

**Comment by kewinrausch** [comment]
I repeated the tests today again, same conf file and eth tools restriction, but this time instead of hacing an intermediate node I had point-to-point direct communication between client and server.

So from: A - - - C - - - D to C - - - D.

The result of such run are:

CLIENT
```
4310(1447660793)#traffic-generator (INFO): sent statistics:   1243683 SDUs,    621841500 bytes in  60003328 us, 82.9076 Mb/s
```

SERVER
```
3861(1447660793)#traffic-generator (INFO): Port    2:   1225559 SDUs,    612779500 bytes in     60182 ms, 81.4568 Mb/s
```

So it seems that, less or more, the bandwidth restriction are respected (obviously not looking at the performance of the stack). I repeated the experiment on other couple of my small net (A to C, for example) and i got similar results.

Can it be that having a node relaying in between cut of lot of bandwidth (well, less or more half of it)?

**Comment by kewinrausch** [comment]
Ok, now the same experiment did as my last comment of 1h ago produced the effect.
```
29286(1447665746)#traffic-generator (INFO): Port    2:   1222726 SDUs,    611363000 bytes in     60072 ms, 81.4174 Mb/s
```
So it seems to go, even if before the performance were not in line with the restriction. Running a longer experiment (than 60 seconds) lead my client to a log of logs report like:
```
Nov 16 10:24:52 alpha kernel: [ 5831.965695] rina-rmt(ERR): Failed to send a PDU to port-id 1
Nov 16 10:24:52 alpha kernel: [ 5831.969899] rina-rmt(ERR): ps or ps->requeue_tx null, dropping PDU
```

and:
```
Nov 16 10:26:48 alpha kernel: [ 5943.336512] rina-rmt(ERR): Could not find the N-1 port
Nov 16 10:26:48 alpha kernel: [ 5943.336513] rina-rmt(ERR): Failed to send a PDU to port-id 1
```

which ultimately lead my client node to:
```
Nov 16 10:26:48 alpha kernel: [ 5944.337298] NMI watchdog: BUG: soft lockup - CPU#3 stuck for 23s! [kworker/3:1:64]
```

So ultimately seems that the stack is going, after some pushing, less or more under the given restriction, if I keep the experiment limited. Now I'm investigating this last problem.

**Comment by kewinrausch** [comment]
I logged an interesting problem on the vWall, or so it seems. This can also be the source of the problems that I bound to ethtool, and that probably was not really coming from ethtool.

I setup the experiment (always same topology) to go at 80Mb/s, and run the client-server in order to register the effective performances between the nodes.

On my client I got:
```
15153(1447679364)#traffic-generator (INFO): sent statistics:   1204545 SDUs,    602272500 bytes in  59999566 us, 80.3036 Mb/s
```

while the server computes:
```
15037(1447679365)#traffic-generator (INFO): Port    3:     13261 SDUs,      6630500 bytes in     60152 ms, 0.8818 Mb/s
```

I spent all the morning looking for the problem (I saw that no-flow control communication was working less or more good, with 400Mb/s performances), and I was thinking about a problem in the rate based implementation too.

But after seeing that the client respect the rate, and the intermediate node does not report any problem, I looked at more basic problems. So after a logging of the networking interfaces I got:

Before experiment (note, the numbers are the packets visible by **ifconfig** statistics):
```
alpha: 0 <- - - - - - - - - -> 0 charlie 0 <- - - - - - - - - -> 0 delta
```

After the experiment:
```
alpha: 1204387 <- - - - - - - - - -> 1204385 charlie 1204384 <- - - - - - - - - -> 13896 delta
```

This is a huuuuuge difference (and respect the proportion of the performances I got), but the intermediate node and the client are sending the right amount of traffic (80Mb/s) while the server is only receiving a very little part of this. 

The problem really **seems to be located in vWall** networks, or so the test say this.

This could also generate the problem of ethtool bad response; it was not ethtool the problem, but the network itself.

**Comment by kewinrausch** [comment]
Aaaawww.. c'mon!!!

From Delta to Charlie:
```
------------------------------------------------------------
Client connecting to 192.168.2.2, UDP port 5001
Sending 1470 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 192.168.2.3 port 35255 connected with 192.168.2.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-30.0 sec   286 MBytes  80.0 Mbits/sec
[  3] Sent 204082 datagrams
[  3] Server Report:
[  3]  0.0-30.0 sec   286 MBytes  80.0 Mbits/sec   0.005 ms    0/204081 (0%)
[  3]  0.0-30.0 sec  1 datagrams received out-of-order
```

From Alpha to Charlie:
```
------------------------------------------------------------
Client connecting to 192.168.3.3, UDP port 5001
Sending 1470 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 192.168.3.2 port 49903 connected with 192.168.3.3 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-30.0 sec   286 MBytes  80.0 Mbits/sec
[  3] Sent 204083 datagrams
[  3] Server Report:
[  3]  0.0-30.0 sec   286 MBytes  80.0 Mbits/sec   0.011 ms    0/204082 (0%)
[  3]  0.0-30.0 sec  1 datagrams received out-of-order
```
And the difference between sent packet and received ones is 0, so no lost/dropped.

With iperf the problem seems not to emerge. 
Now I don't know where to hit my head. :sob:

**Comment by edugrasa** [comment]
@kewinrausch is this still happening with latest pristine-1.4?

**Comment by kewinrausch** [comment]
Dunno, I'm testing with local testbed now. 

From what I have detected (together with Dimitri), the problem **seems** to be the nvidia network card driver with the shim over eth.

**Comment by edugrasa** [comment]
@kewinrausch any updates about this? What should we do with this issue?

**Comment by kewinrausch** [comment]
@edugrasa: I don't have this anymore. You can close this issue. :)

**Comment by edugrasa** [comment]
Great!
