### ISSUE TITLE
Pristine-1.4: Difference of performance between client/server when using asyc/no Flow Control

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#798]
This problem has been detected on **real PC** (not virtualized ones), but the issue can be absolutely (and probably is) independent from this aspect.

**How to replicate it:** 
use a simple network "on-a-line" with one relaying node in the middle. Something like A - - B - - C, with A and C running client/server instances shall be enough to detect this. I actually am able to see the problem with one DIF over a shim configuration.

**NO Flow Control test:**
```
Client:
8859(1448288258)#traffic-generator (INFO): sent statistics: 5914461 SDUs, 2957230500 bytes in  29999011 us, 788.6208 Mb/s

Server:
8762(1448302730)#traffic-generator (INFO): Port 3: 415738 SDUs, 207869000 bytes in 30231 ms, 55.0082 Mb/s
```
Here, as you can see, there's a huge amount of difference between the two.

**Rate based Flow Control test, with 10 Mb/s:**
```
Client:
10684(1448288622)#traffic-generator (INFO): sent statistics: 75747 SDUs, 37873500 bytes in  30052185 us, 10.0821 Mb/s

Server:
10606(1448303095)#traffic-generator (INFO): Port 4: 73989 SDUs, 36994500 bytes in 30118 ms, 9.8265 Mb/s
```
Everything goes well when 10Mb/s is used (and the interface is not limited with external tools, like ethtool).

**Rate based Flow Control test, with 100 Mb/s:**
```
Client:
15049(1448289487)#traffic-generator (INFO): sent statistics: 754331 SDUs, 377165500 bytes in  30060883 us, 100.3738 Mb/s

Server:
14864(1448303960)#traffic-generator (INFO): Port 6: 379337 SDUs, 189668500 bytes in 30361 ms, 49.9769 Mb/s
```
Sending rate is respected, but the receiving one if very bad. Note that the links/interfaces are fully able to handle such speed.

**Comment by edugrasa** [comment]
@kewinrausch is this still happening with latest pristine-1.4?

**Comment by kewinrausch** [comment]
Tests with faster rates produced good results, so i guess this problem has been resolved.

I still measured performance degradation with NO flow control when sending from client to server with an intermediate node. I'll post a more precise issue if I find where this problem take place in the stack.

You can close this one for now.
