### ISSUE TITLE
Pristine-1.4: Policies can be build only in certain directories

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#823]
Kernel-mode policies which uses the template Makefile works only if you put the sources (and so the make file) in a precise location: two folder deep than the linux source folder. This is a false assumption.

This is due the statement:
```
KDIR=../../linux
```

Linux kernel Documentation about modules et all says to format the Makefile as follows:
```
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd)

install:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) modules_install

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) clean
```

Of course personalization shall be introduced, but this format allow to abstract from kernel version and file system location of the sources.

**Comment by vmaffione** [comment]
No, this is not what we want.

The makefile you are proposing is designed to build out-of-tree kernel modules against your running kernel (e.g. using the Kbuild of your running kernel).

Since we have an ad-hoc IRATI kernel, the plugins (modules) must be compiled against the IRATI kernel, which is not necessary the running kernel.

Think of a guy that clones the IRATI repository on his machine. He's not running the IRATI kernel for sure. As a consequence, when he tries to build a plugin using such a Makefile, the compilation (and also linking and loading) will fail, because - among the other problems - it won't find the IRATI-specific kernel symbols.

To the converse, now that I'm noticing this (thanks :) ), I'm changing all the Makefiles to use something like
````
KER=../../linux
````

**Comment by kewinrausch** [comment]
I don't agree with this, but if it's a project policy then no problem. :)

**Comment by vmaffione** [comment]
It's not a project policy, it's a matter of correctness and functionality.

What exactly don't you agree?
How do you manage the case where you are compiling a kernel plugin into a machine that is not running the IRATI kernel - which is the common case for a new user?

**Comment by kewinrausch** [comment]
Simply the Makefile will inform that is not possible to compile the module because some part on the kernel are missing. This is what happens also with the normal Linux kernel if you try to compile modules which are not maintained up-to-date with the kernel API updates (which happens with major changes on the kernel). This is even more true with some research projects which are done and then no more updated.

When an additional argument is introduced or changed, the module that you try to build simply will notify to you about the error, so you are informed about the problem (your current kernel has no IRATI support). 

This can also be an additional WARNING if you try to use the module but you did not boot with IRATI kernel. If you try this now the only problem inserting such modules (and I tried this) is that Netlink does not recognize the messages/protocol. This can be a legit problem (triggered by a bug or else), and one can start spending lot of time trying to realize why Netlink does not work, while the only solution is to boot in IRATI.

**Comment by vmaffione** [comment]
But it is possible to build modules for a kernel different from the one you're running. This is what the current Makefile does. And the problem with your solution is that it is not able to do it. That's why I was asking how would you manage it.

Of course you need to boot the IRATI kernel if you want to use IRATI and its modules/plugins. But here we are just talking about building, not running.

If you try insmod a kernel plugin into a non-IRATI running kernel (at least with the current plugin Makefiles), the operation will fail because the module system recognizes that the module was built for a different kernel. In this way you're safe.

**Comment by kewinrausch** [comment]
If you make them build successfully under another kernel they can try to load it under that kernel. If you load the module in a non IRATI kernel you only get the Netlink error (tried yesterday with pristine-1.4 last version), and working with IRATI for 1 year and so I immediately recognized the problem. Someone which use it for the first time could take a little more to remember to boot in IRATI. If you compiled it successfully, it should go.

You probably use that solution because you don't boot in IRATI until you launch your qemu VM, and you want to build the modules outside. 

I'm used to build IRATI, boot in it and them perform building/testing directly inside the IRATI compiled kernel (while having a shared/ssh sync. folder of something else which contains the sources, which i edit from my host system). I adopted this system because i have to work via ssh on real machines (sending changes on policy modules/kernel without issuing 100 small commits [or re-basing] in Git), not only on VMs (and so i have one procedure which goes for both the case).

Is just a matter of correctness and functionality on HOW you are used to test your system, and not in general. 100 person can have 100 correct ways to do the same operation. In my personal opinion saying: "Stop, this is not the right kernel" during compilation is right.

Correctness and functionality is bound to the person, so maybe it has to be forced as a policy of the project.

**Comment by edugrasa** [comment]
I also agree with Vincenzo, I wouldn't like to require developers to load our kernel just for building a module. Sometimes people use a setup in which the development machine is not the test machine, therefore requiring them to work with our modified kernel just to build the module is adding a burden that is really not required.

**Comment by kewinrausch** [comment]
And some people does not have Linux on their host machine, nor they can/want to install it. 

Compiling a module without trying it in my opinion makes no sense, and to try it you have to dispatch to an IRATI kernel (so regardless of the setup the kernel must be compiled somewhere) on a VM or on another testing node. Even if you dispatch to a VM, you need to use it on a real machine, otherwise there can be problems (which all of us have seen).

Well, this is not an issue in the end, so it can be closed. I told my opinion; everything is up to IRATI maintainers.

**Comment by edugrasa** [comment]
Compile in one machine (e.g. laptop), deploy and test in different ones (e.g. VM farm, Virtual Wall, etc), that is a development model we want to support (as far as I understood from Vincenzo, and I agree also). 

You don't want to support it, if I understood correctly? The other maintainers should express their opinions as well, and then let's decide.

**Comment by vmaffione** [comment]
@kewinrausch
I'm also used to build IRATI and modules in a machine running the IRATI kernel, but that's not the point. Here we are not discussing about testing or running, just about building.
People do their test as they wish, as you pointed out.

The point is that the makefile you are proposing is exactly **the source of the problems you are describing**, because you are allowing to build the IRATI modules (e.g. plugins) against your running kernel, which could be non-IRATI.

The current makefiles, instead, (KDIR=../../linux) make sure that you always build the plugins against the IRATI kernel, **independently on the running kernel**. In this way, if you try to load the build plugins into a non-IRATI kernel, the insmod operation will automatically fail (because modules contain information). And this is the behaviour we want.

Moreover, current makefiles allow to correctly build IRATI kernel modules irrespective of the running kernel.

Let's summarize.
Current solution:
   A) Builds the IRATI modules only for the IRATI kernel, does not allow to build the modules for not-IRATI kernel (which leads to the problems you described). So this is **safe**.
   B) Allow to build the IRATI modules, independently of the running kernel being IRATI or not.This is flexible, and handy for newcomers (to @edugrasa, yes cross-compilation is what one would normally do, but also compiling the IRATI kernel from the distro kernel, to be run on the same machine).
   C) insmod prevent you from loading IRATI modules on non-IRATI kernel, automatically.

Proposed alternative:
   D) Build the IRATI modules against the current kernel, be it IRATI or non-IRATI.If you build against non-IRATI, you have two cases. 1) Compilation fails --> good, you know you're doing it wrong. 2) Compilation ok --> you won't see anything, but when you load the modules, it will malfunction.

Apparently, this is not a matter of opinions. I don't see any reason why we should fall back to a solution that comes with disadvantages (D) and removes existing advantages(A,B,C).

IOW, I still don't see your point :)

**Comment by kewinrausch** [comment]
@vmaffione 

> A) Builds the IRATI modules only for the IRATI kernel, does not allow to build the modules for not-IRATI kernel (which leads to the problems you described). So this is safe.

And you will not build also with the other approach; as you said it miss the necessary element to complete the compilation (net/rina is missing, headers not found!).

> B) Allow to build the IRATI modules, independently of the running kernel being IRATI or not. This is flexible, and handy for newcomers (to @edugrasa, yes cross-compilation is what one would normally do, but also compiling the IRATI kernel from the distro kernel, to be run on the same machine).

This is right, but cross compilation is not the default/first choice (as it is now). Usually projects build against the current kernel and then you can decide to cross-compile for another platform/version.

> C) insmod prevent you from loading IRATI modules on non-IRATI kernel, automatically.

This is right for both the approach, but building against the current kernel does not generate the .ko if you are in not-IRATI kernel. There are not the necessary headers/kAPI.

> D) Build the IRATI modules against the current kernel, be it IRATI or non-IRATI.If you build against non-IRATI, you have two cases. 1) Compilation fails --> good, you know you're doing it wrong. 2) Compilation ok --> you won't see anything, but when you load the modules, it will malfunction.

Case 2 is not possible, because the kernel has no rina/net folder.

> Apparently, this is not a matter of opinions. I don't see any reason why we should fall back to a solution that comes with disadvantages (D) and removes existing advantages(A,B,C).

Apparently A is for both, B is not lost because you can always use (as Linux documentation says in the "shared Makefile" chapter): 
```
KDIR ?= /lib/modules/`uname -r`/build
```
and C does not happens with the other approach (because of the missing net/rina in the linux kernel). If the official linux kernel support net/rina (because in the future it's possible for it to be merged) then still I don't see the problem, because it will always be present.

Counting up: 
current IRATI approach: (A, B, C)
eventual approach: B + compatibility with the Linux kernel build rules

@edugrasa 
> Compile in one machine (e.g. laptop), deploy and test in different ones (e.g. VM farm, Virtual Wall, etc), that is a development model we want to support (as far as I understood from Vincenzo, and I agree also). You don't want to support it, if I understood correctly? The other maintainers should express their opinions as well, and then let's decide.

No, i want to support an even wider case: you don't have to have the building system on your PC (forcing you to install Linux on it), but you can always use it if that's the case. As a result Windows and Mac and whatever else users can have their own (favourite) editor and organize policies as they want (must not be in that folder) without messing up with make files.

If they want to cross compile, the options is always there to allow it to doing so.

**@ both:**
I will also want to remember you that someone want to compile the kernel on a machine and dispatch only the kernel image and the headers in a remote system (in order to avoid that hell of compilation on every IRATI node!) though make-kpkg. 

In that case you wont have the IRATI folder on the node, but you have the headers, and the system I'm proposing still works.

**Comment by vmaffione** [comment]
2015-12-22 16:20 GMT+01:00 Kewin Rausch <notifications@github.com>:

> @vmaffione <https://github.com/vmaffione>
>
> A) Builds the IRATI modules only for the IRATI kernel, does not allow to
> build the modules for not-IRATI kernel (which leads to the problems you
> described). So this is safe.
>
> And you will not build also with the other approach; as you said it miss
> the necessary element to complete the compilation (net/rina is missing,
> headers not found!).
>
yes, but current solution it's safer anyway, we don't even allow people to
try to do that (which would be wrong).

> B) Allow to build the IRATI modules, independently of the running kernel
> being IRATI or not. This is flexible, and handy for newcomers (to
> @edugrasa <https://github.com/edugrasa>, yes cross-compilation is what
> one would normally do, but also compiling the IRATI kernel from the distro
> kernel, to be run on the same machine).
>
> This is right, but cross compilation is not the default/first choice (as
> it is now). Usually projects build against the current kernel and then you
> can decide to cross-compile for another platform/version.
>
This is an opinion of yours ;)
It's not a matter of choices, there is no reason why we should move to a
solution that lose flexibility. This is like saying "most people use
software X with Linux, so if we change X in such a way that creates
problems with FreeBSD, who cares".

> C) insmod prevent you from loading IRATI modules on non-IRATI kernel,
> automatically.
>
> This is right for both the approach, but building against the current
> kernel does not generate the .ko if you are in not-IRATI kernel. There are
> not the necessary headers/kAPI.
>
So why are you saying this

"If you make them build successfully under another kernel they can try to
load it under that kernel. If you load the module in a non IRATI kernel you
only get the Netlink error (tried yesterday with pristine-1.4 last
version), and working with IRATI for 1 year and so I immediately recognized
the problem."


> D) Build the IRATI modules against the current kernel, be it IRATI or
> non-IRATI.If you build against non-IRATI, you have two cases. 1)
> Compilation fails --> good, you know you're doing it wrong. 2) Compilation
> ok --> you won't see anything, but when you load the modules, it will
> malfunction.
>
> Case 2 is not possible, because the kernel has no rina/net folder.
>
> Apparently, this is not a matter of opinions. I don't see any reason why
> we should fall back to a solution that comes with disadvantages (D) and
> removes existing advantages(A,B,C).
>
> Apparently A is for both, B is not lost because you can always use (as
> Linux documentation says in the "shared Makefile" chapter):
>
> KDIR ?= /lib/modules/`uname -r`/build
>
> and C does not happens with the other approach (because of the missing
> net/rina in the linux kernel). If the official linux kernel support
> net/rina (because in the future it's possible for it to be merged) then
> still I don't see the problem, because it will always be present.
>
Again, so what are the netlink errors you are talking about?


> Counting up:
> current IRATI approach: (A, B, C)
> eventual approach: B + compatibility with the Linux kernel build rules
>
> @edugrasa <https://github.com/edugrasa>
>
> Compile in one machine (e.g. laptop), deploy and test in different ones
> (e.g. VM farm, Virtual Wall, etc), that is a development model we want to
> support (as far as I understood from Vincenzo, and I agree also). You don't
> want to support it, if I understood correctly? The other maintainers should
> express their opinions as well, and then let's decide.
>
> No, i want to support an even wider case: you don't have to have the
> building system on your PC (forcing you to install Linux on it), but you
> can always use it if that's the case. As a result Windows and Mac and
> whatever else users can have their own (favourite) editor and organize
> policies as they want (must not be in that folder) without messing up with
> make files.
>
> The build system works only on Linux, so you need it anyways. How your
proposal helps building on Windows or mac?
Nobody is preventing you from using your own Makefile to build kernel
plugins.
Here we are discussing about the plugins in the IRATI repository.


> If they want to cross compile, the options is always there to allow it to
> doing so.
>
> *@ both:*
> I will also want to remember you that someone want to compile the kernel
> on a machine and dispatch only the kernel image and the headers in a remote
> system (in order to avoid that hell of compilation on every IRATI node!)
> though make-kpkg.
>
> In that case you wont have the IRATI folder on the node, but you have the
> headers, and the system I'm proposing still works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/823#issuecomment-166644588>.
>



-- 
Vincenzo Maffione

**Comment by kewinrausch** [comment]
> So why are you saying this "If you make them build successfully under another kernel they can try to load it under that kernel. If you load the module in a non IRATI kernel you only get the Netlink error (tried yesterday with pristine-1.4 last version), and working with IRATI for 1 year and so I immediately recognized the problem."

My error, that was user-space application logs. I confused it.
I tried 20 minutes ago and the insmod does not allow you to load it.

> This is an opinion of yours ;)

Not a my opinion.<_< 
If you want to dispatch kernel policies as kernel modules then you have to follow what they (Linux kernel official maintainers) say about it (and we are building such module externally from the IRATI kernel). Reference: https://www.kernel.org/doc/Documentation/kbuild/modules.txt
Unless you want to do a particular setup, which is actually what you are doing. So, if you want to do a particular setup for "safer" purpose, then no problem. But then is you which are assuming that X software is most used.

Besides, you do not loose flexibility... at all... You gain flexibility (not forced to place the policies inside a fixed folder). The KDIR can always be rewritten for cross-compiling, but that is the default proposed (again, not by me but by kernel documentation).

```
KDIR ?= /lib/modules/`uname -r`/build
```

> Again, so what are the netlink errors you are talking about?

From the user-space part. If you try to run the ipcm in a non-IRATI kernel you get that error.
My bad for confusing it with the kernel plugins.

> proposal helps building on Windows or mac?

Not building, but having a Mac/Windows host, or you can see it as assuming that the ideal IRATI user is not forced to use Linux on it's host. I never speak to try to build it (Linux kernel) on Windows/Mac. I don't even think that it's possible by now.

> Here we are discussing about the plugins in the IRATI repository.

I'm speaking about plugins Makefiles for IRATI. If you assume that no plugins will ever exists outside the irati/plugins folder, then no problem about that. But again, you force a policy for IRATI source code structure.
Of course one can always dump the Makefile and do one itself; I did that (because i don't cross-compile having a Windows host).

**Comment by vmaffione** [comment]
2015-12-22 17:14 GMT+01:00 Kewin Rausch <notifications@github.com>:

> So why are you saying this "If you make them build successfully under
> another kernel they can try to load it under that kernel. If you load the
> module in a non IRATI kernel you only get the Netlink error (tried
> yesterday with pristine-1.4 last version), and working with IRATI for 1
> year and so I immediately recognized the problem."
>
> My error, that was user-space application logs. I confused it.
> I tried 20 minutes ago and the insmod does not allow you to load it.
>
> This is an opinion of yours ;)
>
> Not a my opinion.<_<
> If you want to dispatch kernel policies as kernel modules then you have to
> follow what they (Linux kernel official maintainers) say about it (and we
> are building such module externally from the IRATI kernel). Reference:
> https://www.kernel.org/doc/Documentation/kbuild/modules.txt
>

>

> Unless you want to do a particular setup, which is actually what you are
> doing. So, if you want to do a particular setup for "safer" purpose, then
> no problem. But then is you which are assuming that X software is most used.
>
I know what this document says, but yes, we are doing a safer setup, for
the plugins in the repo. You are free to use your custom makefile for your
out-of-repo plugins.The only important think is that you build your plugin
against an IRATI kernel.


> Besides, you do not loose flexibility... at all... You gain flexibility
> (not forced to place the policies inside a fixed folder). The KDIR can
> always be rewritten for cross-compiling, but that is the default proposed
> (again, not by me but by kernel documentation).
>
> KDIR ?= /lib/modules/`uname -r`/build
>
>
You are not forced to place policies in a fixed folder, all you have to do
is change the KDIR variable. Here

https://github.com/IRATI/stack/pull/827

you can set KDIR if you're not happy with it.

> Again, so what are the netlink errors you are talking about?
>
> From the user-space part. If you try to run the ipcm in a non-IRATI kernel
> you get that error.
> My bad for confusing it with the kernel plugins.
>
> proposal helps building on Windows or mac?
>
> Not building, but having a Mac/Windows host, or you can see it as assuming
> that the ideal IRATI user is not forced to use Linux on it's host. I never
> speak to try to build it (Linux kernel) on Windows/Mac. I don't even think
> that it's possible by now.
>
> Here we are discussing about the plugins in the IRATI repository.
>
> I'm speaking about plugins Makefiles for IRATI. If you assume that no
> plugins will ever exists outside the irati/plugins folder, then no problem
> about that. But again, you force a policy for IRATI source code structure.
> Of course one can always dump the Makefile and do one itself; I did that
> (because i don't cross-compile having a Windows host).
>
We really want to have uniform makefiles, it's easier to maintain. Plugins
in the IRATI repo are going to be in that folder, that was decided a while
ago.
Then people can develop their plugins, out of the IRATI repo, and can then
use whatever makefile they want.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/823#issuecomment-166662883>.
>



-- 
Vincenzo Maffione

**Comment by kewinrausch** [comment]
Ok, then is a policy of the IRATI project (to maintain a safer approach), and I wont discus it more. :)
I'm not here to discuss chosen policies; I was just pointing out what the official kernel document says.

**Comment by vmaffione** [comment]
Yes, it's a safer approach.

But it is also conformant to what documentation (
https://www.kernel.org/doc/Documentation/kbuild/modules.txt) says:

````

	The command to build an external module is:

		$ make -C <path_to_kernel_src> M=$PWD

	The kbuild system knows that an external module is being built
	due to the "M=<dir>" option given in the command.

	To build against the running kernel use:

		$ make -C /lib/modules/`uname -r`/build M=$PWD


````


And we don't want to build against the running kernel by default, so we use
the first option.

Moreover, we already used the shared makefile, and I fixed the Makefiles in
plugins/rdsr-ps/ to use that too.

Finally, we already perform installation in the right way:

````

Modules which are included in the kernel are installed in the
directory:

	/lib/modules/$(KERNELRELEASE)/kernel/

And external modules are installed in:

	/lib/modules/$(KERNELRELEASE)/extra/


````
You see here it doesn't use $(shell uname -r). And that's what we want,
because we always want to install into /lib/modules/4.1.0-irati (or
similar).


2015-12-23 8:58 GMT+01:00 Kewin Rausch <notifications@github.com>:

> Ok, then is a policy of the IRATI project (to maintain a safer approach),
> and I wont discus it more. :)
> I'm not here to discuss chosen policies; I was just pointing out what the
> official kernel document says.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/823#issuecomment-166829936>.
>



-- 
Vincenzo Maffione

**Comment by edugrasa** [comment]
I guess we can close this issue, right?
