### ISSUE TITLE
Pristine-1.4: Memory leak(s) in PFF module

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#833]
This is present in Multipath one, but i encountered it in Loop-free policy so probably it's inherithed from the dummy one and ported to all the others.

When the policy instance is created, and a fail occurs on ```ps``` allocation, the priv data is never released.
```
priv = rkzalloc(sizeof(*priv), GFP_KERNEL);

[...]

ps = rkzalloc(sizeof(*ps), GFP_KERNEL);
if (!ps)
    return NULL;
```
See: https://github.com/IRATI/stack/blob/pristine-1.4/plugins/lfa/ps.c#L671

**Comment by kewinrausch** [comment]
Another one, same thing as before, but in a different place.

https://github.com/IRATI/stack/blob/pristine-1.4/plugins/lfa/ps.c#L602

**Comment by vmaffione** [comment]
Good catch! You can provide a patch for it, if you want

2016-01-14 14:31 GMT+01:00 Kewin Rausch <notifications@github.com>:

> Another one, same thing as before, but in a different place.
>
> https://github.com/IRATI/stack/blob/pristine-1.4/plugins/lfa/ps.c#L602
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/833#issuecomment-171645557>.
>



-- 
Vincenzo Maffione

**Comment by kewinrausch** [comment]
I'm still analyzing the policy, to see if there's something more...

**Comment by vmaffione** [comment]
ok, thanks!

2016-01-14 14:44 GMT+01:00 Kewin Rausch <notifications@github.com>:

> I'm still analyzing the policy, to see if there's something more...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/833#issuecomment-171647955>.
>



-- 
Vincenzo Maffione

**Comment by kewinrausch** [comment]
PR for the fix of such memory leaks: https://github.com/IRATI/stack/pull/834
