### ISSUE TITLE
Echo time rina default policy set failed to set default policy while running ipcmanager.conf-normalovereth1 test program. 

### ISSUE THREAD

**Issue by rskumar9** [IRATI/stack#843]
Installed latest Irati stack in debian 8.2. No issues in installation complete successfully both user and kernel space modules.

while running test program echo time with  ipcmanager.conf-normalovertcpudp conf file. Echo time normal DIF registration with shim-tcp-udp DIF  with  the error Policy set ' ' failed to load. I did modprobe rina-default-plugin + modprobe shim-tcp-udp + modprobe normal-ipcp. All modules loaded without any error, but when i use policy paramter in the policy set at the below lines in default.dif getting the error as not able to use the plugin set. "local configuration" parameters of all the path location of modules are given correct in the ipcmanager.conf-normalovertcpudp conf file also. below is the snippet where i am getting issue.
"rmtConfiguration" : {
        "pftConfiguration" : {
          "policySet" : {
            "name" : "default",
            "version" : "0"
          }
        },
        "policySet" : {
          "name" : "default",
          "version" : "1"
        }

In the ipc-manager console if i type show-catalog empty. no plugin details are coming. So I dont know why rina plugin modules are not loading. I will be very greatful if anyone help me to solve this issue.

**Comment by vmaffione** [comment]
Can you post the exact IPCM configuration file you are using?

**Comment by edugrasa** [comment]
Are you using the master branch?

**Comment by sandervrijders** [comment]
Probably pftConfiguration should be changed to pffConfiguration

**Comment by vmaffione** [comment]
Yes, @sandervrijders  is right

**Comment by rskumar9** [comment]
Thanks for all your reply's. I am using master branch only(4.1.10). Even I changed to pffconfiguration in the defaul.dif configuration file. but still problem persists. I think something is wrong in shim-tcp-udp file itself in the below 2 lines.
         "dirEntry" : "1:25:rina.apps.echotime.server0:192:168.0.101:2426",
         "expReg" : "1:25:rina.apps.echotime.server0:4:2426" 

Getting Error in syslog file as follows
Jan 27 06:06:49 debian kernel: [ 1887.044672] rina-shim-tcp-udp(ERR): Failed to convert int
Jan 27 06:06:49 debian kernel: [ 1887.044674] rina-shim-tcp-udp(ERR): Failed to convert ip to int
Jan 27 06:06:49 debian kernel: [ 1887.044674] rina-shim-tcp-udp(ERR): Failed to parse configuration
Jan 27 06:06:49 debian kernel: [ 1887.044681] rina-kipcm(ERR): Assign to dif shim/// operation failed for IPC process 1

If i modify this parameter with by removing the ":4:" like this "expReg" : "1:25:rina.apps.echotime.server0:2426"  the entire system hangs i need to reboot it again.

CONF files are as follows
ipcmanager.conf-normalovertcpudp1
{
   "localConfiguration": {
        "installationPath": "/bin",
        "libraryPath": "/home/srm/stack/linux/lib",
        "logPath": "/var/log",
        "consolePort": 32766,
        "pluginsPaths": [
                "/lib/modules/4.1.10/kernel/net/rina/ipcps",
                "/lib/modules/4.1.10/kernel/net/rina"
        ]
    },
    "applicationToDIFMappings": [
        {
            "encodedAppName": "rina.apps.echotime.server-1--",
            "difName": "test1.IRATI"
        }
    ],
    "ipcProcessesToCreate": [
        {
            "apName": "test-eth",
            "apInstance": "1",
            "difName": "shim.DIF"
        },
        {
            "apName": "test1.IRATI",
            "apInstance": "1",
            "difName": "normal.DIF",
            "difsToRegisterAt": [
                "shim.DIF"
            ]
        }
    ],
    "difConfigurations": [
        {
             "name" : "shim.DIF",
             "template" : "shim-tcp-udp.dif"
        },
        {
            "name": "normal.DIF",
            "template": "default.dif"
        }
    ]
}

default.dif
{
    "difType" : "normal-ipc",
    "dataTransferConstants" : {
        "addressLength" : 2,
        "cepIdLength" : 2,
        "lengthLength" : 2,
        "portIdLength" : 2,
        "qosIdLength" : 2,
        "sequenceNumberLength" : 4,
        "maxPduSize" : 10000,
        "maxPduLifetime" : 60000
    },
    "qosCubes" : [ {
         "name" : "unreliablewithflowcontrol",
         "id" : 1,
         "partialDelivery" : false,
         "orderedDelivery" : true,
         "efcpPolicies" : {
              "dtpPolicySet" : {
                "name" : "default",
                "version" : "0"
              },
              "initialATimer" : 300,
              "dtcpPresent" : true,
              "dtcpConfiguration" : {
                   "dtcpPolicySet" : {
                     "name" : "default",
                     "version" : "0"
                   },
                   "rtxControl" : false,
                   "flowControl" : true,
                   "flowControlConfig" : {
                       "rateBased" : false,
                       "windowBased" : true,
                       "windowBasedConfig" : {
                         "maxClosedWindowQueueLength" : 50,
                         "initialCredit" : 50
                        }
                   }
              }
 }
       }, {
         "name" : "reliablewithflowcontrol",
         "id" : 2,
         "partialDelivery" : false,
         "orderedDelivery" : true,
         "maxAllowableGap": 0,
         "efcpPolicies" : {
              "dtpPolicySet" : {
                "name" : "default",
                "version" : "0"
              },
              "initialATimer" : 300,
              "dtcpPresent" : true,
              "dtcpConfiguration" : {
                   "dtcpPolicySet" : {
                     "name" : "default",
                     "version" : "0"
                   },
                   "rtxControl" : true,
                   "rtxControlConfig" : {
                       "dataRxmsNmax" : 5,
                       "initialRtxTime" : 1000
                   },
                   "flowControl" : true,
                   "flowControlConfig" : {
                       "rateBased" : false,
                       "windowBased" : true,
                       "windowBasedConfig" : {
                         "maxClosedWindowQueueLength" : 50,
                         "initialCredit" : 50
                            }
                        }
                  }
         }
     } ],
     "knownIPCProcessAddresses" : [ {
         "apName" : "test1.IRATI",
         "apInstance" : "1",
         "address" : 16
          }, {
         "apName" : "test2.IRATI",
         "apInstance" : "1",
         "address" : 17
        } ],
        "addressPrefixes" : [ {
         "addressPrefix" : 0,
         "organization" : "N.Bourbaki"
          }, {
         "addressPrefix" : 16,
         "organization" : "IRATI"
      } ],
  "rmtConfiguration" : {
        "pffConfiguration" : {
          "policySet" : {
            "name" : "default",
            "version" : "0"
          }
        },
        "policySet" : {
          "name" : "default",
          "version" : "1"
        }
     },
     "enrollmentTaskConfiguration" : {
        "policySet" : {
           "name" : "default",
           "version" : "1",
           "parameters" : [{
               "name"  : "enrollTimeoutInMs",
               "value" : "10000"
             },{
               "name"  : "watchdogPeriodInMs",
               "value" : "30000"
             },{
               "name"  : "declaredDeadIntervalInMs",
               "value" : "120000"
             },{
               "name"  : "neighborsEnrollerPeriodInMs",
               "value" : "30000"
             },{
               "name"  : "maxEnrollmentRetries",
               "value" : "3"
             }]
        }
     },
     "flowAllocatorConfiguration" : {
         "policySet" : {
           "name" : "default",
           "version" : "1"
          }
     },
     "namespaceManagerConfiguration" : {
         "policySet" : {
           "name" : "default",
           "version" : "1"
           }
     },
     "securityManagerConfiguration" : {
         "policySet" : {
           "name" : "default",
           "version" : "1"
           }
     },
     "resourceAllocatorConfiguration" : {
         "pduftgConfiguration" : {
           "policySet" : {
             "name" : "default",
             "version" : "0"

           }
         }
     },
     "routingConfiguration" : {
         "policySet" : {
           "name" : "link-state",
           "version" : "1",
           "parameters" : [{
             "name"  : "objectMaximumAge",
             "value" : "10000"
           },{
             "name"  : "waitUntilReadCDAP",
             "value" : "5001"
           },{
             "name"  : "waitUntilError",
             "value" : "5001"
           },{
             "name"  : "waitUntilPDUFTComputation",
             "value" : "103"
           },{
             "name"  : "waitUntilFSODBPropagation",
             "value" : "101"
           },{
             "name"  : "waitUntilAgeIncrement",
             "value" : "997"
           },{
             "name"  : "routingAlgorithm",
             "value" : "Dijkstra"
           }]
     }
  }
}
~                                                                                                                                     
~                                       

shim-tcp-udp.dif
{
    "difType" : "shim-tcp-udp",
     "configParameters" : {
         "hostname" : "192.168.0.101",
         "dirEntry" : "1:25:rina.apps.echotime.server0:192:168.0.101:2426",
         "expReg" : "1:25:rina.apps.echotime.server0:4:2426"
     }
}

please someone help me to solve this issue. or otherwise i need to go with any older stable version of irati, instead of master branch.. If so which branch version i need to use. Thanks in advance

**Comment by vmaffione** [comment]
please try with pristine-1.4 branch.
Note that you are missing something like "/usr/local/irati/lib/rinad/ipcp" in your pluginsPaths

**Comment by rskumar9** [comment]
yea for me in this path only plugin modules are there
"/lib/modules/4.1.10/kernel/net/rina/ipcps",
"/lib/modules/4.1.10/kernel/net/rina"

**Comment by vmaffione** [comment]
No, but those paths are wrong.
See mine for example:
````
     "pluginsPaths": [
                "/home/vmaffione/irati/local/lib/rinad/ipcp",
                "/lib/modules/4.1.10-irati/extra"
        ]
````

In this case '/home/vmaffione/irati/local' is where the userspace part of the stack (librina, rinad, rina-tools) is installed on my machine. To do so I

````
$ sudo ./install-user-from-scratch /home/vmaffione/irati/local
````

The second path is where custom plugins are installed
````
$ export INSTALLDIR=/home/vmaffione/irati/local
$ cd plugins
$ make && sudo make install
````
````
