### ISSUE TITLE
Failed to allocate flow in the echo-time program with ipcmanager.conf-appovereth conf file

### ISSUE THREAD

**Issue by rskumar9** [IRATI/stack#844]
Server program runs with echo-time -l in the server side terminal with vlan interfaces of 2 machines connected point to point in eth0 interfaces. shim-dif (dif name is 300) and modules are loaded before running client/server programs in both machines. vlan interfaces also created(eth0.300 and its up on both machines) I followed the tutorial to run this program step by step.

when i start the client program echo-time -c 100 in the another machine to connect with server. Program fails with the error message ERR: failed to allocate flow to the server.

Can someone please help me to resolve this issue. It will be very nice. Thanks in advance.

**Comment by lbergesio** [comment]
Could you check the log of the IPCM on both systems when you launch the client? Moreover have you enrolled the IPCPs in the normal DIF?

**Comment by rskumar9** [comment]
this is the log that i am getting error message app is unable to register with dif only in the client side... server app is registered and up, client side only gives this issue when running without normal DIF(ipcmanager.conf-appovereth example).
Jan 27 05:18:30 debian kernel: [ 2678.285724] rina-shim-eth-vlan(ERR): Wrong request, app is not registered
Jan 27 05:18:30 debian kernel: [ 2678.285726] rina-kipcm(ERR): Failed allocating flow request

./rina-echo-time -c 100
2114(1453889910)#librina.logs (DBG): New log level: INFO
2114(1453889910)#librina.nl-manager (INFO): Netlink socket connected to local port 2114 
2114(1453889910)#rina-echo-time (ERR): Failed to allocate a flow
2114(1453889910)#rina-echo-time (ERR): Problems creating flow, exiting

**Comment by rskumar9** [comment]
while running ipcm -c ipcmanager.conf-normalovereth1 at server side application fails to register with DIF... System hangs too. I need to reboot after the run.

Jan 27 05:23:22 debian kernel: [ 2970.028481] rina-arp826-tables(ERR): Cannot add GPA/GHA couple, there is no table for ptype 0xd1f0
Jan 27 05:23:22 debian kernel: [ 2970.028484] rina-shim-eth-vlan(ERR): Failed to register application in ARP

IPCM >>> list-ipcps
Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | test-eth:1:: | shim-eth-vlan | ASSIGNED TO DIF 300 | test1.IRATI-1-- | -
    2 | test1.IRATI:1:: | normal-ipc | INITIALIZED | - | 

./rina-echo-time -l
2137(1453890572)#librina.logs (DBG): New log level: INFO
2137(1453890572)#librina.nl-manager (INFO): Netlink socket connected to local port 2137 
2137(1453890573)#rina-echo-time (ERR): Failed to register application

using master branch IRATI(4.1.10)

**Comment by edugrasa** [comment]
Did you create the VLANs before loading the RINA kernel modules?
