### ISSUE TITLE
pristine-1.4 Kernel BUG when terminating IPC after a failed shim-eth-vlan ipcp creation

### ISSUE THREAD

**Issue by lbergesio** [IRATI/stack#849]
Launch ipcm with a wrong shim-vlan interface (i.e. dif name 110 in eth1 in the configuration file, but eth1.100 in the system). The ipcm will fail to create the shim ipcp as expected. Finish execution with ctrl+c.

Got this:

kernel BUG at net/rina/ipcps/shim-eth-vlan-core.c:196!
[ 1054.108897] invalid opcode: 0000 [#1] SMP 
[ 1054.108897] Modules linked in: normal_ipcp rina_default_plugin shim_eth_vlan rinarp arp826 8021q garp stp llc nfsd auth_rpcgss oid_registry nfs_acl nfs lockd grace fscache sunrpc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbhid hid floppy
[ 1054.108897] CPU: 2 PID: 3231 Comm: ipcm Not tainted 4.1.16 #163
[ 1054.108897] Hardware name: Xen HVM domU, BIOS 4.4.1 06/11/2015
[ 1054.108897] task: ffff8800e3a2e200 ti: ffff88002ec78000 task.ti: ffff88002ec78000
[ 1054.108897] RIP: 0010:[<ffffffffa01b5b98>]  [<ffffffffa01b5b98>] inst_data_mapping_get+0x78/0x80 [shim_eth_vlan]
[ 1054.108897] RSP: 0018:ffff88002ec7bed0  EFLAGS: 00210246
[ 1054.108897] RAX: 000000000000001e RBX: ffff8800eb91b5c0 RCX: ffffea0000bb73c0
[ 1054.108897] RDX: 000000000000001f RSI: 000000000001aac0 RDI: 0000000000000000
[ 1054.108897] RBP: ffff88002ec7bef8 R08: 0000000000000001 R09: 000000018040003f
[ 1054.108897] R10: ffffffff81753a03 R11: 0000000000000000 R12: ffff8800eb91b620
[ 1054.108897] R13: ffff88002f606780 R14: ffff8800eb91b620 R15: 0000000000000000
[ 1054.108897] FS:  0000000000000000(0000) GS:ffff880108e80000(0063) knlGS:00000000f6dfe700
[ 1054.108897] CS:  0010 DS: 002b ES: 002b CR0: 0000000080050033
[ 1054.108897] CR2: 00000000081093d0 CR3: 000000002d21f000 CR4: 00000000001406e0
[ 1054.108897] Stack:
[ 1054.108897]  ffffffffa01b5d44 ffff88002f602180 0000000000000001 ffff88002f602188
[ 1054.108897]  0000000000000000 ffff88002ec7bf28 ffffffff817729d2 0000000000004d98
[ 1054.108897]  0000000000000001 0000000000000000 0000000000000000 ffff88002ec7bf48
[ 1054.108897] Call Trace:
[ 1054.108897]  [<ffffffffa01b5d44>] ? eth_vlan_destroy+0x1a4/0x290 [shim_eth_vlan]
[ 1054.108897]  [<ffffffff817729d2>] kipcm_ipc_destroy+0xc2/0x150
[ 1054.108897]  [<ffffffff817778f9>] SyS_ipc_destroy+0x69/0xa0
[ 1054.108897]  [<ffffffff8178f8c5>] sysenter_dispatch+0x7/0x21
[ 1054.108897] Code: e0 c6 1b a0 e8 aa 72 5d e1 48 89 d8 5b 41 5c 5d c3 66 90 48 c7 c7 e0 c6 1b a0 e8 94 72 5d e1 5b 31 c0 41 5c 5d c3 0f 1f 44 00 00 <0f> 0b 66 0f 1f 44 00 00 0f 1f 44 00 00 48 85 ff 0f 84 dd 01 00 
[ 1054.108897] RIP  [<ffffffffa01b5b98>] inst_data_mapping_get+0x78/0x80 [shim_eth_vlan]
[ 1054.108897]  RSP <ffff88002ec7bed0>
[ 1054.290779] ---[ end trace 10bab096603b005c ]---
[ 1055.856212] rina-rwq(DBG): Work posted on workqueue ffff88002fc53800, please wait ..

**Comment by edugrasa** [comment]
fixed by #867
