### ISSUE TITLE
Remove hardwired paths and binaries from the IPCManager

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#88]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [salvestrini](https://github.com/salvestrini)**
_Friday Oct 11, 2013 at 09:22 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/85_

----

Paths should be passed as preprocessor symbols (detected/imposed at configuration time)

**Comment by sandervrijders** [comment]
Can probably be closed...
