### ISSUE TITLE
Pristine-1.4 segfault while orinting error in assign_to_dif

### ISSUE THREAD

**Issue by vicalro** [IRATI/stack#884]
While testing the new console I got into a segmentation fault.

These are the 2 commands that I was giving to the console:

`create-ipcp test_console 3 normal-ipc`
`assign-to-dif 3 normal.DIF default.dif`

the error is related to accessing the ipcp pointer when it is still not set
I have already a PR for it

**Comment by vicalro** [comment]
someone to take a look at it... @vmaffione , @edugrasa ?

Thanks!

**Comment by edugrasa** [comment]
Fixed by #885
