### ISSUE TITLE
Rinad compilation without Java fails

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#898]
I compiled librina without the Java bindings. When I try to install rinad, it fails in the configure phase:

```
configure: error: No suitable java compiler found
```

But I want a stack without Java bindings.

**Comment by kewinrausch** [comment]
Probably come from ```configure.ac``` rinad project file

```
build_bindings=yes
build_bindings_java=yes
```

When I edit these to "no", I am able to use the stack without having Java in it.

**Comment by sandervrijders** [comment]
Yes of course, but that's hardcoding them...

**Comment by edugrasa** [comment]
Can this issue be closed? If not, what action is required?

**Comment by vmaffione** [comment]
rinad in the buildroot image is compiled without java, and it succeeds
