### ISSUE TITLE
RINA-IP gateway

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#900]
Implement a RINA-IP gateway that allows "client" applications on the Internet (or a private IP network) running on hosts with no RINA support to establish TCP/UDP flows to "server" applications running over RINA networks. As seen in the figure below, the gateway would terminate TCP connections (or UDP flows) on one side, and RINA flows on the other side, and relay data between both. 

![RINA-IP gateway](https://cloud.githubusercontent.com/assets/325005/14646327/635ac7f6-0659-11e6-878e-9aa27354cb4e.png)

The gateway could work as follows (example with TCP, UDP would work in a similar way):
1. The gateway must have a map of the names of all applications that can be accessed from the IP network. The gateway must map IP@ + port to application process name and instance.
2. A client application on the Internet requests a TCP connection to a gateway IP address and TCP/UDP port
3. The gateway accepts the TCP connection, looks up the map using the IP @ and port as the key and gets an application process name/instance (if it doesn't get a name/instance it closes the TCP connection).
4. The gateway requests a flow to the "server" application process, using as a source app name a combination of the gateway app name and the IP address of the client application. 
5. If the "server" application process rejects the flow, the gateway closes the TCP connection.
6. If the "server" application process accepts the flow, the gateway starts relaying data from the TCP connection to the RINA flow and vice-versa.
7. Whenever one of both ends terminates the TCP connection or releases the RINA flow, the gateway requests the termination of the other side.

In terms of the code organization, the gateway is an application, therefore it could be part of rina-tools for example (as rina-echo-time). Let's discuss if other location for this code is more convenient.

_Caveat: _The gateway breaks the end to end flow and retransmission control loops of TCP and the RINA flows - each flow is broken into two control loops by the gateway: "server" app<->Gateway and Gateway<->"client app". This opens the door to losing data and/or congestion problems.

**Comment by vmaffione** [comment]
An additional problem is related to buffer size. Current IRATI implementation does not support fragmentation. Therefore the gateway must do the fragmentation when read()ing buffers from TCP connection, or it can limit of the buffer passed to read().

**Comment by nacarino** [comment]
Hello guys,

I have a couple of questions:

1) Within RINA, would this be considered an application or more like a relaying node (member of a DIF but not necessarily an application)? Do you think this would have a direct influence on how the gateway is built?

2) You mention that you want a mapping of IP@ + Port to RINA services. Within what was written you mostly mention TCP. Would UDP's IP@PORT be a separate mapping for a different set of services?

3) Are you guys assuming that within the TCP/IP transport layer packets, the payload contains something that can be directly understood and forwarded to a RINA service? Has there been any conversation about adding an intermediate session maintaining protocol between the IP-RINA gateway and the TCP/IP client?

4) Is there a preferred programming language in which to implement the IP-RINA gateway?

5) Should work for this component be branched from the pristine-1.5 or pristine-1.4?

Look forward the discussion!

**Comment by edugrasa** [comment]
Hi Jairo,

Some answers, probably triggering another round of questions :)

1) It is an application that does relaying. It is a member of a DAF but not a member of a DIF (members of DIFs have to be IPC Processes, the RINA-IP gateway is definitely not an IPC Process).

2) We need to map applications names of the TCP/IP world (which don't exist, the IP@ + port is the equivalent) to application names in the RINA world. Regardless if its TCP or UDP the mapping will be the same, the only difference is that if it is TCP, the RINA-IP gateway will have to request a flow that doesn't loss data and provides reliable and in-order delivery of data.

3) The TCP/IP packets contains application data (the client application - e.g. a web browser - is completely unaware that the server application - e.g. a web server - runs on a RINA network), which will be delivered to the destination application by the RINA-IP gateway by means of a flow over a RINA network. What do you mean by an intermediate session maintaining protocol?

4) Currently bindings for the librina API are only generated for the C, C++ and Java languages, so it should be one of these three. Probably C++ is the one that offers a best performance/quick development tradeoff? But if you have a strong preference for Java let's talk :)

5) From pristine-1.5 (pristine-1.4 just admits bug fixes right now).

**Comment by vmaffione** [comment]
2016-04-20 16:49 GMT+02:00 Eduard Grasa <notifications@github.com>:

> Hi Jairo,
>
> Some answers, probably triggering another round of questions :)
>
> 1) It is an application that does relaying. It is a member of a DAF but
> not a member of a DIF (members of DIFs have to be IPC Processes, the
> RINA-IP gateway is definitely not an IPC Process).
>
> 2) We need to map applications names of the TCP/IP world (which don't
> exist, the IP@ + port is the equivalent) to application names in the RINA
> world. Regardless if its TCP or UDP the mapping will be the same, the only
> difference is that if it is TCP, the RINA-IP gateway will have to request a
> flow that doesn't loss data and provides reliable and in-order delivery of
> data.
>
This is a possible approach, but we may also allow the same port number to
map to two different applications, depending on the request being TCP or
UDP. In any case, obviously, TCP translates into a reliable flow.
Anyway, it's a minor point.

Cheers,
  Vincenzo


> 3) The TCP/IP packets contains application data (the client application -
> e.g. a web browser - is completely unaware that the server application -
> e.g. a web server - runs on a RINA network), which will be delivered to the
> destination application by the RINA-IP gateway by means of a flow over a
> RINA network. What do you mean by an intermediate session maintaining
> protocol?
>
> 4) Currently bindings for the librina API are only generated for the C,
> C++ and Java languages, so it should be one of these three. Probably C++ is
> the one that offers a best performance/quick development tradeoff? But if
> you have a strong preference for Java let's talk :)
>
> 5) From pristine-1.5 (pristine-1.4 just admits bug fixes right now).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/900#issuecomment-212456235>
>



-- 
Vincenzo Maffione

**Comment by nacarino** [comment]
@edugrasa 

Thank you for your answers. As always, more questions, lead to more questions.

1) We can work on the assumption that the RINA-IP Gateway is a DAF Application. However I am not quite sure why this process could not be considered an IPC process. Could you expand on this point?

2+3) @vmaffione response falls into this question as well. We can have a one-to-one mapping between IP@+TCP port <-> RINA app and IP@+UDP port <-> RINA app. What am I curious about is if you want to be able to have more options within the RINA-IP gateway when connecting to a RINA App, regardless of the TCP/IP protocol you decide to use.

For example, maybe you want the RINA App to have a reliable flow within the RINA network, but care less about the reliability on the TCP/IP network, so you use UDP. An inverse scenario is also possible - unreliable RINA network internal flow and TCP on the TCP/IP network.

Another unrelated example, if I have a TCP/IP client that suddenly changes IP, the direct IP <-> RINA connection would be severed. Unless there is some sort of session handling somewhere, a new IP connection would create a new RINA flow. Am I understanding this correctly?

4) Given the choices, I will attempt to program something in C++. Are you guys limiting the use of non-standard libraries for these cases? Boost is the only big third party library that comes to mind at the moment, but I am wondering if there are any other limitations.

5) No problem. I will branch from pristine-1.5. Do you have any preferences for branch names?

New! 6) Should I attempt to develop within the rina-tools directory?

As always, thanks for the discussion.

Cheers,
Jairo

**Comment by edugrasa** [comment]
More answers!

1) An IPC Process of a normal DIF does not terminate TCP or UDP connections, it just deals with the protocols in the DIF. The gateway impersonates the "server" application in the IP world (it is the application that gets the data from the TCP connection / UDP datagrams with the client) and also impersonates the "client application" in the RINA world (it is the destination application that reads/writes data from the flow). If you look at the diagram attached to the issue, it is clear that the RINA-IP gateway is at the same layer as the "client" and "server" applications.

2-3) If the point of the gateway is to allow applications on the Internet to connect to applications in RINA networks, then all you need is a mapping of IP@+port to application process naming. The specific transport protocol used by the application in the IP network (TCP, UDP, SCTP, etc..) will just influence the characteristics of the RINA flow between the gateway and the "server" application. It is the client application the one that decides how it wants the flow. If it uses TCP is because it wants a reliable flow with the server application (not with the gateway, the gateway is just a man in the middle not visible to the client application), so the RINA flow must be reliable as well.

If a TCP/IP client suddenly changes the IP the TCP connection dies anyway, so the flow must be deallocated.

4) We do it for rinad. I guess that for the gateway this limitation could be relaxed, @vmaffione, what do you think?

5) Usually start with pristine-1.5-<feature_name>, although sometimes people uses <featue_name> alone

6) Yes, I think so

**Comment by vmaffione** [comment]
2016-04-21 10:07 GMT+02:00 Eduard Grasa <notifications@github.com>:

> More answers!
>
> 1) An IPC Process of a normal DIF does not terminate TCP or UDP
> connections, it just deals with the protocols in the DIF. The gateway
> impersonates the "server" application in the IP world (it is the
> application that gets the data from the TCP connection / UDP datagrams with
> the client) and also impersonates the "client application" in the RINA
> world (it is the destination application that reads/writes data from the
> flow). If you look at the diagram attached to the issue, it is clear that
> the RINA-IP gateway is at the same layer as the "client" and "server"
> applications.
>
> 2-3) If the point of the gateway is to allow applications on the Internet
> to connect to applications in RINA networks, then all you need is a mapping
> of IP@+port to application process naming. The specific transport
> protocol used by the application in the IP network (TCP, UDP, SCTP, etc..)
> will just influence the characteristics of the RINA flow between the
> gateway and the "server" application. It is the client application the one
> that decides how it wants the flow. If it uses TCP is because it wants a
> reliable flow with the server application (not with the gateway, the
> gateway is just a man in the middle not visible to the client application),
> so the RINA flow must be reliable as well.
>
Correct, but I was more thinking to the case where a port X correspond to
UDP application A and tcp application B, with A different from B (We know
that usually A==B).

> If a TCP/IP client suddenly changes the IP the TCP connection dies anyway,
> so the flow must be deallocated.
>
> 4) We do it for rinad. I guess that for the gateway this limitation could
> be relaxed, @vmaffione <https://github.com/vmaffione>, what do you think?
>
We could relax the limitation, but I still think we should avoid adding
dependencies, if possible, even in rinad. Librina has some abstractions for
threads, locks, etc, so those should be enouogh.
What do you exactly need from boost that is not available in librina?

> 5) Usually start with pristine-1.5-, although sometimes people uses alone
>
You can create a branch called gateway, branching from pristine-1.5.


> 6) Yes, I think so
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/900#issuecomment-212796953>
>



-- 
Vincenzo Maffione

**Comment by nacarino** [comment]
@edugrasa 

1,2,3) Thank you very much for your explanation about the gateway application. I think I have cleared up my doubts about where the gateway application should sit in RINA.

4) @vmaffione I have not yet found something that I think I could need outside RINA, but it was worth considering for a second. I recently played with the Boost.ASIO library and the point about limitations popped up. For now, I will stick to what is within librina and will discuss any new additions should I stumble upon something I didn't foresee.

5-6) I will make a gateway branch starting from pristine-1.5

@vmaffione, I was also thinking about separating UDP ports from TCP ports, just for the sake of having a larger number of service possibilities.

I also have some new questions (yey!) I would like to share:

1.1) Have you discussed a particular method to signal the gateway to open a particular listening TCP/IP port for a DIF service?

2.1) Does the gateway application have the possibility to connect clients to RINA apps in distinct DIFs?

Cheers,

**Comment by vmaffione** [comment]
2016-04-22 10:04 GMT+02:00 Jairo Eduardo Lopez <notifications@github.com>:

> @edugrasa <https://github.com/edugrasa>
>
> 1,2,3) Thank you very much for your explanation about the gateway
> application. I think I have cleared up my doubts about where the gateway
> application should sit in RINA.
>
> 4) @vmaffione <https://github.com/vmaffione> I have not yet found
> something that I think I could need outside RINA, but it was worth
> considering for a second. I recently played with the Boost.ASIO library and
> the point about limitations popped up. For now, I will stick to what is
> within librina and will discuss any new additions should I stumble upon
> something I didn't foresee.
>
> 5-6) I will make a gateway branch starting from pristine-1.5
>
> @vmaffione <https://github.com/vmaffione>, I was also thinking about
> separating UDP ports from TCP ports, just for the sake of having a larger
> number of service possibilities.
>
> I also have some new questions (yey!) I would like to share:
>
> 1.1) Have you discussed a particular method to signal the gateway to open
> a particular listening TCP/IP port for a DIF service?
>
I think we can start with static configuration: the TCP/IP ports to open
(mapped to RINA apps) are specified through a configuration file.
Then, once we have this, we could add a mechanism to dynamically configure
the gateway (e.g. adding new mappings or remove existing ones). This
mechanism, however, can be gateway-specific: ad hoc console, a cmd line
tool that connects to the gateway through an UNIX socket or a CDAP
connection.


> 2.1) Does the gateway application have the possibility to connect clients
> to RINA apps in distinct DIFs?
>
Yes, the gateway is also a RINA app, and when it ask for allocating a flow,
the proper DIF will be selected by the system (unless the gateway itself
does not specify a DIF).

> Cheers,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/900#issuecomment-213313649>
>



-- 
Vincenzo Maffione

**Comment by edugrasa** [comment]
Closing since a TCP gateway using the POSIX API was already developed by @vmaffione https://github.com/vmaffione/rlite/blob/master/user/tools/rina-gw.cpp
