### ISSUE TITLE
Research Proposal - Prototype IRATI with SDN Controller (floodlight)

### ISSUE THREAD

**Issue by DjalmaFilho-UFPE** [IRATI/stack#904]
Dear @edugrasa, good morning!

I'm working with RINA architecture at the Federal University of Pernambuco. To work in the management area of the IPC processes thought about using the SDN Floodlight controller. It would be possible to work with the SDN controller using RINA prototype (IRATI) in the management of IPC processes? There is some work to RINA for this purpose. I thank attention. I want to use the prototype IRATI in my research using the SDN Floodlight controller.

**Comment by edugrasa** [comment]
Good morning!

My first question is: what is the added value of using Floodlight? RINA networks are not Openflow networks.. Managing IPC Processes is done through the interaction with the Management Agent running at each RINA-enabled system, which requires the use of the CDAP protocol.

**Comment by DjalmaFilho-UFPE** [comment]
@edugrasa, good morning!

Using the floodlight thought I would have more centralized control of the application processes, specifically, the allocation of resources in Rina architecture. From what I have studied each application process has a local RIB. In this case the controller would be a single RIB to manage every request of the application process (AP).

But I understand that the communication network with RINA openflow networks are not feasible since openflow networks work at Layer 2 (MAC) unlike RINA architecture that works only with IPC's processes.

I'm trying to find something relevant to work with RINA architecture in my research project.

Could you give some tips on what can and is working on architecture to be viable a possible implementation through the prototype?

Thank attention.

**Comment by edugrasa** [comment]
I think you are confusing a number of things here. You can use a central Manager to manage a RINA network (composed by a set of RINA-enabled systems - hosts and routers). In fact this is what we are doing at the PRISTINE and ARCFIRE projects. 

Now, the interaction between Managers and Management Agents is done via CDAP, you can find some details here: http://ict-pristine.eu/wp-content/uploads/2013/12/pristine_d51_common_management_elements_v1_0.pdf (first 3 chapters are enough for a detailed introduction).

Openflow is just a protocol to control the forwarding table of Ethernet/IP routers. It has nothing to do with managing RINA networks.

There's lots to research in RINA :) What are your interests and constraints? Network management, routing, congestion control, quality of service, security? How much time do you plan to spend on the project?

**Comment by DjalmaFilho-UFPE** [comment]
I'm sorry if I expressed myself wrong. I would like to work with network management and / or also with security in RINA architecture. But I'm looking for something viable that can be implemented in IRATI prototype. I will study these documents and try to find something related to these two areas. I have time for one year and a half to find something in these two areas of interest.

Again thank attention. Sorry for any poorly worded expression.

**Comment by edugrasa** [comment]
You don't need to ask for excuses, come on :)

So RINA network security management could be a potential target, right? Once you've read the documentation let's continue the discussion.

**Comment by DjalmaFilho-UFPE** [comment]
Ok, @edugrasa 

Vou estudar a documentação e qualquer dúvida mantemos contato.

Obrigado!
