### ISSUE TITLE
Can't make an IPCP enroll to several neighbours

### ISSUE THREAD

**Issue by jmuchemb** [IRATI/stack#909]
With a single shim-tcp-udp to link more than 2 machines, there are cases where making each node a neighbour of all other machines (full-mesh) fail.

Given 3 VMs setup as follows: VM0 -> VM1 -> VM2 where "->" is an enrollment
VM0 -> VM2 then fails (after the TCP connection is established successfully), whereas VM2 -> VM0 succeeds.

Here are logs from VM2:

>  # VM1 -> VM2
> 290(1460111733)#ipcm.flow-alloc (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between vm2.IRATI:1:: and Unknown app:::
> 290(1460111733)#ipcm.flow-alloc (INFO)[allocate_flow_response_event_handler]: : Informing IPC process shim2:1:: about flow allocation from application vm2.IRATI:1:: to application Unknown app::: in DIF shim::: [success = 1, port-id = 1]
>
>  # VM0 -> VM2
> 290(1460111735)#ipcm.flow-alloc (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between vm2.IRATI:1:: and Unknown app:::
> 290(1460111735)#ipcm.flow-alloc (INFO)[allocate_flow_response_event_handler]: : Informing IPC process shim2:1:: about flow allocation from application vm2.IRATI:1:: to application Unknown app::: in DIF shim::: [success = 0, port-id = -1]

**Comment by edugrasa** [comment]
Just realized what is going on.. one IPC Process is trying to accept two flows from an "Unknown app". The first one will work; for the second one the current default policy checks that the IPCP is not already enrolled to an IPCP with the same name.. and since it is already enrolled to "Unknown app" then it fails. Will issue a fix in short..

**Comment by edugrasa** [comment]
Fixed by #914
