### ISSUE TITLE
valgrind error

### ISSUE THREAD

**Issue by bernatgaston** [IRATI/stack#912]
22989(1462186539)#ipcm.scripting (DBG): Starting...
==22989== Thread 5:
==22989== Syscall param socketcall.bind(my_addr.sun_path) points to uninitialised byte(s)
==22989==    at 0x48FC297: bind (socket.S:63)
==22989==    by 0x80C2A34: rinad::IPCMConsole::init() (console.cc:215)
==22989==    by 0x80C58DA: rinad::IPCMConsole::body() (console.cc:290)
==22989==    by 0x80C5B17: rinad::console_function(void*) (console.cc:76)
==22989==    by 0x46A3EFA: start_thread (pthread_create.c:309)
==22989==    by 0x48FAEDD: clone (clone.S:129)
==22989==  Address 0x6ddf28f is on thread 5's stack
==22989==  in frame #1, created by rinad::IPCMConsole::init() (console.cc:189)
==22989==

**Comment by edugrasa** [comment]
Fixed by #918
