### ISSUE TITLE
Help in the Tutorial 3: Security provider net

### ISSUE THREAD

**Issue by DjalmaFilho-UFPE** [IRATI/stack#917]
I'm working on tutorial available on https://github.com/IRATI/stack/wiki/Tutorial-3:-Security-provider-net site, but when access the IPCM with list-ipcps command is not presenting the information to the IPC A.IRATI and E. IRATI (assign-to-diff). The files were downloaded as tutorial. What can is going on? Follow the exit at IPCM, loaded modules and ipcm.conf file..

Setting Customer border router

IPCM >>> list-ipcps
Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | test-eth-vlan:1:: | shim-eth-vlan | ASSIGNED TO DIF 300 | A.IRATI-1-- | -
    2 | A.IRATI:1:: | normal-ipc | INITIALIZED | - | -
    3 | E.IRATI:1:: | normal-ipc | INITIALIZED | - | -

Module                  Size  Used by
rina_default_plugin    16384  2
shim_eth_vlan          32768  1
rinarp                 16384  1 shim_eth_vlan
arp826                 36864  2 shim_eth_vlan,rinarp
8021q                  24576  0

  "localConfiguration" : {
    "installationPath" : "/usr/local/irati/bin",
    "libraryPath" : "/usr/local/irati//lib",
    "logPath" : "/usr/local/irati//var/log",
    "consolePort" : 32766,
    "pluginsPaths" : ["/usr/local/irati/lib/rinad/ipcp"]
  },
  "applicationToDIFMappings" : [ {
    "encodedAppName" : "traffic.generator.server-1--",
    "difName" : "multi-provider.DIF"
  }, {
    "encodedAppName" : "traffic.generator.client-1--",
    "difName" : "multi-provider.DIF"
  }, {
    "encodedAppName" : "rina.apps.echotime.server-1--",
    "difName" : "multi-provider.DIF"
  }, {
    "encodedAppName" : "rina.apps.echotime.client-1--",
    "difName" : "multi-provider.DIF"
  } ],
  "ipcProcessesToCreate" : [ {
    "type" : "shim-eth-vlan",
    "apName" : "test-eth-vlan",
    "apInstance" : "1",
    "difName" : "300"
   }, {
    "type" : "normal-ipc",
    "apName" : "A.IRATI",
    "apInstance" : "1",
    "difName" : "access.DIF",
    "difsToRegisterAt" : ["300"]
   }, {
    "type": "normal-ipc",
    "apName" : "E.IRATI",
    "apInstance" : "1",
    "difName" : "multi-provider.DIF",
    "difsToRegisterAt" : ["access.DIF"]
  "difConfigurations" : [ {
    "name" : "300",
    "template" : "shim-eth-vlan.dif"
  }, {
    "name" : "access.DIF",
    "template" : "access.dif"
  }, {
    "name" : "multi-provider.DIF",
    "template" : "multi-provider.dif"
  } ]
}

IPCM >>> assign-to-dif 2 access.DIF access.dif
DIF assignment failed

IPCM >>> assign-to-dif 3 access.DIF access.dif
DIF assignment failed

ipcm.log
807(1462276469)#ipcm (ERR): Asssign IPCP 2 to dif access.DIF::: failed. Bad configuration.
807(1462276682)#ipcm (ERR)[assign_to_dif]: No address for IPC process E.IRATI:1:: in DIF access.DIF:::

**Comment by koenveelenturf** [comment]
It looks like you have the same problem as I had (although I have now another issue). I had to change the access, multi-provider and regional.dif files to have the extra lines like in the default default.dif (installed by compiling the kernel and user-space programs):

{
    "difType" : "normal-ipc",
    "dataTransferConstants" : {
      "addressLength" : 2,
      "cepIdLength" : 2,
      "lengthLength" : 2,
      "portIdLength" : 2,
      "qosIdLength" : 2,
      "rateLength" : 4,
      "frameLength" : 4,
      "sequenceNumberLength" : 4,
      "ctrlSequenceNumberLength" : 4,
      "maxPduSize" : 10000,
      "maxPduLifetime" : 60000
    },
[...]

**Comment by edugrasa** [comment]
Closing, problem due to tutorials not up to date, will fix that the next couple of days
