### ISSUE TITLE
pristine-1.5 : Kernel bug reported when shutting down IPCM

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#925]
The IPCM process never terminates and the IPCM log reports the following as a last line:
1154(1462890456)#librina.syscalls (DBG): Invoking SYS_destroyIPCProcess (324)

The following is error is reported (from dmesg):

[  474.489571] ------------[ cut here ]------------
[  474.489799] kernel BUG at net/rina/ipcps/shim-eth-vlan-core.c:196!
[  474.489929] invalid opcode: 0000 [#1] SMP 
[  474.490052] Modules linked in: normal_ipcp(E) rina_default_plugin(E) shim_eth_vlan(E) rinarp(E) arp826(E) 8021q(E) garp(E) stp(E) mrp(E) llc(E) ppdev(E) serio_raw(E) parport_pc(E) lp(E) parport(E) psmouse(E) ahci(E) libahci(E)
[  474.490507] CPU: 0 PID: 1154 Comm: ipcm Tainted: G            E   4.1.16-150-rina #27
[  474.490728] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[  474.490951] task: ffff88003d213220 ti: ffff880037f94000 task.ti: ffff880037f94000
[  474.491167] RIP: 0010:[<ffffffffa009eb33>]  [<ffffffffa009eb33>] inst_data_mapping_get+0x73/0x80 [shim_eth_vlan]
[  474.491414] RSP: 0018:ffff880037f97eb8  EFLAGS: 00010246
[  474.491536] RAX: 0000000080408001 RBX: ffff88003d18d0c0 RCX: 000000018040003f
[  474.491671] RDX: 0000000000000040 RSI: ffffea0000df1100 RDI: 0000000000000000
[  474.491804] RBP: ffff880037f97ec8 R08: ffff880037c44880 R09: 000000018040003e
[  474.492173] R10: ffffea0000df1100 R11: ffffffff817660f3 R12: 0000000000000000
[  474.492232] R13: ffff88003d152cc0 R14: ffff88003d18d120 R15: 00007ffdfb94d6d8
[  474.492279] FS:  00007f9efa661780(0000) GS:ffff88003fc00000(0000) knlGS:0000000000000000
[  474.492355] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[  474.492398] CR2: 00007fa0cb785e38 CR3: 000000003d260000 CR4: 00000000000006f0
[  474.492571] Stack:
[  474.492571]  ffff88003d18d0c0 ffff88003d18d120 ffff880037f97ef8 ffffffffa009ece4
[  474.492571]  ffff880037ab12a0 ffff880037ab12a8 0000000000000001 00000000023ee720
[  474.492571]  ffff880037f97f28 ffffffff81784593 0000000000000001 0000000000000001
[  474.492571] Call Trace:
[  474.492571]  [<ffffffffa009ece4>] eth_vlan_destroy+0x1a4/0x290 [shim_eth_vlan]
[  474.492571]  [<ffffffff81784593>] kipcm_ipc_destroy+0x73/0x110
[  474.492571]  [<ffffffff81789284>] SyS_ipc_destroy+0x54/0x60
[  474.492571]  [<ffffffff817a1e72>] system_call_fastpath+0x16/0x75
[  474.492571] Code: 75 ee 48 c7 c7 80 56 0a a0 e8 ba 2f 70 e1 48 89 d8 5b 41 5c 5d c3 66 90 48 c7 c7 80 56 0a a0 e8 a4 2f 70 e1 5b 41 5c 31 c0 5d c3 <0f> 0b 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 55 48 85 
[  474.492571] RIP  [<ffffffffa009eb33>] inst_data_mapping_get+0x73/0x80 [shim_eth_vlan]
[  474.492571]  RSP <ffff880037f97eb8>
[  474.500441] ---[ end trace 4c81a8053c9a3fc9 ]---

**Comment by edugrasa** [comment]
Did you do anything special that you remember? Or just shutting down as usual?

**Comment by mcrotty** [comment]
Nothing special, just shutting down the cdap-connector (which terminates) ipcm however does not, and the error is in the kernel log.

**Comment by edugrasa** [comment]
Fixed by #1086
