### ISSUE TITLE
pristine-1.5: No java exceptions emitted on IPC-API calls in librina

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#947]
See ipc-api.h:

        /// Reads an SDU from the flow. This function will block until there is an
        /// SDU available.
        ///
        /// @param sdu A buffer to store the SDU data
        /// @param maxBytes The maximum number of bytes to read
        /// @return int The number of bytes read
        /// @throws UnknownFlowException if the port-id is not valid
        /// @throws FlowNotAllocatedException if the flow has been deallocated
        /// @throws InvalidArgumentsException if the arguments of the call are not valid
        /// @throws ReadSDUException if an error happens while reading the SDU
        /// @throws IPCException if an unknown error happens
        int readSDU(int portId, void * sdu, int maxBytes);

No throws in the declaration => no exception code generated by SWIG.
Exception happens => Native code bails with an un-handled exception.

**Comment by msune** [comment]
On 3 June 2016 at 14:59, M Crotty <notifications@github.com> wrote:

> See ipc-api.h:
>
>     /// Reads an SDU from the flow. This function will block until there is an
>     /// SDU available.
>     ///
>     /// @param sdu A buffer to store the SDU data
>     /// @param maxBytes The maximum number of bytes to read
>     /// @return int The number of bytes read
>     /// @throws UnknownFlowException if the port-id is not valid
>     /// @throws FlowNotAllocatedException if the flow has been deallocated
>     /// @throws InvalidArgumentsException if the arguments of the call are not valid
>     /// @throws ReadSDUException if an error happens while reading the SDU
>     /// @throws IPCException if an unknown error happens
>     int readSDU(int portId, void * sdu, int maxBytes);
>
> No throws in the declaration => no exception code generated by SWIG.
> Exception happens => Native code bails with an un-handled exception.
>

C++ explicit throws declaration is NOT a guarantee that other exception
types are not going to be raised. That's why most people consider harmful
and misleading, and a possible cause of future errors, to explicitly
declare exceptions in method prototypes. See [1]

A better solution is to make sure SWIG maps correctly librina exceptions
using typemap **and** maps any other exception to a Java runtime exception.

http://stackoverflow.com/questions/13993747/handling-c-exceptions-in-java-via-swig


[1] http://www.gotw.ca/publications/mill22.htm

**Comment by mcrotty** [comment]
Yes, agree on the general advice in [1].  

However, for SWIG if there is no "throws" in the ".h" then the exception typemaps we have defined are not invoked.  In the link you provide, there is at least one "throw" on the C++ class function definition => code gets generated. Without it, no exception handling code is generated (in the swig native code) See generated code below (with no try{ } catch() ):

  arg1 = *(rina::IPCManager **)&jarg1;
  arg2 = (int)jarg2;
  {
    arg3 = (void *) jenv->GetByteArrayElements(jarg3, 0);
  }
  arg4 = (int)jarg4;
  result = (int)(arg1)->writeSDU(arg2,arg3,arg4);
  jresult = (jint)result;
  {
    jenv->ReleaseByteArrayElements(jarg3, (jbyte *) arg3, 0);
  }
  return jresult;

We may have to resort to explicitly using %exception macro with a catch () blocks to generate an Java IOException.

**Comment by edugrasa** [comment]
Fixed!
