### ISSUE TITLE
pristine-1.5:  Wrong type used IPC create.

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#950]
Looks like the ipcp name is passed as the type identifier.

See the logging below:

2295(1465322072)#rib (DBG): Found a callback for create operation of class 'IPCProcess' and path '/computingSystemID=1/processingSystemID=1/kernelApplicationProcess/osApplicationProcess/ipcProcesses'
2295(1465322072)#ipcm (ERR)[create_ipcp]: IPCP type parameter ipcp.s:1:: is wrong, options are: [normal-ipc, shim-eth-vlan, ]
2295(1465322072)#ipcm (ERR)[create_ipcp]: Failed to create IPC process 'ipcp.s:1::' of type 'normal-ipcp'

2295(1465322072)#ipcm.mad.ipcp_obj (ERR): Error while creating IPC process
2295(1465322072)#ipcm.mad.ipcp_obj (ERR): Create operation failed in '/computingSystemID=1/processingSystemID=1/kernelApplicationProcess/osApplicationProcess/ipcProcesses/ipcProcessID=7'. Unknown error.
2295(1465322072)#librina.syscalls (DBG): Invoking SYS_writeSDU (326)

**Comment by mcrotty** [comment]
Sorry, spotted the error (normal-ipcp -> normal-ipc), I will retry in the morning.

**Comment by edugrasa** [comment]
Closing, was not an error
