### ISSUE TITLE
Problems with Tutorial 3

### ISSUE THREAD

**Issue by koenveelenturf** [IRATI/stack#959]
Hi all,

I am trying to run the 3rd tutorial described on this wiki (https://github.com/IRATI/stack/wiki/Tutorial-3:-Security-provider-net), but I'm getting stuck at the point where I'm enrolling the difs on the Provider Border router 1. Enrolling difs on the most right router is going fine, but I get the following error on Provider Border Router 1:

IPCM >>> list-ipcps
Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | test-eth-vlan:1:: | shim-eth-vlan | ASSIGNED TO DIF 300 | B.IRATI-1-- | -
    2 | test-eth-vlan2:1:: | shim-eth-vlan | ASSIGNED TO DIF 310 | C.IRATI-1-- | 1
    3 | C.IRATI:1:: | normal-ipc | ASSIGNED TO DIF regional.DIF | F.IRATI-1-- | 2
    4 | B.IRATI:1:: | normal-ipc | ASSIGNED TO DIF access.DIF | F.IRATI-1-- | -
    5 | F.IRATI:1:: | normal-ipc | ASSIGNED TO DIF multi-provider.DIF | - | -

IPCM >>> enroll-to-dif 4 access.DIF 300 A.IRATI 1
Enrollment operation failed

I've tried this tutorial with both the kernel compiled from the master branch and from the pristine-1.5 branch. Can anyone help me with this one? I had to slightly change the access.dif, regional.dif, and the multi-provider.dif by making sure the first lines look similar to the default.dif installed on the system by default after compilation. Maybe other stuff also needs to be changed?

Cheers,
Koen

**Comment by koenveelenturf** [comment]
This is the part of the ipcm.log when trying to enroll on Provider Border Router 1:

2972(1465895680)#librina.nl-manager (DBG): NL msg TX. Fam: 21; Opcode: 7_ENROLL_TO_DIF_REQ; Sport: 1; Dport: 2991; Seqnum: 13; Request; SIPCP: 0; DIPCP: 4
2972(1465895680)#ipcm (INFO)[enroll_to_dif]: Requested enrollment of IPC process B.IRATI:1:: to DIF access.DIF::: through DIF 300::: and neighbor IPC process A.IRATI:1::

2972(1465895680)#librina.nl-manager (DBG): NL msg RX. Fam: 21; Opcode: 44_APP_ALLOC_FLOW_REQ; Sport: 2991; Dport: 1; Seqnum: 1465895646; Request; SIPCP: 4; DIPCP: 0 
2972(1465895680)#librina.core (DBG): Added event of type 0_FLOW_ALLOCATION_REQUESTED and sequence number 1465895646 to events queue
2972(1465895680)#ipcm (DBG): Got event of type 0_FLOW_ALLOCATION_REQUESTED and sequence number 1465895646
2972(1465895680)#librina.nl-manager (DBG): NL msg TX. Fam: 21; Opcode: 11_IPCM_ALLOC_FLOW_REQ; Sport: 1; Dport: 0; Seqnum: 14; Request; SIPCP: 4; DIPCP: 1
2972(1465895680)#ipcm.flow-alloc (INFO)[flow_allocation_requested_local]: IPC process test-eth-vlan:1:: requested to allocate flow between B.IRATI:1:: and A.IRATI:1::

2972(1465895680)#librina.nl-manager (DBG): NL msg RX. Fam: 21; Opcode: 13_IPCM_ALLOC_FLOW_REQ_RES; Sport: 0; Dport: 1; Seqnum: 14; Response; SIPCP: 1; DIPCP: 0 
2972(1465895680)#librina.core (DBG): Added event of type 26_IPCM_ALLOCATE_FLOW_RESULT and sequence number 14 to events queue
2972(1465895680)#ipcm (DBG): Got event of type 26_IPCM_ALLOCATE_FLOW_RESULT and sequence number 14
2972(1465895680)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Informing IPC process test-eth-vlan:1:: about flow allocation from application B.IRATI:1:: to application A.IRATI:1:: in DIF 300::: [success = 1, port-id = 1]

2972(1465895680)#librina.ipc-manager (DBG): ApplicationManager::flowAllocated called
2972(1465895680)#librina.nl-manager (DBG): NL msg TX. Fam: 21; Opcode: 45_APP_ALLOC_FLOW_REQ_RES; Sport: 1; Dport: 2991; Seqnum: 1465895646; Response; SIPCP: 0; DIPCP: 4
2972(1465895680)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Applications B.IRATI:1:: and A.IRATI:1:: informed about flow allocation result

**Comment by edugrasa** [comment]
Hi Koen, if I'm not wrong this issue was fixed via the irati mailing list? If so, can we close this issue? Thanks!

**Comment by koenveelenturf** [comment]
Hi Eduard,

I'm afraid that my issue through the mailing list is another issue. I think the tutorial's configuration files are a bit outdated, because it looked like the config changed a bit. I'll check this afternoon if the other issue is solved when recompiling the librina, etc. This issue is for me not really important anymore, but it would be nice for future researchers if they can play around with this tutorial as well.

Thanks.

**Comment by edugrasa** [comment]
Oh right, the tutorial was documenting an experiment with the pristine-1.3
branch, has to be updated for sure :). Let's keep the issue open as a
reminder

2016-06-29 12:07 GMT+02:00 koenveelenturf <notifications@github.com>:

**Comment by edugrasa** [comment]
Closing, problem is addressed by issue #889
