### ISSUE TITLE
pristine-1.5 rina::auth::policies::googleprotobuf::authOptsTLSHandshake_t  not a member of rina::auth::policies::googleprotobuf 

### ISSUE THREAD

**Issue by nacarino** [IRATI/stack#982]
I was attempting to compile everything from RINA on the pristine-1.5 branch, commit d4214bf22f9f9e5f396adad5cec99c6a8e1082c3 using the install-from-scratch script on a Debian 8.5.

I get the following errors when the script attempts to compile librina:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/home/stack/librina/src -isystem /usr/include/c++/4.9 -isystem /usr/include/x86_64-linux-gnu/c++/4.9 -isystem /usr/include/c++/4.9/backward -I/home/stack/linux/usr/include -DSTUB_API=0 -I/home/stack/librina/include -I/home/stack/librina/src/jsoncpp -I/usr/include/libnl3 -I/usr/include/libnl3 -pthread -Wall -Wformat -Wnon-virtual-dtor -Woverloaded-virtual -Werror -Wfatal-errors -g -O0 -fno-inline -g -O2 -MT librina_la-tlshand-authp.lo -MD -MP -MF .deps/librina_la-tlshand-authp.Tpo -c /home/stack/librina/src/tlshand-authp.cc  -fPIC -DPIC -o .libs/librina_la-tlshand-authp.o
/home/stack/librina/src/tlshand-authp.cc: In function 'void rina::decode_tls_hand_auth_options(const ser_obj_t&, rina::TLSHandAuthOptions&)':
/home/stack/librina/src/tlshand-authp.cc:51:2: error: 'authOptsTLSHandshake_t' is not a member of 'rina::auth::policies::googleprotobuf'
  rina::auth::policies::googleprotobuf::authOptsTLSHandshake_t gpb_options;

I haven't modified anything so I am not quite sure what to make of the error. Has anyone else encountered this?

Thanks for your time.

**Comment by edugrasa** [comment]
Hi,

I'm not sure what may be the problem, I have not seen this issue before. Pristine-1.5 is compiling well for me. Did you clean before compiling from scratch?

Could you try to update to latest pristine-1.5 and compile again?

**Comment by nacarino** [comment]
@edugrasa,

Very sorry for the late reply. I have no idea what caused this issue, but updating the pristine-1.5 branch made the error I was getting go away.

Sorry for the hassle.

**Comment by edugrasa** [comment]
No probs, issue solved then :)
