### ISSUE TITLE
pristine-1.5: Compile issue with RDS ringq

### ISSUE THREAD

**Issue by miguelpdl** [IRATI/stack#985]
During a build of pristine-1.5 on a fresh machine, the compiler bombs out with 

>  In file included from net/rina/rds/ringq.c:27:0:
>  net/rina/rds/ringq.c:
>  In function ‘ringq_destroy’:
> 
>  net/rina/rds/ringq.c:168:58: error: ‘f’ undeclared (first use in this function)
> 
> ```
>       LOG_DBG("RING Queue %pK destroyed successfully", f);
>                                                        ^
> ```
> 
>  ./net/rina/logs.h:34:62: note: in definition of macro ‘__LOG’
>           do { printk(LVL __GPFX PFX "(" BAN "): " FMT "\n", ##ARGS); } while (0)
>                                                                ^
>  net/rina/rds/ringq.c:168:9: note: in expansion of macro ‘LOG_DBG’
>           LOG_DBG("RING Queue %pK destroyed successfully", f);
>           ^
>  net/rina/rds/ringq.c:168:58: note: each undeclared identifier is reported only once for each function it appears in
>           LOG_DBG("RING Queue %pK destroyed successfully", f);
>                                                            ^
>  ./net/rina/logs.h:34:62: note: in definition of macro ‘__LOG’
>           do { printk(LVL __GPFX PFX "(" BAN "): " FMT "\n", ##ARGS); } while (0)
>                                                               ^
>  net/rina/rds/ringq.c:168:9: note: in expansion of macro ‘LOG_DBG’
>           LOG_DBG("RING Queue %pK destroyed successfully", f);
>           ^
>  make[3]: **\* [net/rina/rds/ringq.o] Error 1
>  make[2]: **\* [net/rina/rds] Error 2
>  make[1]: **\* [net/rina] Error 2
>  make: **\* [net] Error 2
>  compile-kernel: Cannot complete kernel compilation
>  install-from-scratch: Cannot compile or install the kernel from scratch

Found the error on Line 168 of [linux/net/rina/rds/ringq.c](https://github.com/IRATI/stack/blob/pristine-1.5/linux/net/rina/rds/ringq.c)

[`LOG_DBG("RING Queue %pK destroyed successfully", f);`](https://github.com/IRATI/stack/blob/pristine-1.5/linux/net/rina/rds/ringq.c#L168)

I don't know what the f is supposed to be, but it's not right here.

For the moment I will comment out the line, which will allow the build to continue, however this bug should be fixed up.

**Comment by edugrasa** [comment]
Has been already fixed, closing
